openstax/tutor-js

- src/components/all-steps.cjsx
- src/components/breadcrumbs.cjsx
- src/components/exercise.cjsx
- src/components/index.cjsx
- src/components/task-step.cjsx
- src/components/task.cjsx
- src/flux/task.coffee
- src/router.coffee
- test/components/task/exercise.spec.cjsx
- test/components/task/interactive.spec.coffee
- test/components/task/reading.spec.coffee
> Add support for breadcrumbs

- api/tasks/1
- api/tasks/4
- api/user/tasks
- src/components/all-steps.cjsx
- style/reading.less
- style/reading/grasp-check.less
- style/reading/links-to-physics.less
- style/reading/tips-for-success.less
- style/tutor.less
Adding in initial styles for reading step for the following reading components:
- Grasp Checks
- Tips for Success
- Link to Physics
> Reading step styles

- src/components/exercise-multiple-choice.cjsx
- src/components/question.cjsx
- style/question.less
- style/tutor.less
Adding in styles for questions and answers.  Will need to check more question types later as we get access to them.
> Exercise question styling

- api/tasks/1
- api/tasks/2
- api/tasks/3
- api/tasks/4
- api/user/tasks
- src/api.coffee
- src/components/question.cjsx
- src/flux/task.coffee
the route used to be `/tasks/123/steps/1` (the step index in the steps array) and has been changed to `/tasks/123/steps/234` where `234` is the `{id: }` in the JSON for the TaskStep
> Use TaskStep.id instead of index for updates

- api/tasks/4
- api/user/tasks
- src/components/task.cjsx
This adds 2 new pages for the Reading Task:
> display task intro/done pages

- package.json
- src/components/teacher/reading.cjsx
- src/router.coffee
- style/react-widgets.less
- style/tutor.less
Adding in initial component for creating iReadings.
> Ireading for teachers

- src/components/app.cjsx
- src/components/index.cjsx
- src/components/task-plan/reading.cjsx
- style/tutor.less
1. Added styling/prompt for selected readings
2. Added in button on dashboard to create reading
> Selected reading styles

- src/flux/helpers.coffee
- src/flux/task-plan.coffee
- src/flux/task-step.coffee
- src/flux/task.coffee
No UI changes
1. Fixed CrudConfig to be a function that has it's own scope
2. Fixed task store hasTopics/removeTopics to use settings.page_ids
3. Fixed error when user clears the date field
> Create ireading bugs

- src/components/task-plan/reading.cjsx
tested with @state.id.  datetimepicker can be emptied after population but retains last value.
> publish button greyed out unless add reading form complete

- src/components/html.cjsx
- src/components/task-step/all-steps.cjsx
- src/components/task/index.cjsx
> remove JQuery except for $.ajax and in tests

- src/router.coffee
- src/sandbox.coffee
- style/sandbox.less
- style/tutor.less
Adding in sandbox for Fred and Jason.
> adding in sandbox route/component/initial styles

- style/tutor.less
> reinsert logo

- src/components/index.cjsx
- src/components/task-plan/reading.cjsx
Blank:
With all fields entered:
> refactor the readings editor

- api/courses/1/plans.json
- src/api.coffee
- src/components/app.cjsx
- src/components/index.cjsx
- src/components/task-plan/teacher-task-plans-listing.cjsx
- src/flux/teacher-task-plan.coffee
- src/router.coffee
- test/all-tests.coffee
- test/teacher-task-plan-store.spec.coffee
Names and file locations very much subject to change, I'm not at all sure if I've implemented any of this correctly :)
> Add Teacher Task Plans listing

- src/api.coffee
- src/components/task-plan/reading.cjsx
- src/flux/task-plan.coffee
also, restricts the dates that can be selected.
> Add TaskPlan.opens_at

- src/api.coffee
- src/components/app.cjsx
- src/components/index.cjsx
- src/components/task-plan/reading.cjsx
- src/components/task-plan/teacher-task-plans-listing.cjsx
- src/components/task/index.cjsx
- src/flux/helpers.coffee
- src/router.coffee
No UI Changes.
Prefix course-specific routes with `/courses/:courseId`
Also, fixes the React `InvariantViolation` when transitioning after publish.
> add courseId to browser routes

- src/components/task-step/all-steps.cjsx
- src/components/task-step/index.cjsx
The video shows up (bug) and has a link to the video below.
I think the video should not show up because the whole `<iframe>` should be removed but it works for now.
> Add video step

- src/router.coffee
No UI changes.
makes the last slash in the practice URL optional like the rest of the routes
> fix practice route

- Gulpfile.coffee
- package.json
No UI Changes.
fixes `gulp prod` by not trying to import external fonts while minifying the CSS.
@gregfitch
> Fix gulp prod

- src/components/task-plan/reading.cjsx
moves the title into the panel header
> tweak panel styling

- src/components/task-step/ends.cjsx
- src/components/task/index.cjsx
No UI changes, but should work for different task types now, including type: reading
> making end panel type more flexible and forgiving of different task types

- src/api.coffee
- src/flux/task.coffee
No UI changes, fixes bug  when completing a task and then trying to load the task list again results in:
* Uncaught Error: BUG: Steps not loaded (task.coffee:66) as reported by @kevinburleigh75
> fixing bug where a task step setAnswerId mistakenly loads as a task

- api/steps/step-id-1-1.json
- api/steps/step-id-2-1.json
- api/steps/step-id-3-1.json
- src/api.coffee
- src/components/loadable-item.cjsx
- src/components/task/index.cjsx
- src/flux/helpers.coffee
- src/flux/task-step.coffee
force load from steps api when initial task load from server api does not allow full access to step contents.  you could see this error particularly when you sign in as no_history on tutor_server and then attempt to complete a task.
No UI changes.  have tested through using both client stub and server data, and karma tests
> force load steps from steps api when needed

- test/components/helpers/router.coffee
- test/components/helpers/task-checks.coffee
- test/components/helpers/task.coffee
- test/components/helpers/utilites.coffee
- test/components/practice.spec.coffee
- test/components/task.spec.coffee
> Tests clean-up, and an attempt to woo Travis

- src/api.coffee
- src/components/index.cjsx
- src/components/practice-button.cjsx
- src/components/task-plan/guide.cjsx
- src/components/task-step/ends.cjsx
No UI changes, just putting things in place for when guide server side is working and these practice buttons can render.
> linking up practice button on crude guide to post with page_ids

- api/courses.json
Adds a dashboard with course list for local mock data. Used for testing
> add mock course list data

- style/reading.less
- style/reading/links-to-physics.less
- style/reading/tips-for-success.less
- style/reading/work-in-physics.less
> Remove parentheses around variable names

- src/components/learning-guide-chart.coffee
- src/components/learning-guide.cjsx
- style/learning-guide.less
> practice link and button nav, display title in chart and footer

- package.json
- src/components/markdown.cjsx
Related to https://nodesecurity.io/advisories/marked_redos
> replace insecure marked package

- style/react-widgets.less
- style/reading.less
- style/tutor.less
No UI Changes.
Importing LESS files was inconsistent. This aims to consolidate the format.
> consolidate LESS import syntax

- src/components/dialog.cjsx
> add a generic dialog component

- .travis.yml
No UI Changes.
http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
> Speed up Travis by not using sudo and caching packages

- src/components/loadable.cjsx
No UI changes.
Thanks @jivewise and @pandafulmanda for providing reproducible steps!
> fix InvariantViolation when switching screens

- src/components/task-plan/teacher-task-plans-listing.cjsx
- style/calendar.less
Adds a "Loading" screen until the calendar has loaded and removed some LESS variable interpolation in the calendar.
This is a PR to #111
> tweak calendar styling and loading

- README.md
This PR needs to be reviewed by someone who knows more about `npm` and `gulp` than I do.
> add instructions to README for handling local updates

- src/components/task-plan/homework.cjsx
- style/homework.less
> Pin Exercise Summary on Scroll

- api/courses/1/performance.json
- src/api.coffee
- src/components/performance.cjsx
- src/flux/performance.coffee
- src/router.cjsx
Welcome to JP's learning experience.  This PR adds a basic version of the teacher's view of the performance book.  I pretty much copied and pasted work from the rest of the frontend team, so cheers to y'all ;-).  
I winged it on the div classes (not knowing the rules there), didn't add any styling, and definitely didn't add tests.  
But it does print the table from the mock API data, so I'm declaring a partial victory :-)
> WIP initial draft of teacher performance book

- coffeelint.json
- src/components/-old-exercise.cjsx
- src/components/app.cjsx
- src/components/html.cjsx
- src/components/index.cjsx
- src/flux/course.coffee
- src/flux/current-user.coffee
- src/flux/exercise.coffee
- src/flux/helpers.coffee
- src/flux/task-plan.coffee
- src/flux/task.coffee
- src/flux/teacher-task-plan.coffee
- src/flux/toc.coffee
No UI Changes.
Fixes lint warnings from common components and flux stores.
> Fix lint warnings from common components and flux stores

- style/typography.less
No UI changes.
changes `@import url('http://...')` to `@import url('//...')` so fonts load securely
> load fonts securely

- src/components/task-step/ends.cjsx
- src/components/task-step/exercise-multiple-choice.cjsx
- src/components/task-step/index.cjsx
- src/flux/task.coffee
- src/helpers/policies/utils.coffee
- style/task-step.less
- test/all-tests.coffee
- test/components/helpers/task/checks.coffee
- test/components/task-homework-past-due.spec.coffee
- test/step-panel-policy.spec.coffee
> Homework end with appropriate message and review on past due

- src/components/index.cjsx
- src/components/student-dashboard/dashboard.cjsx
- src/router.cjsx
Also, Moves the “Practice” button to the student dashboard
> remove old task list and move practice button

- src/components/student-dashboard/all-events-by-week.cjsx
- src/components/student-dashboard/dashboard.cjsx
- src/components/student-dashboard/event-row.cjsx
- src/components/student-dashboard/events-panel.cjsx
- src/components/student-dashboard/homework-row.cjsx
- src/components/student-dashboard/reading-row.cjsx
- src/components/student-dashboard/upcoming-panel.cjsx
- src/flux/student-dashboard.coffee
- style/student-dashboard.less
- test/components/student-dashboard.spec.coffee
Also fixed a few things so the dashboard conforms to the notes that were transcribed during it's review, mainly that the Upcoming panel was just showing only next week,not all future tasks.
Also fixes a few lint warnings
> Link tasks to viewTask route so they can be worked

- src/components/performance.cjsx
> added awareness of 'not_started' status in the performance book

- src/components/task-step/ends.cjsx
instead of tutor dashboard.
No UI changes
> send student back to course dashboard

- src/components/task-plan/homework.cjsx
> Fixing homework due date when coming from the calendar

- src/components/task-plan/reading-stats.cjsx
> reading-stats lint

- src/components/task-plan/guide.cjsx
this page is not active, but was showing lint errror anyway, so linted.
> crude guide lint

- Gulpfile.coffee
> include fonts in production archive

- Gulpfile.coffee
> remove url warnings from tests

- src/components/index.cjsx
- src/components/question.cjsx
- test/time.spec.coffee
> fix accidental double to single quote conversions

- src/helpers/policies/policies.coffee
- src/helpers/policies/utils.coffee
no ui changes.
noticed that backend is return task type chapter_practice.  policies need to accomodate
> make missing policy for task type explicit, update policies to include chapter_practice

- src/helpers/policies/policies.coffee
- src/helpers/policies/utils.coffee
no ui changes.
just makes it so that we dont need to define a new policy for every new task type.
> set a default policy for task steps by step types

- src/components/learning-guide-chart.coffee
This adds new resource path helper to PLANE_PATH
> lg updated resource path

- api/courses.json
- src/components/index.cjsx
currently having transitionTo in render causes errors, not sure if its the where I call transitionTo or maybe how.
> WIP: 1 course / 1 role redirect from dashboard

- src/components/task-plan/footer.cjsx
- src/components/task-plan/homework/exercises.cjsx
- src/components/task-plan/index.cjsx
- src/components/task-plan/reading.cjsx
- src/flux/exercise.coffee
> General exercises code clean up

- README.md
No UI Changes.
for testing without starting up a production VM
> add instructions for production-like config

- Gulpfile.coffee
- resources/styles/mixins.less
- src/components/learning-guide-chart.coffee
- src/flux/app-config.coffee
- test/all-tests.coffee
- test/app-config.spec.coffee
> Fix assets serving under production

- src/components/loadable-item.cjsx
- src/components/task-plan/teacher-task-plans-listing.cjsx
- src/flux/exercise.coffee
- src/flux/helpers.coffee
- test/components/course-calendar.spec.coffee
- test/components/homework/homework-plan.spec.coffee
- test/components/practice.spec.coffee
- test/components/student-dashboard.spec.coffee
- test/components/task-homework-past-due.spec.coffee
- test/components/task-homework.spec.coffee
- test/components/task.spec.coffee
Student:
- Doing part of an iReading and then going back to the course list shows updated data
Teacher:
- Editing the title of a HW and going back to the calendar should show the new title
> reload an item when mounted so updates are seen

- api/user.json
- src/components/navbar/index.cjsx
- src/flux/current-user.coffee
Couldn't figure out how to add a navbar test for admins...
Depends on https://github.com/openstax/tutor-server/pull/257 "Return whether user is an admin in /api/user"
> Add "Admin Console" link in navbar dropdown if user is an admin

- src/api.coffee
- src/components/task-plan/footer.cjsx
- src/components/task-plan/reading.cjsx
- src/flux/task-plan.coffee
- test/DEBUG_README.md
- test/components/reading-plan.spec.coffee
- test/karma.config.coffee
Removed save button, stats link and making publish button save first, then publish.
> Making publish button save and publish

- resources/styles/components/course-calendar/month.less
- src/components/course-calendar/month.cjsx
> fix hiding add homework and reading dropdown on calendar

- resources/styles/components/pinned-header-footer-card/sections.less
- src/components/pinned-header-footer-card/index.cjsx
- src/components/pinned-header-footer-card/sections.cjsx
- src/components/task-step/ends.cjsx
- src/components/task-step/exercise/index.cjsx
- src/components/task-step/step-mixin.cjsx
i feel like back to dashboard should be a secondary button
> homework review page continue buttons shouldn't pin

- resources/styles/components/question.less
- src/components/question.cjsx
> fix answer re-lettering on feedback showing bug

- resources/styles/components/course-calendar/month.less
- resources/styles/components/task-plan/reading-stats.less
- src/components/course-calendar/header.cjsx
- src/components/course-calendar/index.cjsx
- src/components/course-calendar/month.cjsx
- src/components/task-plan/reading-stats.cjsx
- test/components/course-calendar.spec.coffee
- test/components/helpers/calendar/checks.coffee
- test/components/task-homework.spec.coffee
- test/step-panel-policy.spec.coffee
quick styles around current, past, and future dates, to set up logic needed for when styles are finalized
> Quick calendar styles

- resources/styles/components/book-content.less
- resources/styles/components/pinned-header-footer-card/sections.less
- resources/styles/components/task-step/reading.less
- resources/styles/variables/colors.less
- src/components/task-step/all-steps.cjsx
Objectives now:
Overlay on splash image:
> IReading visual design

- src/flux/current-user.coffee
- src/router.cjsx
- test/components/navbar.spec.coffee
- test/current-user-store.spec.coffee
and add it to the hamburger menu
> move performance book to a teacher route

- api/steps/step-id-4-2.json
- api/steps/step-id-4-2/recovery/PUT.json
- api/tasks/4-recovered.json
- src/api.coffee
- src/components/task-step/exercise/modes.cjsx
- src/components/task/index.cjsx
- src/flux/task-step.coffee
- test/components/helpers/task/actions.coffee
- test/components/helpers/task/checks.coffee
- test/components/task.spec.coffee
> makes sure load recovery happens in exactly the right order

- index.coffee
- src/components/loadable-item.cjsx
- src/components/loadable.cjsx
- src/flux/helpers.coffee
- src/flux/toc.coffee
Pages will silently update if successful and error loudly otherwise.
> do not show "loading..." if local data is available

- api/steps/step-id-4-2.json
- api/tasks/4-recovered.json
- api/tasks/4.json
- src/components/task-step/exercise/group.cjsx
- test/components/helpers/task/checks.coffee
@kevinburleigh75, in preparation for switch from "spaced practice" to "spaced_practice"
> handle both spaced_practice and space practice for transition

- resources/styles/components/pinned-header-footer-card/index.less
- resources/styles/components/task/details.less
> fix breadcrumb bar nav height things

- resources/styles/components/course-calendar/header.less
- resources/styles/components/course-calendar/index.less
- resources/styles/components/course-calendar/month.less
- resources/styles/components/course-calendar/plan-details.less
- resources/styles/components/course-calendar/plan.less
- resources/styles/components/task-plan/reading-stats.less
- resources/styles/variables/colors.less
- src/components/course-calendar/header.cjsx
- src/components/course-calendar/month.cjsx
- src/components/course-calendar/plan.cjsx
- test/components/course-calendar.spec.coffee
> Calendar styles

- src/components/student-dashboard/event-row.cjsx
- src/components/task/index.cjsx
- src/router.cjsx
No UI Changes.
Thoughts @nathanstitt since I think you introduced the step index in the URL
> add steps to task URL

- resources/styles/components/task-step/reading/book-content/index.less
- src/components/task-step/all-steps.cjsx
> Rename css class to tutor-ui-overlay for splash image overlays

- resources/styles/components/task-step/all-steps.less
- resources/styles/components/task-step/reading.less
- resources/styles/components/task-step/reading/video.less
- resources/styles/components/task-step/video.less
- resources/styles/tutor.less
- src/components/task-step/all-steps.cjsx
@Fredasaurus: Not sure about what's intended for the "Visit Video" button.  It used to be a text link that just said "video" and appeared directly under the video.  Perhaps it should be hidden altogether?
> Video styles for iReading

- resources/styles/components/task-step/reading/book-content/index.less
- resources/styles/components/task-step/reading/book-content/work-in-physics.less
> Work in Physics styles

- resources/styles/components/question.less
- resources/styles/variables.less
- src/components/html.cjsx
- src/components/question.cjsx
- src/components/task-step/exercise/free-response.cjsx
- src/components/task-step/exercise/modes.cjsx
- test/components/helpers/task/checks.coffee
removes the need to individually adjust each label margin-left
> styles refactoring for answer and label alignments, minor style changes

- src/components/task-step/exercise/modes.cjsx
- src/components/task/breadcrumb.cjsx
- src/components/task/index.cjsx
- src/flux/task-step.coffee
- test/components/helpers/task/actions.coffee
- test/components/helpers/task/checks.coffee
- test/components/task-homework.spec.coffee
@kevinburleigh75 i shake my fist at you
> Fix placeholder "?" breadcrumb to update as soon as it's available

- src/flux/task-plan.coffee
removes `exercise_ids` from iReadings
> fix iReading publish

- resources/styles/components/student-dashboard.less
- resources/styles/components/student-dashboard/dashboard.less
- resources/styles/components/student-dashboard/dont-forget-panel.less
- resources/styles/components/student-dashboard/empty-panel.less
- resources/styles/components/student-dashboard/panel.less
- resources/styles/components/student-dashboard/task.less
- resources/styles/variables.less
- src/components/student-dashboard/event-row.cjsx
- src/components/student-dashboard/events-panel.cjsx
Lots of little alignment tweaks
> Dashboard spacing / sizing fixes

- resources/styles/components/task-step/reading.less
- resources/styles/components/task-step/reading/interactive.less
- src/components/task-step/all-steps.cjsx
TODO: (In a different PR) Figure out cross iframe communication so the iframe can resize to fit content.  Not sure if content will be same-origin but suspect not
> Style iframe on sims to be 100% and height 800px

- resources/styles/components/task-step/video.less
- resources/styles/mixins.less
- resources/styles/variables.less
> Set size of iframe for .ost-video

- resources/styles/components/task-step/reading/book-content/fun-in-physics.less
- resources/styles/components/task-step/reading/book-content/index.less
- resources/styles/components/task-step/reading/book-content/work-in-physics.less
- resources/styles/components/task-step/reading/watch-physics.less
> Style fun in physics, use @tutor-card-body-padding-horizontal

- resources/styles/components/task-plan/chapter-section.less
- resources/styles/components/task-plan/index.less
- resources/styles/components/task-plan/select-topics.less
- src/components/task-plan/homework/exercises.cjsx
- src/components/task-plan/select-topics.cjsx
> Select reading cancel button and chapter select logic

- resources/styles/components/task-plan/homework/exercises.less
- src/components/task-plan/homework/exercises.cjsx
- src/flux/exercise.coffee
Putting exercise LO on it's own line.
> Exercise Card LO Display

- resources/styles/components/task-plan/homework/exercises.less
> Correct Answer Check Mark on Exercise Selector

- bower.json
- resources/styles/components/task-plan/homework.less
- resources/styles/global/material-form-wrapper.less
- resources/styles/tutor.less
- src/components/task-plan/homework.cjsx
- src/components/tutor-input.cjsx
Making homework match styles sent over by @Fredasaurus
> New Homework Styles

- resources/styles/components/task-plan/reading.less
- src/components/task-plan/reading.cjsx
- src/components/tutor-input.cjsx
- src/flux/task-plan.coffee
Making iReading builder match styles sent over by @Fredasaurus
> New iReading Builder Styles

- resources/styles/components/learning-guide.less
- resources/styles/global/typography.less
- src/components/learning-guide-chart.coffee
safari fixes - fixed font size and parentNode bug in Safari8
> learning guide fixes

- resources/styles/components/student-dashboard/task.less
- resources/styles/components/task/breadcrumbs.less
- resources/styles/mixins.less
- resources/styles/old/global/icons.less
has drop-shadow and transition
> using the same animation for hover of dashboard icons and breadcrumbs

- src/components/learning-guide-chart.coffee
- src/components/learning-guide.cjsx
fixes bug in displaying string version of chapter_section in panel
> fixed chapter_section format in panel when not array

- package.json
- src/components/navbar/index.cjsx
> Update react-bootstrap for their progress bar fix

- src/components/course-calendar/duration.cjsx
> fix tasks on calendar overlap issue

- src/components/task-step/ends.cjsx
styling is not the best, but i think the workflow is improved
> makes it more obvious when student is transitioning from problems to review page on past due homeworks

- api/plans/1/stats.json
- api/plans/13/stats.json
- api/plans/2/stats.json
- api/plans/3/stats.json
- api/plans/5/stats.json
- api/plans/6/stats.json
- api/plans/7/stats.json
- api/plans/8/stats.json
- api/plans/9/stats.json
- src/components/chapter-section-mixin.cjsx
- src/components/learning-guide.cjsx
- src/components/task-plan/reading-stats.cjsx
@nathanstitt @darrenmason i changed something in learning guide and I checked that it's still working, but please confirm
uses openstax/tutor-server#301
> Fix for chapter sections on stats

- resources/styles/components/course-calendar/add.less
- resources/styles/components/course-calendar/index.less
- resources/styles/components/course-calendar/month.less
- src/components/course-calendar/add.cjsx
- src/components/course-calendar/month.cjsx
- test/components/course-calendar.spec.coffee
- test/components/helpers/calendar/actions.coffee
- test/components/helpers/calendar/checks.coffee
> dropdown on calendar will check if adding to that date is allowed

- resources/styles/components/question.less
> safari webkit-box prefixer

- resources/styles/components/task-step/exercise/group.less
- resources/styles/old/global/icons.less
- src/components/task-step/exercise/group.cjsx
- need to ask how small
- related to #290
@Fredasaurus, any questions?
> Group label styling fixes

- api/courses/1/dashboard.json
- src/components/student-dashboard/reading-row.cjsx
- test/components/student-dashboard.spec.coffee
Was using incorrect attribute for determining reading status.
> Correct progress display for readings

- src/flux/student-dashboard.coffee
No UI changes are visible for me.  When I view the dashboard the events are always sent by the backend in due_at order.
However they must not be in some cases since the issue was reported during testing. I'm guessing that the DB on the the production server may sort differently in some cases.  
This also removes the check for the nonexistent data.exams key and uses _.groupBy vs my earlier adhoc implementation of it.
> Sort each weeks events when reading them

- src/components/task-step/ends.cjsx
> reword to back to dashboard to return to flight path, make secondary

- resources/styles/global/material-form-wrapper.less
- src/components/task-plan/homework.cjsx
- src/components/task-plan/plan-mixin.coffee
- src/components/task-plan/reading.cjsx
- src/components/tutor-input.cjsx
Textarea autoexpands.  Still flickers sometimes, but it seems fairly functional for now.
> Tutor Textarea auto expand

- src/components/task-step/exercise/index.cjsx
- src/components/task-step/exercise/modes.cjsx
- src/components/task/index.cjsx
Skips the step where the user chose to refresh their memory
> skip step that triggers memory refresh

- resources/styles/components/course-calendar/plan.less
- src/components/course-calendar/add-menu-mixin.cjsx
Make match http://mockups.openstax.org/Tutor_MVP_v2/start.html#p=course_calendar_-_teacher_-_visual_design
> Calendar UI Tweaks

- resources/styles/components/learning-guide.less
- src/components/learning-guide-chart.coffee
- src/components/learning-guide.cjsx
- src/components/practice-button.cjsx
Overview guide:
Per section guide:
> Learning guide footer

- resources/styles/components/task-step/ends.less
- resources/styles/mixins.less
- src/components/task-step/ends.cjsx
- src/flux/task.coffee
This shows different messages depending on how many questions are correct for readings and practices.
all correct: Great job, all questions answered correctly!
1 incorrect: Good job, only 1 question incorrect!
anything else:  <#incorrect> questions were incorrect, try harder next time
> Don't over praise when questions are incorrect

- resources/styles/global/progress-bars.less
- resources/styles/tutor.less
- src/components/task-plan/reading-stats.cjsx
Need to check with @Fredasaurus
> striped incorrect for further differentiation for color-blindness

- src/components/task-plan/homework.cjsx
- src/components/task-plan/plan-mixin.coffee
- src/components/task-plan/reading.cjsx
- src/components/tutor-input.cjsx
- test/components/homework/homework-plan.spec.coffee
> Calendar auto expand

- src/components/task-plan/homework.cjsx
- src/components/task-plan/reading.cjsx
- src/components/tutor-input.cjsx
- test/components/homework/homework-plan.spec.coffee
Reverts openstax/tutor-js#300
Causes a 422 error when publishing a new iReading
> Revert "Calendar auto expand"

- src/components/task-plan/homework.cjsx
- src/components/task-plan/reading.cjsx
- src/components/tutor-input.cjsx
- test/components/homework/homework-plan.spec.coffee
Another PR for date picker auto-expand.
> Datepicker Auto Expand

- src/components/task-step/ends.cjsx
- src/flux/task.coffee
iReadings show "Great job completing all the steps", others say "Great job answering all the questions"
> Everyone does a great job

- resources/styles/global/forms.less
- src/components/task-step/exercise/modes.cjsx
- src/components/task-step/step-mixin.cjsx
Disable continue button and show a spinner with "Loading ..." message while store is loading.
> Exercise loading indication

- src/components/learning-guide.cjsx
the main button now navigates to dashboard from overall
> restored 'back to dash' button

- resources/styles/global/navbar.less
- src/components/navbar/index.cjsx
No longer is upper case and no longer has an exclamation
> style sign out button

- src/flux/exercise.coffee
- src/flux/task-plan.coffee
- src/flux/toc.coffee
> Smarter exercise builder

- src/components/course-calendar/add.cjsx
- src/components/course-calendar/month.cjsx
- test/components/course-calendar.spec.coffee
- test/components/helpers/calendar/actions.coffee
- test/components/helpers/calendar/checks.coffee
> Dont allow adding to today

- src/components/pinned-header-footer-card/index.cjsx
- src/components/task/index.cjsx
> Handle back on task steps

- resources/styles/components/task-plan/reading.less
- resources/styles/components/task-plan/select-topics.less
- src/components/task-plan/reading.cjsx
- src/components/task-plan/select-topics.cjsx
- src/flux/exercise.coffee
- src/flux/task-plan.coffee
> Select Topics Sorting

- resources/images/icons/icon-worked-example.svg
- resources/styles/old/global/icons.less
- src/components/task/breadcrumb.cjsx
> add worked-example icon for breadcrumb

- resources/styles/components/pinned-header-footer-card/index.less
- resources/styles/global/scaffold.less
- src/components/pinned-header-footer-card/index.cjsx
- src/components/task/index.cjsx
- src/router.cjsx
scroll is at top on first load
scroll is at buffer point, making nav shy, on changing step
> force shy nav on task step through

- resources/styles/book-content/tips-for-success.less
- resources/styles/components/task-step/all-steps.less
making the border and background on tips for success simpler.
> Ireading style polish - cleanup of tip-for success

- resources/styles/components/task-plan/reading.less
- resources/styles/components/task-plan/select-topics.less
- src/components/task-plan/homework.cjsx
- src/components/task-plan/homework/exercise-summary.cjsx
- src/components/task-plan/plan-mixin.coffee
- src/components/task-plan/reading.cjsx
- src/components/task-plan/select-topics.cjsx
- src/components/tutor-input.cjsx
- src/flux/exercise.coffee
- src/flux/task-plan.coffee
> Homework footer logic

- src/components/student-dashboard/homework-row.cjsx
- test/components/student-dashboard.spec.coffee
> Change homework to read x/x answered before due date

- resources/styles/components/task-plan/homework/exercises.less
> fit img in HW question, display block, center

- resources/styles/components/task-plan/homework/exercises.less
- src/components/task-plan/homework/exercises.cjsx
> Hide images from exercise summary table

- resources/styles/components/student-dashboard/dashboard.less
- resources/styles/components/student-dashboard/panel.less
> Making labels consistent and aligned

- src/components/performance.cjsx
- src/flux/current-user.coffee
- test/components/navbar.spec.coffee
- test/current-user-store.spec.coffee
changes perfbook name on page and dropdown menu.
adds coming soon message to perf report.
> perfbook rename and coming soon message

- src/components/performance.cjsx
This removes NaN error in perfbook when average number not available
> NaN fix for average row

- src/api.coffee
> Use X-App-Date header

- src/components/task-plan/homework/exercise-summary.cjsx
Updating "Problems Selected" label to be "Total Problems"
> Updating "Problems Selected" label text

- resources/styles/components/course-calendar/plan.less
- src/components/course-calendar/plan.cjsx
> plan title should have ellipsis when it's too long to show initially

- api/courses/1/performance.json
- resources/styles/components/performance.less
- resources/styles/tutor.less
- src/components/performance.cjsx
- src/flux/current-user.coffee
- test/components/navbar.spec.coffee
- test/current-user-store.spec.coffee
Some initial layout ideas.  Long header names could be truncated with tooltips are simply shortened.  Overflow could handle horizontal scrolling
> performance report layout and styling

- resources/styles/components/course-calendar/plan.less
- src/api.coffee
- src/components/course-calendar/plan.cjsx
- src/components/performance.cjsx
- src/components/task-plan/homework/exercise-summary.cjsx
Bring changes made for alpha into master.
- show ellipses for long titles in calendar
- timecop server date
> Alpha to master

- src/components/course-periods-nav.cjsx
fixes the bug where the stats and nav are out of sync
> set course period for nav on load

- resources/styles/components/tutor-input.less
> Fix Broken Required Styles

- api/courses/1.json
- api/plans/1/stats.json
- api/plans/13/stats.json
- api/plans/2/stats.json
- api/plans/3/stats.json
- api/plans/4/review.json
- api/plans/4/stats.json
- api/plans/5/review.json
- api/plans/5/stats.json
- api/plans/6/stats.json
- api/plans/7/stats.json
- api/plans/8/stats.json
- api/plans/9/stats.json
- api/user/courses.json
- src/components/course-calendar/plan-details.cjsx
- src/components/task-plan/reading-stats.cjsx
- src/components/task-teacher-review/crumb-mixin.cjsx
- src/flux/task-teacher-review.coffee
- test/components/helpers/calendar/checks.coffee
from ```periods``` to ```stats``` with period_id, quick update from using transition to to router.Link on calendar modal
BE: openstax/tutor-server#390
> update stats and review stub json to match api change

- package.json
- resources/styles/components/tutor-input.less
- resources/styles/global/react-datepicker.less
- resources/styles/tutor.less
- src/components/task-plan/builder.cjsx
- src/components/task-plan/reading.cjsx
- src/components/tutor-input.cjsx
> New datepicker

- src/api.coffee
- src/components/task-plan/plan-mixin.coffee
- src/flux/task-plan.coffee
> Publish api changes

- resources/styles/components/task-plan/select-topics.less
- src/components/reference-book/index.cjsx
- src/components/reference-book/page.cjsx
- src/components/reference-book/toc.cjsx
- src/components/task-plan/select-topics.cjsx
- src/flux/reference-book.coffee
- src/router.cjsx
Adds links to the topic selector to jump to the related chapter in the book.
> Browse book link for teacher task builder

- src/flux/exercise.coffee
> Sorting exericise builder by chapter and section

- src/components/close.cjsx
- src/components/navbar/signout.cjsx
No UI changes other than the console's a bit quieter.
> Silence a few React warnings

- resources/styles/components/question.less
- resources/styles/components/task-step/index.less
- resources/styles/components/task-step/step-footer-mixin.less
- resources/styles/components/task-step/step-mixin.less
- resources/styles/components/task/index.less
- resources/styles/tutor.less
- src/components/performance.cjsx
- src/components/task-step/all-steps.cjsx
- src/components/task-step/ends.cjsx
- src/components/task-step/exercise/index.cjsx
- src/components/task-step/exercise/modes.cjsx
- src/components/task-step/index.cjsx
- src/components/task-step/step-footer-mixin.cjsx
- src/components/task-step/step-mixin.cjsx
- src/components/task/index.cjsx
- src/components/task/viewing-as-student-name.cjsx
- src/flux/current-user.coffee
- src/flux/performance.coffee
- src/flux/task.coffee
- src/helpers/policies/index.coffee
- src/helpers/policies/policies.coffee
- src/helpers/policies/utils.coffee
> Teacher viewing tasks for individual student

- src/components/resize-listener-mixin.cjsx
- src/components/smart-overflow.cjsx
* no setting nextState in component will update
* no using delay to set a state change on the event queue
> refactor sneaky parts of smart overflow stats

- api/plans/2.json
- src/flux/task-plan.coffee
Moving description out of the settings object for task plans.
> Updating how description for task plans

- resources/styles/components/performance.less
- src/components/performance.cjsx
course-periods-nav component added, wip: bind to data
> performance report tabs by period

- src/components/performance.cjsx
> performance report: view/switch tabs by period

- resources/styles/book-content/mixins.less
> Making dropcaps scale on browser zoom

- resources/styles/components/task-plan/reading.less
- src/components/task-plan/reading.cjsx
> Validation message for add readings button

- api/courses/1/performance.json
- src/components/course-periods-nav.cjsx
- src/components/task-step/step-footer-mixin.cjsx
- src/components/task/viewing-as-student-name.cjsx
- src/flux/performance.coffee
> fix step footer when viewing as teacher

- resources/styles/components/task-plan/builder.less
- resources/styles/components/tutor-input.less
- src/components/task-plan/builder.cjsx
- src/components/tutor-input.cjsx
- src/flux/task-plan.coffee
> Fix due date/open date on load

- resources/styles/components/task-plan/footer.less
- src/components/task-plan/footer.cjsx
> Footer instruction popover

- resources/styles/global/navbar.less
No visible UI changes. fixes #403
> widen signout button

- resources/styles/components/performance.less
- src/components/performance.cjsx
> link to review page from perf report

- src/components/course-periods-nav.cjsx
possible due to openstax/tutor-server#418
> course nav uses api/courses/courseId route again

- resources/styles/components/task-plan/builder.less
- src/components/task-plan/builder.cjsx
- src/flux/task-plan.coffee
> Period Selection Validation

- src/components/task-step/exercise/free-response.cjsx
> "My answer" free response label was being set to undefined

- resources/styles/components/performance/index.less
- resources/styles/tutor.less
- src/components/performance/index.cjsx
Tweaks, as advised by @Fredasaurus
> performance style tweaks, update style files to match in performance folder

- src/components/task-step/exercise/modes.cjsx
- test/components/helpers/task/checks.coffee
- test/components/task.spec.coffee
> temporarily remove Refresh My Memory

- resources/styles/components/task-teacher-review/question.less
- src/components/task-teacher-review/exercise.cjsx
> handle no student answers on teacher plan review page

- api/courses/1/guide.json
- resources/styles/components/learning-guide.less
- src/components/learning-guide.cjsx
- test/components/learning-guide.spec.coffee
> learning guide - updated design/ui, links, expanding panels

- src/components/task-plan/builder.cjsx
- src/flux/task-plan.coffee
> Fixes for loading periods in task plan

- resources/styles/components/task-plan/reading-stats.less
- resources/styles/components/task-teacher-review/question.less
- resources/styles/old/global/buttons.less
- src/components/question.cjsx
- src/components/task-teacher-review/exercise.cjsx
> style adjustments on homework review

- resources/styles/components/task-plan/builder.less
- resources/styles/components/task-plan/reading.less
- src/components/task-plan/footer.cjsx
- src/components/task-plan/homework.cjsx
- src/components/task-plan/reading.cjsx
- test/components/task-plan/footer.spec.coffee
> Move Select Problems Button

- api/courses/1/dashboard.json
- resources/styles/components/course-calendar/index.less
- resources/styles/components/course-calendar/plan.less
- src/components/course-calendar/duration.cjsx
> use published_at on calendar, style published but not opened plan

- resources/styles/components/task-step/index.less
- resources/styles/components/task-step/reading/interactive.less
> Fix duplicate padding being applied to virtual physics

- resources/styles/components/student-dashboard/task.less
- resources/styles/global/tooltip.less
- resources/styles/tutor.less
- src/components/student-dashboard/event-info-icon.cjsx
- src/components/student-dashboard/event-row.cjsx
- src/components/student-dashboard/homework-row.cjsx
- test/components/student-dashboard.spec.coffee
> Dashboard hw status icons

- resources/styles/components/course-calendar/header.less
> Right align action buttons on header

- src/helpers/task.coffee
- test/all-tests.coffee
- test/task-helpers.spec.coffee
This way the logic can be shared between components and stores as needed
> Add a Task helper with a getLateness method

- src/components/task-plan/builder.cjsx
- src/components/tutor-input.cjsx
- src/flux/task-plan.coffee
> Default Open Date

- src/components/task-plan/builder.cjsx
- src/components/task-plan/footer.cjsx
> no more feedback note for external plan form

- src/components/navbar/index.cjsx
- src/flux/current-user.coffee
- test/components/navbar.spec.coffee
> Add help link to navbar

- resources/styles/components/performance/index.less
- src/components/performance/cell-status-mixin.cjsx
- src/components/performance/external-cell.cjsx
- src/components/performance/homework-cell.cjsx
- src/components/performance/index.cjsx
- src/components/performance/late-icon.cjsx
- src/components/performance/name-cell.cjsx
- src/components/performance/reading-cell.cjsx
- src/components/student-dashboard/event-info-icon.cjsx
This:
* Display late icon and message when task is late
* Add first and last name columns
* sets columns to expand to fit available space. 
* Fixes the header for external assignments to show the 'X of X clicked' message.
The late icon and extern assignments header parts depend on BE PR: https://github.com/openstax/tutor-server/pull/502
> Performance report updates. Cell types, display First/Last name

- resources/styles/components/learning-guide.less
- resources/styles/components/learning-guide/chapter-panel-mixin.less
- src/components/learning-guide/guide.cjsx
- src/components/learning-guide/practice-by-type-button.cjsx
- src/components/learning-guide/progress-bar.cjsx
- src/components/learning-guide/student.cjsx
- src/components/learning-guide/teacher.cjsx
- src/components/student-dashboard/progress-guide.cjsx
> learning guide misc tweaks

- resources/styles/components/student-dashboard/task.less
- src/components/student-dashboard/event-row.cjsx
> Add time to due at date

- resources/styles/components/learning-guide.less
> Scroll large student listing

- resources/styles/components/performance/index.less
- src/components/performance/cell-status-mixin.cjsx
- src/components/performance/index.cjsx
- src/components/performance/name-cell.cjsx
- src/components/performance/sorting-header.cjsx
* Adds due dates to the column headers
* Formats the name columns a little narrower
* Fixes sorting by names
> Perf report due date

- resources/images/icons/icon-external.svg
- resources/styles/old/global/icons.less
- src/components/student-dashboard/events-panel.cjsx
- src/components/student-dashboard/external-row.cjsx
> add external row and icon to dashboard

- src/components/task-plan/builder.cjsx
> feedback note on builder is only for homework

- src/components/course-calendar/add.cjsx
- test/components/course-calendar.spec.coffee
- test/components/helpers/calendar/checks.coffee
> add menu works for today,tests updates to match

- src/flux/task-plan.coffee
> dont do new date with null value

- resources/styles/components/course-listings.less
- resources/styles/global/tutor-booksplash-background.less
- resources/styles/mixins.less
- resources/styles/tutor.less
- src/components/course-listing.cjsx
- test/components/course-listing.spec.coffee
My loose interpretation of what @Fredasaurus suggested
> course list restyling with specs update

- src/flux/current-user.coffee
- test/components/navbar.spec.coffee
- test/current-user-store.spec.coffee
> Add "Browse the Book" to teacher & student menu

- resources/styles/components/performance/index.less
- src/components/performance/index.cjsx
- src/components/performance/name-cell.cjsx
> Render combined name in one column, sort by last_name

- resources/styles/components/reference-book/navbar.less
- src/components/reference-book/navbar.cjsx
> Change logo to not be a link on reference book

- src/components/student-dashboard/event-row.cjsx
- src/components/student-dashboard/events-panel.cjsx
> Move due time to panel headings on student dashboard

- test/all-tests.coffee
- test/components/tutor-input.spec.coffee
> tests for for single date input and multiple date input

- api/courses/1.json
- test/components/course-periods-nav.spec.coffee
> course ordering tests for the course periods nav

- src/components/navbar/index.cjsx
The course name in the nav is one step behind from the routes update somehow...
> update nav course name when courses are loaded and route has courseId params

- src/components/app.cjsx
- src/components/buttons/back-button.cjsx
- src/components/task-step/ends.cjsx
- src/components/task-teacher-review/breadcrumbs.cjsx
- src/flux/transition.coffee
- src/helpers/routes-and-destinations.coffee
Also gets rid of "Back to Flight Path" bug/text :bug: 
Tests will be in a separate PR
> back button with fallback link option for when there is no browser history

- src/components/learning-guide/guide.cjsx
- src/components/learning-guide/student.cjsx
- src/components/learning-guide/teacher-student.cjsx
- src/components/learning-guide/teacher.cjsx
> learning guide - message if no assignments worked

- src/components/performance/export.cjsx
- src/flux/performance-export.coffee
No UI change except the isWaiting maps properly now to statuses from the job as well
> Export button behavior matching export job status

- src/components/task-plan/builder.cjsx
- src/flux/task-plan.coffee
* open date was not automatically setting
* December 1969 bug
> builder was not getting default open date

- src/components/course-calendar/plan.cjsx
- src/flux/job.coffee
- src/flux/performance-export.coffee
- src/flux/plan-publish.coffee
Updates ```state``` to ```status``` when looking at jobs, matches BE PR openstax/tutor-server#535
> update state to status to make BE update for the jobs api

- resources/styles/components/learning-guide.less
- src/components/learning-guide/guide.cjsx
> subheading text, align main title

- src/components/task-step/exercise/modes.cjsx
> free response cannot be empty spaces

- src/components/task-plan/builder.cjsx
- src/flux/task-plan.coffee
Or to 1 day past the opens_at whichever is greater.
> Set the minimum value for due_at to 1 day in future

- resources/styles/components/tutor-input.less
- src/components/task-plan/builder.cjsx
- src/components/tutor-input.cjsx
Hard to get a screenshot of the disabled field...we don't really have disabled styles right now...
> Disables opens at once plan is visible

- src/components/course-settings/period-roster.cjsx
Teacher should not see the researcher id. From Micaela: "Against policy". 
Maybe a BE update to the api @jpslav?
> remove random id

- src/components/course-periods-nav.cjsx
- src/components/plan-stats/index.cjsx
- src/flux/course.coffee
- src/flux/task-plan-stats.coffee
> start moving periods sorting logic to stores, stats need to initialize review period on load

- src/components/task-plan/builder.cjsx
> Disabling selecting periods when plan is visible

- resources/styles/book-content/learning-objectives.less
- resources/styles/components/question.less
- resources/styles/components/reference-book/page-navigation-controls.less
- resources/styles/components/task-step/step-footer-mixin.less
- resources/styles/components/task-teacher-review/question.less
- resources/styles/mixins.less
Thoughts @philschatz and rest of FE team?
If this looks good I'll switch out the remainder of the places we use flexbox with this.
> Flexbox mixin with webkit and ie vendor prefixes

- resources/styles/book-content/index.less
- resources/styles/book-content/os-teacher.less
- resources/styles/book-content/theming-mixins.less
Removed os-teacher from theming mixin, added style specific to os-teacher feature
> adding universal colors for teacher edition

- resources/styles/components/student-dashboard/dashboard.less
- resources/styles/components/student-dashboard/progress-guide.less
> quick type fixes, book backgrounds

- resources/styles/components/learning-guide/guide-key-mixin.less
- resources/styles/components/reference-book/page-navigation-controls.less
- resources/styles/mixins/flexbox.less
Fixes 
**refbook arrows**
**Guide key alignment**
> Style tweaks for IE 10

- index.coffee
- resources/styles/components/tutor-dialog.less
- resources/styles/tutor.less
- src/api.coffee
- src/components/navbar/index.cjsx
- src/components/navbar/server-error-monitoring.cjsx
- src/flux/app.coffee
> add server 40x and 50x errors to show to the user

- resources/styles/book-content/index.less
- resources/styles/book-content/questions.less
- resources/styles/components/reference-book/page.less
I used .ost-chapter-review to target every chapter review type. Let me know if it would be best to target each class individually to avoid using .ost- classes
> Adding numbering to questions in Reference View

- src/components/navbar/index.cjsx
regarding ticket:
https://www.pivotaltracker.com/n/projects/1156756/stories/100940050
> menu under the class picker now includes the My Account link

- resources/styles/components/reference-book/page.less
> Clearing h2 for real

- resources/styles/components/course-listings.less
teehehehe the branch name is just for funnies.
> Fix the course listings

- resources/styles/components/task-step/ends.less
- resources/styles/components/task/breadcrumbs.less
- src/components/task-step/ends.cjsx
- src/flux/task.coffee
- src/helpers/policies/policies.coffee
> handle page_practice type like other practice, breadcrumb/task behavior

- src/components/navbar/account-link.cjsx
Regarding issue:  https://www.pivotaltracker.com/n/projects/1156756/stories/101144278
> Bug: No way to come back to dashboard after click on Account

- resources/styles/old/global/buttons.less
> more disabled button

- resources/styles/components/question.less
- resources/styles/components/task-teacher-review/question.less
- src/components/course-periods-nav.cjsx
- src/components/question.cjsx
See openstax/tutor-server#585 for period name being too long
> Review summary minor visual fixes

- resources/styles/book-content/index.less
> adding back in target highlight from link, and external link icon style

- api/courses/1.json
- api/user/courses.json
- api/user/courses/1.json
- src/api.coffee
- src/components/buttons/browse-the-book.cjsx
- src/components/navbar/index.cjsx
- src/components/reference-book/index.cjsx
- src/components/reference-book/navbar.cjsx
- src/components/reference-book/page.cjsx
- src/components/reference-book/reference-book.cjsx
- src/components/reference-book/toc.cjsx
- src/components/student-dashboard/progress-guide.cjsx
- src/components/task-plan/select-topics.cjsx
- src/flux/current-user.coffee
- src/flux/learning-guide.coffee
- src/flux/reference-book.coffee
- src/router.cjsx
- test/all-tests.coffee
- test/components/buttons/browse-the-book.spec.coffee
- test/components/course-calendar.spec.coffee
- test/components/helpers/component-testing.coffee
- test/components/navbar.spec.coffee
- test/components/student-dashboard.spec.coffee
- test/courses-test-data.coffee
- test/current-user-store.spec.coffee
Companion to https://github.com/openstax/tutor-server/pull/580, needs openstax/tutor-server#595 as well
> Use book_id for loading the reference book

- src/components/navbar/index.cjsx
- src/flux/current-user.coffee
- test/components/navbar.spec.coffee
- test/current-user-store.spec.coffee
No UI changes, other than the link now uses the `BrowseTheBook` component so it opens in a new tab.
> Open reference book in new tab

- resources/styles/variables/colors.less
- resources/styles/variables/tutor-bootstrap.less
Smallest PR ever! Making the link color easier to read.
> Changing link color

- src/components/course-calendar/duration.cjsx
- src/components/course-calendar/plan-details.cjsx
- src/components/task-plan/builder.cjsx
- src/components/task-plan/footer.cjsx
- src/flux/task-plan.coffee
- test/components/helpers/component-testing.coffee
- test/components/task-plan/footer.spec.coffee
Hi!
Re-enable second button on plan details, but only for viewing for past due assignments:
Not yet due assignments still working
> is editable check for plan stuffssssss

- src/components/task-plan/footer.cjsx
Sorry this was my bad :disappointed: when I moved the info icon into a conditional, i failed to notice the popover.  Fixes [127](https://docs.google.com/spreadsheets/d/1P0eq49e7u1uM3SUI9pULo7EQYZIJt1KLOOfBidHdFSY/edit#gid=1446311939)
> i should now be clickable and show tips

- src/components/book-content-mixin.cjsx
- test/components/task.spec.coffee
Fixes [142](https://docs.google.com/spreadsheets/d/1P0eq49e7u1uM3SUI9pULo7EQYZIJt1KLOOfBidHdFSY/edit#gid=1446311939)
Important to merge because this will fix quite a few links.
* link matching wasnt matching on links that were media links but weren't `#ed`
* update task test to handle making links
> Fix media links to another module

- src/api.coffee
- src/components/book-content-mixin.cjsx
- src/components/buttons/browse-the-book.cjsx
- src/components/reference-book/index.cjsx
- src/components/reference-book/navbar.cjsx
- src/components/reference-book/page.cjsx
- src/components/reference-book/reference-book.cjsx
- src/components/reference-book/toc.cjsx
- src/components/task-plan/select-topics.cjsx
- src/flux/reference-book.coffee
- src/router.cjsx
- test/components/book-content-mixin.spec.coffee
- test/components/buttons/browse-the-book.spec.coffee
I'm still testing manually but this seems to work so far.
> Replace bookId with courseId

- src/components/book-content-mixin.cjsx
- src/components/reference-book/page.cjsx
- src/components/task-step/all-steps.cjsx
- test/components/book-content-mixin.spec.coffee
> interactives and videos can now have links on them that need to be processed

- src/components/task/index.cjsx
- src/flux/task-step.coffee
It's pretty much ready, but i want to improve it a little bit,-- the concept coach flashes for a bit before the recovery is loaded and I would just like to prevent that
> fixes the not making a try another for a task with 2 + recovers

- src/components/navbar/server-error-monitoring.cjsx
- src/components/question.cjsx
- src/flux/app.coffee
And a few other tiny bug fixes :grin:
> Redirect on 403 server errors

- src/components/task-plan/builder.cjsx
> Fix for adding in periods

- src/components/performance/name-cell.cjsx
use `first_name` and `last_name` as opposed to `name`
> first name last name use instead of name from BE

- src/components/task-plan/homework/exercises.cjsx
hwbuilder sort rendered answers by id
> hwbuilder sort rendered answers by id

- src/components/task-step/exercise/modes.cjsx
- src/flux/task-step.coffee
- src/flux/task.coffee
- src/helpers/durations.coffee
- test/all-tests.coffee
- test/task-step-store.spec.coffee
If try another is clicked while store is saving answer a 422 error is encountered.
> Do not display  "Try Another" while store is not loading or saving

- src/components/course-settings/drop-student.cjsx
- src/components/learning-guide/teacher-student.cjsx
- src/components/name.cjsx
- src/components/performance/name-cell.cjsx
- src/components/task-plan/builder.cjsx
- src/components/task-plan/homework/exercises.cjsx
- src/components/task-step/exercise/modes.cjsx
- src/components/task/viewing-as-student-name.cjsx
- src/flux/task-step.coffee
- src/flux/task.coffee
- src/helpers/durations.coffee
- test/all-tests.coffee
- test/components/name.spec.coffee
- test/task-step-store.spec.coffee
This'll bring master up to date so we can begin merging other PR's
> Merge changes from beta branch into master

- src/flux/current-user.coffee
- test/components/navbar.spec.coffee
- test/current-user-store.spec.coffee
Regarding pivotal task:  https://www.pivotaltracker.com/story/show/101625092
> forecast link in teacher dropdown

- src/helpers/mathjax.coffee
> Fast MathJax rendering

- src/components/performance/index.cjsx
regarding pivotal task: https://www.pivotaltracker.com/story/show/101628600
reduces table bottom margin to match with top.
> perf report - reduced bottom margin height

- Gulpfile.coffee
- src/components/task-plan/builder.cjsx
- src/components/task-plan/homework.cjsx
- src/components/task-plan/plan-mixin.coffee
- src/components/task-plan/reading.cjsx
- test/components/helpers/component-testing.coffee
- test/components/helpers/task-plan.coffee
- test/components/task-plan/builder.spec.coffee
- test/components/task-plan/footer.spec.coffee
- test/components/task-plan/homework-plan.spec.coffee
- test/components/task-plan/reading-plan.spec.coffee
Adds in specs for the following components:
-TaskPlanBuilder
-ReadingPlan
-HomeworkPlan
-PlanFooter
> Task Plan Testing

- index.coffee
- index.html
> use readystatechange for loading the app to be compatible with async js loading

- resources/styles/book-content/base.less
- resources/styles/components/question.less
- resources/styles/mixins.less
Adding styles to tables within assessment in iReading
> Adding tables to assessments

- src/components/scores/index.cjsx
@philschatz I think I remember you saying there was another location that the earlier rename missed?
> Rename link from Scores Report to Student Scores

- test-integration/README.md
For those without current tutor-js environments...
> add instructions for running the test suite

- src/components/scores/index.cjsx
https://www.pivotaltracker.com/story/show/101992284
> scores initial sort on load : ascending

- resources/styles/components/loadable.less
- resources/styles/variables.less
- src/components/learning-guide.cjsx
- src/components/loadable-item.cjsx
- src/components/loadable.cjsx
no visible UI changes...loading timeout to display refresh button is increased to 120s from 30s for the perf forecast
> add a long loadable option, make perf forecast loading timeout long

- resources/styles/components/task-step/ends.less
- src/components/navbar/index.cjsx
- src/components/question.cjsx
- src/components/task-step/ends.cjsx
- src/components/task-step/exercise/modes.cjsx
- src/components/task-step/step-footer-mixin.cjsx
- src/components/task-step/step-mixin.cjsx
- src/helpers/policies/policies.coffee
> Fix homework review jumpiness -- make it animate nicely

- package.json
- src/components/tutor-input.cjsx
It looked to me like the tutor-input's would benefit the most from it so that was chosen as the place to introduce it at.  
I'm sure there's other spots that could also use refactoring as well, but not sure if we need/want to target them all at once.
> Add classnames lib

- src/helpers/period.coffee
- test/helpers/period.spec.coffee
regarding task: https://www.pivotaltracker.com/story/show/104121340
sort will now handle 'period 1 period 2' as well as '1st 2nd' name formats
> updated period tab sorting

- Gulpfile.coffee
- webpack.config.coffee
No UI Changes.
When building the files for production, build without extra runtime checks and warnings
> use the production version of React

- src/api.coffee
Will be needed once BE https://github.com/openstax/tutor-server/pull/643 is merged
> Default exercise load api to be homework_core type

- resources/styles/qa.less
- resources/styles/variables.less
- src/components/qa/content-toggle.cjsx
- src/components/qa/exercise-card.cjsx
- src/components/qa/exercises.cjsx
- src/components/qa/view-book.cjsx
- src/components/reference-book/navbar.cjsx
- src/components/reference-book/slide-out-menu-toggle.cjsx
- src/components/task-plan/homework/exercises.cjsx
- src/flux/exercise.coffee
- src/helpers/string.coffee
- test/helpers/string.spec.coffee
Finish up the qa exercise using the teacher exercise preview component.
Adds:
* tags
* type of exercise display
* toggle to switch between normal book content and exercises
> Complete exercise QA view

- resources/styles/tutor.less
> fix teacher review styles

- src/components/plan-stats/course-bar.cjsx
- src/components/plan-stats/index.cjsx
- src/components/plan-stats/performances.cjsx
- src/components/plan-stats/progress.cjsx
No UI changes, a code clean-up I've been wanting to do
> breakdown plan stats into smaller components

- src/components/course-calendar/add.cjsx
- src/components/course-calendar/month.cjsx
- src/components/course-calendar/plan.cjsx
No UI updates, use classnames lib in calendar
> use classnames lib in calendar

- src/components/task-plan/builder.cjsx
- src/components/task-plan/event/index.cjsx
> make event date label more clear

- webpack.config.coffee
Hopefully this will fix the QA js loading
> Set asset path to "/assets/" for production for QA view

- src/components/chapter-section-mixin.cjsx
- src/components/plan-stats/progress.cjsx
- src/components/reference-book/page-navigation.cjsx
- src/components/task-step/all-steps.cjsx
- src/components/task-step/exercise/group.cjsx
- src/components/task-teacher-review/crumb-mixin.cjsx
- src/components/task/crumb-mixin.cjsx
> change from state to props for chapter section mixin

- resources/styles/components/course-calendar/header.less
- resources/styles/components/scores/index.less
- resources/styles/global/buttons.less
- resources/styles/mixins/tutor-plans.less
- resources/styles/old/global/buttons.less
Eventually, we should find a new way around this, but this will help for now.
> btn preselector variable

- resources/images/icons/icon-event.svg
- resources/styles/global/icons.less
> add event icon

- resources/styles/components/exercise-card.less
- resources/styles/components/task-plan/homework/exercises.less
- resources/styles/global/tutor-material.less
- resources/styles/tutor.less
- src/components/exercise-card.cjsx
- src/components/qa/exercise-card.cjsx
- src/components/task-plan/homework/exercises.cjsx
- test/components/exercise-card.spec.coffee
Splits most of the functionality into a `ExerciseCard` component and leaves the mixing with only the toggle control.
Also adds the detailed solution to the bottom and styles the component to match the mockup.
> Display exercise feedback using a checkbox control

- src/components/plan-stats/performances.cjsx
"even though space is cool and all"
> Correct label name to be "Spaced Practice Performance"

- src/components/performance-forecast/chapter.cjsx
- src/components/performance-forecast/guide.cjsx
- src/components/performance-forecast/section.cjsx
- src/components/performance-forecast/statistics.cjsx
- src/components/performance-forecast/teacher-student.cjsx
- test/components/performance-forecast/chapter.spec.coffee
- test/components/performance-forecast/section.spec.coffee
regarding task: https://www.pivotaltracker.com/n/projects/1156756/stories/105344550
Teacher viewing a single student says "N problems worked"
> changed worked text for teacher-student

- api/user/courses.json
- src/components/task-plan/builder.cjsx
- test/components/task-plan/builder.spec.coffee
> Sort periods using period helper sort in HW builder

- src/components/exercise-card.cjsx
- src/components/task-plan/homework/exercises.cjsx
Allowing selection of exercises on the homework builder:
> Fix for exercise selection on the builder

- src/components/navbar/user-actions-menu.cjsx
See https://github.com/openstax/tutor-server/pull/738
> Add link to content analyst console in dropdown menu

- api/courses/1.json
- api/courses/1/dashboard.json
- resources/styles/components/course-settings.less
- src/api.coffee
- src/components/course-settings/remove-teacher.cjsx
- src/components/course-settings/roster.cjsx
- src/components/course-settings/settings.cjsx
- src/components/course-settings/teacher-roster.cjsx
- src/flux/teacher-roster.coffee
dependent on : https://github.com/openstax/tutor-server/pull/773
> Course settings - course teachers table and remove action

- api/courses/1/dashboard.json
- src/components/course-settings/remove-teacher.cjsx
- src/components/course-settings/teacher-roster.cjsx
- src/flux/course-listing.coffee
- src/flux/teacher-roster.coffee
> Course Settings - teacher remove - fixed delete arg, update to courselist on delete current teacher

- src/components/task-plan/builder.cjsx
Bug is described here: https://www.pivotaltracker.com/n/projects/1156756/stories/107536766
Seems like this was introduced a while ago here: https://github.com/openstax/tutor-js/commit/3b18b77fca7f6d2be113b630634d69d155416aeb#diff-5a158ad5bde62626d82249fc1b709b77R157
> Fix for set periods when clicking on the all periods radio

- resources/styles/components/scores/index.less
- src/components/scores/index.cjsx
- src/components/scores/name-cell.cjsx
- src/components/scores/sorting-header.cjsx
regarding pivotal tasks: 
https://www.pivotaltracker.com/story/show/107577060
https://www.pivotaltracker.com/story/show/107577064
When Concept Coach, don't show links on student name or due date row.
> don't show namelink / due date when concept coach

- src/components/course-grouping-label.cjsx
- src/components/course-settings/add-period.cjsx
- src/components/course-settings/change-period.cjsx
- src/components/course-settings/delete-period.cjsx
- src/components/course-settings/rename-period.cjsx
- src/components/performance-forecast/info-link.cjsx
- src/components/performance-forecast/teacher.cjsx
- src/components/period-section-label.cjsx
- src/components/task-plan/builder.cjsx
- test/all-tests.coffee
- test/components/course-grouping-label.spec.coffee
Concept Coach is called section, others are period.  In the future other criteria will be used (College vs HS)
`grep -ri period src/*` suggests that this is all occurrences.  It's difficult to be 100% sure though since there's so many variables and props that are also named `period`.
> Switch between saying "period" or "section" depending on course type

- src/components/scores/index.cjsx
To reflect BE changes introduced in https://github.com/openstax/tutor-server/pull/827
> Convert 0-1 range to a user-friendly percent on student scores

- src/components/scores/concept-coach-cell.cjsx
- src/components/scores/index.cjsx
CC scores weren't being rendered.  Still needs CSS work
> Render concept coach scores

- resources/styles/components/course-settings.less
- src/components/course-settings/period-enrollment-code.cjsx
- src/components/course-settings/roster.cjsx
- test/components/course-settings.spec.coffee
related to tickets:
https://www.pivotaltracker.com/story/show/105715924
https://www.pivotaltracker.com/story/show/107577056
> show enrollment codes in student roster w/ instructions

- src/components/course-settings/settings.cjsx
- src/components/course-settings/teacher-roster.cjsx
Fixes course roster view for concept coach.
> Roster view for concept coach

- resources/styles/components/student-dashboard/task.less
> Display text using ellipsis when it is too long

- resources/styles/components/scores/index.less
- src/components/name.cjsx
- src/components/scores/concept-coach-cell.cjsx
- src/components/scores/index.cjsx
- src/components/scores/name-cell.cjsx
- src/components/time-difference.cjsx
TODO:
Student ids depend on BE PR https://github.com/openstax/tutor-server/pull/835
> Fix CC scores report display

- src/components/navbar/index.cjsx
- src/components/navbar/logout.cjsx
- src/components/navbar/user-actions-menu.cjsx
regarding task: https://www.pivotaltracker.com/n/projects/1156756/stories/108517582
> concept coach logout link

- src/components/buttons/browse-the-book.cjsx
- test/components/buttons/browse-the-book.spec.coffee
- test/components/navbar/user-actions-menu.spec.coffee
> Remove "browse the book" option from cc courses

- resources/styles/components/multi-select.less
- resources/styles/qa.less
- resources/styles/tutor.less
- src/components/multi-select.cjsx
- src/components/qa/exercise-card.cjsx
- src/components/qa/exercises.cjsx
- src/flux/exercise.coffee
- test/components/multi-select.spec.coffee
> Filter exercises by pool type and add edit link

- src/components/course-settings/add-period.cjsx
- src/components/course-settings/change-period.cjsx
- src/components/course-settings/delete-period.cjsx
- src/components/course-settings/rename-period.cjsx
This fixes the styling bug referenced in:
https://www.pivotaltracker.com/story/show/105715942
https://www.pivotaltracker.com/story/show/105715940
> roster period edit - header styling bug

- package.json
- resources/styles/components/task-step/ends.less
- resources/styles/components/task/breadcrumbs.less
- src/components/scores/concept-coach-cell.cjsx
- src/components/task-step/exercise.cjsx
- src/components/task-step/step-footer-mixin.cjsx
- src/components/task-step/step-footer.cjsx
- src/components/task/viewing-as-student-name.cjsx
- src/helpers/policies/policies.coffee
Depends on https://github.com/openstax/tutor-server/pull/837
Two things I've noticed:
> Link CC scores to task review screen

- resources/styles/qa.less
- src/components/qa/book-link.cjsx
- src/flux/ecosystems.coffee
> Display ecosystem comments on QA view book menu

- resources/styles/components/cc-dashboard/index.less
- src/components/cc-dashboard/index.cjsx
regarding task: https://www.pivotaltracker.com/n/projects/1156756/stories/107577054
> cc-dashboard pdf and webview links

- src/components/scores/index.cjsx
regarding task: https://www.pivotaltracker.com/story/show/109169388
> show tabs when 'no assignments'

- src/flux/cc-dashboard.coffee
Sorts periods on Concept coach dashboard view.
> Period Sorting on CC Dashboard

- resources/styles/components/course-settings.less
- src/components/course-settings/change-period.cjsx
- src/flux/roster.coffee
https://www.pivotaltracker.com/story/show/107220234
> "Change period" uses async loading status

- resources/styles/components/course-settings.less
- src/components/course-settings/period-roster.cjsx
- src/components/course-settings/roster.cjsx
> Student Roster - added info text on empty period

- src/components/cc-dashboard/index.cjsx
- src/components/course-settings/change-period.cjsx
- src/flux/cc-dashboard.coffee
- src/flux/roster.coffee
Fixes labels for performance and completion progress bars on concept coach dashboard.  Also fixes the ordering for chapters/sections. See screenshots below.
Before:
After:
> Concept Coach Dashboard Labels

- src/components/course-settings/period-enrollment-code.cjsx
- src/components/course-settings/period-roster.cjsx
> Course Roster - updated enrollment code text

- resources/styles/components/course-listings.less
- resources/styles/global/tutor-booksplash-background.less
- resources/styles/variables/colors.less
If someone can figure out how to make the colors be an array that can be looped through with, that'd be awesome.  But I don't think it's possible...
> Colors and styles for additional courses

- resources/styles/components/cc-dashboard/index.less
- src/components/cc-dashboard/chapter.cjsx
- src/components/cc-dashboard/dashboard.cjsx
- src/components/cc-dashboard/index.cjsx
- src/components/navbar/book-links.cjsx
> Add booksplash header to dashboard

- src/components/cc-dashboard/chapter.cjsx
This should remove the "Unable to show progress because not enough data"
> hide chapters without enough data

- src/components/cc-dashboard/dashboard.cjsx
> Update tooltips wording with approved text

- resources/styles/components/scores/index.less
> Add ellipsis to too long student names

- src/components/course-listing.cjsx
- src/flux/course-listing.coffee
And if they're both a teacher and student take them to the teacher dashboard, not the student one.
No UI changes
> Hide CC courses when user is a student

- src/components/navbar/user-actions-menu.cjsx
- src/flux/current-user.coffee
> Adding in concept coach zendesk link

- resources/styles/components/scores/index.less
- src/components/name.cjsx
- src/components/scores/index.cjsx
- src/components/scores/name-cell.cjsx
- test/components/name.spec.coffee
> Scores table - student name/id spacing, truncation, tooltip

- resources/styles/components/cc-dashboard/index.less
- resources/styles/components/course-listings.less
- resources/styles/global/tutor-booksplash-background.less
- resources/styles/global/typography.less
- resources/styles/mixins.less
- resources/styles/mixins/for.less
- resources/styles/variables/colors.less
- src/components/course-data-mixin.cjsx
- src/flux/course.coffee
- test/course-listing-store.spec.coffee
Finally figured out how to interpolate a selector in less.
This styles the following components
Desktop SVG for blank CC course
CC Dashboard
Course chooser
Student Dashboard:
> Booksplash styles

- resources/styles/components/cc-dashboard/index.less
- resources/styles/global/tutor-booksplash-background.less
> Display ellipsis for course titles that do not fit on header

- src/components/course-settings/add-period.cjsx
regarding: https://www.pivotaltracker.com/story/show/109661524
> Roster - add period - new add clears field

- src/components/course-settings/period-roster.cjsx
- src/components/course-settings/roster.cjsx
empty period tutor: 
empty period CC:
> Course Roster - don't show enrollment info text if empty period and tutor

- resources/styles/qa.less
For: https://www.pivotaltracker.com/story/show/109671844
> Scrollable available book list

- resources/styles/components/task-plan/homework/exercises.less
For: https://www.pivotaltracker.com/story/show/109828984
Before:
After:
> HW builder exercise alignment

- resources/styles/components/task-plan/homework/exercises.less
- src/components/task-plan/homework/exercises.cjsx
> Display feedback button alignment

- resources/styles/components/task-teacher-review/question.less
- src/components/scroll-tracker.cjsx
> Teacher Task Review Fixes

- resources/styles/components/task-teacher-review/question.less
> Teacher Task Review Answer Alignment 

- resources/styles/components/scores/index.less
- src/components/course-periods-nav.cjsx
- src/components/scores/index.cjsx
https://www.pivotaltracker.com/story/show/109459986
> Student Scores - updated text and labels

- resources/styles/components/cc-dashboard/index.less
- src/components/cc-dashboard/blank-course.cjsx
- src/components/cc-dashboard/dashboard.cjsx
https://www.pivotaltracker.com/story/show/110076550
> CC Dashboard - show message when period empty/no student data

- src/components/navbar/book-links.cjsx
Fixes: https://www.pivotaltracker.com/n/projects/1156756/stories/110257776
> Updating book link text

- resources/styles/components/course-settings.less
- src/components/course-settings/period-enrollment-code.cjsx
- src/components/course-settings/roster.cjsx
https://www.pivotaltracker.com/story/show/110106454
> Roster - Enrollment Code Instructions Updated

- src/components/cc-dashboard/blank-course.cjsx
For: https://www.pivotaltracker.com/n/projects/1156756/stories/110357124
> Update dashboard message

- src/components/course-listing.cjsx
- src/flux/course-listing.coffee
- test/course-listing-store.spec.coffee
> Link CC students to webview if they end up on Tutor

- resources/styles/components/cc-dashboard/index.less
- src/components/cc-dashboard/blank-course.cjsx
https://www.pivotaltracker.com/story/show/110355252
> CC Dashboard in MS Edge - fix for svg not scaling

- src/components/course-settings/period-enrollment-code.cjsx
https://www.pivotaltracker.com/story/show/110575072
> Roster enrollment code - removed extra spaces from enrollment code links

- src/components/scores/index.cjsx
fixes issue with IE not getting table width from dom ref on initial load
> Student Scores - fix IE table width on load

- src/components/late-icon.cjsx
https://www.pivotaltracker.com/story/show/100222332
Changed "worked" to "started"
> Late icon status message - changed wording

- src/components/scores/sorting-header.cjsx
small fix to proptype warning.
> Scores table - fix proptype warning.

- package.json
from `karma-runner/karma#1782`
> upgrade karma to fix the sockets.forEach error in Travis

- src/components/course-listing.cjsx
- src/components/resize-listener-mixin.cjsx
- src/flux/course-listing.coffee
- src/helpers/window.coffee
- test/components/course-listing.spec.coffee
The main thing causing them all to fail was the redirect on a CC course.  That was being triggered on specs and causing random failures.
> Fix specs and add a few to test CC redirect

- src/components/scores/index.cjsx
i.e. 72.2% becomes 72%
regarding ticket:
https://www.pivotaltracker.com/story/show/109459986
> Student scores - round off average percentages

- .travis.yml
- README.md
currently coveralls is reporting that the coverage changed on master instead of in the Pull Request. Probably because Travis runs on the code with current master merged in.
> Add coverage badge to Readme

- resources/styles/components/course-settings.less
- src/components/course-settings/period-enrollment-code.cjsx
To reflect the new CC login/enrollment code screen
> Update CC enrollment code help text

- test-integration/README.md
- test-integration/helpers/course-select.coffee
as suggested by @nathanstitt.  Course selection part of tests work, not it gets stuck on the calendar sometimes.  Sample of the report
```
4 passing (7m)
1 pending
5 failing
1) Calendar and Stats Opens the review page for every visible plan (readonly):
UnknownError: disconnected: not connected to DevTools
(Session info: chrome=47.0.2526.111)
(Driver info: chromedriver=2.19.346063 (38b35413bd4a486d436a9749e090454bc9ff6708),platform=Mac OS X 10.10.5 x86_64)
at Array.forEach (native)
From: Task: <anonymous>
From: Task: Waiting until element is visible
at Context.waitAnd (test-integration/helpers/describe.coffee:98:17)
at Object.Popup.verify (test-integration/helpers/calendar.coffee:40:10)
at Context.<anonymous> (test-integration/calendar.coffee:77:24)
at …
```
> allows courses to be selected again

- test-integration/calendar.coffee
- test-integration/helpers/calendar.coffee
- test-integration/helpers/course-select.coffee
- test-integration/helpers/items.coffee
- test-integration/helpers/reading-builder.coffee
- test-integration/helpers/task.coffee
- test-integration/helpers/test-element.coffee
- test-integration/helpers/user.coffee
- test-integration/helpers/utils/wait.coffee
- test-integration/reference-book.coffee
- test-integration/simple.js
- test-integration/task-plan/cleanup.coffee
- test-integration/task-plan/draft.coffee
- test-integration/task-plan/publish.coffee
- test-integration/task.coffee
we're here to helper!
moar of #931, continuation of #953
> Selenium: continue helper-ish work

- test-integration/helpers/index.coffee
- test-integration/helpers/reading-builder.coffee
- test-integration/helpers/reference-book.coffee
- test-integration/helpers/test-element.coffee
- test-integration/helpers/utils/window-position.coffee
- test-integration/reference-book.coffee
includes commit from #965, related to: #931
> Selenium: make and use reference book test helper

- package.json
- src/components/task-step/exercise.cjsx
- src/components/task/index.cjsx
- src/flux/task-step.coffee
- src/flux/task.coffee
Adding code to remember free response when user switches to a different exercises.  Also alerts the user if they have unsaved work.
This is for: https://www.pivotaltracker.com/story/show/108888036
> Remember Free Response

- package.json
- resources/styles/components/exercise-card.less
- src/components/exercise-card.cjsx
Depends on https://github.com/openstax/react-components/pull/43
> add "Report Trouble" link

- package.json
- resources/styles/components/reference-book/page.less
> Extend past floated elements by using clearfix

- package.json
- scripts/run-test-integration.sh
- test-integration/calendar.coffee
- test-integration/cc-dashboard.coffee
- test-integration/helpers/calendar.coffee
- test-integration/helpers/cc-dashboard.coffee
- test-integration/helpers/course-select.coffee
- test-integration/helpers/describe.coffee
- test-integration/helpers/reading-builder.coffee
- test-integration/helpers/scores.coffee
- test-integration/helpers/student-dashboard.coffee
- test-integration/helpers/task.coffee
- test-integration/helpers/test-element.coffee
- test-integration/helpers/timeout.coffee
- test-integration/helpers/user.coffee
- test-integration/helpers/utils/for-each.coffee
- test-integration/helpers/utils/verbose.coffee
- test-integration/helpers/utils/wait.coffee
- test-integration/helpers/utils/window-position.coffee
- test-integration/scores.coffee
- test-integration/student/dashboard.js
- test-integration/task-plan/publish.coffee
- test-integration/task.coffee
When trying to run the tests against `dev` I ran into some issues. This is what I changed to get them working (for me at least). refs #931
Follow-up to #970
> Selenium: fix tests to run remotely and more consistently

- Gulpfile.coffee
- src/components/scores/cc-table-filters.cjsx
- src/components/scores/table-cc.cjsx
temporarily hides basedOn toggle and shows only average possible.
> Scores: hide basedOn temporarily, shows only possible avg

- package.json
- src/components/task-step/exercise.cjsx
- src/flux/task-step.coffee
- test/components/helpers/task/checks.coffee
- test/components/task.spec.coffee
Will need an update after openstax/react-components#45 is merged.
See [ticket](https://www.pivotaltracker.com/story/show/113635573) for more details
> for reading exercise, if can only continue, button should say continue and not 'Next Question'

- src/components/scores/cc-table-filters.cjsx
- src/components/scores/index.cjsx
- src/components/scores/table-cc.cjsx
- test-integration/helpers/scores.coffee
- test-integration/scores.coffee
made removal of basedOn toggle permanent instead of temp (commented)
> CC Student Scores - removed basedOn toggle 

- CONTRIBUTING.md
Adds a `CONTRIBUTING.md` file for folks to refer to which links to the main `CONTRIBUTING.md` file
> Best GitHub Practices for tutor-js!

- package.json
For: https://www.pivotaltracker.com/story/show/113945873
Updating react components so answers are not sorting on the front end.
Relates to: https://github.com/openstax/react-components/pull/46
> Exercise: Remove answer sorting

- test-integration/README.md
- test-integration/calendar.coffee
- test-integration/cc-dashboard.coffee
- test-integration/exhaustive/calendar.coffee
- test-integration/helpers/calendar.coffee
- test-integration/helpers/cc-dashboard.coffee
- test-integration/helpers/course-select.coffee
- test-integration/helpers/reading-builder.coffee
- test-integration/helpers/scores.coffee
- test-integration/helpers/student-dashboard.coffee
- test-integration/helpers/user.coffee
- test-integration/helpers/utils/wait.coffee
- test-integration/helpers/utils/window-position.coffee
- test-integration/scores.coffee
- test-integration/simple.js
- test-integration/student/dashboard.js
- test-integration/task-plan/cleanup.coffee
- test-integration/task-plan/draft.coffee
- test-integration/task-plan/publish.coffee
- test-integration/task.coffee
Addresses naming convention described in #987. refs #931
> Selenium: clean up helper commands

- resources/styles/components/scores/table-cc.less
- src/components/scores/concept-coach-cell.cjsx
- test-integration/helpers/scores.coffee
- test-integration/scores.coffee
dependent on https://github.com/openstax/tutor-server/pull/985
regarding story: https://www.pivotaltracker.com/n/projects/1156756/stories/111067052
> CC Student Scores - progress info hover

- test-integration/helpers/ui/test-element.coffee
- test-integration/helpers/utils/wait.coffee
The `forHidden` will help with the tests for #996 without `addTimeout`s, [example here](https://github.com/openstax/tutor-js/compare/export-button-single-step...export-button-single-step-test)
> Selenium: Update/test code cleanups crazy

- api/notifications.json
small add to #1008 so that dev version running stub api can poll it
> have some local notification messages for completely serverless dev version

- src/components/exercise-card.cjsx
- test/components/exercise-card.spec.coffee
Removes answer sorting from the exercise cards which is used by qa view and homework builder.
> Remove Exercise card answer sorting

- package.json
from openstax/react-components#49, should do a quick update after it's merged with the official tag
> matching update for FR caching with answer button fix

- src/components/task-plan/builder.cjsx
- src/components/task-plan/homework.cjsx
- src/flux/task-plan.coffee
- test-integration/all.coffee
- test-integration/helpers/ui/reading-builder.coffee
- test-integration/task-plan/homework.coffee
- test/components/task-plan/homework-plan.spec.coffee
BE PR: https://github.com/openstax/tutor-server/pull/1023  needs to be merged prior to this one
> Option to display immediate feedback for homework

- resources/styles/components/scores/export.less
- src/components/scores/export.cjsx
- test-integration/helpers/describe.coffee
- test-integration/helpers/ui/scores.coffee
- test-integration/scores.coffee
> Scores Export - single step to generate/download file

- resources/styles/qa.less
- resources/styles/variables.less
- src/components/qa/exercise-card.cjsx
- src/components/qa/exercises.cjsx
- src/flux/exercise.coffee
> Switch from using pool_types to 'type:' and 'filter-type:' tag for filtering on QA view

- test-integration/helpers/ui/test-element.coffee
- test-integration/helpers/ui/user.coffee
- test-integration/task-plan/homework.coffee
There were some bugs in the Selenium tests that arose from me not running the Selenium tests before every merge :blush:
> Selenium: fix lodash downgrade and new accounts UI

- Gulpfile.coffee
- test/components/exercise-card.spec.coffee
fixes a few lint errors that cropped up.
> :art: gulp lint fixes

- resources/styles/components/multi-select.less
- src/components/multi-select.cjsx
- src/components/qa/exercises.cjsx
- test/components/multi-select.spec.coffee
> QA View: Toggle off all exercise types when 'only' is selected

- src/api.coffee
- src/components/course-settings/drop-student.cjsx
- src/components/course-settings/dropped-roster.cjsx
- src/components/course-settings/roster.cjsx
- src/components/course-settings/settings.cjsx
- src/components/course-settings/undrop-student.cjsx
- src/flux/roster.coffee
- test-integration/all.coffee
- test-integration/helpers/ui/roster.coffee
- test-integration/roster.coffee
Regarding story: https://www.pivotaltracker.com/story/show/115538039
> Course Settings - Undrop students

- CONTRIBUTING.md
Here's the additions. Did I miss or get something wrong @openstax/tutor-fe ?
---
- include a screenshot in the **Issue/PR body**
- add either `Needs Code` or `Needs Review` label
- if it is waiting on input from someone add the `blocked` label
- if it is linked to another Issue or Pull Request, link the Issue/PR number by editing the Issue/PR **body**
1. Find the commit SHA to base the hotfix on
2. create a `hotfix-*` branch
3. make a Pull request to `master` (note: it may have merge conflicts)
4. add the `HOTFIX` label
5. deploy the hotfix
6. merge master in (**DO NOT REBASE!** It is important to make sure the deployed commit is in master for undoability)
7. merge the Pull request
- Add selenium code to be able to exercise the feature or bug in the Pull Request
- test by [Running …
> Docs: add some more instructions for contributing

- src/components/navbar/server-error-monitoring.cjsx
- test/components/navbar/server-error-monitoring.spec.coffee
> Generalize error modal and add a no_exercises handler

- src/components/task-plan/homework.cjsx
- src/components/task-plan/reading.cjsx
- test-integration/helpers/ui/exercise-selector.coffee
- test-integration/helpers/ui/task-builder.coffee
- test-integration/task-plan/homework.coffee
Migrating some of the tests from #957, it was easier to create a new PR than to rebase.
> Add tests for Exercise selection

- src/components/task-plan/homework/exercises.cjsx
- src/flux/exercise.coffee
- test/flux/exercise.spec.coffee
Hehehe
Requires https://github.com/openstax/tutor-server/pull/1075
Feel free to take over... Took me a long time to figure out what's going on in exercise.coffee (and why I can't reuse the question library functions).
Also, no clue how to write those tests :)
> Exclude exercises from the HW builder

- src/components/qa/exercise-card.cjsx
- test/components/qa/exercises.spec.coffee
Depends on https://github.com/openstax/react-components/pull/59
> Display question formats, update react-components

- package.json
- resources/styles/components/tutor-input.less
- src/components/course-calendar/duration.cjsx
- src/components/course-calendar/index.cjsx
- src/components/course-calendar/month.cjsx
- src/components/reference-book/index.cjsx
- src/components/student-dashboard/dashboard.cjsx
- src/components/student-dashboard/event-row.cjsx
- src/components/student-dashboard/event-task-row.cjsx
- src/components/student-dashboard/external-row.cjsx
- src/components/student-dashboard/index.cjsx
- src/components/student-dashboard/upcoming-panel.cjsx
- src/components/task-plan/builder.cjsx
- src/components/task-plan/homework.cjsx
- src/components/task-plan/plan-mixin.coffee
- src/components/task-plan/reading.cjsx
- src/components/tutor-input.cjsx
- src/flux/course.coffee
- src/flux/plan-publish.coffee
- src/flux/scores-export.coffee
- src/flux/task-plan.coffee
- src/helpers/job.coffee
- src/helpers/policies/index.coffee
- src/helpers/time.coffee
- test/components/course-calendar/plan.spec.cjsx
- test/components/task-plan/builder.spec.coffee
- test/components/task-plan/footer.spec.coffee
- test/components/tutor-input.spec.cjsx
- test/helpers/time.spec.coffee
Updates various time dependencies and fixes timezone issue in calendar
For [timezone bug ticket](https://www.pivotaltracker.com/story/show/117736371)
> Fix timezone related issues in calendar

- src/components/task-step/exercise.cjsx
- test-integration/helpers/ui/task.coffee
- test-integration/task.coffee
https://github.com/openstax/react-components/pull/68
> Student Exercise - help link back to content

- package.json
- src/components/buttons/browse-the-book.cjsx
- src/components/new-tab-link.cjsx
- src/components/task-step/exercise.cjsx
- test/components/helpers/task/index.cjsx
- test/components/task.spec.coffee
Updates shared to [d-20160520.a](https://github.com/openstax/react-components/releases/tag/d-20160520.a) for #1059 and #1057
> update to shared with student help links and exercise preview updates

- resources/styles/components/course-calendar/plan-details.less
- resources/styles/components/task-plan/index.less
- resources/styles/components/task-plan/lms-info.less
- src/components/course-calendar/plan-details.cjsx
- src/components/task-plan/lms-info.cjsx
- test-integration/exhaustive/calendar.coffee
- test-integration/helpers/ui/calendar.coffee
- test/components/task-plan/lms-info.spec.coffee
Needs BE PR: https://github.com/openstax/tutor-server/pull/1079
> display LMS assignment link

- src/helpers/policies/policies.coffee
- src/helpers/policies/utils.coffee
needed to display new true-false formats properly
> add true-false format as an alias for multiple-choice for panels

- src/components/performance-forecast/guide.cjsx
- src/components/scores/index.cjsx
- test-integration/calendar.coffee
- test-integration/cc-dashboard.coffee
- test-integration/exhaustive/calendar.coffee
- test-integration/helpers/describe.coffee
- test-integration/helpers/index.coffee
- test-integration/helpers/ui/course-select.coffee
- test-integration/helpers/ui/exercise-selector.coffee
- test-integration/helpers/ui/forecast.coffee
- test-integration/helpers/ui/roster.coffee
- test-integration/helpers/ui/scores.coffee
- test-integration/helpers/ui/task-builder.coffee
- test-integration/helpers/ui/task-plan-review.coffee
- test-integration/helpers/ui/task-teacher.coffee
- test-integration/helpers/ui/test-element.coffee
- test-integration/helpers/utils/wait.coffee
need to wait until the modal is not present at all.  For use in `openstax/test-automation`
Tests have been fixed/updated as much as possible.  Current failures in this branch from running tests will be due to:
* Teacher task review being unable to render
* will be fixed when #1046 is merged
* assignment open/due date bugs
* will be fixed when #1067 is merged
* assignment feedback immediate bug
* will be fixed when #1069 is merged
> Selenium: modal is considered closed too early in chrome. 

- test-integration/calendar.coffee
- test-integration/helpers/ui/exercise-selector.coffee
- test-integration/helpers/ui/task-builder.coffee
also, waits for the HW Builder "Tutor Selections" buttons to be visible before clicking on them. /cc @pandafulmanda since she helped diagnose as part of #1067
> Selenium: fixes to handle scores when 0 work has been done by any student

- src/components/course-listing.cjsx
- src/components/course-listing/empty.cjsx
- test/components/course-listing.spec.coffee
> Show "no courses" message to un-associated users

- api/courses/1.json
- api/user/courses/1.json
- resources/styles/components/course-settings.less
- src/components/course-settings/cc-enrollment-code.cjsx
- src/components/course-settings/delete-period.cjsx
- src/components/course-settings/dropped-roster.cjsx
- src/components/course-settings/rename-period.cjsx
- src/components/course-settings/roster.cjsx
- src/components/course-settings/settings.cjsx
- src/components/course-settings/student-enrollment-link.cjsx
- src/components/course-settings/student-enrollment.cjsx
- src/flux/course.coffee
- test/components/course-settings.spec.coffee
Requires BE PR: https://github.com/openstax/tutor-server/pull/1099
> Add box to copy enrollment code link from to course settings

- api/courses/1/dashboard.json
- resources/styles/components/task-plan/lms-info.less
- resources/styles/components/task/progress.less
- resources/styles/variables/colors.less
- src/components/course-calendar/plan-details.cjsx
- src/components/task-plan/lms-info.cjsx
- src/components/task/progress/arrow.cjsx
- src/components/task/progress/panel.cjsx
- src/flux/teacher-task-plan.coffee
- src/helpers/clipboard.coffee
- src/helpers/task-plan.coffee
- test/helpers/task-plan.spec.coffee
When all periods have same due date:
With different due dates for periods:
> Implement due dates and other fixes to LMS info link

- src/flux/current-user.coffee
- test/components/navbar/spec-test-params.coffee
- test/current-user-store.spec.coffee
> rename 'Course Roster' menu option to 'Course Settings and Roster'

- resources/styles/global/navbar.less
Was rendering transparent rather than tutor-white
> fixed collapsible (hamburger) dropdown bg color on navbar

- api/user/courses/1.json
- src/components/course-grouping-label.cjsx
- src/flux/course.coffee
- test/components/course-grouping-label.spec.coffee
Goes with BE PR: https://github.com/openstax/tutor-server/pull/1125
> Use `is_college` flag for choosing period/section label

- resources/styles/components/course-settings.less
- src/components/course-settings/settings.cjsx
- src/components/course-settings/teacher-roster.cjsx
regarding https://www.pivotaltracker.com/story/show/121079843
depends on https://github.com/openstax/tutor-server/pull/1130
> Teacher Roster - use roster endpoint

- src/components/course-settings/change-period.cjsx
- src/components/course-settings/drop-student.cjsx
- src/components/course-settings/period-roster.cjsx
- test/components/course-settings/change-period.spec.coffee
No UI changes, other than archived periods no longer show up
> Only display non-archived periods as option to change to in roster

- resources/styles/components/exercises.less
- resources/styles/components/questions-dashboard.less
- src/api.coffee
- src/components/questions/exercise-controls.cjsx
- src/components/questions/exercises-display.cjsx
- src/flux/exercise.coffee
Missed doing this as part of https://github.com/openstax/tutor-js/pull/1082
Also corrects the excluded mask color to match mockup
> Auto-save included/excluded exercises

- src/components/questions/exercise-cards.cjsx
- src/components/questions/exercises-display.cjsx
- test/components/questions/exercises-display.spec.coffee
Yeah... so this didn't get pushed up before #1096 got merged  
Sorry!
> 😿 Specs and a fix for exercise exclusions

- package.json
For: https://www.pivotaltracker.com/story/show/121084413 and 
https://www.pivotaltracker.com/story/show/121084435
Before:
After:
> Updating react components to for an android css fix

- src/components/tutor-input.cjsx
Pivotal ticket: https://www.pivotaltracker.com/n/projects/1156756/stories/121077903
> Fix datepicker, allow months to be changed

- resources/styles/components/scores/table.less
- src/components/scores/reading-cell.cjsx
regarding: https://www.pivotaltracker.com/story/show/121453633 
Reading cells can link back to reading as before, via popover.
> Student Scores reading links

- src/flux/task-plan.coffee
Updating how default feedback is getting set, so it is able to be changed.
For: https://www.pivotaltracker.com/story/show/121620619
> Default feedback for homeworks

- resources/styles/components/task-step/ends.less
- src/components/task-step/ends.cjsx
- src/flux/task.coffee
For: https://www.pivotaltracker.com/story/show/121083971
Immediate feedback report: 
Delayed feedback report:
> Completion Report for Immediate/Delayed Feedback 

- resources/styles/components/course-settings.less
regarding: https://www.pivotaltracker.com/story/show/121525887
> Course settings - fixed IE enrollment link height

- src/components/course-settings/add-period.cjsx
regarding: https://www.pivotaltracker.com/story/show/121079865
> Course Settings - add period form clears previous value, fixed validation

- src/components/course-settings/cc-enrollment-code.cjsx
- src/components/course-settings/change-period.cjsx
- src/components/course-settings/drop-student.cjsx
- src/components/course-settings/period-roster.cjsx
- src/components/course-settings/student-enrollment.cjsx
@emma-min13 found a few more inappropriate uses of "section"
> Replace 'section' string with CourseGroupingLabel in roster

- resources/styles/components/reference-book/exercise.less
Pivotal: https://www.pivotaltracker.com/story/show/121771939
Before:
After:
> Hide Book Solutions

- src/flux/scores.coffee
Fixes bug when task are null for a student after they're freshly created
> Don't attempt to cache null tasks on stores

- resources/styles/mixins.less
> style table captions to match CNX

- src/flux/task-plan.coffee
fix the bug from #1132 so that new assignments  dont trip up the get original
> fix not being able to make new assignments

- src/components/exercises/cards.cjsx
- src/components/task-plan/homework/add-exercises.cjsx
- src/flux/task-plan.coffee
Adding in a preview wrapper to the exercise cards that will re-render the exercise card instead of all the cards that are rendered.
> Exercise Preview Wrapper

- api/courses/4/dashboard.json
- resources/styles/components/cc-dashboard/help.less
- resources/styles/components/cc-dashboard/index.less
- resources/styles/components/course-settings.less
- resources/styles/variables.less
- src/components/cc-dashboard/dashboard.cjsx
- src/components/cc-dashboard/empty-period.cjsx
- src/components/cc-dashboard/help.cjsx
- src/components/cc-dashboard/index.cjsx
- src/components/course-settings/cc-enrollment-code.cjsx
- src/flux/cc-dashboard.coffee
- src/flux/current-user.coffee
- src/router.cjsx
- test/components/cc-dashboard/dashboard.spec.coffee
- test/components/cc-dashboard/index.spec.coffee
- test/flux/cc-dashboard.spec.coffee
> Updated help and instructions for CC pages

- resources/styles/book-content/base.less
regarding: https://www.pivotaltracker.com/story/show/121780633
> Book content - multiple choice lettered list style

- resources/styles/components/course-settings.less
- src/components/course-settings/cc-enrollment-code.cjsx
> Mention student portal in CC instructions

- src/components/scores/index.cjsx
https://www.pivotaltracker.com/n/projects/1156756/stories/123189821
> Better wording for the note about scores past the due date

- resources/styles/book-content/index.less
- resources/styles/book-content/theming-mixins.less
regarding: https://www.pivotaltracker.com/story/show/121780773
> Reference book - redesigned tables

- src/components/task-plan/footer.cjsx
https://www.pivotaltracker.com/n/projects/1156756/stories/121527791
> Show different confirmation for deleting draft vs published assignment

- src/components/tutor-popover.cjsx
> this removes hack from #974 as firefox version is now well beyond when bug was fixed

- src/flux/helpers.coffee
- src/flux/task.coffee
with more time, we should check/see about removing this altogether
> take out task specific code from crud helper

- resources/styles/components/exercises.less
- src/components/exercises/cards.cjsx
Pivotal: https://www.pivotaltracker.com/story/show/121524179
> Adds in message for when no exercises are found

- resources/styles/components/cc-student-redirect.less
- resources/styles/tutor.less
- src/components/cc-student-redirect.cjsx
- src/components/countdown-redirect.cjsx
- src/components/navbar/logout.cjsx
- src/components/student-dashboard/index.cjsx
- src/router.cjsx
- test/components/countdown-redirect.spec.coffee
- test/components/student-dashboard.spec.coffee
Blocked until @jivewise's PR #1172 lands
> Redirect a CC student to web view url of book

- resources/styles/components/task-plan/lms-info.less
- src/components/task-plan/lms-info.cjsx
Removes strange dash and "Summary" heading.  Removes strange line-height that was added to close buttons.
> Fix LMS info popup appearance

- resources/styles/components/scores/index.less
- resources/styles/components/scores/table.less
- src/components/reference-book/page-shell.cjsx
- src/components/scores/cell-status-mixin.cjsx
- src/components/scores/concept-coach-cell.cjsx
- src/components/scores/external-cell.cjsx
- src/components/scores/homework-cell.cjsx
- src/components/scores/index.cjsx
- src/components/scores/late-work.cjsx
- src/components/scores/reading-cell.cjsx
- src/components/scores/table-filters.cjsx
- src/components/scores/table.cjsx
- src/components/task-step/step-with-reading-content.cjsx
- test/components/scores/homework-cell.spec.coffee
https://www.pivotaltracker.com/n/projects/1156756/stories/120312461
http://jdy18n.axshare.com/#p=tutor_detailed_student_scores_5_8_new_solid_icons_
http://jdy18n.axshare.com/#p=scores_visual_design_notes_refinements&c=1
New look:
Original look:
> New Student Scores Page Design

- package.json
includes https://github.com/openstax/react-components/pull/94
> Update react-components with fix for MPQ scrolling

- api/plans/8.json
- src/components/task-plan/external/index.cjsx
- test/components/task-plan/external-plan.spec.coffee
Fixes [Creating/editing External Assignments not working](https://www.pivotaltracker.com/n/projects/1156756/stories/126056879)
> Fix external plans

- src/components/task-plan/event/index.cjsx
- src/flux/task-plan.coffee
fixes [cannot edit or publish event](https://www.pivotaltracker.com/story/show/126067285)
> fix event typo that was causing event plans to not work

- src/components/task-plan/builder/index.cjsx
- src/flux/course.coffee
- src/flux/tasking.coffee
- test/flux/tasking.spec.coffee
archived periods need to be ignored, otherwise trying to check for validity gets confused because it tries to validing the tasking for the archived period as well
addresses [Cannot publish readings](https://www.pivotaltracker.com/story/show/126168299)
> fixes assignments not publishing for certain courses

- src/components/task-plan/homework/choose-exercises.cjsx
- src/components/task-plan/select-topics.cjsx
- test/components/task-plan/homework/choose-exercises.spec.coffee
No real UI changes other than the "No exercise found" message doesn't appear
> hide exercises instead of the "no exercises" message when sections change

- src/components/course-listing/empty.cjsx
> Add help for Tutor instructors

- src/components/navbar/server-error-monitoring.cjsx
when going to support from server error message modal, pre-populate message with error details
> pre-fill support link

- src/components/course-settings/roster.cjsx
- src/components/no-periods.cjsx
- src/components/task-plan/builder/index.cjsx
- src/components/task-teacher-review/review.cjsx
This way it'll switch to reading section when needed for college
> Use CourseGroupingLabel instead of "period" string

- src/components/task-plan/builder/index.cjsx
- src/components/task-plan/builder/time-zone-settings-link.cjsx
- test/components/task-plan/builder/index.spec.coffee
> Display default time zone in task builder

- resources/styles/book-content/index.less
- resources/styles/book-content/interactive.less
- resources/styles/components/task-step/all-steps.less
- resources/styles/components/task-step/reading/interactive.less
- resources/styles/variables.less
Sets the right negative margin for interactives in the book so they're centered.
> Fixes uncentered sims in book content

- resources/styles/global/tutor-booksplash-background.less
- resources/styles/variables/colors.less
- src/components/course-data-mixin.cjsx
regarding: https://www.pivotaltracker.com/story/show/109905656
Tested on knowable titles Physics I, Biology I and Sociology.  Fixed Physics having the same color as Bio. Truncation is still possible if the book name is really long.
> Book Title - background banner font/size

- src/flux/current-user.coffee
https://www.pivotaltracker.com/n/projects/1156756/stories/126805533
> Fixes bad CC Dashboard links in nav menu

- src/components/navbar/server-error-monitoring.cjsx
- src/flux/app.coffee
- src/helpers/api.coffee
- test/components/navbar/server-error-monitoring.spec.coffee
Current error dialog is below, @openstax/ux please review and advise if it should be changed
Goes with BE PR: https://github.com/openstax/tutor-server/pull/1192, but can be merged independently
> Display "No Exercises" message when loading fails

- resources/styles/components/scores/table.less
- src/components/scores/table.cjsx
Prints the click rate summary for external assignments in the class average header cell.
Requires https://github.com/openstax/tutor-server/pull/1186
> Student Scores: External Assignment Click Rates

- resources/styles/components/student-dashboard/dashboard.less
- resources/styles/variables/colors.less
- src/flux/course-appearance-codes.coffee
will be needed once https://github.com/openstax/tutor-server/pull/1211 is merged
> Add ap_biology appearance code, fix missing book icons

- resources/styles/components/reference-book/navbar.less
- resources/styles/qa.less
- src/components/reference-book/index.cjsx
- src/components/reference-book/navbar.cjsx
- src/components/reference-book/teacher-content-toggle.cjsx
> reference book title handle smaller screen widths

- resources/styles/global/navbar.less
- resources/styles/global/tutor-material.less
- src/components/navbar/index.cjsx
- src/components/navbar/user-actions-menu.cjsx
> Better nav menu for small screens

- src/components/scroll-spy.cjsx
- src/components/task-teacher-review/breadcrumbs.cjsx
- src/components/task-teacher-review/exercise.cjsx
- src/components/task-teacher-review/index.cjsx
- src/components/task-teacher-review/review.cjsx
there's some funkiness with the Reading task reviews, due to the way section headings are set up right now.  that can be fixed in a different PR.
overall this will be an improvement over the current teacher review view, fixes:
* [mis-positioning of scroll](https://www.pivotaltracker.com/story/show/121622375)
* **significant** performance improvement when scrolling
> fix teacher review scrolling

- resources/styles/components/task-step/all-steps.less
https://www.pivotaltracker.com/n/projects/1156756/stories/127106185
> Fixes embedded videos not fitting in their wrappers

- resources/styles/components/course-listings.less
- src/components/course-listing.cjsx
regarding https://www.pivotaltracker.com/story/show/127076359
> Course Listing - visual distinction between Tutor/CC

- src/components/scores/table.cjsx
https://www.pivotaltracker.com/n/projects/1156756/stories/127294403/comments/145207727
> Student Scores Table: "Class Average" to "Class Performance"

- src/components/scores/late-work.cjsx
https://www.pivotaltracker.com/n/projects/1156756/stories/127295143/comments/145208761
> Student Scores Table: Changed late acceptance text for reading assignments

- src/components/navbar/book-links.cjsx
- src/components/navbar/index.cjsx
- src/components/navbar/user-actions-menu.cjsx
https://www.pivotaltracker.com/n/projects/1156756/stories/127202601
> Fix for mobile dropdown nav menu not hiding after click

- src/components/scores/homework-cell.cjsx
- src/components/scores/reading-cell.cjsx
Every homework that has been started and is past due shows a score, and every progress pie that is past due is blue.
> Student Scores: past-due shows score and is blue

- package.json
waiting to include openstax/react-components#104 before ready for review
> need to update react-components

- src/components/student-dashboard/event-row.cjsx
https://www.pivotaltracker.com/n/projects/1156756/stories/127497803
> Fixes a withdrawn assignment's hide button triggering a view action

- tutor/resources/styles/components/student-dashboard/task.less
- tutor/src/components/student-dashboard/event-row.cjsx
- tutor/test/components/student-dashboard/event-row.cjsx
https://www.pivotaltracker.com/n/projects/1156756/stories/127494711
> Fixes semi-transparent event tasks

- tutor/src/components/task-plan/lms-info.cjsx
https://www.pivotaltracker.com/n/projects/1156756/stories/127492803
> Fixes close button on the "get assignment link" popover

- tutor/src/components/questions/exercise-controls.cjsx
https://www.pivotaltracker.com/n/projects/1156756/stories/127578009
> Fixes "All" button not showing selection in the Question Library's nav bar

- tutor/resources/styles/global/navbar.less
- tutor/resources/styles/variables/tutor-bootstrap.less
- tutor/src/components/icon.cjsx
- tutor/src/components/navbar/center-controls.cjsx
- tutor/test/components/icon.spec.cjsx
https://www.pivotaltracker.com/n/projects/1156756/stories/127581441
> Fixes calendar button's tooltip rendering underneath the navbar

- tutor/resources/styles/global/navbar.less
- tutor/src/components/navbar/account-link.cjsx
- tutor/src/components/navbar/user-actions-menu.cjsx
- Fixes problem where users could not click on elements to the left of the dropdown menu.
- Fixes problem where menu wouldn't close after clicking "My Account" or "Get Help".
> Fixes mobile nav menu problems

- tutor/src/components/course-periods-nav.cjsx
- tutor/src/components/plan-stats/index.cjsx
- tutor/src/components/scores/table.cjsx
- tutor/src/components/task-teacher-review/crumb-mixin.cjsx
- tutor/src/components/task-teacher-review/index.cjsx
- tutor/src/flux/task-plan-stats.coffee
- tutor/src/router.cjsx
[Bug: No period tab selected when you try to review an assignment ](https://www.pivotaltracker.com/story/show/127280523)
> Fix scores review link period

- tutor/src/flux/task.coffee
For pivotal: https://www.pivotaltracker.com/story/show/127185325
Fixes one step reading sections.  See gif below:
> Fixing one step reading sections

- tutor/src/components/task-step/all-steps.cjsx
- tutor/src/components/task/progress/milestones.cjsx
> Rename "Concept Coach" steps to "Reading Review"

- tutor/resources/styles/components/student-dashboard/task.less
- tutor/src/components/student-dashboard/event-row.cjsx
Pivotal ticket: https://www.pivotaltracker.com/story/show/127946475
Before:
After:
> Updating how the withdrawn event rows look

- coach/src/user/model.coffee
- shared/index.cjsx
- tutor/index.coffee
- tutor/test/components/task-homework.spec.coffee
> Bootstrap instead of Bootrap, and initialize maybe helps with the specs

- coach/resources/styles/components/concept-coach/breadcrumbs.less
- coach/resources/styles/components/course/registration.less
- coach/resources/styles/demo.less
- coach/resources/styles/main.less
- coach/src/course/model.coffee
- coach/src/navigation/index.cjsx
- coach/src/user/menu.cjsx
- coach/test/course/error-list.spec.coffee
Pivotal Ticket: https://www.pivotaltracker.com/story/show/127655219
> Coach Enrollment Error Message

- coach/src/navigation/index.cjsx
- coach/src/user/menu.cjsx
> Fix Concept Coach's navbar user's dropdown menu appearance

- package.json
- shared/index.cjsx
- shared/src/helpers/polyfills.coffee
> Add Object.assign polyfill for IE

- tutor/src/components/course-settings/student-id-field.cjsx
Not against `master`, against #1288
> adjustments to #1288 decrease use of delay and defer

- tutor/resources/styles/components/scores/table.less
- tutor/src/components/scores/homework-cell.cjsx
- tutor/src/components/scores/late-work.cjsx
- tutor/src/components/scores/reading-cell.cjsx
https://www.pivotaltracker.com/story/show/127670785
> make late score indicator larger on hover

- coach/src/course/modify-registration.cjsx
- coach/src/course/registration.cjsx
- coach/src/user/menu.cjsx
- coach/test/course/registration.spec.coffee
- coach/test/user/menu.spec.coffee
Pivotal: https://www.pivotaltracker.com/story/show/127655219
> Remove change section from drop down menu in coach

- tutor/src/components/scores/index.cjsx
Fixes bug that broke reverse sorting, introduced in #1297
> check correct sort key; `asc`

- .gitignore
- test/all-tests.coffee
if you want to only use some tests, make a file at `<projectDir>/test/some-tests.coffee` and require the tests files like so:
```coffee
require './components/performance-forecast/index.spec'
require './components/performance-forecast/chapter.spec'
require './components/performance-forecast/section.spec'
```
> test `some-tests` file if exists in project dir, otherwise, use all-tests

- tutor/src/api.coffee
- tutor/src/components/course-settings/undrop-student.cjsx
- tutor/src/flux/roster.coffee
- tutor/src/helpers/api.coffee
Note the new `route` api method.  Feedback welcome on using that to make routes.
> Handle "already_dropped" api error as if drop succeeds

- exercises/src/stores/question.coffee
No real UI changes, other than it removes the blank creation and validation of detailed solutions
> Exercise Editor: allow detailed solutions to be blank

- tutor/resources/styles/components/course-settings.less
- tutor/src/api.coffee
- tutor/src/components/course-settings/period-roster.cjsx
- tutor/src/components/course-settings/student-id-field.cjsx
- tutor/src/components/student-dashboard/event-info-icon.cjsx
- tutor/src/flux/helpers.coffee
- tutor/src/flux/roster.coffee
- tutor/src/helpers/api.coffee
- tutor/test/components/course-settings/student-id-field.spec.coffee
> Handle errors when setting student id to a duplicate value

- tutor/src/components/task-step/all-steps.cjsx
- tutor/src/components/task/progress/milestones.cjsx
> Rename "Reading Review" to "Spaced Practice"

- tutor/src/components/task-step/all-steps.cjsx
> Update help text on Reading Review card

- tutor/src/flux/app.coffee
- tutor/src/helpers/api.coffee
- tutor/test/components/navbar/server-error-monitoring.spec.coffee
* skip for now, will add tests for shared api
> request response update

- tutor/resources/styles/components/cc-dashboard/index.less
- tutor/src/components/icon.cjsx
- tutor/test/all-tests.coffee
- tutor/test/components/icon.spec.cjsx
Pivotal: https://www.pivotaltracker.com/story/show/128099687
With this fix:
> Tappable Icons with Tooltips

- tutor/resources/styles/components/task-step/index.less
- tutor/resources/styles/components/task-teacher-review/question.less
- tutor/resources/styles/variables.less
Pivotal: https://www.pivotaltracker.com/story/show/128105343
Before:
After:
> Fix teacher review styles on tablets

- tutor/resources/styles/components/related-content-link.less
- tutor/resources/styles/tutor.less
- tutor/src/components/related-content-link.cjsx
- tutor/src/components/task-step/exercise.cjsx
- tutor/src/components/task-step/step-with-reading-content.cjsx
- tutor/test/components/related-content-link.spec.coffee
Extracts the "Comes from section/ title" from exercises and shares it with readings.
> Add section & name that reading step comes from

- tutor/resources/styles/components/cc-dashboard/index.less
- tutor/src/components/cc-dashboard/dashboard.cjsx
regarding: https://www.pivotaltracker.com/story/show/127123201
updated button spacing and icon position
> CC Dashboard: Formatting issues on android tablet

- tutor/src/components/book-content-mixin.cjsx
> grouped figures should be allowed to float naturally next to each toher

- tutor/src/components/scores/index.cjsx
- tutor/src/flux/scores.coffee
> re-render after late work accept, calculate score average after class/section

- tutor/resources/styles/book-content/interactive.less
regarding: https://www.pivotaltracker.com/story/show/127010335
> Book Content: College Physics section 2.5 has incorrectly sized sim

- exercises/src/components/tags/book-selection.cjsx
> Exercises: enable additional books in tag dropdown

- bin/test-ci
- shared/resources/styles/components/change-student-id-form.less
- shared/resources/styles/main.less
- shared/resources/styles/variables/openstax-bootstrap.less
- shared/src/components/change-student-id-form.cjsx
weird that builds for coach randomly started happening.  this should not be considered a permanent fix.  need to investigate further why this started happening
coach was not building due to variables less being loaded multiple times/within the change student id styles.  this fix does not cause any ui changes
> fix failing coach build

- shared/test/helpers/index.coffee
- tutor/src/components/dialog.cjsx
- tutor/src/flux/exercise.coffee
Mainly just silences warnings and corner-cases.  These came out of my investigation of a different bug that turned out to be because I was running chrome beta
> Some minor bug fixes

- coach/src/course/model.coffee
Noticed this about 5 mins after #1353 (minor bug fixes pr) was merged :(
> rm console.log

- tutor/src/components/paging-navigation.cjsx
- tutor/src/components/reference-book/navbar.cjsx
- tutor/src/components/reference-book/reference-book.cjsx
- tutor/src/components/reference-book/slide-out-menu-toggle.cjsx
- tutor/src/components/reference-book/slide-out-menu.cjsx
- tutor/test/components/reference-book/slide-out-menu-toggle.spec.coffee
* Makes reference book menu hide/show control tabbable
* Disables tabbing in reference book menu when it's closed
* Labels readings forward/back paging controls, and disables tabbing if the control isn't shown
> fix some of the easy accessibility things

- tutor/src/components/paging-navigation.cjsx
- tutor/test/components/paging-navigation.spec.cjsx
Vs -1 which means disable tabbing :(
> set paging tabindex to 0 when enabled

- tutor/resources/styles/components/scores/table.less
per @rvnewell on https://github.com/openstax/tutor-js/pull/1356#issuecomment-248728112
> Change student-id color to #999999 (neutral-lite)

- tutor/resources/styles/components/questions-dashboard.less
- tutor/src/components/questions/exercises-display.cjsx
- tutor/src/helpers/exercise.coffee
> Update question library exercise exclude/include wording

- coach/test/exercise/index.spec.coffee
- shared/resources/styles/components/question.less
- shared/src/components/exercise-identifier-link.cjsx
- shared/src/components/exercise/mode.cjsx
- shared/src/components/question/answer.cjsx
- shared/src/components/spy-mode.cjsx
- shared/test/components/exercise/index.spec.coffee
- shared/test/components/question/index.spec.coffee
- tutor/resources/styles/components/student-dashboard/task.less
- tutor/resources/styles/components/tabs.less
- tutor/src/components/buttons/browse-the-book.cjsx
- tutor/src/components/new-tab-link.cjsx
- tutor/src/components/related-content-link.cjsx
- tutor/src/components/student-dashboard/event-row.cjsx
- tutor/src/components/student-dashboard/event-task-row.cjsx
- tutor/src/components/student-dashboard/external-row.cjsx
- tutor/src/components/student-dashboard/generic-event-row.cjsx
- tutor/src/components/student-dashboard/homework-row.cjsx
- tutor/src/components/student-dashboard/reading-row.cjsx
- tutor/src/components/tabs.cjsx
- tutor/test/components/buttons/browse-the-book.spec.coffee
- tutor/test/components/helpers/task/checks.coffee
https://trello.com/c/pFHif8f1/152-showstopper-accessibility-screen-readers-are-not-fully-supported-in-tutor-blocking-some-students-from-completing-assignments
> Accessibility fixes

- tutor/src/components/task-teacher-review/exercise.cjsx
> add exercise trouble link to teacher task review

- coach/resources/styles/components/concept-coach/base.less
- coach/resources/styles/components/concept-coach/index.less
- coach/resources/styles/variables.less
- coach/src/concept-coach/base.cjsx
- coach/src/concept-coach/safari-warning.cjsx
- coach/test/concept-coach/safari-warning.spec.coffee
> Display a warning message for Safari ver < 10

- tutor/resources/styles/components/task/index.less
- tutor/resources/styles/components/task/teacher-review-controls.less
- tutor/resources/styles/global/navbar.less
- tutor/src/components/navbar/center-controls.cjsx
- tutor/src/components/task/index.cjsx
- tutor/src/components/task/teacher-review-controls.cjsx
- tutor/src/components/task/viewing-as-student-name.cjsx
- tutor/src/router.cjsx
> Fix reading task details

- shared/resources/styles/variables/openstax-bootstrap.less
quick container width adjustments so that all columns are whole number of pixels, to help with design.
> grid adjustments based on working with fred

- shared/src/components/smart-overflow.cjsx
- tutor/src/components/task-teacher-review/index.cjsx
- tutor/src/routes.coffee
Was missed when upgrading.  This gets it working, but routes aren't being updated when page scrolls
> Fix metrics review screen

- tutor/src/components/scores/assignment-header.cjsx
- tutor/src/components/scores/index.cjsx
it was displaying the "no period" message for all courses :(
> Fix scores report

- tutor/specs/components/assignment-links.spec.cjsx
- tutor/src/components/assignment-links.cjsx
- tutor/src/components/course-listing/index.cjsx
- tutor/src/routes.coffee
Another link that we missed :(
> fix CC assignment links screen

- exercises/src/api/adapter.coffee
- exercises/src/components/app.cjsx
- exercises/src/components/exercise-load-errors.cjsx
- exercises/src/components/exercise/preview.cjsx
- exercises/src/components/network-activity-spinner.cjsx
- exercises/src/components/record-not-found.cjsx
- exercises/src/components/search.cjsx
- exercises/src/stores/exercise.coffee
- exercises/src/stores/helpers.coffee
Updates exercises to display the loading error message on the all screens, not just search.
> Display error when loading from preview screen

- exercises/src/api/index.coffee
- exercises/src/components/published-modal.cjsx
- exercises/src/components/vocabulary.cjsx
- exercises/src/components/vocabulary/distractors.cjsx
- shared/src/components/demo.cjsx
- shared/src/components/exercise/mode.cjsx
- shared/src/components/scroll-tracker.cjsx
A handful of fixes with bad URL's and still using getDOMNode.
> Fix vocabulary editing

- tutor/src/components/related-content-link.cjsx
- tutor/src/components/task-step/step-footer-mixin.cjsx
- tutor/src/components/task/review.cjsx
And silence a few React warnings
> Fix back to dashboard on footer

- tutor/specs/components/course_settings/undrop-student.spec.cjsx
- tutor/specs/components/new-course/build-course.spec.cjsx
- tutor/src/components/course-listing/course.cjsx
- tutor/src/components/navbar/course-name.cjsx
- tutor/src/components/new-course/build-course.cjsx
Also found the "Teach Again" button was reloading the entire app, vs push state with router.
> Redirect to CC help page after creating CC course

- tutor/resources/styles/components/course-listings.less
- tutor/resources/styles/components/new-course.less
- tutor/resources/styles/components/ox-fancy-loader.less
- tutor/resources/styles/tutor.less
- tutor/specs/components/new-course/build-course.spec.cjsx
- tutor/src/components/course-listing/course.cjsx
- tutor/src/components/new-course/build-course.cjsx
- tutor/src/components/new-course/index.cjsx
- tutor/src/components/new-course/offering.cjsx
- tutor/src/components/new-course/wizard.cjsx
- tutor/src/components/ox-fancy-loader.cjsx
Loading and building animation for course builder widget
> Course cloner details

- tutor/src/api/index.coffee
- tutor/src/components/course-settings/add-period.cjsx
- tutor/src/components/course-settings/rename-course.cjsx
Fixes:
* updating student ids
* changing course title
* moving students between periods
* updating period name
* dropping a student
* undropping a student
> Fix bugs with updates on course settings

- tutor/resources/styles/components/course-calendar/sidebar.less
- tutor/resources/styles/components/course-listings.less
- tutor/resources/styles/components/task-plan/mini-editor.less
- tutor/resources/styles/mixins.less
- tutor/resources/styles/mixins/drag-and-drop.less
- tutor/specs/components/course-listing.spec.cjsx
- tutor/specs/components/helpers/enzyme-context.coffee
- tutor/specs/components/navbar/spec-test-params.coffee
- tutor/specs/components/scores/homework-cell.spec.cjsx
- tutor/specs/components/task-plan/mini-editor/index.spec.cjsx
- tutor/specs/current-user-store.spec.coffee
- tutor/src/components/app.cjsx
- tutor/src/components/course-calendar/index.cjsx
- tutor/src/components/course-listing/course-dnd.cjsx
- tutor/src/components/course-listing/course.cjsx
- tutor/src/components/course-listing/index.cjsx
- tutor/src/components/course-listing/listings.cjsx
- tutor/src/components/new-course/wizard.cjsx
- tutor/src/components/task-plan/mini-editor/editor.cjsx
- tutor/src/components/task-plan/mini-editor/index.cjsx
- tutor/src/flux/current-user.coffee
- tutor/src/helpers/conditional-handlers.cjsx
- tutor/src/routes.coffee
> Dnd courses onto add button

- shared/src/factories/link.cjsx
- tutor/resources/styles/components/course-calendar/plan.less
- tutor/resources/styles/components/course-calendar/sidebar.less
- tutor/resources/styles/components/task-plan/mini-editor.less
- tutor/resources/styles/global/buttons.less
- tutor/src/components/course-calendar/add-assignment-sidebar.cjsx
- tutor/src/components/course-calendar/add-menu-mixin.cjsx
- tutor/src/components/course-calendar/duration.cjsx
- tutor/src/components/course-calendar/header.cjsx
- tutor/src/components/course-calendar/month.cjsx
- tutor/src/components/course-calendar/past-assignments.cjsx
- tutor/src/components/course-calendar/plan-clone-placeholder.cjsx
- tutor/src/components/course-calendar/plan.cjsx
- tutor/src/components/course-calendar/sidebar-toggle.cjsx
- tutor/src/components/course-calendar/task-dnd.cjsx
- tutor/src/components/task-plan/builder/tasking-date-times.cjsx
- tutor/src/components/task-plan/footer/save-as-draft.cjsx
- tutor/src/components/task-plan/footer/save-button.cjsx
- tutor/src/components/task-plan/mini-editor/editor.cjsx
- tutor/src/flux/helpers.coffee
https://trello.com/c/RRjPCAB1/335-course-cloning-bugs 3, 6, 7, 9, 10, 11, 12, also 2 and 3 from the lower priorities
> more course clone/task cloning details

- tutor/src/components/task-plan/initialize-editing.coffee
https://trello.com/c/RRjPCAB1/335-course-cloning-bugs lower 5
> defaul due at should not be filled in when is new and no queries

- tutor/specs/components/new-course/select-course.spec.cjsx
- tutor/specs/components/new-course/select-dates.spec.cjsx
- tutor/specs/components/new-course/select-type.spec.cjsx
- tutor/src/components/new-course/course-clone.cjsx
- tutor/src/components/new-course/course-details.cjsx
- tutor/src/components/new-course/new-or-copy.cjsx
- tutor/src/components/new-course/select-course.cjsx
- tutor/src/components/new-course/select-dates.cjsx
- tutor/src/components/new-course/select-type.cjsx
- tutor/src/components/new-course/wizard.cjsx
- tutor/src/flux/new-course.coffee
https://trello.com/c/RRjPCAB1/335-course-cloning-bugs for number 1
> deafult values for new ocurse widget

- tutor/src/components/course-listing/index.cjsx
https://trello.com/c/a2axP1Hg/262-bug-teachers-with-1-course-are-taken-to-the-course-picker
> redirect for single course regardless of role
