tutor/specs/components/navbar/spec-test-params.coffee
tutor/specs/components/navbar/user_actions_menu.spec.cjsx
tutor/specs/current-user-store.spec.coffee
tutor/src/components/navbar/user-actions-menu.cjsx
tutor/src/flux/current-user.coffee

try to separate the sections of the teacher menu a little

---

tutor/resources/styles/components/course-calendar/plan-details.less
tutor/resources/styles/components/task-plan/index.less
tutor/resources/styles/components/task-plan/mini-editor.less
tutor/resources/styles/components/tutor-input.less
tutor/src/components/task-plan/event/index.cjsx
tutor/src/components/task-plan/external/index.cjsx
tutor/src/components/task-plan/homework.cjsx
tutor/src/components/task-plan/reading.cjsx

Task plan and builder fixes

---

tutor/specs/components/course-calendar/add-assignment-sidebar.spec.cjsx
tutor/specs/components/course-calendar/sidebar-toggle.spec.cjsx
tutor/src/components/course-calendar/add-assignment-sidebar.cjsx
tutor/src/components/course-calendar/helper.coffee
tutor/src/components/course-calendar/month.cjsx
tutor/src/components/course-calendar/sidebar-toggle.cjsx

Delay each sidebar step by 1.5 seconds

---

configs/test/jest.setup.coffee
tutor/resources/styles/components/new-course.less
tutor/specs/components/course-calendar/add-assignment-sidebar.spec.cjsx
tutor/specs/components/helpers/enzyme-context.coffee
tutor/specs/components/new-course/build-course.spec.cjsx
tutor/specs/components/new-course/course-details.spec.cjsx
tutor/specs/components/new-course/select-course.spec.cjsx
tutor/src/components/new-course/build-course.cjsx
tutor/src/components/new-course/course-details.cjsx
tutor/src/components/new-course/select-course.cjsx

Sort source course listing and don't select by default
Redirect immediately after creating course

Update cloning wizard's panels

---

shared/src/components/scroll-to-mixin.cjsx
tutor/src/components/task-plan/index.cjsx

Scroll task plan builder to top when it mounts

Task plan builder scroll to top on mount

---

tutor/src/components/unsaved-state.cjsx
tutor/src/helpers/plan.coffee

https://trello.com/c/7nczHRQe/257-bug-when-publishing-it-throws-do-you-really-want-to-leave-message

when unloading window due to server error, do not try to confirm

---

shared/src/api/action-adapter.coffee
shared/src/api/interceptors.coffee
tutor/resources/styles/components/task-plan/mini-editor.less
tutor/src/api/index.coffee
tutor/src/components/navbar/server-error-monitoring.cjsx
tutor/src/components/server-error-message.cjsx
tutor/src/components/task-plan/mini-editor/editor.cjsx
tutor/src/components/task-plan/mini-editor/index.cjsx
tutor/src/components/task-plan/plan-mixin.cjsx
tutor/src/components/tutor-input.cjsx
tutor/src/flux/task-plan.coffee

silent mini editor errors and fix some error handling details

---

tutor/src/helpers/conditional-handlers.cjsx

need to redirect with query if there is one for showIntro

---

tutor/resources/styles/components/course-calendar/sidebar.less

https://trello.com/c/fsGdjFBX/274-bug-cannot-select-the-last-assignment

last plan needs to be not covered by fancy gradient

---

coach/src/user/accounts-iframe.cjsx

As part of https://github.com/openstax/accounts/pull/402 I discovered the iframe code had a bug where it was calling findDOMNOde on React, not ReactDOM.
Also the updated accounts code doesn't set the title.

Use ReactDOM and remove title

---

tutor/src/components/course-calendar/past-assignments.cjsx
tutor/src/components/task-plan/mini-editor/editor.cjsx

Change editor header name from "Past" to "Copied"

---

tutor/resources/styles/global/navbar.less
tutor/src/components/navbar/user-actions-menu.cjsx
tutor/src/flux/current-user.coffee

Also tweaks menu's css to remove weird 5px border around menu toggle
on course picker:
But when viewing a course:

add option for cloning when course isn't present

---

tutor/resources/styles/components/task-plan/controls.less
tutor/resources/styles/components/task-plan/index.less
tutor/resources/styles/components/task-plan/mini-editor.less
tutor/src/components/task-plan/footer/index.cjsx
tutor/src/components/task-plan/mini-editor/editor.cjsx

Make buttons match for both mini & full editor

---

tutor/resources/styles/components/course-calendar/index.less
tutor/src/components/course-calendar/sidebar-toggle.cjsx

Gif doesn't have enough resolution to really show the transition but you get the idea

Animate the background color, delay icon change

---

tutor/specs/components/course-calendar/helper.spec.coffee
tutor/specs/components/course-calendar/sidebar-toggle.spec.cjsx
tutor/src/components/course-calendar/header.cjsx
tutor/src/components/course-calendar/helper.coffee
tutor/src/components/course-calendar/sidebar-toggle.cjsx

It's nice to see the work we put into the UI Settings paying off 😁

Use ui settings to store sidebar open/close state

---

shared/resources/styles/globals/externals.less
shared/resources/styles/mixins/index.less
shared/resources/styles/variables/openstax-bootstrap.less
tutor/resources/styles/components/course-calendar/add.less
tutor/resources/styles/components/course-calendar/month.less
tutor/resources/styles/components/course-calendar/sidebar.less
tutor/resources/styles/components/course-listings.less
tutor/resources/styles/components/new-course.less
tutor/resources/styles/components/task-plan/controls.less
tutor/resources/styles/components/task-plan/mini-editor.less
tutor/resources/styles/mixins.less

fix tooltip styling

---

tutor/resources/styles/components/course-calendar/sidebar.less
tutor/src/components/course-calendar/add-assignment-sidebar.cjsx

https://trello.com/c/XRPfiWaS/305-bug-tooltip-should-collapse-when-dragging
also fixes

fix drag weirdness and also closes intro on drag

---

tutor/resources/styles/components/course-settings.less

https://trello.com/c/4plbMd7C/306-bug-start-and-end-dates-merge-together

course settings styling got a little bit mixed up

---

tutor/src/components/plan-stats/index.cjsx

Add message for assignments without students

---

tutor/resources/styles/components/task-plan/builder.less
tutor/resources/styles/components/tutor-input.less
tutor/src/components/task-plan/builder/index.cjsx
tutor/src/components/task-plan/footer/index.cjsx
tutor/src/components/task-plan/homework.cjsx
tutor/src/components/task-plan/reading.cjsx
tutor/src/components/tutor-errors.cjsx
tutor/src/components/tutor-input.cjsx

Per
http://2jsgoo.axshare.com/#g=1&p=assignment_builder_style_bug_fixes&c=1

Style required field error messages consistently

---

tutor/src/components/course-listing/listings.cjsx
tutor/src/flux/current-user.coffee

https://trello.com/c/EGofO1p9/342-teach-this-course-again-button-shows-for-all-teachers-regardless-of-verification-status

check for verified teacher before using course role

---

tutor/resources/styles/components/new-course.less
tutor/resources/styles/components/questions-dashboard.less
tutor/src/components/new-course/select-course.cjsx

also center the `i` here vertically

make minor style adjustments, auto select course if there is only one

---

tutor/specs/components/course-listing.spec.cjsx
tutor/src/components/course-listing/course.cjsx

capitalization

---

bin/test-ci
configs/test/jest.setup.coffee

I think this might help with the random timeouts that happen only on travis

run Jest in-band on Travis, log unhandled Promise

---

tutor/src/components/course-settings/remove-teacher.cjsx
tutor/src/flux/roster.coffee

https://trello.com/c/OnhduDof/380-bug-removing-yourself-from-a-course-throws-an-error

redirect to course listing when removing self as teacher

---

tutor/src/components/course-settings/settings.cjsx

https://trello.com/c/PqBveUIc/346-bug-course-start-date-is-dec-31-should-be-jan-1

semester start and end dates

---

tutor/src/components/course-calendar/plan-clone-placeholder.cjsx
tutor/src/components/task-plan/initialize-editing.coffee

https://trello.com/c/1SQMU3gD/357-bug-dragging-an-assignment-makes-it-open-today

Fix start date for mini editor

---

shared/src/components/pinned-header-footer-card/index.cjsx

https://trello.com/c/suWaGT0S/358-bug-menu-disappearing-on-all-browsers-randomly

alternate fix for navbar

---

tutor/src/api/index.coffee

https://trello.com/c/bsBnRQqQ/378-bug-cannot-remove-withdrawn-assignments-as-a-student

add back in api handling for hiding student dashboard assignments

---

shared/resources/styles/components/change-student-id-form.less
shared/resources/styles/mixins/index.less
shared/resources/styles/mixins/input.less
shared/specs/components/change-student-id-form.spec.coffee
shared/src/components/change-student-id-form.cjsx
tutor/resources/styles/components/tutor-input.less
tutor/src/components/change-student-id.cjsx

Update styles for student id screen

---

coach/configs/webpack.development.coffee
shared/api/exercise-multipart/index.coffee
shared/configs/webpack.debug.coffee
shared/specs/components/exercise-preview/index.spec.coffee
shared/src/api/action-adapter.coffee
shared/src/api/collections.coffee
shared/src/api/index.coffee
shared/src/api/interceptors.coffee
shared/src/components/demo.cjsx
shared/src/model/notifications.coffee
tutor/configs/base.coffee

unfortunately, main `lodash` is using `_` global somewhere.  `_.noConflict()` could be used to fix this issue, but requiring the single functions seem less hacky.

updates for coach launcher

---

tutor/src/components/course-settings/cc-enrollment-code.cjsx

Note the change request doesn't mention changing the large enrollment code that appears at the top, I'm checking on that

Update CC enrollment; include enrollment_code param

---

coach/src/concept-coach/base.cjsx
coach/src/concept-coach/coach.cjsx
coach/src/concept-coach/launcher/index.cjsx
coach/src/course/new-registration.cjsx

should work for now, but not smooth
needs a little bit of styling love

Update coach skip enroll code if available

---

tutor/src/helpers/string.coffee

CourseInformation.forAppearanceCode can call this with undefined when a
course's appearance code is missing

Default string to '' when titleizing it

---

coach/specs/course/enrollment-code-input.spec.cjsx
coach/specs/course/new-registration.spec.cjsx
coach/src/concept-coach/base.cjsx
coach/src/course/enrollment-code-input.cjsx
coach/src/course/model.coffee
coach/src/course/new-registration.cjsx
coach/src/helpers/index.coffee
coach/src/navigation/index.cjsx
shared/src/components/notifications/course-has-ended.cjsx

2nd semester enrollment screen

---

coach/resources/styles/components/concept-coach/launcher.less
coach/resources/styles/components/course/registration.less
coach/resources/styles/components/graphics/launcher-animation.less
coach/src/concept-coach/coach.cjsx
coach/src/concept-coach/launcher/index.cjsx
coach/src/concept-coach/modal.cjsx

Fix coach launching

---

coach/src/navigation/index.cjsx
shared/resources/styles/components/notifications-bar.less
shared/specs/components/notifications/bar.spec.cjsx
shared/specs/components/notifications/pollers.spec.coffee
shared/specs/model/notifications.spec.coffee
shared/src/components/notifications/bar.cjsx
shared/src/components/notifications/email.cjsx
shared/src/components/notifications/system.cjsx
shared/src/model/notifications.coffee
shared/src/model/notifications/pollers.coffee

display multiple notices at once

---

coach/resources/styles/components/course/enrollment-code.less
coach/specs/concept-coach/launcher/__snapshots__/index.spec.cjsx.snap
coach/specs/course/__snapshots__/enrollment-code-input.spec.cjsx.snap
coach/specs/course/enrollment-code-input.spec.cjsx
coach/src/concept-coach/index.cjsx
coach/src/concept-coach/launcher/index.cjsx
coach/src/course/enrollment-code-input.cjsx
coach/src/exercise/index.cjsx
coach/src/navigation/settings.coffee
shared/specs/components/notifications/__snapshots__/course-has-ended.spec.cjsx.snap
shared/specs/model/notifications.spec.coffee
shared/src/components/notifications/course-has-ended.cjsx
shared/src/model/notifications.coffee
tutor/resources/styles/components/course-settings.less
tutor/specs/components/course_settings/cc-enrollment-code.spec.cjsx
tutor/src/components/course-settings/cc-enrollment-code.cjsx

CC fixes and enrollment verbiage updates

---

shared/specs/components/breadcrumb/index.spec.coffee
shared/specs/model/notifications.spec.coffee
shared/src/components/breadcrumb/index.cjsx
shared/src/model/notifications.coffee

Fix beadcrumbs so the "Summary" label appears

---

tutor/resources/styles/components/course-settings.less
tutor/specs/components/course_settings/cc-enrollment-code.spec.cjsx
tutor/src/components/course-settings/cc-enrollment-code.cjsx

add enrollment code to instructions for CC users

---

tutor/specs/components/task-plan/__snapshots__/select-topics.spec.cjsx.snap
tutor/specs/components/task-plan/select-topics.spec.cjsx
tutor/src/components/sections-chooser.cjsx
tutor/src/components/task-plan/select-topics.cjsx

In some cases such as when a course is cloned, a old task can have a different ecosystem than the course currently has, which causes a bug when the course ecosystem isn't found in the TocStore

Use ecosystem of task for reading table of contents

---

tutor/specs/helpers/task-plan.spec.coffee
tutor/src/api/index.coffee
tutor/src/components/error-monitoring/handlers.cjsx
tutor/src/flux/task-plan.coffee
tutor/src/helpers/task-plan.coffee

This way the BE knows what ecosystem should be used

Add ecosystem_id param to task plan saving endpoint

---

shared/resources/styles/components/notifications-bar.less
shared/specs/components/notifications/__snapshots__/course-has-ended.spec.cjsx.snap
shared/src/components/notifications/course-has-ended.cjsx

Update wording & styles for second semester banner

---

shared/specs/components/notifications/__snapshots__/course-has-ended.spec.cjsx.snap
shared/src/components/notifications/course-has-ended.cjsx

Remove un-loved "here"

---

coach/resources/styles/components/concept-coach/modal.less
coach/resources/styles/components/course/enroll-or-login.less
coach/resources/styles/components/course/registration.less
coach/specs/course/enroll-or-login.spec.cjsx
coach/specs/navigation/index.spec.coffee
coach/src/course/enroll-or-login.cjsx
coach/src/navigation/index.cjsx

note that buttons will be styled properly when embedded in webview
https://trello.com/c/ggAQGGyw/406-if-browser-full-width-sign-up-and-enroll-button-becomes-unclickable-resizing-the-browser-window-does-make-it-clickable
https://trello.com/c/FjnEL6WN/407-bug-1st-cc-enrollment-screen-right-after-cc-launcher-not-implemented-per-design

Fix enroll or login ui

---

coach/auth/status/GET.json
coach/specs/user/model.spec.coffee
coach/src/user/model.coffee
shared/specs/components/notifications/missing-student-id.spec.cjsx
shared/specs/model/notifications.spec.coffee
shared/src/components/notifications/missing-student-id.cjsx

Requires https://github.com/openstax/tutor-server/pull/1343

Switch FE to using latest_enrollment_at instead of joined_at to determine current CC course

---

bin/build

Looks like I missed renaming one of the $F vars as part of the git rev work

$F is renamed to $hashed, use that var

---

coach/demo.cjsx
coach/specs/concept-coach/launcher/index.spec.cjsx
coach/src/concept-coach/base.cjsx
coach/src/concept-coach/coach.cjsx
coach/src/concept-coach/index.cjsx
coach/src/concept-coach/launcher/index.cjsx
coach/src/course/enroll-or-login.cjsx
coach/src/course/model.coffee
coach/src/course/new-registration.cjsx
coach/src/course/registration.cjsx
coach/src/navigation/index.cjsx
coach/src/user/model.coffee
coach/src/user/status-mixin.coffee
shared/src/api/collections.coffee
shared/src/components/notifications/bar.cjsx
shared/src/model/notifications.coffee

Dependent on openstax/tutor-server#1344
If student is currently enrolled in a previous semester, clicking enroll will start enrolling the student into the course that matches the enrollment code.
If the student is not previously enrolled in courses relating to the book, clicking enroll will start enrolling, as in the above case.
for those enrolled in a past course:
with proper enrollment code:
without proper enrollment code:
both will require confirmation
after a message about joining and loading first exercise, exercise should load within 2 seconds.

if enrollment code doesnt match user's course, send user to enrollment workflow

---

coach/resources/styles/components/exercise/index.less
shared/resources/styles/components/exercise/step-card.less
shared/resources/styles/variables/index.less

Wrap long "comes from" text on CC exercises

---

shared/src/components/exercise-preview/index.cjsx
shared/src/helpers/match-by-router.cjsx
tutor/specs/components/book-link.spec.cjsx
tutor/specs/components/qa.spec.cjsx
tutor/specs/components/qa/__snapshots__/content.spec.cjsx.snap
tutor/specs/components/qa/__snapshots__/exercise-card.spec.cjsx.snap
tutor/specs/components/qa/book-link.spec.cjsx
tutor/specs/components/qa/content.spec.cjsx
tutor/specs/components/qa/exercise-card.spec.cjsx
tutor/src/components/match-for-tutor.cjsx
tutor/src/components/qa/book-link.cjsx
tutor/src/components/qa/content.cjsx
tutor/src/components/qa/exercise-card.cjsx
tutor/src/components/qa/exercises.cjsx
tutor/src/components/qa/index.cjsx
tutor/src/components/qa/reference-book-wrapper.cjsx
tutor/src/components/qa/view-book.cjsx
tutor/src/components/reference-book/page-shell.cjsx
tutor/src/flux/ecosystems.coffee

Otherwise it may render if the loads before the ecosystems are ready.  This happens if the book is extremely small

Fix qa view loading so it waits for ecosystems to be available

---

shared/resources/styles/components/ox-colored-stripe.less
shared/resources/styles/main.less
shared/resources/styles/variables/colors.less
shared/specs/components/__snapshots__/ox-colored-stripe.spec.cjsx.snap
shared/specs/components/ox-colored-stripe.spec.cjsx
shared/src/components/ox-colored-stripe.cjsx
tutor/resources/styles/components/invalid-page.less
tutor/resources/styles/tutor.less
tutor/specs/components/__snapshots__/invalid-page.spec.cjsx.snap
tutor/specs/components/helpers/component-testing.coffee
tutor/specs/components/invalid-page.spec.cjsx
tutor/src/components/invalid-page.cjsx

Style 404 page

---

tutor/resources/styles/components/task-plan/mini-editor.less
tutor/specs/components/error-monitoring/handlers.spec.cjsx
tutor/specs/components/task-plan/mini-editor/editor.spec.cjsx
tutor/src/components/error-monitoring/handlers.cjsx
tutor/src/components/error-monitoring/index.cjsx
tutor/src/components/task-plan/mini-editor/editor.cjsx

Use custom error handlers for mini editor

---

tutor/specs/components/task-plan/builder/index.spec.coffee
tutor/specs/components/task-plan/mini-editor/editor.spec.cjsx
tutor/src/components/error-monitoring/handlers.cjsx

Was passing error as an object property instead of as an argument

Fix mini editor spec

---

tutor/resources/styles/components/task-plan/lms-info.less
tutor/resources/styles/global/navbar.less
tutor/resources/styles/global/popover.less
tutor/src/components/task-plan/footer/help-tooltip.cjsx

Left align popovers, specifically the task builder help one.

---

coach/specs/user/login-gateway.spec.cjsx
coach/src/user/login-gateway.cjsx

Needed for https://github.com/openstax/tutor-server/pull/1354 so accounts will pre-select "student" and hide the role for student signups.

Set "go" parameter to be student_signup

---

tutor/api/courses/1/performance.json
tutor/resources/styles/components/scores/header.less
tutor/resources/styles/components/scores/table.less
tutor/specs/components/scores/__snapshots__/pie-progress.spec.cjsx.snap
tutor/specs/components/scores/pie-progress.spec.cjsx
tutor/specs/components/scores/student-data-sorter.spec.coffee
tutor/src/components/scores/assignment-header.cjsx
tutor/src/components/scores/name-cell.cjsx
tutor/src/components/scores/pie-progress.cjsx
tutor/src/components/scores/student-data-sorter.coffee
tutor/src/components/scores/table.cjsx

Fix safari layout bugs with scores report

---

tutor/resources/styles/components/course-calendar/month.less

hide overflow from plan

---

shared/src/components/scroll-to-mixin.cjsx
tutor/api/plans/1/review.json
tutor/specs/components/task-teacher-review/__snapshots__/breadcrumbs.spec.cjsx.snap
tutor/specs/components/task-teacher-review/__snapshots__/index.spec.cjsx.snap
tutor/specs/components/task-teacher-review/breadcrumbs.spec.cjsx
tutor/specs/components/task-teacher-review/index.spec.cjsx
tutor/src/components/plan-stats/index.cjsx
tutor/src/components/task-teacher-review/exercise.cjsx
tutor/src/components/task-teacher-review/index.cjsx
tutor/src/components/task-teacher-review/review.cjsx

The root cause was we weren't setting the markers properly in the MPQ parts.  Also noticed that it didn't scroll to exercises with video properly and set the top offset a bit better.

Fix breadcrumb scrolling to MPQ in teacher review

---

.codecov.yml
tutor/specs/components/questions/__snapshots__/dashboard.spec.cjsx.snap
tutor/specs/components/questions/dashboard.spec.cjsx
tutor/specs/components/questions/exercises-display.spec.cjsx
tutor/src/components/questions/exercise-controls.cjsx

Really a front for testing codecov

re-enable coverage of test directories

---

coach/src/course/model.coffee
shared/src/api/collections.coffee

get moment-timezone out of coach build, it's not necessary for collections or the coach course model
shaves off ~190 kb

decrease coach build more

---

shared/src/model/notifications/pollers.coffee

I must have been thinking too much es6 importy there

Use individual requires so it doesn't pull in entire lodash

---

coach/src/user/model.coffee
shared/specs/model/exercise.spec.coffee
shared/src/model/exercise.coffee
tutor/index.coffee

Needs: https://github.com/openstax/tutor-server/pull/1365

Set the errata url from bootstrap data

---

tutor/resources/styles/components/scores/table.less

This: ![screen shot 2017-03-13 at 11 13 27 am](https://cloud.githubusercontent.com/assets/79566/23863663/4a102066-07de-11e7-9b00-6f5bd4e8b83b.png)
Becomes:

Apply ellipsis to scores report names column

---

coach/api/steps/4573/GET.json
shared/specs/components/exercise-identifier-link.spec.cjsx
shared/specs/model/exercise.spec.coffee
shared/src/components/exercise-identifier-link.cjsx
shared/src/components/exercise/group.cjsx
shared/src/components/exercise/index.cjsx
shared/src/model/exercise.coffee
tutor/src/components/questions/exercises-display.cjsx
tutor/src/components/task-plan/homework/add-exercises.cjsx
tutor/src/flux/exercise.coffee
tutor/src/helpers/exercise.coffee

https://trello.com/c/yF8QUneX/574-bug-not-everything-is-being-sent-to-the-new-errata-tool

Fix trouble url location

---

tutor/src/components/course-calendar/plan-label.cjsx
tutor/src/components/course-calendar/plan.cjsx

plan joyride wrapping

---

shared/src/api/action-adapter.coffee
tutor/index.coffee
tutor/src/api/index.coffee
tutor/src/models/user.js

Is on top of #1630, when that's merged this should be pretty small
Depends on BE https://github.com/openstax/tutor-server/pull/1370

Save tour views to server

---

package.json
tutor/resources/styles/components/tours/joyride.scss
tutor/resources/styles/components/tours/navbar.less
tutor/resources/styles/variables/colors.less
tutor/specs/models/tour/ride.spec.js
tutor/src/models/tour/context.js
tutor/src/models/tour/ride.js
tutor/src/models/tour/step.js
tutor/src/tours/teacher-calendar.json

* Next button should read "Got it" for first 3 and last step
* Don't scroll indicator when pointing to fixed element
* Bugfix for joyride to position itself better
* make tour replay navbar icon smaller
* Per @Fredasaurus our light blue should be even lighter
* Adjust tour font colors and use font-awesome chevron for back

Trying wheel updates II

---

package.json
tutor/specs/models/tour/context.spec.js
tutor/specs/models/tour/ride.spec.js
tutor/src/models/tour/context.js
tutor/src/models/tour/ride.js

Also fixes bug with tours failing to play successively unless they were unmounted

Show "got it" for tours with 3 or fewer steps

---

tutor/src/components/course-listing/course.cjsx
tutor/src/components/navbar/user-actions-menu.cjsx

Add attributes for targeting elements in specs

---

tutor/specs/flux/new-course.spec.coffee
tutor/src/flux/new-course.coffee

Goes with https://github.com/openstax/tutor-server/pull/1373

Added is_preview flag to new-course (defaults to false)

---

LICENSE

See https://github.com/blog/1530-choosing-an-open-source-license .
It adds some useful indicators for folks (and ppl searching to contribute to AGPL projects) and is detectable via their API
and Notice GitHub detected it (link to the API call) https://api.github.com/repos/philschatz/test/license

update license filename so GitHub recognizes it

---

tutor/src/models/courses-map.js

fix previous/old sections on course picker

---

shared/specs/components/static.spec.jsx
shared/src/components/exercise-badges/interactive-icon.jsx
shared/src/components/exercise-badges/multipart-icon.jsx
shared/src/components/static.js

Hat tip to @pandafulmanda for coming up with the idea

Add and use StaticComponent that will only render once

---

shared/src/api/index.coffee
shared/src/model/networking.coffee
tutor/src/api/adapter.coffee
tutor/src/models/user.js

https://trello.com/c/qxH2IZ8E/672-bug-actions-fail-with-a-422-in-firefox-but-they-works-on-chrome
Actually fails on both

csrf token change on User model needs to be observed for change to update xhr options

---

shared/index.cjsx
shared/src/components/handle-body-classes-mixin.coffee
shared/src/components/pinned-header-footer-card/index.cjsx
tutor/resources/styles/components/task/milestones.less
tutor/resources/styles/components/top-nav-bar.less
tutor/src/components/book-content-mixin.cjsx
tutor/src/components/breadcrumb/index.cjsx
tutor/src/components/task/breadcrumbs.cjsx
tutor/src/components/task/index.cjsx
tutor/src/flux/task-step.coffee
tutor/src/flux/task.coffee

Fix various

---

tutor/src/components/course-calendar/index.jsx

remove stray ;

---

tutor/specs/components/navbar/__snapshots__/index.spec.jsx.snap
tutor/specs/components/navbar/spec-test-params.js
tutor/specs/models/user/menu.spec.js
tutor/src/components/course-listing/course.jsx
tutor/src/components/navbar/user-actions-menu.jsx
tutor/src/models/user/menu.js

Per: https://trello.com/c/c4oTGYKJ/655-use-create-or-copy-a-course-everywhere-deprecate-add-a-course-teach-this-course-teach-a-new-course

Teacher user menu to read 'create or copy a course'

---

tutor/resources/styles/components/my-courses.less

* Sets the preview belt colors
* Drop shadow for belt
* Uniform heading color
* All sections get bottom border

Style "MyCourses" page

---

shared/src/api/action-adapter.coffee
shared/src/api/index.coffee
tutor/resources/styles/components/my-courses.less
tutor/src/components/error-monitoring/handlers.cjsx
tutor/src/components/my-courses/course.jsx
tutor/src/models/course/offerings/previews.js

Display error modal when claiming preview fails

---

tutor/index.js
tutor/resources/styles/components/my-courses.less
tutor/resources/styles/components/top-nav-bar/drop-down-menu.less
tutor/specs/components/__snapshots__/app.spec.jsx.snap
tutor/specs/components/app.spec.jsx
tutor/specs/components/my-courses.spec.jsx
tutor/specs/components/my-courses/__snapshots__/pending-verification.spec.jsx.snap
tutor/specs/components/my-courses/pending-verification.spec.jsx
tutor/specs/components/navbar/__snapshots__/index.spec.jsx.snap
tutor/specs/components/navbar/index.spec.jsx
tutor/specs/components/navbar/support-menu.spec.jsx
tutor/specs/components/navbar/user_actions_menu.spec.jsx
tutor/src/components/my-courses/pending-verification.jsx
tutor/src/components/navbar/support-menu.jsx
tutor/src/components/navbar/user-actions-menu.jsx
tutor/src/models/chat.js
tutor/src/models/user/menu.js

Salesforce chat

---

tutor/resources/styles/components/new-course.less
tutor/specs/components/new-course/__snapshots__/course-numbers.spec.jsx.snap
tutor/src/components/new-course/course-numbers.jsx

https://trello.com/c/xSeiEtY9/699-bug%3A-%E2%80%9Cestimated-number-of-students-in-your-course%E2%80%9D-is-too-small%2C-unable-to-see-the-number

course nubmers label fix

---

shared/src/api/action-adapter.coffee
tutor/src/api/index.coffee
tutor/src/components/my-courses/index.jsx
tutor/src/models/user.js

There's additional events coming but we can merge this for now
Requires BE PR https://github.com/openstax/tutor-server/pull/1404

Log user interactions to /log/events for marcom

---

exercises/api/exercises/1.json
exercises/api/exercises/1@draft.json
exercises/src/api/index.coffee
exercises/src/components/exercise/attachments/attachment.cjsx
exercises/src/components/exercise/attachments/chooser.cjsx
exercises/src/components/exercise/attachments/index.cjsx
exercises/src/components/exercise/controls.cjsx
exercises/src/stores/exercise.coffee

Goes with https://github.com/openstax/exercises/pull/186
Manually tested on exercises-dev...

Fixed the delete exercise image API url

---

tutor/src/components/task-step/index.cjsx

for @Dantemss's BE https://github.com/openstax/tutor-server/pull/1409

Display task step spy info

---

tutor/resources/styles/components/course-calendar/header.less

expand no-sections message so it fills row and doesn't look weird

---

tutor/src/models/chat.js

It was encountering an error "window.liveagent is null". and would then fail to render page :(

fix for safari chat

---

tutor/specs/components/student-preview/builder-popup.spec.jsx
tutor/specs/components/task-plan/footer.spec.js
tutor/specs/components/task-plan/footer/__snapshots__/preview-button.spec.jsx.snap
tutor/src/components/student-preview/builder-popup.jsx
tutor/src/components/student-preview/index.jsx
tutor/src/components/task-plan/footer/preview-button.jsx

Add approved assigment videos

---

shared/resources/styles/components/breadcrumbs/index.less
shared/specs/helpers/task.spec.coffee
shared/src/helpers/task.coffee
tutor/resources/styles/components/task-step/ends.less
tutor/src/components/task-step/ends.cjsx
tutor/src/flux/task.coffee
tutor/src/helpers/policies/policies.coffee

fixes practice worst appearance, brings back numbers and etc. for practice worst

fix pract worst type behavior

---

tutor/resources/styles/components/tours.less
tutor/resources/styles/components/tours/super-training-wheel.less
tutor/src/components/questions/sections-chooser.cjsx
tutor/src/components/tours/custom/how-to-use-ql.jsx
tutor/src/components/tours/custom/super-training-wheel.jsx
tutor/src/models/tour/actions.js
tutor/src/models/tour/actions/hover-exercise.js
tutor/src/tours/question-library.json

updates ql tour contents, makes super training wheels center vertically and add exercise hover style as action

Fix ql tours

---

tutor/resources/styles/components/questions-dashboard.less
tutor/resources/styles/components/task-plan/index.less

probably not very nice to all browsers though
https://trello.com/c/POEvzixQ/638-change-request-show-show-problems-button-above-the-fold-for-assignment-builder-and-question-library-teachers-fail-to-find-it-and

quick fix for section chooser height

---

tutor/specs/components/onboarding/__snapshots__/course-use-tips.spec.jsx.snap
tutor/specs/components/onboarding/course-use-tips.spec.jsx
tutor/specs/models/courses/information.spec.js
tutor/src/components/onboarding/course-use-tips.jsx
tutor/src/models/course.js
tutor/src/models/course/information.js

Link to best practices docs from course onboarding modal

---

tutor/src/models/course/builder-ux.js

https://trello.com/c/dwR1Gsye/732-bug-copy-course-available-even-if-there-isnt-a-past-course

just need to skip new or copy if there are no nonPreviews

---

tutor/resources/styles/components/course-settings.less
tutor/resources/styles/components/student-preview.less
tutor/resources/styles/global/typography.less
tutor/specs/components/__snapshots__/app.spec.jsx.snap
tutor/specs/components/student-preview/__snapshots__/index.spec.jsx.snap
tutor/specs/components/student-preview/index.spec.jsx
tutor/src/components/navbar/index.jsx
tutor/src/components/navbar/student-previews-link.jsx
tutor/src/components/student-preview/builder-popup.jsx
tutor/src/components/student-preview/index.jsx
tutor/src/routes.coffee

https://trello.com/c/f5SwZ77j/578-osw2onboarding09-faux-student-preview-as-an-instructor-i-want-to-get-a-feel-for-what-oxt-looks-like-as-a-student-so-i-can-see-wh

Style student preview and update content

---

tutor/resources/styles/components/tours.less
tutor/resources/styles/components/tours/centered-wheel.less
tutor/resources/styles/components/tours/super-training-wheel.less
tutor/resources/styles/components/tours/value-prop.less
tutor/resources/styles/variables/tutor-bootstrap.less
tutor/src/components/tours/custom/centered-wheel.jsx
tutor/src/components/tours/custom/common.jsx
tutor/src/components/tours/custom/index.js
tutor/src/components/tours/custom/super-training-wheel.jsx
tutor/src/components/tours/custom/tips-now-or-later.jsx
tutor/src/tours/teacher-calendar.json

https://trello.com/c/Z3EG4nZk/478-osw2onboarding04-training-wheels-as-openstax-we-want-instructors-and-students-to-experience-training-wheels-so-we-can-highlight

Fix tours additional

---

tutor/src/components/task-plan/homework/choose-exercises.cjsx
tutor/src/components/task-plan/reading.cjsx

https://trello.com/c/POEvzixQ/638-change-request-show-show-problems-button-above-the-fold-for-assignment-builder-and-question-library-teachers-fail-to-find-it-and#comment-59419d55dffcc52fbddc520a

buttons should be primary and disabled

---

tutor/specs/models/courses/onboarding/full-course.spec.js
tutor/specs/models/courses/onboarding/preview.spec.js
tutor/src/models/course/onboarding/base.js
tutor/src/models/course/onboarding/full-course.js
tutor/src/models/course/onboarding/preview.js
tutor/src/models/course/role.js

.. actually 4 hours after teacher joins which is equivalent

Display "are you ready to create.." 4 hours after course create

---

tutor/src/components/student-preview/builder-popup.jsx

Update student preview popup font

---

tutor/src/tours/course-settings.json

update verbiage to remove suggestion of setting up student acct

---

tutor/specs/components/onboarding/course-nag.spec.jsx
tutor/specs/models/courses/onboarding/full-course.spec.js
tutor/src/components/onboarding/course-nag.jsx
tutor/src/models/course.js
tutor/src/models/course/onboarding/base.js
tutor/src/models/course/onboarding/full-course.js

Now that nags are time based we don't need to track sessions

Remove old session counting logic

---

tutor/src/models/course/builder-ux.js

After you pick a course type this list is displayed

remove preview courses from clone consideration

---

tutor/resources/styles/components/student-preview.less
tutor/specs/components/student-preview/__snapshots__/index.spec.jsx.snap
tutor/src/components/student-preview/index.jsx

more padding on preview

---

tutor/specs/components/onboarding/course-nag.spec.jsx
tutor/specs/models/courses/onboarding/base.spec.js
tutor/specs/models/courses/onboarding/full-course.spec.js
tutor/specs/models/courses/onboarding/preview.spec.js
tutor/src/models/course/onboarding/base.js
tutor/src/models/course/onboarding/full-course.js
tutor/src/models/course/onboarding/preview.js

Otherwise teachers with old courses will be nagged

Only display nags on active courses

---

tutor/src/components/tours/custom/how-to-build-your-reading.jsx
tutor/src/components/tours/custom/index.js
tutor/src/tours/add-reading.json

https://trello.com/c/EDmfqj7a/586-j29-add-a-reading-training-wheels#comment-59441b1965c505c2b104e0e7

how to, not how we

---

tutor/resources/styles/components/new-course.less
tutor/resources/styles/components/terms-modal.less
tutor/resources/styles/mixins.less
tutor/specs/components/new-course/index.spec.jsx
tutor/src/components/new-course/index.jsx
tutor/src/components/terms-modal.jsx

* Style to match (updated/missed?) mockup 
* Force terms acceptance before creating course

Terms & Conditions fixes

---

tutor/src/components/course-calendar/index.jsx

https://trello.com/c/1CRvb41n/739-j29-bug-assignments-earlier-than-1-month-ago-arent-loading-when-moving-the-calendar

calendar now knows when to update and is more mobx-y

---

tutor/resources/styles/components/terms-modal.less
tutor/src/components/terms-modal.jsx

Terms modal tweaks

---

tutor/resources/styles/components/my-courses.less
tutor/resources/styles/components/top-nav-bar/drop-down-menu.less
tutor/specs/models/user.spec.js
tutor/src/components/my-courses/pending-verification.jsx
tutor/src/components/navbar/support-menu.jsx
tutor/src/models/chat.js
tutor/src/models/user.js

Screenshot is "staged", it won't normally show both options

Style chat buttons, only show to teacher

---

tutor/resources/styles/components/tours/super-training-wheel.less

add super tw breakpoints for narrower screens

---

tutor/src/components/navbar/course-name.jsx
tutor/src/flux/course.coffee
tutor/src/models/courses-map.js

Previously it didn't update until page reload since the model didn't update when flux store did.

Update course name in navbar when it's renamed

---

tutor/src/tours/question-library.json

"Details view" not "Details View"

---

tutor/src/tours/performance-forecast.json

Copy tweaks to PF tour

---

tutor/src/tours/add-homework.json

Copy tweaks to Add a HW tour

---

tutor/src/tours/add-reading.json

Copy tweaks to Add a Reading page tips

---

tutor/src/tours/scores.json

"Export scores" not "Export Scores"

---

tutor/src/components/tours/custom/how-to-use-ql.jsx

"View all questions" not "View all questions here"

---

tutor/src/components/tours/custom/how-to-build-your-reading.jsx

"How to build a reading" not "How to build your reading"

---

tutor/src/tours/teacher-calendar.json

copy tweaks to Preview/Full course page tips

---

tutor/specs/components/onboarding/expired-preview-warning.spec.jsx
tutor/specs/components/onboarding/second-session-warning.spec.jsx
tutor/src/components/onboarding/onboarding-nag.jsx

Remove "No problem" from the ask me later followup

---

tutor/specs/components/onboarding/__snapshots__/second-session-warning.spec.jsx.snap
tutor/src/components/onboarding/second-session-warning.jsx

copy tweak for main nag

---

tutor/src/tours/course-settings.json

Nix suggestion to set up own account using URL

---

tutor/src/tours/question-library.json

Nathan or Amanda -- for this PR, can you check one thing? Did I actually add a break just before "And don't worry ..." ? I am not sure if I did that right 👎

Copy tweaks to page tips tour

---

tutor/specs/components/tours/custom/__snapshots__/value-prop.spec.jsx.snap
tutor/src/components/tours/custom/value-prop.jsx

-- to emdash

---

tutor/resources/styles/components/my-courses.less
tutor/specs/components/my-courses.spec.jsx
tutor/src/components/my-courses/create-a-course.jsx
tutor/src/components/my-courses/index.jsx
tutor/src/models/tour.js
tutor/src/models/tour/ride.js
tutor/src/models/tour/step.js
tutor/src/tours/my-courses.json

https://trello.com/c/VMyRVnbq/775-bug-create-a-course-training-wheel-on-my-courses-not-matching-mockup

convert "Create a course..." popover to a tour

---

tutor/resources/styles/global/tutor-booksplash-background.less
tutor/resources/styles/variables/book-content.less

I tried to get the fancy looping stuff to work, but ran out of time, will make followup

style preview; set inverse color for sociology

---

tutor/resources/styles/global/tutor-booksplash-background.less
tutor/resources/styles/variables/book-content.less

Ran out of time to figure this out on #1772

Convert fg-inverse to using variable list

---

tutor/specs/components/student-preview/__snapshots__/index.spec.jsx.snap
tutor/specs/components/student-preview/index.spec.jsx
tutor/specs/models/courses/student-preview-ux.spec.js
tutor/src/components/student-preview/builder-popup.jsx
tutor/src/components/student-preview/index.jsx
tutor/src/models/course/student-preview-ux.js

re-use videos from builder popup on student experience screen

---

coach/configs/webpack.production.coffee

removing from full build, testing in webview locally

babel polyfill is in webivew

---

tutor/src/components/navbar/preview-add-course-btn.jsx
tutor/src/components/tours/custom/index.js
tutor/src/components/tours/custom/super-training-wheel.jsx
tutor/src/components/tours/custom/viewed-on-blur.jsx
tutor/src/tours/my-courses.json

https://trello.com/c/VMyRVnbq/775-july-10bug-create-a-course-training-wheel-on-my-courses-not-matching-mockup

Fix create a course

---

package.json
tutor/specs/models/tour/context.spec.js
tutor/src/components/tours/custom/centered-wheel.jsx
tutor/src/models/tour/context.js

https://trello.com/c/vomRaSSN/781-fix-and-re-enable-tours-for-ie
2 main things:
* `element.classList.add('more', 'than', 'one', 'class')` only adds the first class in IE
* `document.body.scrollTop` is always 0 in IE
* openstax/react-joyride#4

Fix ie tours

---

README.md
tutor/resources/styles/global/tutor-booksplash-background.less

Also fixed a few typos in the read

Style "preview" as small-caps

---

package-lock.json
tutor/resources/styles/components/onboarding.less
tutor/specs/models/courses/onboarding/student-course.spec.js
tutor/src/components/navbar/student-get-access-btn.jsx
tutor/src/components/onboarding/course-nag.jsx
tutor/src/components/onboarding/make-payment.jsx
tutor/src/components/onboarding/nags.js
tutor/src/components/onboarding/pay-now-or-later.jsx
tutor/src/components/payments/modal.jsx
tutor/src/components/payments/no-or-later.jsx
tutor/src/components/payments/panel.jsx
tutor/src/components/student-dashboard/index.jsx
tutor/src/models/course.js
tutor/src/models/course/onboarding/index.js
tutor/src/models/course/onboarding/student-course.js
tutor/src/models/course/student.js
tutor/src/models/payments.js

Needs BE PR https://github.com/openstax/tutor-server/pull/1437 to test payments

Pay now or later on boarding modal

---

tutor/resources/styles/components/top-nav-bar.less
tutor/src/components/navbar/student-get-access-btn.jsx
tutor/src/models/course/student.js

add days left counter to navbar

---

tutor/src/components/navbar/support-menu.jsx
tutor/src/models/tour/actions/open-calendar-sidebar.js
tutor/src/tours/teacher-calendar.json

Made into a PR so we can easily identify and tag/merge once release goes out

Hotfix branch

---

tutor/src/api/index.coffee
tutor/src/models/payments.js

https://github.com/openstax/tutor-server/pull/1475

use product uuid from BE

---

configs/webpack/base.coffee
tutor/specs/models/courses/student.spec.js
tutor/src/models/course.js
tutor/src/models/course/student.js
tutor/src/models/payments.js

From BE https://github.com/openstax/tutor-server/pull/1479

Use proper UUIDs for payments

---

configs/webpack/base.coffee
tutor/api/purchases.json
tutor/resources/styles/components/payments.less
tutor/specs/components/payments/__snapshots__/manage.spec.jsx.snap
tutor/specs/components/payments/manage.spec.jsx
tutor/specs/courses-test-data.coffee
tutor/specs/models/purchases/purchase.spec.js
tutor/src/api/index.coffee
tutor/src/components/payments/manage.jsx
tutor/src/models/purchases.js
tutor/src/models/purchases/purchase.js
tutor/src/routes.coffee

Refund is waiting on BE support - coming in https://github.com/openstax/tutor-server/pull/1437

Manage payments

---

tutor/resources/styles/components/enrollment-student-id.less
tutor/specs/components/__snapshots__/change-student-id.spec.jsx.snap
tutor/src/components/change-student-id.jsx

update change modal to read student id, not "identifier"

---

tutor/specs/models/courses/enroll.spec.js
tutor/src/models/base.js
tutor/src/models/course/enroll.js

Only set complete after courses list completes loading, otherwise the course listing is redirected to early.

Fix enrollment sequence

---

tutor/resources/styles/components/payments.less
tutor/specs/models/purchases/purchase.spec.js
tutor/src/models/course/student.js
tutor/src/models/purchases/purchase.js

Previously we were removing from course, but it's been decided they should remain but be unpaid.

Mark student as unpaid after refund

---

tutor/resources/styles/components/payments.less
tutor/resources/styles/variables/colors.less
tutor/specs/components/payments/__snapshots__/manage.spec.jsx.snap
tutor/specs/components/payments/manage.spec.jsx
tutor/src/api/index.coffee
tutor/src/components/payments/manage.jsx
tutor/src/components/payments/refund-modal.jsx
tutor/src/helpers/string.coffee
tutor/src/models/purchases/purchase.js

#![screen shot 2017-07-19 at 10 28 22 am](https://user-images.githubusercontent.com/79566/28375404-0a8700a6-6c6d-11e7-8fd2-f87341bef08a.png)

Add "No Payments Found" message and support link to payments screen

---

tutor/resources/styles/components/onboarding.less

Using fixed top made modal unable to scroll up on short screens

use translateY for positioning to allow scrolling

---

tutor/resources/styles/components/onboarding.less
tutor/specs/components/navbar/spec-test-params.js
tutor/specs/models/courses/onboarding/student-course.spec.js
tutor/src/api/index.coffee
tutor/src/components/navbar/student-get-access-btn.jsx
tutor/src/components/onboarding/nags.js
tutor/src/components/onboarding/pay-now-or-later.jsx
tutor/src/components/onboarding/payments-disabled.jsx
tutor/src/models/course.js
tutor/src/models/course/create.js
tutor/src/models/course/onboarding/student-course.js
tutor/src/models/payments.js
tutor/src/models/purchases.js
tutor/src/models/purchases/purchase.js
tutor/src/models/user/menu.js

This is the fallback plan if testing reveals unfixable bad bugs

display "trial" messaging when payments are disabled

---

shared/api/notifications.json
shared/specs/model/notifications/pollers.spec.coffee
shared/src/model/notifications.coffee
shared/src/model/notifications/pollers.coffee
tutor/index.js
tutor/specs/courses-test-data.coffee
tutor/specs/models/courses/student.spec.js
tutor/src/models/course/student.js
tutor/src/models/payments.js

This way when it's switched on/off the UI will update without reloading
Goes along with BE https://github.com/openstax/tutor-server/pull/1489

Load payment enabled/disabled status when polling

---

tutor/src/components/icon.cjsx
tutor/src/components/navbar/student-get-access-btn.jsx

add tooltip to "Free Trial" message

---

tutor/resources/styles/components/tours/value-prop.less

set width: 100% and adjust stlyes for IE

---

tutor/src/models/course.js
tutor/src/models/course/student.js

Fixes bug where "pay now" still appeared for comped student

Add isUnPaid computed property and fix spelling of 'comped' (no t)

---

tutor/src/components/student-dashboard/index.jsx
tutor/src/models/course/onboarding/student-course.js

Fix 422 error when payment is past due

---

tutor/specs/components/navbar/student-get-access-btn.spec.jsx
tutor/specs/courses-test-data.coffee
tutor/src/components/navbar/student-get-access-btn.jsx

Looks like this was missed. It was cosmetic since the student really was marked as paid, but wouldn't see it until a reload :/

mark student record as paid when payment is completed

---

tutor/resources/styles/components/onboarding.less
tutor/specs/components/onboarding/__snapshots__/free-trial-activated.spec.jsx.snap
tutor/specs/components/onboarding/free-trial-activated.spec.jsx
tutor/src/components/onboarding/free-trial-activated.jsx
tutor/src/components/onboarding/nags.js
tutor/src/components/onboarding/pay-now-or-later.jsx
tutor/src/models/course/onboarding/student-course.js

Display "Trial Activated" message after "try later" is clicked

---

tutor/resources/styles/components/top-nav-bar.less
tutor/src/components/navbar/index.jsx
tutor/src/components/navbar/student-pay-now-btn.jsx

rename "Get access" to "Pay now"

---

tutor/resources/styles/components/onboarding.less
tutor/resources/styles/components/terms-modal.less
tutor/resources/styles/mixins.less
tutor/specs/models/courses/onboarding/student-course.spec.js
tutor/src/models/course/onboarding/student-course.js

also styles the on boarding modals a bit better

Fix terms agreement not appearing over top of on boarding

---

shared/src/components/spy-mode.jsx
tutor/specs/components/__snapshots__/app.spec.jsx.snap
tutor/src/components/performance-forecast/progress-bar.cjsx
tutor/src/components/student-dashboard/progress-guide.cjsx
tutor/src/components/task/details.cjsx

label the info buttons
Practice more buttons -> role=link
View All Topics -> role=link

Fix student dashboard accessibility issues

---

tutor/resources/styles/components/performance-forecast/index.less
tutor/resources/styles/components/student-dashboard/dashboard.less
tutor/resources/styles/components/student-dashboard/progress-guide.less
tutor/resources/styles/components/tabs.less
tutor/resources/styles/global/tutor-booksplash-background.less
tutor/specs/components/course_settings/roster.spec.cjsx
tutor/specs/components/payments/__snapshots__/manage.spec.jsx.snap
tutor/specs/components/scores/__snapshots__/index.spec.cjsx.snap
tutor/specs/components/student-dashboard/__snapshots__/dashboard.spec.jsx.snap
tutor/src/components/buttons/button-with-tip.cjsx
tutor/src/components/course-title-banner.jsx
tutor/src/components/payments/manage.jsx
tutor/src/components/performance-forecast/section.cjsx
tutor/src/components/student-dashboard/dashboard.jsx
tutor/src/components/student-dashboard/progress-guide.cjsx
tutor/src/components/tabs.cjsx

Updating the structural elements of the page while keeping the appearance and behavior the same.

Update heading structure on student dashboard

---

tutor/resources/styles/components/task-teacher-review/question.less

Fixed by running on staging, making changes in the debugger, and making the same changes in the css.

Fix position of student name in Review Metrics

---

shared/specs/model/ui-settings.spec.coffee
shared/src/model/ui-settings.coffee
tutor/src/models/course/onboarding/student-course.js

Was causing a bug with free trial start button when user was a member of other courses

fix UiSettings not being deeply observable

---

shared/src/helpers/task.coffee

part of https://trello.com/c/mNpmDvT9/663-t31801b-new-spaced-practice-interstitial-card-rationalize-spaced-practice-as-tutor-we-want-to-make-spaced-practice-work-in-a-way?menu=filter&filter=label:target-170814-tutor

show setting type cards only once for all types

---

tutor/specs/components/enroll.spec.jsx
tutor/src/components/enroll.jsx

Fixes 404 bug where we were redirecting to `undefined` courses

only redirect to course when we have its id

---

tutor/specs/models/courses/__snapshots__/create.spec.js.snap
tutor/specs/models/courses/create.spec.js
tutor/src/models/course/create.js

Everything is considered college now so it's not needed

remove is-college flag

---

CONTRIBUTING.md

fix link to main CONTRIBUTING.md file

---

tutor/src/components/breadcrumb/index.cjsx
tutor/src/components/task-step/exercise.cjsx
tutor/src/components/task-step/index.cjsx
tutor/src/components/task-step/placeholder.cjsx
tutor/src/components/task/progress/panel.cjsx
tutor/src/flux/task-step.coffee
tutor/src/flux/task.coffee

https://trello.com/c/n0AFMRCu/904-bug-personalized-assessment-screen-locked-homework

fix personalized questions while loading

---

tutor/src/components/onboarding/course-nag.jsx
tutor/src/components/student-dashboard/index.jsx

Fixes flash of dashboard appearing behind the modal as it displays

don't animate onboarding modal

---

shared/src/components/exercise/mode.cjsx

Code to focus on free-response field on update was being skipped.

Fix: focus on free response field

---

tutor/specs/components/onboarding/__snapshots__/free-trial-activated.spec.jsx.snap
tutor/src/components/onboarding/free-trial-activated.jsx

update "Get Access" workding to match button text

---

tutor/src/components/payments/refund-modal.jsx

Add $ to amount on refund confirmation modal

---

shared/specs/components/notifications/__snapshots__/course-has-ended.spec.cjsx.snap
shared/specs/model/notifications.spec.coffee
shared/src/components/notifications/course-has-ended.cjsx
shared/src/model/notifications.coffee

And also rename the message from "The first semester of this course has ended." to be "This course has ended"

Clear notices from other courses when setting them

---

package-lock.json
package.json
tutor/api/purchases.json
tutor/resources/styles/components/payments.less
tutor/specs/components/payments/__snapshots__/manage.spec.jsx.snap
tutor/specs/components/payments/manage.spec.jsx
tutor/src/components/payments/manage.jsx
tutor/src/models/purchases.js
tutor/src/models/purchases/purchase.js

Display refunds each on their own line

---

tutor/specs/models/teacher-task-plans.spec.js
tutor/src/components/course-calendar/index.jsx
tutor/src/components/task-plan/mini-editor/editor.cjsx
tutor/src/models/teacher-task-plan.js
tutor/src/models/teacher-task-plans.js

And also updated their status as they are published

don't remove cloned plans when another is dragged

---

tutor/src/components/student-dashboard/index.jsx

BE raises 422 (forbidden) in that case

Don't load tasks if payment is over due

---

tutor/specs/components/student-dashboard/__snapshots__/dashboard.spec.jsx.snap
tutor/specs/components/student-dashboard/dashboard.spec.jsx
tutor/specs/models/student-tasks.spec.jsx
tutor/specs/models/student/task.spec.js
tutor/specs/models/user.spec.js
tutor/src/models/student-tasks.js
tutor/src/models/student/task.js
tutor/src/models/user.js

* Match BE logic for on boarding calls
* Fix `canWork` logic so it matches previous to only look at `complete_exercise_count` when task is deleted

Fix dashboard and my courses

---

shared/src/components/exercise/mode.cjsx
shared/src/components/pinned-header-footer-card/sections.cjsx
shared/src/components/question/answer.cjsx
tutor/specs/components/qa/__snapshots__/exercise-card.spec.cjsx.snap
tutor/specs/components/student-dashboard/__snapshots__/dashboard.spec.jsx.snap
tutor/specs/components/student-dashboard/__snapshots__/events-panel.spec.jsx.snap
tutor/specs/components/task-plan/homework/__snapshots__/add-exercises.spec.cjsx.snap
tutor/src/components/student-dashboard/event-row.jsx

* Fix the answer choice so  it's read
* Makes exercise panel a tab-able section
* Labels the textarea and student dashboard using the correct "aria-label" attribute

Make exercises more accessible for screenreaders

---

tutor/specs/models/teacher-task-plans.spec.js
tutor/src/flux/helpers.coffee
tutor/src/flux/task-plan.coffee
tutor/src/models/teacher-task-plans.js

Before they'd hang out indefinitely until the calendar was moved forward/back

Remove pending deleted plans from calendar

---

shared/resources/styles/globals/maths.less
shared/resources/styles/main.less
shared/src/helpers/mathjax.coffee

Works in chromvox, hopefully also JAWS
needs mathjax update from https://github.com/openstax/tutor-server/pull/1512

Enable reading math with screenreaders

---

shared/resources/styles/components/exercise/intro.less
shared/src/components/exercise/intro.cjsx

Convert button to anchor tag for screenreader compatibility

---

tutor/src/components/error-monitoring/handlers.cjsx

add special message for `biglearn_not_ready` errors

---

tutor/resources/styles/components/new-course.less
tutor/specs/components/new-course/__snapshots__/course-numbers.spec.jsx.snap
tutor/specs/components/new-course/course-numbers.spec.jsx
tutor/specs/models/courses/builder-ux.spec.js
tutor/specs/models/courses/create.spec.js
tutor/src/components/new-course/course-numbers.jsx
tutor/src/models/course/builder-ux.js
tutor/src/models/course/create.js
tutor/src/models/user/menu.js

Rather than rely on the dom attribute's for min/max, which IE doesn't support (surprise!)
This way we can also display error messages

Validate new course counts against range

---

tutor/resources/styles/components/top-nav-bar/center-controls.less

fine tune alignment of center control icons

---

tutor/specs/components/__snapshots__/enroll.spec.jsx.snap
tutor/specs/components/enroll.spec.jsx
tutor/specs/models/courses/enroll.spec.js
tutor/src/components/enroll.jsx
tutor/src/models/base.js
tutor/src/models/course/enroll.js

Needs BE PR https://github.com/openstax/tutor-server/pull/1516

block teacher from enrolling as student

---

tutor/specs/components/__snapshots__/enroll.spec.jsx.snap
tutor/specs/components/enroll.spec.jsx
tutor/src/components/enroll.jsx

remove second "sorry" line, capitalize My courses

---

tutor/resources/styles/components/payments.less
tutor/specs/components/__snapshots__/enroll.spec.jsx.snap
tutor/specs/models/courses/payments.spec.js
tutor/src/components/enroll.jsx
tutor/src/components/payments/panel.jsx
tutor/src/models/payments.js

Goes along with payments PR https://github.com/openstax/ospayments/pull/169

Handle timeouts when loading payments iframe

---

tutor/resources/styles/components/payments.less

remove indent from refunded payments in listing

---

tutor/src/components/tours/custom/student-welcome-to-tutor.jsx

use sub-heading style so it center-aligns

---

tutor/specs/models/courses/onboarding/full-course.spec.js
tutor/src/models/course/onboarding/full-course.js

This prevents it from popping up every time when "I don't know" option is selected

Delay re-showing onboarding nag for 1 week after first view

---

tutor/specs/components/__snapshots__/app.spec.jsx.snap
tutor/specs/components/navbar/__snapshots__/index.spec.jsx.snap
tutor/specs/components/navbar/__snapshots__/user_actions_menu.spec.jsx.snap
tutor/specs/models/user/__snapshots__/menu.spec.js.snap
tutor/src/models/user/menu.js
tutor/src/routes.coffee

Needed the courseId from menu so back button has it on the page

fix back button on accessibility page

---

tutor/specs/models/feature_flags.spec.js
tutor/src/api/index.coffee
tutor/src/models/feature_flags.js

@m1yag1 you should be able to use this like:
```javascript
import FF from '../models/feature_flags';
if (FF.is_highlighting_allowed) { 
// do highlighting stuff 
}
```

Add feature flags interface

---

tutor/resources/styles/components/choices-listing.less
tutor/resources/styles/components/new-course.less
tutor/resources/styles/tutor.less
tutor/specs/components/__snapshots__/enroll.spec.jsx.snap
tutor/specs/components/enroll.spec.jsx
tutor/specs/components/new-course/__snapshots__/select-course.spec.jsx.snap
tutor/specs/components/new-course/__snapshots__/select-dates.spec.jsx.snap
tutor/specs/components/new-course/__snapshots__/wizard.spec.jsx.snap
tutor/specs/helpers/string.spec.coffee
tutor/src/api/index.coffee
tutor/src/components/choices-listing.jsx
tutor/src/components/enroll.jsx
tutor/src/components/enroll/invalid-code.jsx
tutor/src/components/enroll/invalid-teacher.jsx
tutor/src/components/enroll/select-periods.js
tutor/src/components/enroll/student-id.jsx
tutor/src/components/new-course/course-clone.jsx
tutor/src/components/new-course/new-or-copy.jsx
tutor/src/components/new-course/select-course.jsx
tutor/src/components/new-course/select-dates.jsx
tutor/src/components/new-course/select-type.jsx
tutor/src/helpers/string.coffee
tutor/src/models/course/enroll.js

Add period selection to enrollment when coming from LMS

---

shared/specs/helpers/task.spec.coffee
shared/src/helpers/step-helps.cjsx
shared/src/helpers/task.js

Requires https://github.com/openstax/tutor-server/pull/1547
Note: This will ONLY display the review card for assignments created after https://github.com/openstax/tutor-server/pull/1548 is deployed

Display review card based on review label

---

tutor/resources/styles/global/popover.less
tutor/specs/models/courses/enroll.spec.js
tutor/src/components/enroll.jsx
tutor/src/components/enroll/invalid-links-use.jsx
tutor/src/components/enroll/invalid-lms-use.jsx
tutor/src/components/enroll/invalid-lms.jsx
tutor/src/models/course/enroll.js

Display error message for students enrolling incorrectly

---

tutor/specs/models/courses/enroll.spec.js
tutor/src/models/course/enroll.js

Fixes bug where the url was "undefined" instead of having the enrollment code uuid

Use #needsPeriodSelection for choosing data structure to update

---

tutor/src/components/tours/custom/viewed-on-blur.jsx

I think this was broken in the router upgrade

Fix viewed on blur tour action

---

tutor/specs/components/course-settings/__snapshots__/student-access.spec.jsx.snap
tutor/src/components/course-settings/lms-panel.jsx

Change order of secret & key fields to match LMS

---

tutor/specs/models/courses/onboarding/full-course.spec.js
tutor/src/components/course-settings/student-access.jsx
tutor/src/components/scores/lms-push.jsx
tutor/src/components/task-plan/lms-info.jsx
tutor/src/models/jobs/lms-score-push.js
tutor/src/models/jobs/scores-export.js

really need to write specs for these jobs 😦 
maybe fit that in when we add the toast feature

bugfix; don't call set when it's a `get` :(

---

tutor/specs/components/__snapshots__/app.spec.jsx.snap
tutor/specs/components/navbar/__snapshots__/index.spec.jsx.snap
tutor/specs/components/navbar/__snapshots__/support-menu.spec.jsx.snap
tutor/specs/components/navbar/__snapshots__/user_actions_menu.spec.jsx.snap
tutor/specs/models/user/__snapshots__/menu.spec.js.snap
tutor/src/components/navbar/support-menu.jsx
tutor/src/models/user/menu.js

This came up in the demo. I'm pretty sure I didn't create the link properly 😄 .
Not sure if this is what tutor folks actually want, but thought I'd get the ball rolling if there was still interest.
/cc @reedstrm for suggesting the idea

add "Keyboard Shortcuts" to the Help Page

---

tutor/src/components/book-content-mixin.cjsx

This is not going to be the permanent canonical linking scheme as we should make this match the webview canonical link which is going to be discussed soon.

Reading content with canonical link

---

tutor/resources/styles/components/course-calendar/header.less
tutor/resources/styles/components/course-calendar/index.less
tutor/resources/styles/components/course-page.less
tutor/resources/styles/components/my-courses.less
tutor/specs/components/__snapshots__/course-page.spec.jsx.snap
tutor/specs/components/course-page.spec.jsx
tutor/src/components/course-calendar/index.jsx
tutor/src/components/course-calendar/month.cjsx
tutor/src/components/course-page.jsx
tutor/src/components/course-roster/index.jsx
tutor/src/components/no-periods.cjsx

Use course page style for teacher cal and other small style fixes

---

tutor/resources/styles/components/modals/warning.less
tutor/resources/styles/components/scores/controls.less
tutor/resources/styles/components/top-nav-bar.less
tutor/resources/styles/components/top-nav-bar/toasts.less
tutor/specs/components/navbar/__snapshots__/background-toasts.spec.jsx.snap
tutor/specs/components/navbar/background-toasts.spec.jsx
tutor/specs/models/jobs/lms-score-push.spec.js
tutor/specs/models/jobs/scores-export.spec.js
tutor/src/components/navbar/background-toasts.jsx
tutor/src/components/navbar/index.jsx
tutor/src/components/navbar/toasts/lms.jsx
tutor/src/components/navbar/toasts/scores.jsx
tutor/src/components/scores/export.jsx
tutor/src/components/scores/lms-push.jsx
tutor/src/components/student-dashboard/index.jsx
tutor/src/components/support-email-link.jsx
tutor/src/components/warning-modal.jsx
tutor/src/helpers/conditional-handlers.cjsx
tutor/src/models/jobs/lms-score-push.js
tutor/src/models/jobs/queue.js
tutor/src/models/jobs/scores-export.js

Display completed jobs in a toast notice

---

tutor/specs/components/app.spec.jsx
tutor/specs/components/helpers/enzyme-context.coffee
tutor/specs/components/helpers/test-router.coffee
tutor/src/models/user/menu.js

Fix accessing a course the user is no longer a member of

---

tutor/src/components/navbar/toasts/lms.jsx

Per mockup: http://4tk3oi.axshare.com/tutor_scores_paired_new_tabs_toolbar_dashboard_sty_2.html#choose_settings_tab=lms&CSUM=1
We will have to update this page again once we get the final KB link from Carly.

Updated copy

---

tutor/src/components/scores/table.jsx

Per mockup: http://4tk3oi.axshare.com/tutor_scores_paired_new_tabs_toolbar_dashboard_sty.html#choose_settings_tab=lms&CSUM=1

Update copy for no student state

---

tutor/src/components/scores/average-info.jsx

Per mockup: http://4tk3oi.axshare.com/tutor_scores_paired_new_tabs_toolbar_dashboard_sty_2.html#choose_settings_tab=lms&CSUM=1

Update Class Performance (i) copy

---

tutor/resources/styles/components/enrollment-student-id.less
tutor/resources/styles/components/modals/onboarding.less
tutor/resources/styles/components/modals/terms.less
tutor/resources/styles/components/modals/warning.less
tutor/resources/styles/components/new-course.less
tutor/resources/styles/mixins.less
tutor/specs/components/__snapshots__/change-student-id.spec.jsx.snap
tutor/specs/components/course-calendar/plan-details.spec.jsx
tutor/src/components/change-student-id.jsx
tutor/src/components/course-calendar/plan-details.jsx
tutor/src/components/course-roster/rename-period.jsx
tutor/src/components/task-plan/builder/tasking-date-times.cjsx
tutor/src/components/terms-modal.jsx
tutor/src/models/course.js
tutor/src/models/course/period.js

Various fixes

---

tutor/specs/components/course-settings/__snapshots__/student-access.spec.jsx.snap
tutor/src/components/course-settings/student-access.jsx

Mockup link: http://4tk3oi.axshare.com/settings_options_as_accordian_new_tabs_1.html#choose_settings_tab=lms&CSUM=1 
Nathan, I changed the copy on line 169 to "Give students direct links" but I wasn't 100% sure what this line is supposed to be pointing to.

Updated copy per LMS mockups

---

tutor/specs/components/plan-stats/__snapshots__/progress.spec.jsx.snap
tutor/specs/components/plan-stats/progress.spec.jsx
tutor/src/components/plan-stats/progress.jsx
tutor/src/models/task-plan/stats.js

Fix NaN displaying in progress bars when they were all incorrect

---

tutor/resources/styles/components/course-page.less
tutor/resources/styles/components/course-settings.less
tutor/resources/styles/components/scores/controls.less
tutor/resources/styles/components/scores/header.less
tutor/resources/styles/components/scores/index.less
tutor/resources/styles/components/scores/table.less
tutor/resources/styles/variables/colors.less
tutor/specs/courses-test-data.coffee
tutor/specs/helpers/scores-data.js
tutor/specs/models/jobs/lms-score-push.spec.js
tutor/specs/models/jobs/scores-export.spec.js
tutor/src/api/index.coffee
tutor/src/components/scores/export.jsx
tutor/src/components/scores/index.jsx
tutor/src/components/scores/lms-push.jsx
tutor/src/components/scores/overall-header.jsx
tutor/src/components/scores/table.jsx
tutor/src/models/course/scores.js
tutor/src/models/jobs/lms-score-push.js
tutor/src/models/jobs/scores-export.js

Scores styling fixes

---

tutor/resources/styles/components/course-settings/student-access.less
tutor/resources/styles/global/buttons.less
tutor/specs/components/course-settings/__snapshots__/student-access.spec.jsx.snap
tutor/src/components/course-settings/lms-panel.jsx
tutor/src/components/scores/table-filters.jsx
tutor/src/models/course/lms.js

Needs https://github.com/openstax/tutor-server/pull/1583

per LMS panels

---

tutor/resources/styles/components/course-calendar/header.less
tutor/resources/styles/components/course-page.less
tutor/resources/styles/components/course-settings.less
tutor/resources/styles/components/modals.less
tutor/src/components/course-roster/delete-period.jsx
tutor/src/components/course-settings/student-access.jsx

Fixes for modals and other small things

---

tutor/resources/styles/components/task-teacher-review/question.less
tutor/src/components/task-teacher-review/exercise.jsx
tutor/src/components/task-teacher-review/index.jsx
tutor/src/models/task-plan/crumbs.js
tutor/src/models/task-plan/stats.js
tutor/src/models/user.js

re-enable toggling free response answers

---

tutor/resources/styles/global/progress-bars.less
tutor/src/components/navbar/center-controls.jsx
tutor/src/helpers/scroll-to.js

* Fixes bug with the milestones where it would stop appearing if the reading was advanced while it wasn't scrolled to the top
* Adds left-margin to 0% correct progress bar

😭 Fixes for the previous fixes

---

exercises/src/stores/question.coffee

Exercises fix: only add new format if it's not already sent

---

tutor/resources/styles/components/task-teacher-review/question.less
tutor/src/components/task-teacher-review/exercise.jsx
tutor/src/models/task-plan/stats.js

1) move angle bracket to left of "Show student text responses (n)"
2) Change student names font to Helvetica
3) remove box border
4) Do not have expand option for 3 responses or less
5) For more than 3, display 3 responses in minimized state

Style teacher reviews feedback

---

tutor/resources/styles/components/reference-book/navbar.less
tutor/resources/styles/components/top-nav-bar.less
tutor/src/components/annotations/annotation.jsx
tutor/src/components/annotations/summary-page.jsx
tutor/src/components/annotations/summary-toggle.jsx
tutor/src/components/reference-book/index.cjsx
tutor/src/components/reference-book/navbar.cjsx
tutor/src/components/reference-book/page.cjsx
tutor/src/components/task-step/step-with-reading-content.cjsx
tutor/src/models/annotations/annotation.js
tutor/src/models/annotations/ux.js
tutor/src/models/course.js
tutor/src/models/user.js

Add toggle control for viewing annotation summary to navbar 

---

tutor/specs/components/course-roster/bootstrap-data.js
tutor/src/components/course-roster/student-roster.jsx

display loading indicator, use primary style for course settings btn

---

tutor/specs/components/student-dashboard/__snapshots__/events-panel.spec.jsx.snap
tutor/specs/components/student-dashboard/__snapshots__/reading-row.spec.jsx.snap
tutor/specs/components/student-dashboard/events-panel.spec.jsx
tutor/specs/components/student-dashboard/reading-row.spec.jsx
tutor/src/components/student-dashboard/reading-row.jsx

Fix readings so they show as "Not started" until opened

---

tutor/specs/components/__snapshots__/enroll.spec.jsx.snap
tutor/src/components/enroll/invalid-teacher.jsx

Update "Teacher can't enroll as student" copy

---

tutor/specs/components/student-dashboard/__snapshots__/homework-row.spec.jsx.snap
tutor/specs/components/student-dashboard/homework-row.spec.jsx
tutor/src/components/student-dashboard/homework-row.jsx
tutor/src/models/student/task.js

After the due date is past or when showing feedback immediate

Fix student homework rows to show correct/incorrect

---

tutor/resources/styles/book-content/base.less
tutor/resources/styles/components/annotations/annotation.less
tutor/resources/styles/components/paging-navigation.less
tutor/resources/styles/components/reference-book/page.less
tutor/resources/styles/components/task-step/all-steps.less
tutor/resources/styles/components/task-step/reading.less
tutor/src/components/annotations/annotation-card.jsx
tutor/src/components/annotations/annotation.jsx
tutor/src/components/annotations/summary-page.jsx

* Remove blue focus outline on reading content
* position highlight widget in center of rect
* display an error message when highlighting can't work
* remove highlights from page after delete

moar highlighting fixes

---

tutor/resources/styles/components/annotations/annotation.less
tutor/src/components/annotations/annotation-card.jsx
tutor/src/components/annotations/annotation.jsx
tutor/src/components/annotations/edit-box.jsx
tutor/src/components/annotations/inline-controls.jsx
tutor/src/components/annotations/sidebar-buttons.jsx
tutor/src/components/annotations/summary-page.jsx
tutor/src/components/annotations/window-shade.jsx
tutor/src/helpers/dom.coffee
tutor/src/models/annotations.js
tutor/src/models/annotations/annotation.js
tutor/src/models/annotations/hypothesis.js
tutor/src/models/annotations/ux.js
tutor/src/models/user.js

* Adds error handling for hypothesis server calls
* Bugs where we were calculating offsets from page vs the container el
* Ordering bugs & styles next/previous buttons on edit widget
* Safari bug where it'd highlight entire page
* Dismiss edit box on page click
* Autofocus input on edit box

Highlighting fixes ii

---

tutor/resources/styles/components/top-nav-bar.less
tutor/specs/components/navbar/__snapshots__/support-menu.spec.jsx.snap
tutor/specs/components/navbar/support-menu.spec.jsx
tutor/src/components/navbar/support-document-link.jsx
tutor/src/components/navbar/support-menu.jsx
tutor/src/models/course/information.js

Add links to best practices docs in support menu

---

tutor/resources/styles/components/annotations/annotation.less
tutor/src/components/annotations/annotation.jsx
tutor/src/components/annotations/sidebar-buttons.jsx
tutor/src/models/annotations.js
tutor/src/models/annotations/annotation.js

Before it wasn't sorting correctly so notes wouldn't always be selected properly when using buttons on edit box

Fix next/previous note selection

---

tutor/resources/styles/components/top-nav-bar.less
tutor/resources/styles/components/top-nav-bar/preview-add-course-btn.less
tutor/specs/components/__snapshots__/app.spec.jsx.snap
tutor/specs/components/my-courses.spec.jsx
tutor/specs/models/user.spec.js
tutor/src/components/my-courses/create-a-course.jsx
tutor/src/components/my-courses/index.jsx
tutor/src/components/navbar/preview-add-course-btn.jsx
tutor/src/components/tours/custom/no-footer.jsx
tutor/src/models/tour.js
tutor/src/models/user.js
tutor/src/tours/my-courses.json

Once any course has been previewed:

Fix preview or create tour logic

---

tutor/resources/styles/components/annotations/annotation.scss
tutor/src/components/annotations/annotation.jsx
tutor/src/components/annotations/edit-box.jsx
tutor/src/models/annotations/ux.js
tutor/src/models/course.js

* Only allow highlighting if feature flag is turned on
* use mouse up to trigger highlight instead of drag
* Only save highlight text when save button is clicked
* look outside selection for highlight element to remove it, fixes FF/Safari bug with deleting highlight

Highlighting fixes III

---

tutor/resources/styles/components/top-nav-bar/toasts.scss
tutor/src/components/navbar/toasts/lms.jsx
tutor/src/components/navbar/toasts/scores.jsx
tutor/src/components/scores/lms-push.jsx
tutor/src/models/job.js
tutor/src/models/jobs/lms-score-push.js
tutor/src/models/jobs/scores-export.js

Update wording and style export toasts

---

package-lock.json
tutor/resources/styles/components/exercise-preview.scss
tutor/resources/styles/components/task-plan/index.scss
tutor/resources/styles/mixins/tutor-plans.scss

coloring by type was missing from sass conversion, height of homework problem exercise preview was also fixed as opposed to content based.

update package lock and bring plan type based colors back to teacher UI

---

shared/src/components/question/answer.cjsx
tutor/specs/components/qa/__snapshots__/exercise-card.spec.cjsx.snap
tutor/specs/components/task-plan/homework/__snapshots__/add-exercises.spec.cjsx.snap

use button tag for a-b-c-d options for better i11y

---

tutor/resources/styles/components/tours.scss
tutor/resources/styles/components/tours/joyride.scss
tutor/resources/styles/variables/tutor-bootstrap.scss
tutor/src/components/tours/conductor.jsx

set popovers to be same width as training wheels (370px)

---

tutor/resources/styles/components/top-nav-bar/center-controls.scss
tutor/src/components/annotations/summary-toggle.jsx

Use button for annotation summary so it can be tabbed to and highlight

---

tutor/specs/components/course-settings/__snapshots__/student-access.spec.jsx.snap
tutor/src/components/course-settings/student-access.jsx

update copy for direct links body

---

tutor/src/models/chat.js
tutor/src/models/payments.js

Goes along with https://github.com/openstax/ospayments/pull/188

 Pass and init chat for payments

---

shared/resources/styles/components/notifications-bar.scss
shared/specs/model/user.spec.coffee
shared/src/components/notifications/email.cjsx
shared/src/model/networking.coffee
shared/src/model/user.coffee

Stop displaying error modal when email verification fails

---

tutor/resources/styles/book-content/index.scss

https://trello.com/c/nHB8voyG/1236-bug-flash-simulation-out-of-frame

fix sims width in reading content

---

tutor/resources/styles/components/top-nav-bar/drop-down-menu.scss
tutor/specs/components/navbar/__snapshots__/index.spec.jsx.snap
tutor/src/components/navbar/actions-menu.jsx

skip action menu if no menu items, and hide extra last menu divder

---

package.json
tutor/resources/styles/components/scores/header.scss
yarn.lock

bring back scores header coloring

---

tutor/src/components/tours/custom/index.js
tutor/src/components/tours/custom/no-hole-wheel.jsx
tutor/src/tours/student-dashboard.json

https://trello.com/c/KqkCxbON/1193-bug-student-onboarding-tour-this-is-your-dashboard-training-wheel-is-not-vertically-centered-on-page-in-safari-runs-off-bottom-o?menu=filter&filter=label:priority1-high,label:none

fix student dashboard welcome positioning

---

tutor/specs/components/navbar/__snapshots__/support-menu.spec.jsx.snap
tutor/specs/components/navbar/support-menu.spec.jsx
tutor/src/components/navbar/index.jsx
tutor/src/components/navbar/support-menu.jsx

Fix support doc tour sometimes not rendering

---

tutor/resources/styles/components/icon.scss
tutor/resources/styles/components/top-nav-bar/drop-down-menu.scss
tutor/resources/styles/mixins.scss
tutor/specs/components/__snapshots__/app.spec.jsx.snap
tutor/specs/components/navbar/__snapshots__/actions_menu.spec.jsx.snap
tutor/specs/components/navbar/__snapshots__/index.spec.jsx.snap
tutor/specs/components/navbar/__snapshots__/support-menu.spec.jsx.snap
tutor/src/components/navbar/actions-menu.jsx
tutor/src/components/navbar/support-menu.jsx

screenshot showing all the items with focus manually set with dev tools:

add focus style to remaining navbar items

---

tutor/specs/components/__snapshots__/enroll.spec.jsx.snap
tutor/specs/components/enroll.spec.jsx
tutor/src/components/enroll.jsx
tutor/src/components/enroll/course-ended.jsx
tutor/src/components/enroll/unknown-error.jsx
tutor/src/models/course/enroll.js

Handle `course_ended` error and add a generic handler

---

package.json
yarn.lock

use adapting horizontal scrollbar sizing

---

tutor/src/models/task-plan/teacher.js
tutor/src/screens/teacher-dashboard/plan.jsx
tutor/src/screens/teacher-dashboard/styles/plan-details.scss
tutor/src/screens/teacher-dashboard/styles/plan.scss

https://trello.com/c/8Qt7jbQh/1197-bug-ui-teacher-calendar-view-not-showing-assignment-open-dates and other small fixes

Fix calendar details

---

bin/build
configs/webpack/base.coffee
tutor/configs/webpack.base.coffee
tutor/index.js

Styles are now loaded as part of the JS chunk so they can be dynamic
and load via System.import
Goes along with https://github.com/openstax/tutor-server/pull/1652

remove ExtractTextPlugin

---

tutor/resources/styles/components/top-nav-bar.scss
tutor/resources/styles/components/top-nav-bar/plugable.scss
tutor/src/components/navbar/plugable.jsx
tutor/src/screens/qa/styles.scss
tutor/src/screens/reference-book/styles/navbar.scss

fix styles on pluggable navbar so the parts are aligned properly

---

tutor/resources/styles/mixins.scss

Set a line-height for done message

---

shared/resources/styles/components/exercise-preview/index.scss
shared/resources/styles/components/question.scss
shared/resources/styles/mixins/questions.scss

fix styles on hw builder select and feedback

---

tutor/src/models/tour.js
tutor/src/models/tour/context.js

https://trello.com/c/tEP1nQa8/955-bug-view-tips-now-tour-on-full-course-dashboard-launches-into-another-tour

page-tips-reminders was playing back to back, this addresses that

---

tutor/resources/styles/mixins/tutor-plans.scss
tutor/src/screens/teacher-dashboard/styles/plan.scss

Fix missing draft & failed task background colors

---

shared/src/components/popout-window.jsx
tutor/specs/components/student-preview/builder-popup.spec.jsx
tutor/src/components/student-preview/builder-popup.jsx

Was causing errors that'd prevet re-showing the popup window

Fix re-opening student preview pop-up window 

---

tutor/src/components/task-plan/builder/time-zone-settings-link.cjsx

The've been moved so that the time settings are there now

go to second tab for setting time

---

shared/specs/helpers/logging.spec.coffee
shared/src/components/question/answers-table.cjsx
shared/src/helpers/logging.coffee
tutor/src/components/annotations/highlighter.js
tutor/src/components/media-preview.cjsx
tutor/src/components/navbar/support-document-link.jsx
tutor/src/flux/step-title.coffee
tutor/src/models/tour/context.js

Fixes:
* TypeError: document.querySelectorAll(...).forEach is not a function
* IE 11 doesn't have forEach for nodeList
* Uncaught TypeError: Cannot read property 'preventDefault' of undefined
* TypeError: Cannot read property 'classList' of null  at Constructor.unhighlightMedia
* Uncaught TypeError: Cannot read property 'isStudent' of undefined 
* Uncaught Invariant Violation: attempted to add region student-highlighting-reading, but it already exists!
* TypeError: undefined is not an object (evaluating 'crumb.id')

Fix errors that were logged to papertrail

---

tutor/resources/styles/components/task-plan/index.scss
tutor/src/components/navbar/context.js
tutor/src/components/navbar/plugable.jsx
tutor/src/screens/reference-book/ux.js

Navbar's title lacked margin
Task builder's close button was left aligned

Fix various spacing things

---

tutor/src/models/user.js

this way the initials will be correct even if the user has a surname or title

read first and last name from server

---

tutor/resources/styles/components/tours.scss
tutor/resources/styles/components/tours/new-enrollment-link.scss
tutor/specs/components/course-settings/__snapshots__/student-access.spec.jsx.snap
tutor/specs/components/course-settings/student-access.spec.jsx
tutor/src/components/course-settings/student-access.jsx
tutor/src/components/enroll/course-ended.jsx
tutor/src/components/tours/custom/centered-wheel.jsx
tutor/src/components/tours/custom/index.js
tutor/src/components/tours/custom/new-enrollment-link.jsx
tutor/src/models/course.js
tutor/src/models/course/period.js
tutor/src/models/tour.js
tutor/src/models/tour/context.js
tutor/src/models/user.js
tutor/src/screens/teacher-dashboard/month.cjsx
tutor/src/tours/index.js
tutor/src/tours/new-enrollment-link.json

https://trello.com/c/NXwmul6k/1224-change-request-ensure-returning-tutor-user-sends-out-new-correct-enrollment-links-for-new-course

new enrollment link tour/modal

---

shared/src/components/exercise/mode.cjsx
shared/src/components/question/answer.cjsx
shared/src/components/question/answers-table.cjsx

https://trello.com/c/RFLdPdNG/1287-bug-multiple-answers-can-appear-as-selected

Fix exercise multi answer

---

tutor/specs/models/course.spec.js
tutor/src/models/course.js
tutor/src/models/courses-map.js

https://trello.com/c/NXwmul6k/1224-change-request-ensure-returning-tutor-user-sends-out-new-correct-enrollment-links-for-new-course

Fix enrollment showing

---

tutor/resources/styles/global/buttons.scss
tutor/src/screens/scores-report/overall-header.jsx
tutor/src/screens/scores-report/set-weights-modal.jsx
tutor/src/screens/scores-report/styles/set-weights-modal.scss
tutor/src/screens/scores-report/weights-ux.jsx

https://trello.com/c/nzF8ZQp5/1088-t30323-give-instructors-a-way-to-get-meaningful-scores-sent-to-the-lms-when-they-only-assign-readings-or-want-to-assign-credit-f

weights modal details and tool tip on toggle

---

tutor/specs/models/user.spec.js
tutor/src/models/user.js

Fix initials so they use first & last names

---

tutor/specs/components/course-settings/__snapshots__/student-access.spec.jsx.snap
tutor/specs/models/courses/period.spec.js
tutor/src/models/course/period.js

use dashes instead of url encoding enrollment links

---

tutor/src/screens/scores-report/set-weights-modal.jsx
tutor/src/screens/scores-report/styles/set-weights-modal.scss
tutor/src/screens/scores-report/weights-ux.jsx

Also adds async button  in chrome/firefox and sets a min/max

Reload scores after save completes

---

tutor/resources/styles/book-content/note.scss
tutor/resources/styles/components/performance-forecast/heading.scss
tutor/resources/styles/mixins/performance-forecast.scss

https://trello.com/c/Oo4ALQx9/1278-bug-spacing-between-or-around-text-is-missing

space performance key keys, and reading content notes

---

tutor/specs/components/__snapshots__/my-courses.spec.jsx.snap
tutor/specs/models/user.spec.js
tutor/src/models/courses-map.js

Before it was showing the oldest courses first on my courses listings

Display latest joined course first

---

tutor/src/components/task-step/step-with-reading-content.cjsx

made a mistake with previous related contented fix

---

tutor/specs/components/__snapshots__/app.spec.jsx.snap
tutor/specs/components/__snapshots__/my-courses.spec.jsx.snap
tutor/src/components/my-courses/listings.jsx

change course cards to 3 wide on medium screens

---

tutor/resources/styles/components/enrollment-student-id.scss
tutor/resources/styles/components/modals.scss
tutor/resources/styles/global/links.scss
tutor/resources/styles/variables/tutor-bootstrap.scss

UX tweaks to enrollment modal

---

tutor/src/flux/transition.coffee
tutor/src/helpers/routes-and-destinations.coffee

Fixes bug with the back button where it would always point to "Dashboard"

fix location store to use singular match and pathname

---

shared/resources/styles/components/breadcrumbs/index.scss

Style homework breadcrumbs like the readings ones

---

tutor/src/screens/scores-report/index.jsx
tutor/src/screens/scores-report/overall-header.jsx
tutor/src/screens/scores-report/table.jsx
tutor/src/screens/scores-report/ux.js
tutor/src/screens/student-dashboard/styles/progress-guide.scss

set table width to min of screen or table size
before:
after:

Set width of scores report to no larger than needed

---

tutor/resources/styles/components/top-nav-bar/drop-down-menu.scss
tutor/specs/components/__snapshots__/app.spec.jsx.snap
tutor/specs/components/navbar/__snapshots__/actions_menu.spec.jsx.snap
tutor/specs/components/navbar/__snapshots__/index.spec.jsx.snap
tutor/specs/components/navbar/__snapshots__/support-menu.spec.jsx.snap
tutor/src/components/navbar/actions-menu.jsx
tutor/src/components/navbar/support-menu.jsx

-15 px left aligned menus, but right aligned user

---

tutor/resources/styles/components/modals.scss

revert global changes to modals

---

configs/webpack/base.coffee
package.json

hard source was [barfing whenever there were syntax errors](https://github.com/mzgoddard/hard-source-webpack-plugin/issues/245#issuecomment-361316377).  make soft source easy for now

Feature soft source flag

---

screenshots/teacher-my-courses-pending-verification.png
tutor/resources/styles/components/my-courses.scss
tutor/resources/styles/components/task/index.scss
tutor/specs/acceptance/my-courses.spec.js

correct scss function from fadeout to be correct "fade-out"

---

tutor/specs/screens/scores-report/index.spec.jsx
tutor/src/screens/scores-report/table.jsx

Fix scores report message for students with no assignments

---

tutor/src/components/performance-forecast/student.cjsx
tutor/src/components/performance-forecast/teacher-student.cjsx
tutor/src/components/performance-forecast/teacher.cjsx

Replace performance report links with BackButton

---

tutor/index.js
tutor/src/models/course/task-plans.js
tutor/src/models/task-plan/teacher.js
tutor/src/models/tasking-plan.js
tutor/src/screens/scores-report/overall-cell.jsx
tutor/src/screens/scores-report/overall-header.jsx
tutor/src/screens/scores-report/table.jsx
tutor/src/screens/scores-report/ux.js
tutor/src/screens/scores-report/weights-ux.js

https://trello.com/c/rmS6rHdx/1301-bug-setting-a-weight-for-a-category-without-any-assignments-may-not-show-the-expected-course-score
need to add specs

Fix scores null averages

---

tutor/src/screens/scores-report/ux.js

when percent was actually 0, null was being returned for average

---

tutor/src/models/course/scores.js
tutor/src/screens/scores-report/assignment-header.jsx

The previous wouldn't work for students

No longer check isDue for headings and display BE data

---

tutor/specs/screens/scores-report/index.spec.jsx
tutor/specs/screens/scores-report/ux.spec.js
tutor/src/models/course/scores.js
tutor/src/screens/scores-report/overall-header.jsx
tutor/src/screens/scores-report/styles/overall-cell.scss
tutor/src/screens/scores-report/table.jsx
tutor/src/screens/scores-report/ux.js

Scores warning triangle

---

tutor/specs/screens/scores-report/ux.spec.js
tutor/src/models/course/scores.js
tutor/src/screens/scores-report/ux.js

Fix overall averages so they display n/a and --- vs 0%

---

tutor/specs/screens/scores-report/homework-cell.spec.jsx
tutor/specs/screens/scores-report/reading-cell.spec.jsx
tutor/src/screens/scores-report/assignment-header.jsx
tutor/src/screens/scores-report/homework-cell.jsx

Fix NaN for 0% clicked case on ext assign

Hide late work triangle from students on HW

---

tutor/resources/styles/components/annotations/annotation.scss
tutor/resources/styles/components/annotations/summary-page.scss
tutor/resources/styles/mixins.scss
tutor/resources/styles/mixins/triangle.scss
tutor/specs/components/__snapshots__/annotations.spec.jsx.snap
tutor/src/components/annotations/annotation-card.jsx
tutor/src/components/annotations/annotation.jsx
tutor/src/components/annotations/inline-controls.jsx
tutor/src/components/annotations/sidebar-buttons.jsx
tutor/src/components/annotations/summary-page.jsx
tutor/src/models/course.js

Allows students to highlight on any subject
Flips the controls so pointer triangle is on bottom and makes the review page use column layout

Highlighting updates

---

tutor/src/screens/qa-view/ecosystem-selector.jsx
tutor/src/screens/reference-book/index.jsx
tutor/src/screens/reference-book/ux.js

Fixes the reference book so that it will use the first available section instead of defaulting to `1`

Fix reference view for APUSH content

---

tutor/specs/screens/scores-report/assignment-header.spec.jsx
tutor/src/screens/scores-report/assignment-header.jsx

will need to rebase with master after #2158 is merged

Add small score header specs

---

shared/specs/helpers/exercise.spec.js
shared/src/helpers/exercise.js
tutor/src/models/app.js

Goes with https://github.com/openstax/tutor-server/pull/1706

record and use osweb_base_url

---

tutor/specs/components/navbar/spec-test-params.js
tutor/specs/components/payments/__snapshots__/manage.spec.jsx.snap
tutor/specs/components/student-preview/__snapshots__/index.spec.jsx.snap
tutor/specs/components/task-teacher-review/__snapshots__/breadcrumbs.spec.jsx.snap
tutor/specs/screens/question-library/__snapshots__/dashboard.spec.jsx.snap
tutor/src/components/buttons/back-button.cjsx
tutor/src/components/performance-forecast/teacher-student.cjsx
tutor/src/helpers/routes-and-destinations.coffee

https://trello.com/c/bpJ2TZK6/1342-bug-performance-forecast-back-to-button-as-will-all-pages-in-a-tutor-course-should-be-dynamic-and-state-back-to-and-the-previous mostly fixed by #2155, this pr only fixes the button color
also brings back teacher student dropdown

update back button colors

---

tutor/api/ecosystems/1/readings.json
tutor/api/ecosystems/3/readings.json
tutor/specs/screens/reference-book.spec.js
tutor/src/models/reference-book.js

Probably fixes the 404 on Question Library

Fix reference book getting the ID from the /readings API

---

tutor/specs/screens/scores-report/__snapshots__/overall-cell.spec.jsx.snap
tutor/specs/screens/scores-report/overall-cell.spec.jsx
tutor/src/screens/scores-report/overall-cell.jsx

Besides being inefficient, idenifier might be duplicated causing incorrect averages to be displayed

use index for finding student's score not identifier

---

tutor/api/courses/1/performance.json
tutor/specs/models/courses/scores.spec.js
tutor/specs/screens/scores-report/assignment-header.spec.jsx
tutor/specs/screens/scores-report/external-cell.spec.jsx
tutor/specs/screens/scores-report/student-data-sorter.spec.js
tutor/src/components/late-icon.cjsx
tutor/src/models/course/scores/task-result.js
tutor/src/screens/scores-report/assignment-header.jsx

Scores report late external popover, reword external clicked heading

---

tutor/resources/styles/book-content/base.scss
tutor/resources/styles/book-content/page.scss
tutor/src/components/book-content-mixin.cjsx

https://trello.com/c/2sxMuFac/1371-change-request-images-display-half-or-full-width
https://trello.com/c/mkcznfBE/1372-change-request-display-figure-numbers-and-titles

Adjust images

---

tutor/specs/models/course.spec.js
tutor/src/models/course.js

this is (hopefully) a stop-gap measure since highlighting math is pretty bad

Disable highlighting for physics

---

tutor/specs/components/task-plan/homework/choose-exercises.spec.js
tutor/specs/models/exercises.spec.js
tutor/src/components/task-plan/homework/choose-exercises.jsx
tutor/src/models/exercises.js
tutor/src/models/exercises/exercise.js

extracted from https://github.com/openstax/tutor-js/pull/2194 + some specs

Hide excluded exercises on HW builder

---

tutor/src/screens/surveys/styles.scss

Otherwise they pollute Tutor's styles and make various things strange, such as the logout button

Fix styles for menu changing after viewing surveys

---

tutor/specs/screens/__snapshots__/surveys.spec.js.snap
tutor/src/screens/student-dashboard/surveys.jsx
tutor/src/screens/surveys/index.jsx
tutor/src/screens/surveys/styles.scss

* Only apply styles to research-surveys course page
* Set a max-width
* Style button-groups
* Style alerts and move them below question

Fix survey range and misc styles

---

exercises/src/components/tags/book-selection.jsx
exercises/src/components/tags/books.jsx

Previously an exercise that contained multiple book tags wouldn't load

fix book tags selector on exercises

---

package.json
tutor/specs/models/app.spec.js
tutor/src/models/app.js
tutor/src/models/app/raven.js
yarn.lock

Goes along with https://github.com/openstax/tutor-server/pull/1699

use sentry for client-side error monitoring

---

tutor/resources/styles/components/toasts.scss
tutor/specs/screens/scores-report/homework-cell.spec.jsx
tutor/src/screens/scores-report/correctness-value.jsx
tutor/src/screens/scores-report/styles/table.scss
tutor/src/screens/teacher-dashboard/add-assignment-sidebar.jsx
tutor/src/screens/teacher-dashboard/add-menu.jsx
tutor/src/screens/teacher-dashboard/add.jsx
tutor/src/screens/teacher-dashboard/month.jsx
tutor/src/screens/teacher-dashboard/task-dnd.jsx

* Moves toast down a bit
* fix pie progress being dark grey even for unfinished portions
* Add events popup menu on calendar wasn't navigating on click

Misc fixes from review

---

tutor/specs/screens/scores-report/__snapshots__/assignment-cell.spec.jsx.snap
tutor/specs/screens/scores-report/assignment-cell.spec.jsx
tutor/src/components/book-content-mixin.cjsx
tutor/src/models/app/raven.js
tutor/src/screens/scores-report/absent-cell.jsx
tutor/src/screens/scores-report/assignment-cell.jsx

Concept coach was looking for the course but it wasn't available

render Absent cell by default instead of old ConceptCoach

---

tutor/resources/styles/global/links.scss

style external links with icon

---

tutor/resources/styles/components/choices-listing.scss
tutor/resources/styles/components/new-course.scss
tutor/resources/styles/global/alerts.scss

New course creation style tweaks

---

shared/resources/styles/components/exercise-preview/index.scss
shared/specs/components/exercise-preview/__snapshots__/index.spec.js.snap
shared/specs/components/exercise-preview/index.spec.js
shared/specs/model/exercise/tag.spec.js
shared/src/components/exercise-preview/index.jsx
shared/src/model/exercise/tag.js
tutor/specs/components/exercises/__snapshots__/cards.spec.js.snap
tutor/specs/components/exercises/__snapshots__/details.spec.jsx.snap
tutor/specs/components/exercises/__snapshots__/preview.spec.js.snap
tutor/specs/components/task-plan/homework/__snapshots__/review-exercises.spec.js.snap
tutor/specs/screens/__snapshots__/qa-view.spec.jsx.snap
tutor/src/models/exercises/tag.js

Default to only previewing "important" tags 

---

tutor/resources/styles/components/my-courses.scss
tutor/specs/components/app.spec.jsx
tutor/specs/components/my-courses.spec.jsx
tutor/specs/models/user.spec.js
tutor/src/components/my-courses/index.jsx
tutor/src/components/my-courses/listings.jsx
tutor/src/components/my-courses/no-hs-teachers.jsx
tutor/src/models/user.js

Don't allow non-college instructors to use Tutor

---

tutor/specs/models/courses/scores/task-result.spec.js
tutor/src/models/course/scores/period.js
tutor/src/models/course/scores/student.js

Don't need to divide by 100, doing so causes the average to be way to low

Course weights are in percents already

---

tutor/src/components/my-courses/no-hs-teachers.jsx

update copy for no-hs teachers message

---

shared/src/components/exercise/mode.cjsx
shared/src/components/question/answer.jsx
shared/src/components/question/answers-table.jsx
tutor/src/components/buttons/browse-the-book.jsx
tutor/src/components/related-content-link.cjsx
tutor/src/components/task-step/step-with-reading-content.cjsx

Since it can grow long and wasn't deemed useful by UX
Before:
After:

Change next step's continue text to be a button

---

tutor/specs/components/my-courses.spec.jsx
tutor/src/components/my-courses/listings.jsx

Prevents a 403 because they can't fetch the offering

hide preview from non-college instructors

---

tutor/specs/components/navbar/__snapshots__/actions_menu.spec.jsx.snap
tutor/src/components/navbar/actions-menu.jsx
tutor/src/models/reference-book/ux.js

* The menu's view book was using the old url
* Reference view was lacking course styles for it's banners.  That was traced back to the ux missing a return so the data-attributes were missing

Fix items detected during internal review

---

package.json
shared/src/helpers/react.coffee
tutor/src/components/browser-warning-modal/index.jsx
tutor/src/components/task-plan/reading.cjsx
tutor/src/components/task-step/index.cjsx
tutor/src/models/annotations.js
yarn.lock

https://sentry.cnx.org/openstax/tutor/issues/259/
TypeError<unknown module> in render
Cannot read property 'type' of null
https://sentry.cnx.org/openstax/tutor/issues/167/
TypeError<unknown module> in render
Cannot read property 'chapter_section' of undefined
https://sentry.cnx.org/openstax/tutor/issues/273/
TypeErrorshared/src/helpers/react in DEFINE_PROPERTY
undefined is not an object (evaluating 'browser.name')
https://sentry.cnx.org/openstax/tutor/issues/210/
TypeErrortutor/src/models/annotations in ?
Cannot set property 'listing' of undefined
https://sentry.cnx.org/openstax/tutor/issues/270/
TypeError<unknown module> in ReadingContentMixin.removeCanonicalLink
Object doesn't support property or method 'remove'

Bugfixes from sentry

---

exercises/specs/components/tags/__snapshots__/books.spec.js.snap
exercises/specs/components/tags/books.spec.js
exercises/src/components/tags/books.jsx
exercises/src/models/exercises.js

Fix exercise books tags controls and error msg

---

tutor/resources/styles/components/book-menu.scss
tutor/resources/styles/components/task-plan/chapter-section.scss
tutor/resources/styles/global/misc.scss
tutor/resources/styles/variables/book-content.scss
tutor/resources/styles/variables/colors.scss

add biology 2e style

---

tutor/specs/components/task-plan/homework/__snapshots__/choose-exercises.spec.js.snap
tutor/specs/components/task-plan/homework/choose-exercises.spec.js
tutor/specs/models/exercises.spec.js
tutor/specs/screens/question-library/dashboard.spec.jsx
tutor/src/components/task-plan/homework/add-exercises.jsx
tutor/src/components/task-plan/homework/choose-exercises.jsx
tutor/src/components/task-plan/homework/review-exercises.jsx
tutor/src/models/exercises.js
tutor/src/models/exercises/exercise.js
tutor/src/models/reference-book/page.js
tutor/src/screens/question-library/sections-chooser.jsx

Goes along with https://github.com/openstax/tutor-server/pull/1748

Load exercises by ecosystem and support filtering by id

---

tutor/specs/components/__snapshots__/app.spec.jsx.snap
tutor/specs/components/navbar/__snapshots__/index.spec.jsx.snap
tutor/specs/components/navbar/__snapshots__/support-menu.spec.jsx.snap
tutor/src/components/navbar/best-practices-guide.jsx
tutor/src/components/navbar/support-document-link.jsx
tutor/src/components/navbar/support-menu.jsx
tutor/src/models/course/information.js

Splits the best practices document into it's own component

add instructor version of getting started guide

---

exercises/specs/components/__snapshots__/exercise.spec.js.snap
exercises/specs/components/tags/__snapshots__/cnx-mod.spec.js.snap
exercises/specs/components/tags/cnx-mod.spec.js
exercises/src/components/tags/cnx-mod.jsx
exercises/src/components/tags/multi-input.jsx

the "value" wasn't being initialized causing the field to always be empty.

Fix CNX-module editing on exercises

---

tutor/specs/components/course-settings/__snapshots__/student-access.spec.jsx.snap
tutor/src/components/course-settings/student-access.jsx

mention LMS option on course settings

---

tutor/specs/models/courses/create.spec.js
tutor/src/models/course/create.js
tutor/src/screens/new-course/ux.js

The if clause was malformed and would return false for any
year other than 2018, such as 2019 :-(

Don't allow use of bio1 past summer 2018

---

tutor/resources/styles/components/tours.scss
tutor/resources/styles/components/tours/mini-notice.scss
tutor/resources/styles/variables/book-content.scss
tutor/specs/screens/new-course/__snapshots__/bio2e.spec.jsx.snap
tutor/specs/screens/new-course/bio2e.spec.jsx
tutor/src/components/tours/custom/mini-notice.jsx
tutor/src/screens/new-course/bio1e-unavailable.jsx
tutor/src/screens/new-course/styles.scss
tutor/src/tours/my-courses.json

* Add mask on tour notice
* Add megaphone to bio2 heading on new course wizard

Bio2e ux fixes

---

tutor/resources/styles/components/course-settings/student-access.scss
tutor/specs/components/course-settings/__snapshots__/student-access.spec.jsx.snap
tutor/src/components/course-settings/lms-panel.jsx

Update LMS specific help links

---

tutor/specs/models/courses/__snapshots__/create.spec.js.snap
tutor/specs/models/courses/create.spec.js
tutor/src/models/course/create.js

don't send the cloned_from_id property if the cloned from course's offering is marked unavailable

do not clone a course if the it's offering is no longer available

---

tutor/resources/styles/components/annotations/annotation.scss
tutor/specs/components/__snapshots__/annotations.spec.jsx.snap
tutor/specs/components/annotations.spec.jsx
tutor/specs/models/course.spec.js
tutor/src/components/annotations/annotation-card.jsx
tutor/src/components/annotations/annotation.jsx
tutor/src/components/annotations/highlighter.js
tutor/src/helpers/dom.js
tutor/src/models/course.js

runs mathjax on the summary so it looks much better

re-enable physics highlighting

---

tutor/src/tours/new-enrollment-link.json

update wording on cloned course tour to include mention of LMS

---

tutor/specs/components/payments/__snapshots__/manage.spec.jsx.snap
tutor/src/components/payments/manage.jsx

correct "Contact Support" link on manage payments 

---

exercises/specs/components/__snapshots__/exercise.spec.js.snap
exercises/specs/factories.js
exercises/specs/models/exercises.spec.js
exercises/src/api/index.js
exercises/src/components/exercise/attachments/attachment.jsx
exercises/src/models/exercises/exercise.js
shared/specs/factories/exercise.js
tutor/specs/screens/teacher-dashboard/month.spec.js

Instead of just doing so in memory :(

Delete attachments on the server

---

exercises/specs/components/__snapshots__/exercise.spec.js.snap
shared/specs/model/exercise/answer.spec.js
shared/specs/model/exercise/question.spec.js
shared/src/model/exercise.js
shared/src/model/exercise/answer.js
shared/src/model/exercise/question.js

add open-ended format

---

tutor/src/models/course/create.js
tutor/src/screens/new-course/ux.js

This way it will update to match the new bio2 offering instead of being stuck on the bio1 name

always update new course name to match the offering

---

tutor/src/tours/new-enrollment-link.json

whoops... somehow this made it through multiple people's 👀

remove duplicate "new" in course links popup message

---

tutor/src/screens/scores-report/late-work.jsx
tutor/src/screens/scores-report/styles/table.scss

this is what it used to look like:
these are what it looks like now:

update styles for popovers on student scores page

---

README-IE.md
configs/webpack/base.coffee

this is the config for accessing your local development environment from a windows virtual machine.

add steps to configure IE development

---

tutor/resources/styles/components/course-roster.scss
tutor/resources/styles/components/modals.scss
tutor/resources/styles/variables.scss
tutor/src/components/task-plan/footer/delete-link.jsx

before i updated the modal padding it looked like this:

use modal for assignment delete instead of popover

---

script/bootstrap

Related PR https://github.com/Connexions/cnx-recipes/pull/462

Update 'which' to 'command -v'

---

exercises/specs/components/__snapshots__/exercise.spec.js.snap
exercises/specs/components/exercise.spec.js
exercises/specs/components/exercise/__snapshots__/controls.spec.js.snap
exercises/specs/components/exercise/controls.spec.js
exercises/src/app.jsx
exercises/src/components/exercise/controls.jsx
exercises/src/models/exercises.js
shared/specs/factories/exercise.js
shared/src/model/exercise.js
shared/src/model/exercise/question.js
shared/src/model/exercise/solution.js

Fixes for:
* Form not clearing after publishing
* Publish button was enabled even if the exercise was already published
* Clicking new button would sometimes not display a new record
* Answer distractor field would not be cleared when a new record was editing
* JS error when "Exercise contains multiple parts" was checked

Fixes for exercise editing

---

tutor/specs/components/navbar/student-pay-now-btn.spec.jsx
tutor/src/components/navbar/student-pay-now-btn.jsx
tutor/src/models/course/student.js

use more time units in the trial countdown nav element

---

tutor/resources/styles/book-content/note.scss

restyle note titles to handle multiline titles

---

tutor/src/flux/task-plan.coffee
tutor/src/tours/add-homework.json

merge this after https://github.com/openstax/tutor-server/pull/1759

allow homeworks with 0-4 personalized problems

---

tutor/src/components/annotations/annotation.jsx
tutor/src/models/course.js
tutor/src/models/course/role.js
tutor/src/models/course/student.js

depends on https://github.com/openstax/tutor-server/pull/1757

enable highlighting for teachers

---

tutor/resources/styles/book-content/note.scss
tutor/resources/styles/book-content/variables.scss

reduces title line height and adds styles that will fix the multi line title issue when content is re-imported into tutor-server

1581 bug feature styling doesnt accommodate two line titles

---

tutor/src/components/annotations/highlighter.js
tutor/src/components/annotations/inline-controls.jsx
tutor/src/helpers/scroll-to.js
tutor/src/models/courses-map.js

Make selection scrollable when highlighting math
Fixes highlighting controls appearing way to the right of selection

math highlight changes

---

exercises/specs/components/__snapshots__/exercise.spec.js.snap
exercises/specs/components/tags/__snapshots__/books.spec.js.snap
exercises/src/app.jsx
exercises/src/components/tags/book-selection.jsx

Add APUSH to books:
Fix navbar so it works with narrow screens
before:
after:

Exercise fixes

---

package.json
shared/src/helpers/react.coffee
tutor/src/components/my-courses/listings.jsx
tutor/src/screens/new-course/offering-title.jsx
webpack.config.js

`sideEffects: false` worked a little too well

fix styles being tree-shaken out of build

---

tutor/resources/styles/components/annotations/annotation.scss
tutor/resources/styles/variables/colors.scss

change highlight active color

---

tutor/specs/models/jobs/task-plan-publish.spec.js
tutor/src/models/jobs/task-plan-publish.js
tutor/src/models/task-plan/teacher.js
tutor/src/screens/teacher-dashboard/plan-details.jsx
tutor/src/screens/teacher-dashboard/plan.jsx
tutor/src/screens/teacher-dashboard/styles/plan-details.scss
tutor/src/screens/teacher-dashboard/styles/plan.scss

Display as a failure when an assignment publishing fails

---

tutor/specs/models/courses/onboarding/student-course.spec.js
tutor/specs/screens/student-dashboard/__snapshots__/dashboard.spec.jsx.snap
tutor/specs/screens/student-dashboard/dashboard.spec.jsx
tutor/src/models/course/onboarding/student-course.js
tutor/src/models/student-tasks.js
tutor/src/screens/student-dashboard/all-events-by-week.jsx
tutor/src/screens/student-dashboard/empty-panel.jsx
tutor/src/screens/student-dashboard/this-week-panel.jsx
tutor/src/screens/student-dashboard/upcoming-panel.jsx

The student dashboard should poll until that is true.  Goes with https://github.com/openstax/tutor-server/pull/1770

use new "all_tasks_are_ready" flag for polling

---

shared/src/components/exercise-identifier-link.cjsx
tutor/src/components/task-plan/homework/add-exercises.jsx
tutor/src/screens/question-library/exercises-display.jsx

change errata "Report an error" to "Suggest a correction"

---

exercises/specs/components/__snapshots__/exercise.spec.js.snap
exercises/src/components/exercise/tags.jsx

we'll go with I was thinking I was using preact 😁

fix propname to be className

---

tutor/api/courses/1/dashboard.json
tutor/api/courses/2/dashboard.json
tutor/specs/models/courses/onboarding/student-course.spec.js
tutor/specs/models/student-tasks.spec.jsx
tutor/src/models/course/onboarding/student-course.js
tutor/src/models/student-tasks.js

Since the class inherits from Map it doesn't auto-update like
a normal model
Also adds a safety valve where we only wait if the flag is false.

Update "all_tasks_are_ready" flag when loaded

---

tutor/resources/styles/book-content/mixins.scss
tutor/resources/styles/components/task-step/all-steps.scss

set width of sims on narrow screens so they'll overflow if needed

---

shared/src/helpers/react.coffee
tutor/index.js
tutor/lms-pair.js
tutor/specs/screens/lms-pair/__snapshots__/index.spec.js.snap
tutor/specs/screens/lms-pair/index.spec.js
tutor/specs/screens/new-course/__snapshots__/wizard.spec.jsx.snap
tutor/src/api/index.coffee
tutor/src/models/course/pair-to-lms.js
tutor/src/models/courses-map.js
tutor/src/screens/lms-pair/app.js
tutor/src/screens/lms-pair/create-course-ux.js
tutor/src/screens/lms-pair/create-course.jsx
tutor/src/screens/lms-pair/existing-course.jsx
tutor/src/screens/lms-pair/index.js
tutor/src/screens/lms-pair/index.jsx
tutor/src/screens/lms-pair/new-or-existing.jsx
tutor/src/screens/lms-pair/router.js
tutor/src/screens/lms-pair/styles.scss
tutor/src/screens/lms-pair/ux.js
tutor/src/screens/new-course/select-course.jsx
tutor/src/screens/new-course/ux.js
tutor/src/screens/new-course/wizard.jsx
tutor/src/screens/screen-styles.scss
webpack.config.js

User interface for pairing a course to LMS

---

tutor/resources/styles/book-content/mixins.scss

Otherwise it was still being cut-off

Adjust left margin of sims when they're very narrow

---

tutor/src/components/annotations/annotation.jsx

https://trello.com/c/jhHwobOx/1654-bug-few-highlighted-text-omitted-in-the-highlight-summary-page
https://trello.com/c/gLCDrZT1/1592-bug-issues-with-table-highlighting-issue-when-math-and-text-are-highlighted-together

fix range.cloneContents in safari

---

tutor/src/components/annotations/annotation.jsx
tutor/src/components/book-content-mixin.cjsx
tutor/src/helpers/images-complete.js

The most common was on highlighting when we attempt to attach and there's not any reference elements

Fixes from sentry logs

---

shared/specs/model/exercise/question.spec.js
shared/src/model/exercise/question.js

before clicking "open-ended" multiple times would cause "free-response" to appear multiple times

make sure formats are unique

---

jenkins/continuous-integration.jenkins
tutor/src/components/tours/anchor.jsx

fix multiple ids on page issue

---

tutor/specs/components/__snapshots__/app.spec.jsx.snap
tutor/specs/components/exercises/__snapshots__/cards.spec.js.snap
tutor/specs/components/exercises/__snapshots__/preview.spec.js.snap
tutor/specs/components/navbar/__snapshots__/actions_menu.spec.jsx.snap
tutor/specs/components/navbar/__snapshots__/index.spec.jsx.snap
tutor/specs/components/navbar/__snapshots__/preview-add-course-btn.spec.jsx.snap
tutor/specs/components/navbar/__snapshots__/support-menu.spec.jsx.snap
tutor/specs/components/navbar/support-menu.spec.jsx
tutor/specs/components/task-plan/homework/__snapshots__/review-exercises.spec.js.snap
tutor/specs/screens/scores-report/__snapshots__/assignment-header.spec.jsx.snap
tutor/specs/screens/student-dashboard/__snapshots__/events-panel.spec.jsx.snap
tutor/specs/screens/student-dashboard/__snapshots__/homework-row.spec.jsx.snap
tutor/specs/screens/student-dashboard/__snapshots__/reading-row.spec.jsx.snap

IDs were removed in https://github.com/openstax/tutor-js/pull/2389 but
we missed making these updates then

update specs to reflect missing tour IDs

---

exercises/src/components/exercise/question.jsx
shared/specs/model/exercise/question.spec.js
shared/src/model/exercise/question.js

fixes bug where BE would return 422 when it was empty

remove collaborator_solutions when detailed solution is blank

---

tutor/resources/styles/book-content/base.scss
tutor/resources/styles/book-content/note.scss
tutor/resources/styles/mixins/figures.scss

and also style the example title
before:
after:

display example video full width when it's after vertical image

---

tutor/src/components/annotations/summary-popup.jsx

render annotation print content using ArbitraryHtmlAndMath

---

exercises/specs/components/__snapshots__/exercise.spec.js.snap
exercises/specs/components/exercise/__snapshots__/controls.spec.js.snap
exercises/src/components/exercise/controls.jsx
exercises/src/components/exercise/preview.jsx
exercises/src/components/exercise/published-toast.js
shared/specs/components/exercise-preview/__snapshots__/index.spec.js.snap
shared/specs/components/exercise-preview/index.spec.js
shared/specs/factories/exercise.js
shared/specs/model/exercise.spec.js
shared/src/components/exercise-preview/index.jsx
shared/src/components/question/answers-table.jsx
shared/src/components/question/index.jsx
shared/src/model/exercise.js
shared/src/model/exercise/question.js

* remove preview only button
* add nickname to exercise preview
* omit converts model to object
* reword draft toast so it doesn't always say "Created"
* add True/False answers when true-false when q is new and true-false

Various exercise editing fixes

---

tutor/src/components/book-menu/menu.jsx
tutor/src/components/book-menu/toggle.jsx

enter only simulates click if href is present

fix refbook menu toggle keyboard handling

---

exercises/specs/components/__snapshots__/exercise.spec.js.snap
shared/specs/components/exercise-preview/__snapshots__/index.spec.js.snap
shared/specs/components/question/__snapshots__/answer.spec.js.snap
shared/specs/components/question/__snapshots__/index.spec.js.snap
shared/src/components/question/answer.jsx
shared/src/components/question/feedback.jsx
tutor/specs/components/exercises/__snapshots__/cards.spec.js.snap
tutor/specs/components/exercises/__snapshots__/details.spec.jsx.snap
tutor/specs/components/exercises/__snapshots__/preview.spec.js.snap
tutor/specs/components/task-plan/homework/__snapshots__/review-exercises.spec.js.snap

This should cause JAWS and NVDS to be able to jump between the sections

use semantic elements for exercise choices  

---

tutor/src/models/reference-book/ux.js
tutor/src/screens/reference-book/index.jsx
tutor/src/screens/reference-book/ux.js
tutor/src/tours/student-highlighting.json

reposition tour after content loads

---

tutor/specs/models/student-tasks.spec.jsx
tutor/specs/models/time.spec.js
tutor/specs/screens/student-dashboard/__snapshots__/dashboard.spec.jsx.snap
tutor/specs/screens/student-dashboard/dashboard.spec.jsx
tutor/specs/screens/student-dashboard/this-week-panel.spec.js
tutor/specs/screens/student-dashboard/upcoming-panel.spec.js
tutor/src/flux/time.coffee
tutor/src/models/student-tasks.js
tutor/src/models/time.js
tutor/src/screens/student-dashboard/all-events-by-week.jsx
tutor/src/screens/student-dashboard/this-week-panel.jsx
tutor/src/screens/student-dashboard/upcoming-panel.jsx

since a Sunday task wouldn't be on this week, and also wouldn't be after next monday

isoweek starts on monday causing next sundays task to not show up

---

exercises/specs/components/__snapshots__/exercise.spec.js.snap
shared/specs/components/exercise-preview/__snapshots__/index.spec.js.snap
shared/specs/components/question/__snapshots__/answer.spec.js.snap
shared/specs/components/question/__snapshots__/index.spec.js.snap
shared/src/components/question/answer.jsx
tutor/specs/components/exercises/__snapshots__/cards.spec.js.snap
tutor/specs/components/exercises/__snapshots__/details.spec.jsx.snap
tutor/specs/components/exercises/__snapshots__/preview.spec.js.snap
tutor/specs/components/task-plan/homework/__snapshots__/review-exercises.spec.js.snap

test aria-labledby with JAWS

---

exercises/specs/components/__snapshots__/exercise.spec.js.snap
shared/resources/styles/components/exercise-preview/index.scss
shared/specs/components/exercise-badges/__snapshots__/index.spec.js.snap
shared/specs/components/exercise-badges/index.spec.js
shared/src/components/exercise-badges/index.jsx
shared/src/components/exercise-preview/index.jsx
shared/src/helpers/exercise.js
shared/src/model/exercise.js
tutor/specs/components/exercises/__snapshots__/cards.spec.js.snap
tutor/specs/components/exercises/__snapshots__/preview.spec.js.snap
tutor/specs/factories/exercise.js
tutor/src/components/exercises/details.jsx
tutor/src/components/exercises/preview.jsx
tutor/src/models/exercises/exercise.js

Display badges, sim & video content on exercise previews

---

shared/src/components/breadcrumb/index.cjsx
tutor/specs/components/__snapshots__/app.spec.jsx.snap
tutor/specs/components/__snapshots__/sections-chooser.spec.jsx.snap
tutor/specs/components/buttons/__snapshots__/browse-the-book.spec.jsx.snap
tutor/specs/components/navbar/__snapshots__/actions_menu.spec.jsx.snap
tutor/specs/components/navbar/__snapshots__/index.spec.jsx.snap
tutor/specs/components/navbar/__snapshots__/support-menu.spec.jsx.snap
tutor/specs/components/task-plan/__snapshots__/select-topics.spec.jsx.snap
tutor/specs/components/task-plan/homework/__snapshots__/choose-exercises.spec.js.snap
tutor/specs/components/task-teacher-review/__snapshots__/breadcrumbs.spec.jsx.snap
tutor/specs/screens/question-library/__snapshots__/dashboard.spec.jsx.snap
tutor/specs/screens/student-dashboard/__snapshots__/dashboard.spec.jsx.snap
tutor/src/components/buttons/browse-the-book.jsx
tutor/src/components/navbar/actions-menu.jsx
tutor/src/components/navbar/support-menu.jsx
tutor/src/components/navbar/user-menu.jsx

Labels the menu drop down controls, reading breadcrumbs, reference view buttons.

Add aria-label to controls

---

exercises/specs/components/__snapshots__/exercise.spec.js.snap
shared/specs/components/exercise-preview/__snapshots__/index.spec.js.snap
shared/specs/components/question/__snapshots__/answer.spec.js.snap
shared/specs/components/question/__snapshots__/index.spec.js.snap
shared/src/components/question/answer.jsx
tutor/specs/components/exercises/__snapshots__/cards.spec.js.snap
tutor/specs/components/exercises/__snapshots__/details.spec.jsx.snap
tutor/specs/components/exercises/__snapshots__/preview.spec.js.snap
tutor/specs/components/task-plan/homework/__snapshots__/review-exercises.spec.js.snap

JAWS still wasn't reading it correctly

remove labeledBy from answers on exercises

---

configs/test/jest.config.json
shared/specs/helpers/logging.spec.coffee
tutor/specs/components/__snapshots__/annotations.spec.jsx.snap
tutor/specs/components/annotations.spec.jsx
tutor/specs/components/app.spec.jsx
tutor/specs/components/obscured-page.spec.js
tutor/src/components/annotations/summary-popup.jsx
tutor/src/components/obscured-page/overlay-registry.js

This way annotation summary and reading task milestone view will be counted

Record page view when overlay is displayed

---

tutor/specs/components/__snapshots__/app.spec.jsx.snap
tutor/specs/components/__snapshots__/multi-select.spec.jsx.snap
tutor/specs/components/navbar/__snapshots__/center-controls.spec.jsx.snap
tutor/specs/components/navbar/__snapshots__/index.spec.jsx.snap
tutor/src/components/multi-select.jsx
tutor/src/components/navbar/center-controls.jsx
tutor/src/components/navbar/logout.jsx
tutor/src/components/obscured-page/index.js

Add aria attributes and region when overlay is shown

accessibility updates

---

tutor/src/components/task-step/index.cjsx

Goes with 
https://github.com/openstax/tutor-server/pull/1802

only save task step if it's not completed

---

tutor/resources/styles/book-content/note.scss

fixes bug reported https://openstax.slack.com/archives/C0F6Z1JUS/p1542057267257400

use flex layout for notes so they're vertically aligned

---

tutor/resources/styles/book-content/note.scss

Reduce font size of note headings

---

tutor/resources/styles/book-content/baked.scss
tutor/resources/styles/book-content/base.scss
tutor/resources/styles/book-content/note.scss

They're not only for baked content

apply chapter-outline styles to all books

---

tutor/resources/styles/book-content/base.scss
tutor/resources/styles/book-content/learning-objectives.scss

fix objectives styling

---

tutor/specs/helpers/images-complete.spec.js
tutor/specs/helpers/scroll-to.spec.js
tutor/specs/models/reference-book/ux.spec.js
tutor/src/helpers/scroll-to.js
tutor/src/models/reference-book/ux.js
tutor/src/routes.js
tutor/src/screens/teacher-dashboard/add-assignment-sidebar.jsx
tutor/src/screens/teacher-dashboard/add-menu.jsx
webpack.config.js

Before it wouldn't scroll if the page was already loaded and didn't need to be fetched

Scroll page to top after selection from ref-view menu

---

shared/specs/components/exercise-identifier-link.spec.js
shared/specs/helpers/exercise.spec.js
shared/src/components/exercise-identifier-link.js
shared/src/helpers/exercise.js
tutor/src/models/chapter-section.js

We'd previously updated the book UUID, but not the name.  Now that the form supports Bio2e, we can update that as well.  Also fixes a bug I spotted where it would say "undefined.undefined" for the chapter section in. location

Fix link to errata form for biology 2e

---

tutor/resources/styles/mixins/performance-forecast.scss
tutor/specs/flux/task-step-store.spec.js
tutor/specs/screens/assignment-builder/__snapshots__/select-topics.spec.jsx.snap
tutor/specs/screens/assignment-builder/homework/__snapshots__/choose-exercises.spec.js.snap
tutor/src/components/book-page.js
tutor/src/components/dialog.js
tutor/src/components/error-monitoring/server-error-message.jsx
tutor/src/components/task/index.js
tutor/src/flux/task-step.js
tutor/src/flux/task.js
tutor/src/screens/assignment-builder/select-topics.jsx
tutor/src/screens/performance-forecast/student.js
tutor/src/screens/performance-forecast/styles.scss
tutor/src/screens/performance-forecast/teacher-student.js
tutor/src/screens/performance-forecast/teacher.js
tutor/src/screens/student-dashboard/styles/dashboard.scss
tutor/src/screens/student-dashboard/styles/progress-guide.scss

Also a few small UX things I noted like missing padding on sections chooser, overflowing buttons on student dashboard

Fix student task steps loading

---

exercises/specs/components/__snapshots__/exercise.spec.js.snap
shared/resources/styles/components/exercise-preview/index.scss
shared/specs/components/exercise-preview/__snapshots__/index.spec.js.snap
shared/src/components/icon.js
shared/src/components/question/answer.jsx
shared/src/mixins/ScrollListener.js
tutor/resources/styles/components/top-nav-bar/drop-down-menu.scss
tutor/specs/components/exercises/__snapshots__/cards.spec.js.snap
tutor/specs/components/exercises/__snapshots__/details.spec.jsx.snap
tutor/specs/components/exercises/__snapshots__/preview.spec.js.snap
tutor/specs/screens/assignment-builder/homework/__snapshots__/review-exercises.spec.js.snap
tutor/src/screens/assignment-builder/homework/review-exercises.jsx

Fixes 
* scroll fast bug in safari/ff
* icons in exercise review

Fixes for hw builder 

---

tutor/src/routes.js

Looks like this was a copy-n-paste error

Import correct screen for create course routes

---

shared/src/api/action-adapter.js
tutor/resources/styles/book-content/related-content.scss
tutor/src/api/index.js
tutor/src/components/book-menu/menu.jsx
tutor/src/components/book-page.js
tutor/src/components/related-content.js
tutor/src/models/reference-book/page.js
tutor/src/models/reference-book/ux.js
tutor/src/screens/qa-view/ecosystem-selector.jsx
tutor/src/screens/reference-book/section-title.jsx

Fix rendering of baked books

---

tutor/resources/styles/components/modals.scss
tutor/resources/styles/components/modals/warning.scss
tutor/resources/styles/mixins.scss
tutor/src/components/task-step/step-with-reading-content.js
tutor/src/screens/assignment-builder/plan-mixin.js
tutor/src/screens/assignment-builder/reading.js
tutor/src/screens/new-course/course-numbers.jsx
tutor/src/screens/new-course/styles.scss
tutor/src/screens/surveys/index.jsx
tutor/src/screens/surveys/styles.scss

* menu's hidden behind modal mask
* related content showed `,` instead of `.` for chapter section separator
* past assignment info was displayed when a new assignment made
* new course wizard had strange indent for questions

Additional RC bug fixes

---

shared/src/components/buttons/async-button.js
tutor/specs/components/payments/__snapshots__/manage.spec.jsx.snap
tutor/specs/screens/course-settings/__snapshots__/student-access.spec.jsx.snap
tutor/specs/screens/lms-pair/__snapshots__/index.spec.js.snap
tutor/src/models/reference-book/page.js
tutor/src/screens/course-settings/lms-panel.jsx
tutor/src/screens/course-settings/styles/student-access.scss
tutor/src/screens/lms-pair/existing-course.jsx
tutor/src/screens/lms-pair/new-or-existing.jsx
tutor/src/screens/lms-pair/styles.scss
tutor/src/screens/lms-pair/ux.js
tutor/src/screens/question-library/dashboard.jsx

hide all supplementary chapters on teacher's section chooser

Baked content fixes

---

shared/src/helpers/exercise.js

add additional books to errata form

---

tutor/resources/styles/components/tutor-input.scss

tutor-input class is on same element as form-control-wrapper

---

shared/resources/styles/components/exercise/step-card.scss
shared/resources/styles/variables/index.scss
shared/specs/components/__snapshots__/exercise-identifier-link.spec.js.snap
shared/specs/components/exercise-identifier-link.spec.js
shared/src/components/exercise-identifier-link.js
tutor/resources/styles/components/task-step/all-steps.scss

Fix MPQ styles

---

shared/src/components/scroll-to-mixin.js
tutor/resources/styles/book-content/equations.scss
tutor/resources/styles/book-content/index.scss
tutor/resources/styles/book-content/questions.scss
tutor/resources/styles/components/notes/note.scss
tutor/specs/components/__snapshots__/notes.spec.js.snap
tutor/src/components/book-page.js
tutor/src/components/notes.js
tutor/src/components/notes/inline-controls.jsx
tutor/src/components/notes/sidebar-buttons.jsx
tutor/src/components/task-step/step-with-reading-content.js
tutor/src/helpers/scroll-to.js

Uses mutation observer instead of props changing

Fix bugs with highlight icon caching and icon positions

---

tutor/specs/screens/student-dashboard/__snapshots__/dashboard.spec.jsx.snap
tutor/specs/screens/student-dashboard/reading-row.spec.jsx
tutor/src/models/student/task.js
tutor/src/screens/scores-report/homework-cell.jsx
tutor/src/screens/student-dashboard/reading-row.jsx

Fixes issue where tasks would show "not started" until an exercise was completed

use last_worked_at for detecting in progress state

---

tutor/resources/styles/components/media-preview.scss
tutor/src/components/book-content-mixin.js
tutor/src/components/media-preview.js
tutor/src/components/notes.js
tutor/src/components/task/progress/milestones.js
tutor/src/flux/media.js
tutor/src/flux/step-title.js

fix media previews so they include entire os-figure

---

tutor/resources/styles/components/notes/note.scss
tutor/src/components/notes.js
tutor/src/components/notes/sidebar-buttons.jsx

Fix positioning of highlight annotation icon

---

tutor/resources/styles/book-content/base.scss
tutor/resources/styles/mixins/figures.scss
tutor/src/components/book-content-mixin.js

Addresses: 
https://app.zenhub.com/workspaces/openstax-tutor-560aef617a763234615d6a0f/issues/openstax/tutor/171
https://app.zenhub.com/workspaces/openstax-tutor-560aef617a763234615d6a0f/issues/openstax/tutor/168

Temp fix for vertical images

---

tutor/resources/styles/book-content/splash-image.scss
tutor/resources/styles/mixins/figures.scss
tutor/specs/screens/new-course/select-dates.spec.jsx
tutor/src/components/book-content-mixin.js

This will identify splash images in JS and then skip setting image width class on them

Fix splash image positioning 

---

tutor/resources/styles/book-content/base.scss
tutor/resources/styles/book-content/equations.scss
tutor/resources/styles/book-content/examples.scss
tutor/resources/styles/book-content/index.scss
tutor/resources/styles/book-content/learning-objectives.scss
tutor/resources/styles/book-content/os-teacher.scss
tutor/resources/styles/book-content/questions.scss
tutor/resources/styles/book-content/related-content.scss
tutor/resources/styles/book-content/splash-image.scss
tutor/resources/styles/book-content/target.scss
tutor/resources/styles/book-content/typography.scss
tutor/resources/styles/components/notes/summary-page.scss
tutor/src/api/adapter.js

style equations numbering in the highlight summary

---

shared/src/components/icon.js
tutor/resources/styles/global/tutor-bootstrap.scss
tutor/resources/styles/variables/tutor-bootstrap.scss
tutor/src/screens/performance-forecast/info-link.js
tutor/src/screens/performance-forecast/styles/heading.scss
tutor/src/screens/performance-forecast/teacher-student.js

Before the alignment was janky and the popup wasn't styled

Fix various issues with teacher-viewing-student's performance

---

exercises/resources/styles/exercises.scss
exercises/src/app.jsx

Editors don't like it and it mostly fits anyway

don't collapse navbar on lower res screen

---

exercises/resources/styles/attachments.scss
exercises/specs/components/__snapshots__/exercise.spec.js.snap
exercises/src/components/exercise/attachments/chooser.jsx

fix display of "choose different image"

---

tutor/specs/helpers/scroll-to.spec.js
tutor/src/components/task/index.js
tutor/src/helpers/scroll-to.js

Otherwise the top offset may be a bit low if images are slow to load

Scroll to top of next step after images are loaded

---

tutor/resources/styles/book-content/splash-image.scss
tutor/resources/styles/components/task-step/all-steps.scss
tutor/src/components/book-content-mixin.js
tutor/src/components/error-monitoring/server-error-message.jsx
tutor/src/components/tutor-input.js

fixes a few bugs noticed while testing other things

Misc fixes; splash images & date input

---

exercises/specs/components/__snapshots__/exercise.spec.js.snap
shared/resources/styles/_components.scss
shared/resources/styles/components/surety-guard.scss
shared/src/components/buttons/async-button.js
shared/src/components/surety-guard.js
tutor/specs/components/icons/__snapshots__/trouble.spec.js.snap
tutor/specs/screens/scores-report/__snapshots__/overall-header.spec.js.snap

Before it would appear as "primary" orange

Fix cancel button color on delete guard

---

exercises/specs/components/__snapshots__/exercise.spec.js.snap
exercises/src/app.jsx
exercises/src/components/search/clause.jsx
tutor/specs/components/icons/__snapshots__/trouble.spec.js.snap
tutor/specs/screens/scores-report/__snapshots__/overall-header.spec.js.snap

Was missing a callback, also navigate when brand is clicked

fix exercises search drop down

---

package.json
tutor/resources/styles/components/tours/joyride.scss
yarn.lock

update popper version

---

shared/resources/styles/mixins/index.scss
tutor/resources/styles/book-content/base.scss
tutor/resources/styles/book-content/theming-mixins.scss
tutor/resources/styles/mixins.scss

add margin to bottom of table captions

---

tutor/specs/helpers/time.spec.js
tutor/src/helpers/time.js

don't go digging into the private internals of momentjs `._z`

rework isCourseTimezone to use utcOffset

---

tutor/specs/screens/scores-report/overall-cell.spec.jsx
tutor/src/models/course/scores/student.js
tutor/src/screens/scores-report/overall-cell.jsx
tutor/src/screens/scores-report/ux.js

Calculate the averages by student.role and then use the current student
correct sort to render it

Fix course average score sorting

---

tutor/src/flux/step-title.js
tutor/src/models/app.js

Fix reading step titles to use page's document title

---

tutor/specs/factories/index.js
tutor/specs/models/task-plan/teacher.spec.js
tutor/src/models/course/task-plans.js
tutor/src/models/task-plan/teacher.js
tutor/src/screens/teacher-dashboard/month.js
tutor/src/screens/teacher-dashboard/styles/plan.scss
yarn.lock

fix display of events that span multiple days

---

tutor/specs/screens/assignment-builder/homework/choose-exercises.spec.js
tutor/src/models/exercises/exercise.js
tutor/src/screens/assignment-builder/homework/add-exercises.jsx

Sometime an exercise's page may not be found in the current book

fix error when editing cloned assignments

---

tutor/specs/components/task-teacher-review/__snapshots__/breadcrumbs.spec.jsx.snap
tutor/specs/factories/course.js
tutor/specs/screens/__snapshots__/surveys.spec.js.snap
tutor/specs/screens/student-dashboard/__snapshots__/dashboard.spec.jsx.snap
tutor/specs/screens/student-dashboard/dashboard.spec.jsx
tutor/src/screens/student-dashboard/dashboard.jsx
tutor/src/screens/student-dashboard/index.jsx

Before it would only load once, now it'll fetch when visited

Fix student dashboard loading

---

tutor/resources/styles/components/tutor-input.scss
tutor/src/components/tutor-input.js

fix icon & don't pass in format that date doesn't understand
Before:
After:

Fix due date on HW builder

---

tutor/resources/styles/components/notes/note.scss
tutor/src/components/notes/sidebar-buttons.jsx

Adjust note edit icon so it's above full-width text

---

babel.config.js
tutor/specs/screens/assignment-builder/homework/choose-exercises.spec.js
tutor/src/components/notes.js

it appears that it's dropped below %3 in the us, and babel was no longer compiling code for it

fine tune list so it supports Edge browser

---

tutor/resources/styles/components/my-courses.scss
tutor/src/components/my-courses/no-hs-teachers.jsx

style the no HS teacher message so it's not ugly

---

tutor/specs/components/__snapshots__/enroll.spec.jsx.snap
tutor/src/components/enroll/select-periods.js
tutor/src/models/course/enroll.js

There's something strange going on with setting it that removes the sorting helpers on periods

create course before setting it to observable

---

tutor/src/flux/task-plan.js

On cloned assignments the pages may be for a old ecosystem

return blank string if topic isn't found

---

tutor/specs/screens/scores-report/__snapshots__/name-cell.spec.js.snap
tutor/specs/screens/scores-report/name-cell.spec.js
tutor/src/screens/performance-forecast/teacher-student.js
tutor/src/screens/scores-report/dropped-students-caption.js
tutor/src/screens/scores-report/name-cell.jsx

And a small update to performance forecast to remove dropped students from there as well

update legend & don't link to performance forecast for dropped students

---

tutor/specs/models/student/task.spec.js
tutor/specs/screens/student-dashboard/__snapshots__/dashboard.spec.jsx.snap
tutor/specs/screens/student-dashboard/__snapshots__/homework-row.spec.jsx.snap
tutor/specs/screens/student-dashboard/__snapshots__/reading-row.spec.jsx.snap
tutor/src/components/task/details.js
tutor/src/components/time.js
tutor/src/models/student/task.js
tutor/src/screens/student-dashboard/all-events-by-week.jsx
tutor/src/screens/student-dashboard/dashboard.jsx
tutor/src/screens/student-dashboard/event-info-icon.jsx
tutor/src/screens/student-dashboard/event-row.jsx
tutor/src/screens/student-dashboard/events-panel.jsx
tutor/src/screens/student-dashboard/hide-button.js
tutor/src/screens/student-dashboard/homework-row.jsx
tutor/src/screens/student-dashboard/late-icon-ledgend.js
tutor/src/screens/student-dashboard/styles/card.scss
tutor/src/screens/student-dashboard/styles/task.scss
tutor/src/screens/student-dashboard/task-progress-info.js
tutor/src/screens/student-dashboard/this-week-panel.jsx

show late work accepted status on student dashboard

---

tutor/src/models/tour/actions/open-dropdown-menu.js

Otherwise it can calculate the position incorrectly

scroll to top and delay longer for FireFox menu tooltips

---

tutor/specs/screens/student-dashboard/__snapshots__/dashboard.spec.jsx.snap
tutor/src/screens/student-dashboard/late-icon-ledgend.js

Rename red clock's legend to be just "Late"

---

tutor/specs/factories/dashboard.js
tutor/specs/models/student/task.spec.js
tutor/specs/screens/student-dashboard/__snapshots__/dashboard.spec.jsx.snap
tutor/specs/screens/student-dashboard/homework-row.spec.jsx
tutor/specs/screens/student-dashboard/reading-row.spec.jsx
tutor/src/models/student/task.js

match behavior of scores report

show as unaccepted late work when additional work is performed

---

tutor/specs/screens/student-dashboard/__snapshots__/dashboard.spec.jsx.snap
tutor/specs/screens/student-dashboard/__snapshots__/homework-row.spec.jsx.snap
tutor/specs/screens/student-dashboard/__snapshots__/task-progress-info.spec.js.snap
tutor/specs/screens/student-dashboard/homework-row.spec.jsx
tutor/specs/screens/student-dashboard/reading-row.spec.jsx
tutor/src/models/student/task.js
tutor/src/screens/student-dashboard/event-info-icon.jsx
tutor/src/screens/student-dashboard/late-icon-ledgend.js
tutor/src/screens/student-dashboard/task-progress-info.js

always show progress on due date text for HW when it's late

---

shared/src/components/question/answers-table.jsx

Another PR for https://app.zenhub.com/workspaces/openstax-tutor-560aef617a763234615d6a0f/issues/openstax/tutor/227

multiple choice letter and num selections

---

shared/resources/styles/components/spy-mode.scss
shared/src/components/exercise/controls.js
shared/src/components/exercise/mode.js
tutor/specs/models/response_validation.spec.js
tutor/src/api/index.js
tutor/src/flux/task-step.js
tutor/src/models/app.js
tutor/src/models/response_validation.js

depends on 
https://github.com/openstax/tutor-server/pull/1841

add garbage detection for free responses

---

tutor/specs/components/task/__snapshots__/event.spec.js.snap
tutor/specs/components/task/event.spec.js
tutor/src/components/buttons/back-button.js
tutor/src/components/task/event.js
tutor/src/components/task/index.js
tutor/src/helpers/react.js

Renders a plain card with the title & description:

fix clicking on "event" assignments

---

tutor/specs/screens/course-settings/__snapshots__/student-access.spec.jsx.snap
tutor/src/screens/course-settings/student-access.jsx

update url to help article for LMS vs links

---

tutor/resources/styles/components/notes/summary-page.scss
tutor/specs/components/notes/__snapshots__/note-card.spec.js.snap
tutor/specs/components/notes/note-card.spec.js
tutor/specs/factories/index.js
tutor/src/components/notes.js
tutor/src/components/notes/note-card.js
tutor/src/components/notes/summary-page.jsx
tutor/src/components/notes/summary-popup.jsx
tutor/src/models/notes.js
tutor/src/models/notes/note.js

* view highlight in new window
* sort by page position
* HTML appearing in section titles

fix highlighting bugs

---

tutor/specs/models/chapter-section.spec.js
tutor/src/components/notes.js
tutor/src/models/chapter-section.js
tutor/src/models/notes.js

Fix sorting of chapter/sections 

---

tutor/resources/styles/components/notes/summary-page.scss
tutor/specs/components/notes.spec.js
tutor/specs/helpers/index.js
tutor/src/components/notes.js

* Scroll to highlight when the "open in book view" is clicked
* fix `a` tags getting styled as buttons

Fix more highlight bugs

---

bin/test-ci
package-lock.json
package.json
script/ci
script/lint
shared/src/components/html.js
tutor/specs/screens/assignment-builder/homework/__snapshots__/exercises-table.spec.js.snap
tutor/specs/screens/assignment-builder/homework/__snapshots__/review-exercises.spec.js.snap
tutor/specs/screens/assignment-builder/homework/exercises-table.spec.js
tutor/src/screens/assignment-builder/homework/exercises-table.jsx

deleting inside a forEach is a bad idea 😭

Fix adding exercises that contain more than 1 image to homework

---

tutor/resources/styles/book-content/mixins.scss
tutor/resources/styles/components/task-step/all-steps.scss

No issue card was created but this is in reference to https://openstax.slack.com/archives/C0F6Z1JUS/p1551884807250900
Msg from @carlycurran: 
> can you look into this one when you get a chance? It’s a sim in an assessment: The simulation for the pre-class reading problem ID# 11240@5 seem to have problems. About half of the students state that they can’t see the simulation.
The sim is in chapter 25.5 in physics

Max width sim exercises

---

exercises/specs/components/__snapshots__/exercise.spec.js.snap
exercises/src/components/exercise/attachments/attachment.jsx
shared/src/model/exercise.js
shared/src/model/exercise/attachment.js

goes with https://github.com/openstax/exercises/pull/255

support deleting attachments

---

tutor/src/models/app.js

looks like this might have been rebased out by mistake

initialize free response url from bootstrap data

---

tutor/specs/models/scores/student.spec.js
tutor/src/models/scores/student.js

otherwise it'll throw a `[big.js] Invalid number`

default progress/scores to 0 so they can be used in calculations

---

tutor/resources/styles/book-content/note.scss

I removed the styles that were creating the note title from attributes because the note title is already in the content and added styling to the 'in markup' note title
https://app.zenhub.com/workspaces/openstax-tutor-560aef617a763234615d6a0f/issues/openstax/tutor-js/2528
https://app.zenhub.com/workspaces/openstax-tutor-560aef617a763234615d6a0f/issues/openstax/tutor-js/2527

Double note titles AP Bio

---

tutor/src/screens/task/ux.js

restore spy mode to tasks / task steps

---

tutor/specs/screens/task/index.spec.js
tutor/specs/screens/task/progress.spec.js
tutor/specs/screens/task/steps/__snapshots__/end.spec.js.snap
tutor/specs/screens/task/steps/__snapshots__/exercise.spec.js.snap
tutor/specs/screens/task/steps/__snapshots__/html-content.spec.js.snap
tutor/specs/screens/task/steps/__snapshots__/reading.spec.js.snap
tutor/specs/screens/task/ux.spec.js
tutor/src/components/breadcrumb.js
tutor/src/components/notes/inline-controls.jsx
tutor/src/components/notes/sidebar-buttons.jsx
tutor/src/models/student-tasks/step-group.js
tutor/src/screens/assignment-builder/select-topics.jsx
tutor/src/screens/reference-book/section-title.jsx
tutor/src/screens/task/breadcrumbs.js
tutor/src/screens/task/homework.js
tutor/src/screens/task/index.js
tutor/src/screens/task/milestones.js
tutor/src/screens/task/page-content-ux.js
tutor/src/screens/task/reading.js
tutor/src/screens/task/step/card.js
tutor/src/screens/task/step/exercise-question.js
tutor/src/screens/task/step/exercise.js
tutor/src/screens/task/step/index.js
tutor/src/screens/task/ux.js

scroll to each MPQ when it's breadcrumb is clicked

ungroup breadcrumbs so a crumb appears for each step

---

tutor/specs/screens/task/ux.spec.js
tutor/src/components/notes.js
tutor/src/screens/task/step/exercise.js
tutor/src/screens/task/ux.js

before any exercise step was numbered

Do not number reading assignment questions

---

tutor/resources/styles/components/course-page.scss
tutor/resources/styles/components/my-courses.scss
tutor/resources/styles/global.scss
tutor/resources/styles/global/scaffold.scss
tutor/resources/styles/global/typography.scss
tutor/resources/styles/tutor.scss
tutor/resources/styles/variables/colors.scss
tutor/specs/screens/task/steps/exercise.spec.js
tutor/src/components/app.jsx
tutor/src/models/student-tasks/step.js
tutor/src/screens/task/step/exercise.js
tutor/src/screens/task/step/index.js
tutor/src/screens/task/styles.scss
tutor/src/screens/teacher-dashboard/styles.scss

display exercise stimulus before MPQ

---

tutor/specs/screens/task/steps/__snapshots__/html-content.spec.js.snap
tutor/specs/screens/task/steps/__snapshots__/reading.spec.js.snap
tutor/src/models/student-tasks/step.js
tutor/src/screens/task/reading.js
tutor/src/screens/task/step/html-content.js
tutor/src/screens/task/step/reading.js
tutor/src/screens/task/styles.scss

make sure all reading steps have a title

---

package-lock.json
package.json
shared/resources/styles/components/question.scss
shared/src/components/exercise-identifier-link.js
tutor/resources/styles/global/typography.scss
tutor/resources/styles/variables/tutor-bootstrap.scss
tutor/specs/components/__snapshots__/app.spec.jsx.snap
tutor/specs/components/__snapshots__/related-content-link.spec.js.snap
tutor/specs/components/__snapshots__/tutor-layout.spec.js.snap
tutor/specs/screens/task/steps/__snapshots__/end.spec.js.snap
tutor/specs/screens/task/steps/__snapshots__/footer.spec.js.snap
tutor/specs/screens/task/steps/__snapshots__/html-content.spec.js.snap
tutor/specs/screens/task/steps/__snapshots__/reading.spec.js.snap
tutor/src/components/navbar.js
tutor/src/components/related-content-link.js
tutor/src/screens/task/external.js
tutor/src/screens/task/step/card.js
tutor/src/screens/task/step/continue-btn.js
tutor/src/screens/task/step/exercise-free-response.js
tutor/src/screens/task/step/exercise-question.js
tutor/src/screens/task/step/footer.js
tutor/src/screens/task/step/html-content.js
tutor/src/screens/task/styles.scss
tutor/src/screens/task/task-footer-controls.js
tutor/src/screens/task/task-info.js

Adjust UI for nudge to conform closer to specs

---

tutor/specs/screens/task/response-validation-ux.spec.js
tutor/specs/screens/task/steps/exercise-free-response.spec.js
tutor/src/screens/task/response-validation-ux.js
tutor/src/screens/task/step/fr-nudge-help.js

previously it wouldn't display the message but would still record it

do not record nudge message when UI is off

---

bin/lint
bin/lint-cjsx-files.sh
package.json
script/ci
tutor/src/models/tour/actions/open-calendar-sidebar.js

The browser package appears to be broken but that's ok since we no longer support IE anyway

Fix teacher page tips when sidebar isn't open

---

tutor/specs/components/__snapshots__/related-content-link.spec.js.snap
tutor/specs/screens/task/steps/__snapshots__/footer.spec.js.snap
tutor/src/components/related-content-link.js

display "comes from" with ellipsis when it's too long

---

tutor/specs/screens/assignment-builder/homework/choose-exercises.spec.js
tutor/src/screens/assignment-builder/homework/choose-exercises.jsx

Looks like this was broken in the task step rework somehow

Fix HW builder to scroll to section chooser

---

tutor/src/screens/task/task-info.js

display standard "short human" date time format for tasks

---

tutor/specs/components/__snapshots__/sections-chooser.spec.jsx.snap
tutor/specs/components/buttons/browse-the-book.spec.jsx
tutor/specs/components/sections-chooser.spec.jsx
tutor/specs/helpers/analytics.spec.js
tutor/specs/models/window-size.spec.js
tutor/specs/screens/assignment-builder/homework/__snapshots__/choose-exercises.spec.js.snap
tutor/specs/screens/question-library/__snapshots__/dashboard.spec.jsx.snap
tutor/specs/screens/reference-book/index.spec.js
tutor/specs/screens/student-dashboard/__snapshots__/dashboard.spec.jsx.snap
tutor/specs/screens/task/steps/__snapshots__/footer.spec.js.snap
tutor/src/components/book-page.js
tutor/src/components/buttons/browse-the-book.jsx
tutor/src/components/related-content-link.js
tutor/src/components/sections-chooser.jsx
tutor/src/helpers/analytics.js
tutor/src/helpers/conditional-handlers.jsx
tutor/src/models/reference-book/ux.js
tutor/src/models/window-size.js
tutor/src/routes.js
tutor/src/screens/assignment-builder/select-topics.jsx
tutor/src/screens/reference-book/index.jsx
tutor/src/screens/reference-book/ux.js

Previously it used the ecosystem id only but that
fails if there's multiple courses sharing the same ecosystem
In that case the code may pick the wrong course, causing notes
to not appear on the correct books

load reference view by course id

---

tutor/src/screens/task/breadcrumbs.js

allow breadcrumbs to wrap for assignments with many steps

---

tutor/specs/helpers/string.spec.js
tutor/specs/screens/task/response-validation-ux.spec.js
tutor/src/helpers/string.js
tutor/src/models/student-tasks/step.js
tutor/src/screens/task/response-validation-ux.js

Adds a space aware isEmpty check to the string helpers

Require non space free response

---

tutor/resources/styles/variables/tutor-bootstrap.scss
tutor/src/models/app/raven.js

And also turn off sentry debugging

Remove underline styles from links

---

shared/src/model.js
shared/src/model/api.js
tutor/specs/screens/task/steps/index.spec.js
tutor/specs/screens/task/ux.spec.js
tutor/src/models/student-tasks/info-step.js
tutor/src/models/student-tasks/step.js
tutor/src/screens/task/step/index.js
tutor/src/screens/task/ux.js

This will allow BL to add/remove steps if it needs to

Fetch entire task when current step is a placeholder

---

tutor/src/components/book-page.js
tutor/src/components/navbar/actions-menu.jsx
tutor/src/components/notes/summary-toggle.jsx
tutor/src/models/reference-book/ux.js
tutor/src/screens/reference-book/ux.js

The user menu wasn't updated so it was loading by ecosystem id, and the code we had in place to support that also had an error

Fix loading reference view from user menu

---

tutor/src/components/tutor-input.js
tutor/src/screens/course-roster/add-period.jsx
tutor/src/screens/course-roster/rename-period.jsx
tutor/src/screens/course-roster/styles.scss
tutor/src/screens/course-settings/rename-course.jsx
tutor/src/screens/course-settings/styles.scss
tutor/src/screens/course-settings/timezone.jsx
tutor/src/screens/new-course/course-name.jsx

"find" was undefined because it wasn't being imported
And also set course settings/roster to white background

Fix add section modal

---

exercises/specs/components/__snapshots__/exercise.spec.js.snap
exercises/specs/components/tags/__snapshots__/book-selection.spec.js.snap
exercises/specs/components/tags/__snapshots__/books.spec.js.snap
exercises/specs/components/tags/book-selection.spec.js
exercises/src/components/tags/book-selection.jsx

add AP physics to book selection listing

---

tutor/src/components/book-page.js

The "Overlay" stuff isn't needed now that we're displaying the RelatedContent component

Only display page title once

---

tutor/resources/styles/book-content/base.scss
tutor/resources/styles/book-content/theming-mixins.scss

left align math inside tables

---

tutor/specs/factories/student-tasks.js
tutor/specs/screens/task/ux.spec.js
tutor/src/screens/task/ux.js

Fix tasks without steps such as events

---

tutor/specs/components/__snapshots__/tutor-layout.spec.js.snap
tutor/src/components/navbar/menus.js

move "pay now" button to before menus

---

tutor/src/components/book-page.js
tutor/src/models/reference-book/ux.js
tutor/src/screens/qa-view/styles.scss
tutor/src/screens/qa-view/ux.js

This allows QA view to write links to itself.  The previous code would call courseId which the QA view lacks

use UX class to link content

---

tutor/resources/styles/variables/colors.scss
tutor/src/screens/course-roster/styles.scss
tutor/src/screens/course-settings/styles.scss

update link color to be #027EB5 for accessibility

---

tutor/resources/styles/book-content/note.scss
tutor/resources/styles/book-content/os-teacher.scss
tutor/resources/styles/book-content/page.scss

Style Teacher notes

---

tutor/resources/styles/book-content/base.scss
tutor/resources/styles/book-content/index.scss
tutor/resources/styles/book-content/learning-objectives.scss
tutor/resources/styles/book-content/questions.scss
tutor/resources/styles/mixins/figures.scss
tutor/src/components/book-page.js
tutor/src/models/reference-book/page.js

Removes the side-by-side layout of images

image layout and other AP updates

---

tutor/specs/models/response_validation.spec.js
tutor/src/models/response_validation.js

This is _not_ a complete PR, it's me suddenly realizing that Drew and I changed the API a little (added additional returned fields, changed default parameters), so I made what appear to be the minimum changes here to accommodate those changes. This needs a working frontend developer touchup and review (hint hint, @nathanstitt )

 update validation object to new json response

---

tutor/resources/styles/book-content/base.scss

apply math styles to math in table header cells

---

tutor/resources/styles/book-content/base.scss
tutor/resources/styles/book-content/learning-objectives.scss
tutor/resources/styles/book-content/splash-image.scss
tutor/resources/styles/book-content/theming-mixins.scss
tutor/src/components/book-page.js
tutor/src/components/notes.js
tutor/src/components/notes/summary-page.jsx
tutor/src/screens/task/styles.scss

Fixes the case where there's multiple siblings of them

Learning objectives styles

---

tutor/src/models/course/information.js

https://openstax.slack.com/archives/C0F5DE456/p1558381806332800?thread_ts=1558375996.327200&cid=C0F5DE456

rename guides to have the type at end of file

---

tutor/src/models/course.js

No longer limit highlighting to activce courses

allow highlighting on all courses

---

tutor/resources/styles/mixins/figures.scss
tutor/src/components/book-page.js

Otherwise APUSH figures don't honor the scaled-down and other sizes

Don't scale figures that have scaling amount specified

---

tutor/resources/styles/book-content/learning-objectives.scss

display p tags in the objectives styled as the headings

---

tutor/src/components/onboarding/free-trial-ended.jsx

Otherwise you can't see your past courses

only hide back link when there's only 1 course

---

exercises/specs/components/__snapshots__/exercise.spec.js.snap
exercises/specs/components/tags/aplo.spec.js
exercises/src/components/tags/aplo.js

Otherwise it was defaulting to the first available book and wouldn't update after the books were changed

only set book value if the tag has a selection

---

tutor/resources/styles/book-content/learning-objectives.scss
tutor/specs/helpers/reload.spec.js
tutor/specs/helpers/test-router.js
tutor/specs/screens/reference-book/index.spec.js
tutor/specs/screens/task/__snapshots__/breadcrumbs.spec.js.snap
tutor/specs/screens/task/__snapshots__/external.spec.js.snap
tutor/specs/screens/task/__snapshots__/milestones.spec.js.snap
tutor/specs/screens/task/__snapshots__/progress.spec.js.snap
tutor/specs/screens/task/__snapshots__/reading.spec.js.snap
tutor/src/components/book-page.js
tutor/src/helpers/reload.js

otherwise it jumps without taking navbar into account

Scroll to element after navigation or page load

---

tutor/specs/screens/assignment-builder/homework/review-exercises.spec.js
tutor/src/flux/task-plan.js
tutor/src/screens/assignment-builder/event.js
tutor/src/screens/assignment-builder/external.js
tutor/src/screens/assignment-builder/homework.js
tutor/src/screens/assignment-builder/mini-editor/editor.js
tutor/src/screens/assignment-builder/nudge-is-available-message.js
tutor/src/screens/assignment-builder/reading.js
tutor/src/screens/assignment-builder/styles.scss
tutor/src/screens/assignment-builder/wrapper.js
tutor/src/theme.js

Display information message to teachers about FR nudge

---

exercises/specs/components/tags/aplo.spec.js
exercises/src/components/tags/aplo.js
tutor/src/components/book-page.js

Fix APLO error messages

---

exercises/src/components/tags/aplo.js
package.json
yarn.lock

would fail when book was blank

fix switching book on APLO tags

---

exercises/specs/components/__snapshots__/exercise.spec.js.snap
shared/specs/components/exercise-preview/__snapshots__/index.spec.js.snap
shared/specs/model/exercise/tag.spec.js
shared/src/components/exercise-preview/index.jsx
shared/src/model/exercise/tag.js
tutor/specs/components/exercises/__snapshots__/cards.spec.js.snap
tutor/specs/components/exercises/__snapshots__/details.spec.jsx.snap
tutor/specs/components/exercises/__snapshots__/preview.spec.js.snap
tutor/specs/screens/assignment-builder/homework/__snapshots__/review-exercises.spec.js.snap
tutor/specs/screens/task/__snapshots__/breadcrumbs.spec.js.snap
tutor/specs/screens/task/__snapshots__/milestones.spec.js.snap
tutor/specs/screens/task/__snapshots__/reading.spec.js.snap
tutor/specs/screens/task/steps/__snapshots__/exercise-free-response.spec.js.snap
tutor/specs/screens/task/steps/__snapshots__/exercise.spec.js.snap
tutor/specs/screens/task/steps/__snapshots__/nudge-message.spec.js.snap
tutor/specs/screens/task/steps/__snapshots__/question-stem.spec.js.snap

removes the book from aplo tags

sort tags with LO's first

---

tutor/specs/screens/student-dashboard/__snapshots__/dashboard.spec.jsx.snap
tutor/specs/screens/student-dashboard/dashboard.spec.jsx
tutor/src/models/task-plans/student.js
tutor/src/screens/student-dashboard/dashboard.jsx

this will allow us to get an early notice

log when tasks timeout from BL being unready

---

tutor/specs/screens/task/__snapshots__/task-info.spec.js.snap
tutor/specs/screens/task/task-info.spec.js
tutor/src/screens/task/task-info.js

tasks such as practice lack a due date which caused momentjs to default to "now"

do not show due date on tasks that lack it

---

tutor/resources/styles/components/course-page.scss
tutor/specs/courses-test-data.js
tutor/src/components/book-page.js
tutor/src/components/buttons/teacher-become-student.js
tutor/src/components/navbar/best-practices-guide.jsx
tutor/src/components/navbar/support-document-link.jsx
tutor/src/components/navbar/support-menu.jsx
tutor/src/components/teacher-as-student-frame.js
tutor/src/models/course/role.js
tutor/src/models/user/menu.js
tutor/src/screens/student-dashboard/dashboard.jsx

* Sociology student view links are white
* Help menu links to instructor getting started guide
* Help menu links to best practices guide
* Help menu has student video links (which we could 86 in the teacher menu once this is out !!!!)
* Main menu has "Create a Course" link

misc fixes for teacher as student view

---

shared/src/api/action-adapter.js
tutor/src/api/adapter.js
tutor/src/api/index.js
tutor/src/models/task-plans/student.js
tutor/src/models/task-plans/teacher.js

goes along with https://github.com/openstax/tutor-server/pull/1878

Send roleId query param if course has role set

---

tutor/specs/models/course.spec.js
tutor/src/models/course.js

otherwise it'll be null for most users

use primaryRole as backup if current_role_id is unset

---

tutor/src/api/adapter.js
tutor/src/api/index.js
tutor/src/models/course/role.js

code for role id that was missed

---

tutor/specs/components/__snapshots__/tutor-layout.spec.js.snap
tutor/specs/models/user/__snapshots__/menu.spec.js.snap
tutor/src/models/course.js
tutor/src/models/user/menu.js

display research analytics option to AP courses
