- bin/build
Should "just work" since the files are named identically just the method that's used to generate the sha has switched from MD5 to "git rev"
> switch to encoding with git sha for assets

- coach/demo.cjsx
- coach/src/concept-coach/coach.cjsx
- coach/src/concept-coach/launcher/index.cjsx
- shared/src/api/collections.coffee
Previously, if the wrong enrollment code url was loaded, the launcher would display the enrollment code fine-print, but the main coach modal would try to auto enroll you with the wrong code afterwards.  this makes sure the code is valid before passing it onwards for auto enrollment.
included in this PR is a fix that helps the FE know better about whether the api is still pending a response if an error was received.
> Fix coach wrong enrollment

- configs/test/jest.setup.coffee
- configs/test/matchers.coffee
Allows expectations such as:
`expect(wrapper).toHaveRendered('FooComponent')`
And get meaninful error messages such as:
```
Expected wrapper to contain `FooComponent` only once, but it was found 0 times
```
> Add toHaveRendered jasmine/jest expectation

- .codecov.yml
- .travis.yml
- README.md
- configs/test/jest.coach.json
- configs/test/jest.config.json
- configs/test/jest.exercises.json
- configs/test/jest.shared.json
- configs/test/jest.tutor.json
Inspired by [cnx-recipes#136](https://github.com/Connexions/cnx-recipes/pull/136), this generates code coverage for each of `tutor`, `exercises`, `coach`, and `shared` using https://facebook.github.io/jest/docs/configuration.html#collectcoveragefrom-array
You can see the results at https://codecov.io/gh/openstax/tutor-js/commits and then click a commit, and then click the "Files" tab near the top
Thanks @nathanstitt for the how-to! It was surprisingly simple!
refs openstax/napkin-notes#68
> upload jest code coverage to codecov.io

- tutor/src/components/task-plan/plan-mixin.cjsx
- tutor/src/flux/tasking.coffee
https://trello.com/c/ni4A6orX/415-bug-cancel-assignments-edits-doesn-t-discard-edited-dates-immediately-the-changes-aren-t-really-there-but-you-can-see-them
> taskings were not being reset on cancel

- coach/resources/styles/components/concept-coach/launcher.less
- coach/specs/concept-coach/launcher/__snapshots__/index.spec.cjsx.snap
- coach/src/concept-coach/launcher/index.cjsx
Otherwise it'll get squished when page is very narrow and things wrap
Turns this:
Into this:
> set a min height on CC launcher's body

- coach/src/breadcrumbs/index.cjsx
- coach/src/exercise/collection.coffee
- coach/src/task/collection.coffee
- coach/src/user/model.coffee
When I investigated this I found two bugs.  
The first is that when the User adds a second-semester course, the task and exercise stores weren't reset.  This would cause them to have stale data that was referring to the previous course.
The other is that the breadcrumbs component was storing the task in it's `@state`, and not refreshing it when the props changed.  I moved it out of and am fetching it from the store on render.  That way it won't be stale.
> Update CC breadcrumbs when user's course changes

- package.json
- shared/src/helpers/react.coffee
- tutor/resources/styles/components/paging-navigation.less
- tutor/resources/styles/components/task/index.less
While I'm not a fan of browser sniffing, this seems like the only way to get this to work :(
> Attempt to fix safari 9 right arrow on narrow screens

- tutor/specs/components/task-plan/footer.spec.coffee
- tutor/specs/components/task-plan/footer/help-tooltip.spec.cjsx
- tutor/src/components/task-plan/footer/help-tooltip.cjsx
But it's help message should be appropriate for the status of the current task plan
For a new task plan:
When published:
> Task plan builder should always display help icon

- tutor/specs/components/helpers/component-testing.coffee
- tutor/specs/components/task-plan/builder/index.spec.coffee
- tutor/src/components/task-plan/builder/tasking-date-times.cjsx
- tutor/src/components/task-plan/initialize-editing.coffee
This changes it so it'll default to the the max of [ today,  course opens_at ].
Also updates the builder specs so they're all running again
> Fix bug where opens_at would default to today when dropped on first open date of course

- tutor/resources/styles/components/scores/header.less
- tutor/resources/styles/components/scores/table.less
- tutor/specs/components/scores/__snapshots__/assignment-header.spec.cjsx.snap
- tutor/specs/components/scores/__snapshots__/index.spec.cjsx.snap
- tutor/specs/components/scores/assignment-header.spec.cjsx
- tutor/specs/components/scores/index.spec.cjsx
- tutor/src/components/scores/assignment-header.cjsx
More styles for scores to fix some missing and duplicated borders with CC.   I also struck on a neat solution using `only-child` to set header borders and widths for split cells that neatened up the rules a bit.
Before:
After:
Tutor styles remain the same, except the duplicated border under tabs is fixed.
> CC fixes for scores report header borders

- tutor/resources/styles/book-content/note.less
- tutor/resources/styles/book-content/variables.less
Firefox doesn't like the `position: absolute` without any given position and flows it after smaller items
I tested the positioned element on Firefox, Safari, and Chrome (didn't have IE handy)
Before
After:
> Fix reference book labels on firefox..

- .codecov.yml
I noticed on the reports that these folders were being included, seems like they shouldn't be
> ignore spec and test directories from coverage

- shared/specs/helpers/fake-dom-node.coffee
- tutor/specs/components/task-plan/homework/__snapshots__/add-exercises.spec.cjsx.snap
- tutor/specs/components/task-plan/homework/add-exercises.spec.cjsx
- tutor/src/components/exercises/cards.cjsx
- tutor/src/components/task-plan/homework/add-exercises.cjsx
- tutor/src/components/task-plan/homework/choose-exercises.cjsx
- tutor/src/components/task-plan/homework/loading-exercises-mixin.cjsx
- tutor/src/flux/exercise.coffee
Fixes several areas where we were using the course ecosystem id to load exercises.  That works fine normally, but fails when a cloned task is loaded that refers to a past ecosystem.
> Use ecosystemId from task when loading exercises

- tutor/resources/styles/components/task-step/ends.less
Regardless of width, i.e. 33) will be aligned to the right just as 1) will be
Fixes badness like this:
Now looks like:
> Right align exercise numbers so they're spaced correctly

- tutor/resources/styles/components/student-dashboard/task.less
- tutor/src/components/student-dashboard/event-row.cjsx
So it remains visible on narrow screens, otherwise it got pushed
off the column and couldn't be clicked.
Before:
After:
> Move withdrawn icon to left and adjust padding

- tutor/resources/styles/qa.less
> move QA view's edit link up a bit so it sits completly on card

- tutor/resources/styles/components/task/teacher-review-controls.less
Otherwise the paging controls can overlay it
No real visible changes, other than it can be clicked
> use absolute positioning w/z-index for teacher controls so is on top

- tutor/resources/styles/components/course-listings.less
- tutor/specs/helpers/course-data.spec.coffee
- tutor/src/components/course-listing/course.cjsx
- tutor/src/helpers/course-data.coffee
Blocked while @Fredasaurus ponders the proper size the text should be
This is 2rem:
> Treat entire course title the same on course listing

- tutor/resources/styles/components/student-dashboard/task.less
It's too important of information to be hidden, instead it should overflow if needed even if it looks not-so-great.
Before:
After:
> remove ellipsis from due dates

- shared/specs/model/ui-settings.spec.coffee
- shared/src/model/ui-settings.coffee
- tutor/index.coffee
Previously we were setting keys for the calendar sidebar as: `calsidebar.<course id>`.  The code would then create an object with that key so we ended up very flat structure.
This uses lodash's set so that it'll still accept dot notation, but create a nested structure with only one top-level `calsidebar`  
Along with https://github.com/openstax/tutor-server/pull/1362 this should fix the size issue
> Update UiSettings so that it's storage is more compact

- tutor/resources/styles/book-content/base.less
I think on balance this is better than the tiny images we get sometimes.  
example at https://tutor-qa.openstax.org/books/236/section/1.4
> make all images inside figures expand to fill the figure (100% wide)

- tutor/resources/styles/components/course-calendar/month.less
- tutor/resources/styles/components/scores/header.less
- tutor/resources/styles/components/scores/table.less
- tutor/resources/styles/components/sections-chooser.less
- tutor/resources/styles/global/typography.less
- tutor/src/components/scores/pie-progress.cjsx
Since we switched from lato to Helvetica font stack, It was negatively affecting scores icons, course picker panels, and scores names column.
However removing the line-height caused regressions in other areas, which this PR hopefully fixes.
> Remove global line-height style rule

- tutor/resources/styles/book-content/base.less
It interferrs with `.splash` and is also spec'ed above with `:not(.splash)` for that reason
> remove 100% rule for full-width

- shared/specs/model/networking.spec.coffee
- shared/src/api/index.coffee
- shared/src/model/networking.coffee
And use them when making non-routed requests. This way the CRSF token is used if it's set.  Firefox needs is it save ui-settings
> Share options with standalone networking

- tutor/resources/styles/components/course-listings.less
> use slighly less horizontal padding so product names do not wrap

- tutor/src/flux/course-listing.coffee
- tutor/src/flux/current-user.coffee
Fixes loophole where `faculty_verified` instructors from elsewhere could wander into Tutor and create a course even though they aren't part of the beta.
> Only allow teachers who have courses from adding a new one

- tutor/src/components/navbar/user-actions-menu.cjsx
- tutor/src/flux/current-user.coffee
Previously in https://github.com/openstax/tutor-js/pull/1651 it was unavailable when user had no courses, but that posed issues for QA.
> display add course menu option in spy mode when user has no courses

- tutor/src/components/plan-stats/index.cjsx
- tutor/src/flux/task-plan-stats.coffee
Pretty sure I'd gripped for this before, but must have missed 'em.
I checked and this should be it though
> fix a few missing default exports on teacher metrics

- shared/src/components/notifications/email.cjsx
- shared/src/model/networking.coffee
what was happening is that i the xhr was an error then the catch block for errors would fire, but it would receive an exception, not the response.  That would cause the error modal to say "no response received" even though there was a response, but on the `response` key.
The other bug was that when the error handler finished it would return null, breaking following `.then` blocks.
> Fix email validation bar

- tutor/specs/helpers/analytics.spec.js
- tutor/src/components/app.jsx
- tutor/src/helpers/analytics.js
Adds support for multiple GA trackers.  Sends tracking commands to each tracker found under `window.ga`.  
The BE PR that adds multiple trackers is https://github.com/openstax/tutor-server/pull/1410.  This PR can be used with or without that PR.
> multiple GA tracker support

- tutor/specs/models/courses/standard-ux.spec.js
- tutor/src/models/course/standard-ux.js
Appears that salesforce or one of the libraries in-between doesn't like 'em
> Remove apostrophe from on boarding choices for SF

- tutor/resources/styles/components/task-plan/controls.less
https://trello.com/c/CT5CK5NN/733-bug-lost-some-margin-padding-due-to-tours
> Fix footer buttons spacing

- tutor/resources/styles/components/tours.less
- tutor/src/components/tours/custom/how-to-use-preview.jsx
- tutor/src/components/tours/custom/tips-now-or-later.jsx
- tutor/src/tours/teacher-calendar.json
menu item tours dont block menu anymore, and content as updated in https://trello.com/c/8GTjENnb/548-onboarding01c-training-wheel-tour-for-preview-course-dashboard mockup
> update dashboard tours content and position menu tours

- tutor/resources/styles/components/performance-forecast/index.less
- tutor/resources/styles/components/performance-forecast/responsive.less
- tutor/resources/styles/components/performance-forecast/section-mixin.less
- tutor/src/components/performance-forecast/progress-bar.cjsx
https://trello.com/c/MeDZreE7/745-bug-all-text-in-performance-forecast-both-on-the-page-and-in-the-right-rail-on-the-student-dashboard-need-more-padding
From:
> spiffy up performance forecast styles

- tutor/src/models/course/builder-ux.js
https://trello.com/c/dwR1Gsye/732-j29-bug-copy-course-available-even-if-there-isnt-a-past-course
> also need to skip if no courses altogether to clone from

- tutor/resources/styles/components/task-plan/controls.less
- tutor/src/components/task-plan/footer/index.jsx
> vertically align delete assignment button and move to right

- tutor/specs/components/task-plan/footer/preview-button.spec.jsx
- tutor/src/components/task-plan/footer/delete-link.jsx
- tutor/src/components/task-plan/footer/index.jsx
- tutor/src/components/task-plan/footer/preview-button.jsx
https://trello.com/c/EyuSyVu4/771-j29-bug-faux-student-preview-not-available-on-published-assignments
> move delete button to left, display preview regardless of state

- tutor/src/tours/teacher-calendar.json
> do not reposition when displaying preview vid tip

- tutor/specs/components/navbar/support-menu.spec.jsx
- tutor/src/components/navbar/support-menu.jsx
- tutor/src/models/tour/context.js
- tutor/src/models/user.js
Previously it showed if there were any tours, which would also include auto play ones
> Only show page tips menu option if there's manually triggered tours

- tutor/specs/components/task-plan/lms-info.spec.jsx
- tutor/src/components/task-plan/lms-info.jsx
Some preview courses don't have this, but that's ok because the'll have a "NO URL IN PREVIEW" message
> Render assignment link popover even if shareable_url is missing

- tutor/resources/styles/global/tutor-booksplash-background.less
and leave ‘preview’ at normal spacing
> Fix letter spacing on book title

- tutor/src/routes.coffee
Needs to be merged in conjunction with https://github.com/openstax/tutor-server/pull/1474
The BE now handles the first stage /enroll/:code so it can display a splash screen
It then redirects to the FE at this url
> update enrollment URL

- tutor/specs/models/courses/onboarding/student-course.spec.js
- tutor/src/models/course/onboarding/student-course.js
Note this changes default trigger of tooltip to include `hover` - UX would prefer that and react-bootstrap now supports multiple triggers
> Don't display "free trial" message for free courses

- tutor/resources/styles/components/enrollment-student-id.less
Was preventing IE from registering clicks in the modal.
Doesn't seem to be needed in other browsers, not sure why we had it set
> IE z-index fix for student enrollment and id change

- tutor/resources/styles/components/onboarding.less
So background color remains intact
Before:
after:
> Should use padding, not margin

- tutor/specs/models/teacher-task-plans.spec.js
- tutor/src/components/course-calendar/month.cjsx
- tutor/src/flux/task-plan.coffee
- tutor/src/models/teacher-task-plans.js
Two issues:
* We weren't filtering them out when displaying on calendar
* We were relying on the server to reply back with the 'is_deleted' flag,
but it does not, instead they're just not included.
> Remove deleted plans from the teacher task plan map

- tutor/specs/models/courses/builder-ux.spec.js
- tutor/specs/models/courses/create.spec.js
- tutor/src/api/index.coffee
- tutor/src/models/course/builder-ux.js
- tutor/src/models/course/create.js
Cloning a course was broken because we weren't:
* Setting the source course when sourceId was present on router params
* Not using the cloned course endpoint when a clone course was set
> Fix cloning a course

- tutor/resources/styles/components/tours/value-prop.less
Not sure why it was added but was making it look funky
Before:
After:
> Fix personalized icon on student value prop modal

- tutor/resources/styles/components/performance-forecast/section-mixin.less
- tutor/src/components/performance-forecast/practice.cjsx
https://trello.com/c/yVTh05oa/914-bug-if-pw-times-out-on-a-given-section-it-disables-that-section
im very conflicted about this change as i foresee people trying to click the same practice button over and over again.
> Update dont disable for missing pw

- tutor/resources/styles/components/enrollment-student-id.less
- tutor/resources/styles/components/payments.less
The modal was positioned too low, and didn't allow scrolling
> fix enrollment/student-id/refunds modal on small screens

- tutor/src/components/task-plan/footer/index.jsx
- tutor/src/helpers/plan.coffee
Was causing JS errors and causing the task plan emit to stop mid-delivery, which in turn would cause plans to stay as "Publishing.." on the calendar forever
> Unsubscribe from updates when unmounted

- tutor/src/components/navbar/index.jsx
Looks like this was droppped inadvertently when it was renamed from "Get Access"
> Re-add "Pay Now" button

- tutor/resources/styles/components/enrollment-student-id.less
- tutor/resources/styles/mixins.less
Not the best ux but is better than it being visible-but-unclickable. Before it's z-index was placing it over the navbar
> Adjust modal styles so that navbar is usuable

- tutor/specs/components/onboarding/__snapshots__/make-payment.spec.jsx.snap
- tutor/specs/components/onboarding/make-payment.spec.jsx
- tutor/src/components/onboarding/make-payment.jsx
Before it was non-functional because the `ux.payLater` method was renamed to `onPayLater` at some point ☹️
> Fix cancel button on payments modal that's selected from pay-now-or-later

- tutor/resources/styles/components/performance-forecast/index.less
- tutor/resources/styles/components/performance-forecast/section-mixin.less
- tutor/resources/styles/components/student-dashboard/progress-guide.less
- tutor/src/components/performance-forecast/progress-bar.cjsx
- tutor/src/components/performance-forecast/section.cjsx
And also adjust margin / padding to make it cleaner.
> Add labels to progress labels for screen readers

- tutor/specs/models/courses/onboarding/student-course.spec.js
- tutor/src/components/student-dashboard/this-week-panel.jsx
- tutor/src/components/student-dashboard/upcoming-panel.jsx
- tutor/src/models/course/onboarding/student-course.js
When a past-due student loads the dashboard we can't load the tasks since the BE will raise 403.
That means the dashboard may be task-less after a student pays.
> Tasks may be undefined if they're not loaded yet

- shared/src/helpers/mathjax.coffee
Goes along with BE https://github.com/openstax/tutor-server/pull/1534
> update a11y extension so it loads same version as mathjax

- tutor/specs/components/__snapshots__/enroll.spec.jsx.snap
- tutor/specs/components/enroll.spec.jsx
- tutor/specs/models/courses/enroll.spec.js
- tutor/src/components/enroll.jsx
- tutor/src/components/enroll/select-periods.js
- tutor/src/components/enroll/student-id.jsx
- tutor/src/models/course/enroll.js
Previously the period selection would disappear as soon as
a period was clicked and then it would either do a LMS enroll
or a course period one depending on the time of the request
> Fix bug with period selection on LMS courses

- tutor/src/models/jobs/task-plan-publish.js
- tutor/src/models/teacher-task-plans.js
When they were cloned we removed them from the map and then re-inserted with the proper id.
Doing so caused the publish job listener to become unobserved and trigger a removal itself.
> Fix infinite recursion on task plan clone

- package-lock.json
- package.json
Fixes build error: `ERROR in tutor.min.js from UglifyJs`
> update mobx-decorated-models to version without babel-runtime

- tutor/specs/components/__snapshots__/course-page.spec.jsx.snap
- tutor/specs/components/course-page.spec.jsx
- tutor/src/components/course-calendar/index.jsx
- tutor/src/components/course-page.jsx
> Move teachers notifications bar back where it belongs 

- tutor/src/components/scores/lms-push.jsx
Per mockup: http://4tk3oi.axshare.com/tutor_scores_paired_new_tabs_toolbar_dashboard_sty_2.html#choose_settings_tab=lms&CSUM=1
Nathan, I believe this may need more changes than I'm capable of doing: 
1.  Default scores send state is now "Send course averages to LMS" (instead of "Last sent to LMS: Never") The "Last sent to LMS: Date, Time" message appears only after you click the button the first time, per the mockup.
2. Default export scores state is now "Export all scores as spreadsheet" (instead of "Last exported: Never"). Once you click the button the first time, that changes to "Last exported: Date, Time" per the mockup)
> Updated copy (needs more changes)

- tutor/specs/components/navbar/center-controls.spec.jsx
- tutor/src/components/navbar/center-controls.jsx
Looks like this was broken by the router upgrade.  It now returns only the current route, not the entire tree
> Fix milestones

- tutor/resources/styles/components/reference-book/page.less
- tutor/resources/styles/components/task/index.less
- tutor/src/components/task-plan/homework/exercises-table.cjsx
* Sets background color on task-steps and reference book to light grey
* Fixes math not displaying in review table when building hw
> A few style tweaks

- tutor/specs/models/course.spec.js
- tutor/src/models/course.js
- tutor/src/models/course/offerings/offering.js
- tutor/src/models/course/role.js
Before it would show on any course that was fall 2017. 
It now is displayed if the user has created or joined a course in the last 7 days,  and they have courses they're teaching for fall 2017
> Fine tune logic for the "course access has moved" tip

- tutor/src/components/student-dashboard/empty-panel.jsx
Otherwise it can spin forever since it doesn't pickup the change
> Make student tasks empty panel an observer so it'll re-render

- tutor/src/components/task-plan/builder/tasking-date-times.cjsx
- tutor/src/components/task-plan/mini-editor/editor.cjsx
On the full builder the main component will re-render and
ripple down to the times.  However the mini-editor is mobx
powered and doesn't bind to the store
> Fix changing dates on teacher task plans mini-editor

- tutor/src/components/accessibility-statement.jsx
- tutor/src/components/browser-warning-modal/index.jsx
- tutor/src/components/navbar/student-pay-now-btn.jsx
https://trello.com/c/gfKbpURS/521-change-request-user-taken-to-different-page-when-unsupported-browser-is-detected-in-payments
> browser warning modal for payments

- tutor/src/tours/teacher-calendar.json
https://trello.com/c/HfU9jb4V/1091-change-request-add-training-wheel-to-the-end-of-course-dashboard-page-tips-tour-pointing-to-course-settings-page-call-out-studen
> add student enrollment tour step as part of calendar tour

- tutor/src/components/annotations/annotation.jsx
- tutor/src/components/annotations/sidebar-buttons.jsx
- tutor/src/components/annotations/summary-page.jsx
- tutor/src/helpers/dom.coffee
- tutor/src/models/annotations/annotation.js
- tutor/src/models/annotations/hypothesis.js
Fixes bugs where:
* We were only loading public annotations, not the ones from the users's group
*. Annotations were being saved with an incorrect reference element, causing them to appear randomly placed after save
> Highlight fixes for loading and positioning

- tutor/specs/models/course.spec.js
- tutor/src/components/course-periods-nav.jsx
- tutor/src/components/plan-stats/index.jsx
- tutor/src/components/task-teacher-review/breadcrumbs.jsx
- tutor/src/components/task-teacher-review/index.jsx
- tutor/src/components/task-teacher-review/no-stats.jsx
- tutor/src/models/course.js
The root bug was that the tabs were sorted and filtered out archived (as they should) but the stats were not. 
There also wasn't a loading or "no students" message on the stats page so it looked broken when viewing empty periods.
> Fix review metrics displaying wrong stats for periods

- tutor/resources/styles/components/top-nav-bar.scss
For Firefox and probably IE
Before:
After:
> flexbox bug; use height vs min-height

- tutor/src/helpers/lazy-getter.js
Otherwise if "clone" or anything that looks at the properties is called on them their initialized
The api does that when it sets up the routes
> make lazyGetters non-enumerable

- tutor/src/components/course-settings/timezone.jsx
- tutor/src/helpers/time.coffee
Fixes a bug where the course time zone picker would save a blank timezone if
it was saved without a selection being made
> Initialize timezone from course; deal with blank ones

- tutor/resources/styles/components/task-teacher-review/breadcrumbs.scss
> set a background color on the review breadcrumbs

- tutor/resources/styles/components/task-teacher-review/question.scss
- tutor/src/components/task-teacher-review/exercise.jsx
https://trello.com/c/lKALhgPc/1238-change-request-dont-show-student-names-next-to-free-response-answers-in-hw-review-unless-accordion-is-open
> teacher review student answer names

- shared/resources/styles/components/question.scss
- shared/resources/styles/mixins/questions.scss
- tutor/resources/styles/components/task-step/all-steps.scss
Otherwise long text wraps with the new button based bubbles.  It was fine with short (one-line) text which is apparently all I tested with ☹️ 
Before:
after
> use flexbox to layout bubble and answer text

- tutor/src/components/task-plan/builder/tasking-date-times.cjsx
- tutor/src/models/course.js
When the time is changed in the task plan builder, a "Set as default" link appears. However clicking it causes a `Cannot set property 'time_zone' of undefined` error and the time default is not saved.
> Fix `Cannot set property 'time_zone' of undefined`

- tutor/resources/styles/components/annotations/annotation.scss
- tutor/src/components/annotations/inline-controls.jsx
Somehow the onClick handler's were transposed ☹️
> Don't call annotate when highlight button is clicked

- tutor/src/helpers/scroll-to.js
Fixes a bug with annotations where the page will scroll to top
if an annotation is created and immediately deleted while it's scrolling
> stop scrolling if element has been deleted

- tutor/resources/styles/components/top-nav-bar/drop-down-menu.scss
- tutor/specs/components/navbar/__snapshots__/actions_menu.spec.jsx.snap
- tutor/specs/components/navbar/actions_menu.spec.jsx
- tutor/src/components/navbar/actions-menu.jsx
**note** seems like we should be able to use the `match` prop being passed into a `Route`'s children, but that doesn't seem to be updating with each route change
> action active menu

- tutor/specs/components/__snapshots__/app.spec.jsx.snap
- tutor/specs/components/course-settings/__snapshots__/student-access.spec.jsx.snap
- tutor/specs/components/navbar/__snapshots__/index.spec.jsx.snap
- tutor/specs/components/navbar/__snapshots__/support-menu.spec.jsx.snap
- tutor/specs/models/user/menu.spec.js
- tutor/src/components/course-settings/lms-panel.jsx
- tutor/src/components/course-settings/student-access.jsx
- tutor/src/components/my-courses/empty.jsx
- tutor/src/components/navbar/toasts/lms.jsx
- tutor/src/components/payments/manage.jsx
- tutor/src/models/user/menu.js
Removes the teacher/student/cc options from the no-courses-found page so it's now:
> update links to point to new support site

- bin/serve
- configs/webpack/base.coffee
- package.json
Bumps memory up to 2gb from node's default of 1
Removes styles from happy-pack
adds a command to clear cache for when hard-source is messed up
> Fix hard-source/happy-pack build

- bin/build
- configs/webpack/base.coffee
- package.json
- yarn.lock
Fixes bug where node would run out of memory and crash whenever a build error occured.
Seemed to happen regardless of max_old_space_size setting and even if happypack was removed
> remove hard-source

- shared/src/api/index.coffee
- tutor/specs/models/student-tasks.spec.jsx
- tutor/src/models/course/enroll.js
- tutor/src/models/student-tasks.js
Initially the enrollment code would poll for tasks, but then later we also added polling anytime the student dashboard is displayed.  
Which caused double loads and occasionally an error when the action-adapter noticed the same api request and returned undefined instead of a Promise
> Fix double loading tasks when enrolling

- tutor/resources/styles/global/popover.scss
- tutor/resources/styles/global/tooltip.scss
- tutor/resources/styles/variables/tutor-bootstrap.scss
This way the popover colors variables will be applied before bootstrap is read
Before:
After:
> Fix popover styles

- tutor/resources/styles/components/new-course.scss
> Fix book covers on new course

- tutor/src/helpers/task-plan.js
> Fix "orig. due date" popover on plan clone

- tutor/resources/styles/components/task-plan/task-plan-stats.scss
The after label wasn't being displayed and the margin-bottom pushes the following
label down since it's floated
before:
after:
> Fix progress bars on stats

- configs/webpack/base.coffee
- package.json
- yarn.lock
It was running out of memory on production.  Will try to re-introduce as part of an upgrade to webpack in the future
I'm hopeful that web pack 4 is supposed to be faster / use less resources
> remove happy pack

- tutor/resources/styles/components/top-nav-bar.scss
- tutor/specs/components/__snapshots__/app.spec.jsx.snap
- tutor/specs/components/navbar/__snapshots__/actions_menu.spec.jsx.snap
- tutor/specs/components/navbar/__snapshots__/index.spec.jsx.snap
- tutor/specs/components/navbar/__snapshots__/support-menu.spec.jsx.snap
- tutor/specs/components/navbar/account_link.spec.js
- tutor/specs/components/navbar/support-menu.spec.jsx
- tutor/src/components/navbar/account-link.jsx
- tutor/src/components/navbar/actions-menu.jsx
- tutor/src/components/navbar/logout.jsx
- tutor/src/components/navbar/student-previews-link.jsx
- tutor/src/components/navbar/support-document-link.jsx
- tutor/src/components/navbar/support-menu.jsx
- tutor/src/components/navbar/user-menu.jsx
- tutor/src/components/tours/anchor.jsx
One user visible change is that we can no longer wrap the entire menu in a tour region.  Doing so makes the menu stop passing the keyboard handlers down to the MenuItems.
This moves the tour regional that highlighted the help menu from the menu itself to the menu controls at the top.  Basically from this:
to this:
> Fix keyboard navigation on menus

- tutor/resources/styles/components/pinned-header-footer-card.scss
- tutor/resources/styles/components/task-teacher-review/breadcrumbs.scss
- tutor/resources/styles/tutor.scss
In #2036, it only was set on the review header but those css classes are also used
on student homeworks
before:
after:
> set a background color on all pinned headers and footers

- tutor/src/components/task-step/step-with-reading-content.cjsx
This case should be relatively rare and may only happen locally with old content/task steps.
> intros in reading content were not rendering when related_content does not exist

- package.json
- tutor/resources/styles/components/tabs.scss
- tutor/resources/styles/components/top-nav-bar.scss
- tutor/resources/styles/global/externals.scss
- tutor/resources/styles/global/scaffold.scss
- tutor/resources/styles/variables.scss
- tutor/src/screens/screen-styles.scss
- tutor/src/screens/student-dashboard/progress-guide.cjsx
- tutor/src/screens/student-dashboard/styles/dashboard.scss
- tutor/src/screens/student-dashboard/styles/progress-guide.scss
- yarn.lock
@Fredasaurus as we discussed this sets the BG color for student dashboard to light grey.  I added the "panel" style to performance forecast so it is white with shadow.  Should Browse the book also receive that?
> Import headers from pattern-library, style student dashboard using them

- tutor/resources/styles/book-content/base.scss
before:
after:  Note that the Isaac Newton image looks too tall but that's it's correct height.
> maintain aspect ratio of scaled images in reference book

- tutor/resources/styles/variables/tutor-bootstrap.scss
- tutor/specs/flux/step-title.spec.js
- tutor/src/flux/step-title.coffee
Previously if a task step had math in it's `stem_html` that would cause us to parse the title incorrectly and we'd display math in the task step title and it's "Continue to .." text link.
> Fix html in step titles

- tutor/specs/components/enroll.spec.jsx
- tutor/src/models/course/enroll.js
render already enrolled redirect before errors; otherwise we'd render the generic error message because the error check came before the redirect
> Redirect already enrolled students to their course when using enroll link

- package.json
- tutor/specs/components/error-monitoring/__snapshots__/async-load-error.spec.jsx.snap
- tutor/specs/components/error-monitoring/async-load-error.spec.jsx
- tutor/specs/helpers/reload.spec.js
- tutor/src/components/error-monitoring/async-load-error.jsx
- tutor/src/components/error-monitoring/handlers.cjsx
- tutor/src/components/error-monitoring/index.cjsx
- tutor/src/helpers/async-component.js
- tutor/src/helpers/reload.js
- yarn.lock
When I force a load failure by typing gibberish in a scores import it reloads once then displays:
> Reload browser window when an error occurs

- tutor/src/screens/scores-report/styles/header.scss
- tutor/src/screens/scores-report/styles/overall-cell.scss
Before Firefox would display as:
Now it matches other browsers as:
> tweak styles so they're identical in Firefox

- tutor/src/api/index.coffee
https://trello.com/c/qfjqBsAa/1285-change-request-change-mark-exercises-as-completed-api-so-the-selected-answer-is-transmitted-in-the-same-api-call-that-an-exercis
uses openstax/tutor-server#1664
> step completion should submit answer_id and free_response

- tutor/resources/styles/components/modals.scss
- tutor/src/screens/scores-report/assignment-header.jsx
- tutor/src/screens/scores-report/external-cell.jsx
- tutor/src/screens/scores-report/ux.js
* Use pattern library buttons styles on weights modal
* Fix overly wide table for students
* Don't render late icon for student's external assignments
> UX fixes for student scores

- shared/src/helpers/task.js
- shared/src/index.js
These were exported as default but we were re-exporting a named export that didn't exist
I went through `shared/index` and verified that these are the only two JS exports that we're re-exporting.
> Fix re-exporting default exports from JS

- tutor/src/components/course-roster/add-period.jsx
Fixes bug where the period name would be re-used when adding more than one section/period in a row
> Don't re-use default value, instead always start with ''

- tutor/specs/components/helpers/component-testing.coffee
- tutor/specs/models/courses/onboarding/student-course.spec.js
- tutor/specs/screens/student-dashboard/dashboard.spec.jsx
- tutor/src/models/course/onboarding/student-course.js
- tutor/src/models/student-tasks.js
- tutor/src/screens/student-dashboard/empty-panel.jsx
- tutor/src/screens/student-dashboard/index.jsx
Before it wouldn't immediately re-poll after the initial fetch until 4 hours had past 😿 
And the task spinner wasn't displaying while it loaded
> Fix fetching tasks on enrollment

- tutor/resources/styles/components/annotations/summary-page.scss
- tutor/specs/components/__snapshots__/annotations.spec.jsx.snap
- tutor/specs/components/annotations.spec.jsx
- tutor/src/components/annotations/annotation-card.jsx
- tutor/src/components/annotations/annotation.jsx
When an annotation from the summary is clicked it wasn't scrolled to because it was linked via the hash which was cleared for some reason.
Before:
After:
> Fix weird top margin and scroll to linked annotation

- tutor/specs/components/enroll.spec.jsx
- tutor/specs/factories/index.js
- tutor/specs/models/courses/enroll.spec.js
- tutor/specs/models/courses/onboarding/student-course.spec.js
- tutor/src/models/course/enroll.js
- tutor/src/models/course/onboarding/student-course.js
- tutor/src/models/courses-map.js
- tutor/src/models/student-tasks.js
- tutor/src/models/user.js
This fixes bug where it would fast poll for 30 minutes when a course was new and didn't have any tasks
> Only fast poll if the course has tasks available

- tutor/specs/models/annotations.spec.js
- tutor/src/models/annotations.js
Fixes bug on tutor-content where it was attempting to load annotation data even though the feature flag was off.
> Don't load annotations when feature flag is off

- tutor/specs/models/student-tasks.spec.jsx
- tutor/src/models/student-tasks.js
We were using the `w` format which made didn't add a leading 0, so weeks less than 10 didn't sort properly.
Testing also revealed that we need to use the GGGG format otherwise dates that belong to a week that overlaps years such as `2017-01-03`, would become `201601` when formatted, rather than the proper `201701`
> Fix student dashboard past events to list all events

- tutor/specs/models/exercises.spec.js
- tutor/specs/screens/question-library/dashboard.spec.jsx
- tutor/src/models/exercises.js
- tutor/src/screens/question-library/sections-chooser.jsx
Otherwise the returned exercises lack the "is_excluded" flag
> load exercises from course endpoint for QL

- tutor/specs/helpers/images-complete.spec.js
- tutor/src/components/annotations/annotation.jsx
- tutor/src/helpers/images-complete.js
We wait until all the images are loaded before displaying annotations and hiding the message, but it would never resolve if the page had no images
> Fix "Waiting for page to load.." message for pages with no images

- configs/webpack/base.coffee
- package.json
HardSource keeps causing errors for me, so this flips the logic so it's only used if the CACHE env is set
> only cache webpack when cache ENV is set

- tutor/src/screens/scores-report/styles/table.scss
> set color for completed-but-not due pie progress

- tutor/specs/components/__snapshots__/paging-navigation.spec.jsx.snap
- tutor/specs/components/annotations.spec.jsx
- tutor/specs/components/paging-navigation.spec.jsx
- tutor/src/components/annotations/window-shade.jsx
- tutor/src/components/paging-navigation.jsx
Since only one scope can be active at once, the scopes would cancel each other out.
Also discovered a bug where the mount/unmount could occur in the same event loop causing the page to flip rapidly through several pages
> don't use scopes for keybinding, and fix paging loop

- bin/build
Needed so Jenkins builds the archive properly.
> Removed the `archive` arg requirement for generating rev-manifest.json

- configs/test/matchers.coffee
- package.json
- shared/src/model.js
- shared/src/model/types.js
- tutor/api/courses/1/performance.json
- tutor/specs/models/courses/scores.spec.js
- tutor/specs/models/courses/scores/task-result.spec.js
- tutor/src/models/course/scores.js
- tutor/src/models/course/scores/task-result.js
- tutor/src/screens/scores-report/assignment-header.jsx
- yarn.lock
Bugs found/fixed:
* Some of the components weren't observers so they didn't re-render after update
* Reading assignments was reading all steps instead of only exercises
* Lack of precision in calculations when togging from accepted/rejected
> Fix scores recalculation when accepting late work

- tutor/specs/models/user/__snapshots__/menu.spec.js.snap
- tutor/specs/models/user/menu.spec.js
- tutor/src/models/user/menu.js
> hide create/clone course menu option from non-college teachers

- tutor/specs/components/__snapshots__/sections-chooser.spec.jsx.snap
- tutor/specs/components/buttons/__snapshots__/browse-the-book.spec.jsx.snap
- tutor/specs/components/buttons/browse-the-book.spec.jsx
- tutor/specs/components/task-plan/__snapshots__/select-topics.spec.jsx.snap
- tutor/specs/components/task-plan/homework/__snapshots__/choose-exercises.spec.js.snap
- tutor/specs/helpers/analytics.spec.js
- tutor/specs/screens/question-library/__snapshots__/dashboard.spec.jsx.snap
- tutor/specs/screens/reference-book.spec.js
- tutor/src/components/book-content-mixin.cjsx
- tutor/src/components/buttons/browse-the-book.jsx
- tutor/src/helpers/analytics.js
- tutor/src/helpers/conditional-handlers.jsx
- tutor/src/models/reference-book/ux.js
- tutor/src/routes.js
- tutor/src/screens/reference-book/index.jsx
- tutor/src/screens/reference-book/reference-book.jsx
- tutor/src/screens/reference-book/styles.scss
- tutor/src/screens/reference-book/ux.js
before they were `/book/<ecosystemId>/<chapterSection>` but that didn't match what the BE used.
And also display a simple "not found" message instead of displaying spinner forever
> Update book urls to have "section" in between id and chapter/section

- tutor/resources/styles/book-content/index.scss
- tutor/resources/styles/book-content/page.scss
This way they're available everywhere such as readings
Broken images are because I have very old content, but the figures are working now 😁
> include counter-resets in book content instead of book-page

- tutor/specs/screens/qa-view.spec.jsx
- tutor/src/models/exercises.js
- tutor/src/screens/qa-view/ux.js
I think this was caused by a rebase that erased the change to rename the method to `ensurePagesLoaded` when we added the by exercise id methods
> Fix QA view exercise loading

- tutor/src/screens/surveys/styles.scss
Otherwise the button styles are reset to the bootstrap defaults
> prevent global button style reset by scoping under surveys

- tutor/specs/screens/teacher-dashboard/month.spec.js
- tutor/src/components/paging-navigation.jsx
- tutor/src/components/task-step/all-steps.cjsx
- tutor/src/components/task-step/index.cjsx
- tutor/src/components/task-step/step-with-reading-content.cjsx
The continue button for reading content didn't work.  It would scroll to the top of the page but wouldn't display new content.
> Fix the continue button on reading steps

- tutor/specs/models/courses/create.spec.js
- tutor/specs/screens/new-course/course-numbers.spec.jsx
- tutor/specs/screens/new-course/ux.spec.js
- tutor/src/models/course/create.js
If we're able to clone the course, we shouldn't set the name from it
> only name and other info from source course if it's clonable

- shared/src/api/collections.coffee
Fixes bug where data was a string encoded empty object i.e. "{}"
It failed the isEmpty test since it was tested before converting to an object
That in turn threw of the isPending check here since the fingerprint was different
> convert data to JSON then test if empty

- tutor/resources/styles/components/tutor-dialog.scss
also changed overflow from `scroll` to `auto` so it doesn't show unnecessary scroll bars
> handle long content in error modal

- tutor/resources/styles/components/annotations/summary-page.scss
- tutor/specs/components/__snapshots__/annotations.spec.jsx.snap
- tutor/specs/components/annotations.spec.jsx
- tutor/src/components/annotations/annotation-card.jsx
- tutor/src/components/annotations/sections-filter.jsx
- tutor/src/components/annotations/summary-page.jsx
- tutor/src/components/annotations/summary-popup.jsx
- tutor/src/components/annotations/window-shade.jsx
There is a little bit of a hack to ensure that when you tab after the drawer opens, it selects the drawer content first. otherwise you have to tab through all the content behind before getting to the stuff you can see. If anyone knows a cleaner way to accomplish that please let me know.
also the ref mocking in the test is super brittle, would love a better solution to that.
> remove annotation drawer from dom when closed, and allow tabbing to elements inside

- shared/resources/styles/components/question.scss
> fix question answer alignment when text is long

- tutor/resources/styles/components/exercises.scss
- tutor/resources/styles/mixins/exercise-cards-column-layout.scss
@nathanstitt these styles were changing the document height when the navbar pinned, making it possible to be in just the right spot where the nav flashes in and out of it's pinned state.
it didn't seem like these styles were super necessary but if you let me know what they were trying to do i can try to update them to not alter the document height
> remove exercise style overrides when header changes

- package.json
- yarn.lock
Not sure why this suddenly decided to occur, but my web pack was using 100% cpu.
Googling suggested fsevents was to blame and updating it seems to have fixed the issue.
> Fix high webpack cpu usage by requiring recent fsevents

- tutor/specs/components/__snapshots__/annotations.spec.jsx.snap
- tutor/specs/models/course.spec.js
- tutor/src/components/annotations/annotation.jsx
- tutor/src/helpers/dom.js
- tutor/src/models/course.js
the annotation logic is just ripping out all the mathjax stuff so that it is just the `<math>` element that the document starts with, if there is a mathjaxy way to revert the content on the cloned dom and no affect the actual page that would be ideal, but i couldn't find anything like that.
> format math in highlight annotations

- exercises/specs/components/__snapshots__/exercise.spec.js.snap
- exercises/specs/models/exercises.spec.js
- exercises/src/api/index.js
- exercises/src/components/exercise/attachments.jsx
- exercises/src/components/exercise/attachments/attachment.jsx
- exercises/src/models/exercises/exercise.js
Since attachments are shared between versions, removing an attachment might break links on published versions
> remove ability to delete attachments from exercise

- tutor/resources/styles/book-content/note.scss
- tutor/resources/styles/book-content/questions.scss
.note as well as [data-type="note"] were already supported
this matches `.exercise` as well as `[data-type="exercise"] `. previously both selectors were required
> match both data-type and class selectors

- tutor/specs/components/__snapshots__/annotations.spec.jsx.snap
- tutor/src/components/annotations/window-shade.jsx
there will now be a rando div wrapping the windowshade, but apparently the transition group needs it to keep track of the children and not re-mount them all willy nilly 
https://github.com/openstax/tutor-js/pull/2314/files?w=1 is a better diff
> fix annotation summary page re-rendering on delete

- tutor/resources/styles/components/annotations/annotation.scss
otherwise the highlight looks like this:
> set highlighter to be inline-block so it wraps math elements

- tutor/src/components/book-page.cjsx
Previously it wouldn't check for content when it was loaded
> Fix reference book teacher content indicator

- tutor/resources/styles/book-content/questions.scss
Some exercise content wasn't inside a `p` tag, causing the font to be Helvetica instead of the desired Merriweather.
before:
after:
> use serif font for all exercise content

- tutor/resources/styles/book-content/questions.scss
Otherwise FF/Safari inherit the grey font color
before:
After:
> explicitly set answer choice background to white

- tutor/resources/styles/components/tutor-dialog.scss
- tutor/specs/components/error-monitoring/server-error-message.spec.jsx
- tutor/src/components/error-monitoring/server-error-message.jsx
- tutor/src/models/annotations/hypothesis.js
I'd removed the call to `AppActions.setServerError(err)` in https://github.com/openstax/tutor-js/pull/2224 
Then when I was looking at the error message it had a bunch of `undefined` in it because the vars weren't being passed around correctly.
> Display errors when hypothesis server malfunctions

- shared/src/components/surety-guard.cjsx
- tutor/src/components/annotations/annotation-card.jsx
- tutor/src/components/annotations/summary-page.jsx
https://trello.com/c/XoKW1Qke/1611-bug-tabbing-in-highlights-summary-page-selects-the-buttons-in-the-delete-modal-only-after-tabbing-through-all-the-highlighted-st
> manage tab order for surety-guard and deleting annotations

- shared/resources/styles/mixins/questions.scss
Continuation of https://github.com/openstax/tutor-js/pull/2329
before:
after:
> set exercise choice button to white in safari

- jenkins/continuous-delivery.jenkins
- tutor/scripts/accessibility-audit/index.js
artifacts like this will be generated on master
https://jenkins-dev.cnx.org:8080/blue/organizations/jenkins/OpenStax%20-%20Continuous%20Integration%2Ftutor-js/detail/PR-2359/2/artifacts/
had to run 
```groovy
System.setProperty("hudson.model.DirectoryBrowserSupport.CSP", "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; font-src *");
```
on jenkins to get it to allow the html content
> generate audit html files

- configs/test/jest.config.json
- tutor/specs/components/error-monitoring/handlers.spec.jsx
- tutor/specs/components/navbar/index.spec.jsx
- tutor/specs/components/terms-modal.spec.jsx
- tutor/src/components/enroll.jsx
- tutor/src/components/error-monitoring/handlers.jsx
- tutor/src/components/error-monitoring/index.jsx
- tutor/src/components/navbar/index.jsx
- tutor/src/components/terms-modal.jsx
- tutor/src/helpers/react.js
- tutor/src/models/course/enroll.js
- tutor/src/screens/student-dashboard/index.jsx
This change: 
- Prevent error modal from showing for payment_overdue errors
- Will force the "Terms and Conditions" and  "You Must Pay Now!" modals to show anywhere the user in in a course, even if they bypass the dashboard by using an assignment link
> Fix payment_overdue error

- tutor/specs/models/courses/onboarding/student-course.spec.js
- tutor/src/models/course/onboarding/student-course.js
This is needed since the stores are probably in a bad state because the BE would have been raising 403's.
> reload page after a past due payment is made

- tutor/resources/styles/mixins/figures.scss
This way they add up to 100% and will fill the content, preventing small words
from appearing on the side
Before:
After:
> add left margin when image is last

- tutor/specs/models/course.spec.js
- tutor/src/models/course.js
- tutor/src/screens/teacher-dashboard/month.jsx
- tutor/src/tours/teacher-calendar.json
It's well past sprint 2018, shoulda removed it awhile ago
> remove notice about roster split

- tutor/resources/styles/book-content/mixins.scss
- tutor/resources/styles/components/task-step/all-steps.scss
on narrow screens, task-steps have much larger margin then reference book does.  Previously it would chop off the left side of sims.
> adjust interactive's margins to fit task-steps and ref book

- tutor/specs/screens/student-dashboard/empty-panel.spec.js
- tutor/src/screens/student-dashboard/empty-panel.jsx
- tutor/src/screens/student-dashboard/this-week-panel.jsx
Otherwise it says "empty" and then shows
> display a loading spinner while student dashboard fetches tasks

- tutor/src/flux/task.coffee
Otherwise it just updated the steps and didn't update the "feedback_available" property
> update store data by calling loaded on flux base methods

- tutor/src/flux/task.coffee
assign to _local directly instead of calling loaded
Reverts change in commit 8b151dadd1b28ea7c77c9af083da5bd65ef91182
For some unknown reason that causes the task steps to repeat the first step
when the task is completed
> Fix tasks jumping to first step when they're completed

- tutor/src/components/annotations/annotation.jsx
- tutor/src/components/obscured-page/overlay-registry.js
- tutor/src/helpers/dom.js
- tutor/src/models/annotations.js
- tutor/src/models/annotations/annotation.js
stores the selection's bounding rect and the sorts by it when annotations load
Also fixes the window scroll position. bug discovered by @TomWoodward
> Fix annotation sorting and overlay page scroll position

- tutor/specs/models/purchases.spec.js
- tutor/src/models/purchases.js
The map wasn't using strings for keys making it never find the order to refund since it's alphanumeric
> Fix purchases refund button

- shared/resources/styles/components/exercise-preview/index.scss
- tutor/resources/styles/components/enrollment-student-id.scss
- tutor/resources/styles/components/modals.scss
- tutor/resources/styles/components/modals/warning.scss
- tutor/resources/styles/components/plan-stats.scss
- tutor/resources/styles/components/task-teacher-review/question.scss
- tutor/specs/components/__snapshots__/lms-info-card.spec.jsx.snap
- tutor/specs/screens/student-dashboard/reading-row.spec.jsx
- tutor/src/components/lms-info-card.js
- tutor/src/components/notes/note-card.js
- tutor/src/components/notes/summary-popup.jsx
- tutor/src/components/payments/refund-modal.jsx
- tutor/src/models/task-plan/teacher.js
- tutor/src/models/tour/ride.js
- tutor/src/screens/course-roster/delete-period.jsx
- tutor/src/screens/lms-pair/create-course.jsx
- tutor/src/screens/lms-pair/ux.js
- tutor/src/screens/student-dashboard/event-info-icon.jsx
- tutor/src/screens/teacher-dashboard/styles/plan-details.scss
- tutor/src/screens/teacher-dashboard/styles/plan.scss
- tutor/src/theme.js
> Misc upgrade style fixes

- tutor/src/screens/scores-report/styles/table.scss
style bug was triggered if loading the scores report, navigating to teacher dash, then back to scores.
> fix scores report padding

- tutor/src/screens/scores-report/styles/table.scss
this is needed for Firefox so that all the nested cells are using `flex` layout.
> use flex as the default for cells

- tutor/resources/styles/components/notes/summary-page.scss
> vertically center button icons in Firefox

- exercises/specs/components/__snapshots__/exercise.spec.js.snap
- exercises/specs/models/exercises/exercise.spec.js
- exercises/src/components/exercise/preview.jsx
- exercises/src/models/exercises/exercise.js
- exercises/src/models/search.js
- shared/specs/components/__snapshots__/corner-ribbon.spec.jsx.snap
- shared/specs/factories/exercise.js
- shared/src/components/corner-ribbon.jsx
- tutor/specs/components/exercises/__snapshots__/cards.spec.js.snap
- tutor/specs/components/exercises/__snapshots__/details.spec.jsx.snap
- tutor/specs/components/exercises/__snapshots__/preview.spec.js.snap
Previously there was 2 bugs:
* The ribbon was always visible even when the user could edit
* The logic behind the ribbon was intended to only check if the current user was the author
* This failed for vocabulary terms, which aren't editable regardless of who authored them
> Consider author and vocabulary when calulating readOnly status

- bin/build
* npm ci is now ran in previous build script
* progress output just litters the build log
> no longer run 'npm ci' and omit progress output

- tutor/specs/screens/qa-view.spec.jsx
- tutor/src/screens/qa-view/ecosystem-selector.jsx
While rare, this can happen if an import fails
> fix QA Dashboard's ecosystem selector failing for ecosystems without books

- tutor/src/api/index.js
- tutor/src/flux/task-step.js
- tutor/src/models/response_validation.js
No longer display the modal, instead just log it to the console.  We'll probably change this behavior once the full UI for this is specced
> log validation failures to console but don't notify

- tutor/specs/components/navbar/center-controls.spec.jsx
- tutor/src/components/navbar/center-controls.jsx
The correct prop name was renamed to "model" and this was missed
Before the note summary widget would appear on all reading steps, even exercises
> only display the note summary toggle widget for reading steps

- tutor/specs/screens/task/steps/__snapshots__/reading.spec.js.snap
- tutor/src/screens/task/step/reading.js
this was an attempt to push non-splash type things down further
the page but now that each page has the title, it's not really
needed
> remove uneeded top padding/negative margin

- tutor/specs/screens/task/response-validation-ux.spec.js
- tutor/src/screens/task/response-validation-ux.js
That means it shouldn't be recorded on the 2nd attempt since it isn't re-displayed
> only record the nudge message when it was displayed

- tutor/specs/models/student-tasks/step.spec.js
- tutor/specs/screens/task/homework.spec.js
- tutor/specs/screens/task/reading.spec.js
- tutor/specs/screens/task/ux.spec.js
- tutor/src/models/student-tasks/step.js
- tutor/src/screens/task/ux.js
Usually the steps would be ready when the entire task was fetched, but for new students they sometimes wouldn't be
> Fix bug where placeholder steps wouldn't re-load when visited

- tutor/specs/components/notes/__snapshots__/summary-popup.spec.js.snap
- tutor/specs/components/notes/summary-popup.spec.js
- tutor/src/components/notes/summary-popup.jsx
Fixes bug where the user generated note property was renamed to be
"annoation" but the print screen failed to be updated
> include annotation content on summary popup

- tutor/specs/models/student-tasks/step.spec.js
- tutor/src/models/student-tasks/step.js
- tutor/src/screens/task/step/exercise-question.js
Fixes tricky bug where updates would be allowed if a student started working an assignment before it was due, and did not reload after it was due.
The BE would still error and refuse the update but this will disable the controls once the due date passes
> Disallow changing answers after assignment becomes due

- tutor/specs/screens/__snapshots__/qa-view.spec.jsx.snap
- tutor/src/components/book-menu/menu.jsx
- tutor/src/components/book-page.js
- tutor/src/components/related-content.js
- tutor/src/components/sections-chooser.jsx
- tutor/src/models/reference-book/page.js
Prevsiously it'd default to the tutor calculated location when
baked_location was missing, which would throw off the rest of
the section numbering
> Exclusively use baked location if book is collated

- tutor/resources/styles/book-content/note.scss
Removes the specific check for ost-assignable in favor of just checking if the note is inside another note
We do leave the indent and top/bottom border styles intact since that provides a nice visual block
>  do not apply note heading style to notes inside notes

- tutor/resources/styles/book-content/learning-objectives.scss
- tutor/resources/styles/book-content/splash-image.scss
- tutor/resources/styles/book-content/theming-mixins.scss
- tutor/resources/styles/mixins/figures.scss
- tutor/src/components/book-page.js
The newer books have A LOT of learning objectives, which made the column layout very lengthy.  Plus the learning objectives often appeared after the splash image, which made the theme color styles
look strange
> remove LO column layout, only use theme color when it's splashy

- tutor/resources/styles/book-content/note.scss
use cascade override to fix note in notes, when it's not a direct child the :not fails
> Attempt 2 at fixing notes inside notes styles

- tutor/src/models/course/information.js
devops will upload matching file sometime in the next few days
> Update URL to remove "2018" date on teacher guide

- shared/specs/helpers/mathjax.spec.js
- shared/src/components/html.js
- shared/src/helpers/mathjax.js
Bencharking suggest this is a 10x speed improvement for areas with
lots of small math components like the card view in HW builder.
In that case it cut rendering time from 4secs to 400ms
> debounce call to typesetMath and run it for entire document

- tutor/resources/styles/book-content/mixins.scss
- tutor/resources/styles/book-content/splash-image.scss
Prevents expanding past the page margin
> Fix splash image and figures size on narrow screens

- tutor/specs/screens/task/ux.spec.js
- tutor/src/screens/task/ux.js
Fixes case where only the current step would load and continue to display the skeleton for the others
> fetch all parts of a MPQ

- tutor/specs/models/student-tasks/task.spec.js
- tutor/src/api/index.js
- tutor/src/components/buttons/teacher-become-student.js
- tutor/src/models/student-tasks/task.js
Otherwise the task steps can get caught in an infinite loading when a placeholder is encountered because the UX class for the task steps attempts to reload when the step changes.  Since the step is a new object it technically has changed, so the onStepChange handler is called https://github.com/openstax/tutor-js/blob/master/tutor/src/screens/task/ux.js#L116
> merge steps on load instead of re-creating them all

- tutor/specs/models/task-plans/teacher/tasking.spec.js
- tutor/src/models/task-plans/teacher/tasking.js
- tutor/src/screens/assignment-builder/ux.js
fixes bug when the teacher clicks a date on the calendar to start editing with that as the due date
> adjust opens_at if needed when initializing with a due date

- tutor/specs/components/terms-modal.spec.jsx
- tutor/src/components/terms-modal.jsx
When the user has a targeted contract that signs all existing terms
> Fix blank terms being displayed

- package.json
- tutor/resources/styles/components/tutor-input.scss
- tutor/specs/screens/assignment-builder/builder/tasking.spec.js
- tutor/src/components/tutor-input.js
- tutor/src/models/task-plans/teacher/tasking.js
- tutor/src/screens/assignment-builder/builder/tasking.js
- tutor/src/screens/assignment-builder/footer/save-button.jsx
- tutor/src/screens/assignment-builder/ux.js
- yarn.lock
First commit fixes inputs losing focus
Second commit replaces masked inputs with input[type=time]
Polyfill (maybe https://www.npmjs.com/package/time-input-polyfill) will be needed for Safari
> Fix time controls to use native `time` input

- shared/src/model/exercise/tag.js
previously it was 'HTS-3 Source Claims and Evidence'
> rename HTS3 to "HTS-3 Claims and Evidence in Sources"

- tutor/specs/components/exercises/details.spec.jsx
- tutor/specs/models/task-plans/teacher/plan.spec.js
- tutor/specs/screens/assignment-builder/homework.spec.js
- tutor/specs/screens/assignment-builder/mini-editor/editor.spec.js
- tutor/specs/screens/assignment-builder/reading.spec.js
- tutor/specs/screens/assignment-builder/ux.spec.js
- tutor/src/models/task-plans/teacher/plan.js
Previously the ecosystem id wouldn't transfer, causing the plan to load the wrong book
> copy ecosystem_id when cloning a task plan

- tutor/specs/models/user.spec.js
- tutor/src/models/user.js
- tutor/src/screens/student-dashboard/index.jsx
- tutor/src/screens/teacher-dashboard/index.jsx
Set User.terms during bootstrap instead of making it a computed value.
Previously something was causing it to re-initialize and delay the rendering of the terms modal.
Still flashes the content behind the modal briefly though (same as staging).
> Display the terms of use faster

- tutor/specs/components/buttons/teacher-becomes-student.spec.js
- tutor/specs/screens/scores-report/table.spec.jsx
- tutor/src/components/buttons/teacher-become-student.js
- tutor/src/models/course.js
- tutor/src/screens/scores-report/table.jsx
- tutor/src/screens/scores-report/ux.js
When the scores report had no students enrolled and a teacher became a student it would show the "students need to enroll" message
It would also break if the teacher became a student in any period other than the 1st one.
Also the teacher-as-student button would show dropdown state if there were archived periods.
> Fix scores report for teach-as-student 

- tutor/resources/styles/components/media-preview.scss
fixes wrapping like:
the paren should stay with the figure when it's not set to `inline-block`
> display figures inline and adjust preview modal styles

- tutor/src/models/reference-book/page.js
fixes bug where "Connections for AP courses" would have "undefined" chapter section
before:
after:
> only display chapter section if it's present

- tutor/src/helpers/conditional-handlers.jsx
- tutor/src/models/course/role.js
- tutor/src/screens/task/ux.js
Previously a student's data was not cleared when going back to teacher role, causing the teacher to briefly see student score data
> clear student data anytime role is changed

- tutor/specs/screens/student-dashboard/__snapshots__/dashboard.spec.jsx.snap
- tutor/specs/screens/student-dashboard/dashboard.spec.jsx
- tutor/specs/screens/student-dashboard/empty-panel.spec.js
- tutor/specs/screens/student-dashboard/this-week-panel.spec.js
- tutor/src/models/task-plans/student.js
- tutor/src/screens/student-dashboard/all-events-by-week.jsx
- tutor/src/screens/student-dashboard/dashboard.jsx
- tutor/src/screens/student-dashboard/empty-panel.jsx
- tutor/src/screens/student-dashboard/events-panel.jsx
- tutor/src/screens/student-dashboard/late-icon-ledgend.js
- tutor/src/screens/student-dashboard/styles/empty-card.scss
- tutor/src/screens/student-dashboard/this-week-panel.jsx
- tutor/src/screens/student-dashboard/upcoming-panel.jsx
Instead of waiting for all tasks to be ready.
The following screenshots were taken by artificially manipulating the APIs to get the correct flags:
Preparing (10 min):
Fetching:
Loading some more:
No past work:
> Display ready tasks as the dashboard loads

- tutor/specs/screens/task/__snapshots__/external.spec.js.snap
- tutor/specs/screens/task/external.spec.js
- tutor/src/models/student-tasks/step.js
- tutor/src/screens/task/external.js
the issue was that steps were marking themselves complete as soon as they were viewed, but "complete" in the context of a external url means it was clicked.
> don't mark external url steps as complete until link is clicked

- tutor/resources/styles/components/top-nav-bar.scss
- tutor/specs/models/task-plans/teacher/plan.spec.js
- tutor/specs/models/task-plans/teacher/tasking.spec.js
- tutor/specs/models/task-plans/teacher/teacher.spec.js
- tutor/specs/screens/teacher-dashboard/dashboard.spec.js
- tutor/specs/screens/teacher-dashboard/month.spec.js
- tutor/src/components/book-page.js
- tutor/src/components/tutor-input.js
- tutor/src/models/task-plans/teacher/plan.js
- tutor/src/models/task-plans/teacher/tasking.js
- tutor/src/screens/assignment-builder/ux.js
- tutor/src/screens/student-dashboard/event-row.jsx
- tutor/src/screens/teacher-dashboard/month.js
- tutor/src/screens/teacher-dashboard/plan-label.jsx
Fixes a few small irritants:
* Sometimes the individual taskings for a new assignment would be shown one-per-period
* Sometimes the time would be shown as invalid even though it wasn't
* hides the browser auto-complete on the date inputs
* Shows opens at time if it's the same day as today
> Tweak task builder ui

- tutor/resources/styles/components/tutor-input.scss
- tutor/specs/models/task-plans/teacher/tasking.spec.js
- tutor/specs/screens/assignment-builder/builder/tasking.spec.js
- tutor/src/components/tutor-input.js
- tutor/src/models/task-plans/teacher/plan.js
- tutor/src/models/task-plans/teacher/tasking.js
- tutor/src/screens/assignment-builder/builder/index.js
- tutor/src/screens/assignment-builder/builder/tasking.js
- tutor/src/screens/assignment-builder/styles/builder.scss
- tutor/src/screens/assignment-builder/ux.js
the tricky bit is that the check needs to be a per-tasking basis and only look at what's saved, not what is currently set
> Do not allow editing opens_at for published and open plans

- tutor/src/screens/student-dashboard/events-panel.jsx
- tutor/src/screens/student-dashboard/this-week-panel.jsx
The EventsPanel is rendered for both this week, upcoming and past
from:
to:
> Move TeacherPendingLoad to this week panel

- tutor/src/components/plan-stats/index.jsx
when `analytics` is fetched it will overwrite the exercises so don't fetch unless it's needed
> only fetch analytics if needed

- package.json
- tutor/specs/components/error-monitoring/__snapshots__/async-load-error.spec.jsx.snap
- tutor/specs/components/error-monitoring/async-load-error.spec.jsx
- tutor/src/components/error-monitoring/async-load-error.jsx
- tutor/src/helpers/async-component.js
- tutor/src/helpers/conditional-handlers.jsx
- yarn.lock
Fixes some of the console warnings about use of deprecated `componentWillMount`
> replace loadable-component with built-in React.Lazy

- shared/src/components/exercise-identifier-link.js
- tutor/specs/screens/teacher-review-metrics/exercise.spec.jsx
- tutor/src/screens/teacher-review-metrics/exercise.jsx
- tutor/src/screens/teacher-review-metrics/review.jsx
Fixes bug where the trouble link didn't include the book name, causing the errata form would spin forever
> supply bookUUID to identifier-link; make it required

- tutor/api/courses/1/guide.json
- tutor/specs/flux/performance-forecast.spec.js
- tutor/src/flux/performance-forecast.js
- Don't display performance forecast sections without any work done in recent topics.
- Prioritize sections with bars.
- Sort sections by last_worked_at date.
Needs: https://github.com/openstax/tutor-server/pull/1911
> Recent topics fixes

- tutor/src/screens/assignment-builder/mini-editor/index.js
- tutor/src/screens/teacher-dashboard/past-assignments.jsx
- tutor/src/screens/teacher-dashboard/task-dnd.jsx
It's conflicting with drag and drop.  Replace with standard browser title attribute
> Remove popover tooltip from past assignments

- tutor/resources/styles/book-content/base.scss
Most of the links are just urls which lack spaces.  that causes
them to overflow the page unless set to 'break-all'
> break links anwhere

- shared/src/components/icon.js
- tutor/specs/screens/student-dashboard/task-progress-info.spec.js
- tutor/src/models/task-plans/student/task.js
- tutor/src/screens/student-dashboard/progress-guide.js
- tutor/src/screens/student-dashboard/task-progress-info.js
The description used to be displayed like this but it was lost somewhere along the line
> Restore student task info tooltip

- tutor/specs/screens/task/steps/__snapshots__/exercise.spec.js.snap
- tutor/specs/screens/task/ux.spec.js
- tutor/src/screens/task/index.js
- tutor/src/screens/task/ux.js
The `ScrollToTop` component jumps to the top when the path changes, like between MPQ,
and Loading must finish before scrolling
> fix jumping to top before scrolling to MPQ steps

- tutor/src/helpers/dom.js
we're dealing with strange "failed to parse json" errors
> add logging when boostrap JSON fails to parse

- tutor/src/screens/task/step/exercise-free-response.js
- tutor/src/screens/task/step/index.js
- tutor/src/screens/task/ux.js
Otherwise the browser will scroll to the focused element and interrupt
the scroll
> Focus text area after scrolling

- tutor/specs/screens/teacher-dashboard/dashboard.spec.js
- tutor/src/screens/teacher-dashboard/month-title-nav.jsx
No idea why the nav header was setting state itself, instead of relying on the date prop it was passed
> move duplicated navigation logic out of calendar header

- tutor/resources/styles/book-content/base.scss
- tutor/resources/styles/book-content/theming-mixins.scss
otherwise the border is pressed right up to the text
Somehow this rule was lost in https://github.com/openstax/tutor-js/pull/2740
> add left padding to blockquote

- tutor/specs/models/task-plans/student.spec.js
- tutor/specs/screens/student-dashboard/dashboard.spec.jsx
- tutor/src/models/task-plans/student.js
- tutor/src/screens/student-dashboard/dashboard.jsx
sets to 10 secs for "fast polling" state and 1 hour for regular checks
fast polling is enabled for:
* freshly enrolled students
* instructors who've just made an assignment then went into student view
> decrease polling interval for new assignments

- tutor/src/screens/task/ux.js
Otherwise the controls won't render until the user goes forward
> notify center controls of initial step

- tutor/src/components/navbar/actions-menu.jsx
Route should have never been used, but it would render it's children so it wasn't noticed until 5.10 removed that
> Use Link instead of Route

- tutor/specs/screens/question-library/dashboard.spec.jsx
- tutor/src/screens/question-library/dashboard.jsx
Otherwise the details view doesn't get the correct props.  We should always start the display on the cards though so that's desired
> set view to "card view" when selecting more sections

- tutor/src/screens/task/ux.js
hopefully will prevent hammering the keyboard from jumping forward multiple spaces
> Only go forward/back if it's allowed

- tutor/specs/screens/task/__snapshots__/breadcrumbs.spec.js.snap
- tutor/specs/screens/task/__snapshots__/external.spec.js.snap
- tutor/specs/screens/task/__snapshots__/homework.spec.js.snap
- tutor/specs/screens/task/__snapshots__/milestones.spec.js.snap
- tutor/specs/screens/task/__snapshots__/progress.spec.js.snap
- tutor/specs/screens/task/__snapshots__/reading.spec.js.snap
- tutor/specs/screens/task/steps/__snapshots__/exercise-free-response.spec.js.snap
- tutor/specs/screens/task/ux.spec.js
- tutor/src/screens/task/ux.js
This stops keyboard arrows or clicking on next arrow from rapidly skipping all the reading steps
> add a 1.5 seconds delay before a step can be advanced

- tutor/specs/screens/task/ux-task-manipulations.spec.js
- tutor/src/models/student-tasks/step-group.js
- tutor/src/screens/task/ux-task-manipulations.js
- tutor/src/screens/task/ux.js
occasionally only one of the steps in a MPQ will trigger display of a value-prop card.  When that happens the value prop card is displayed after the MPQ but it's breadcrumb would be correct.
This changes the value-prop insertion so that it happens before the first MPQ
> insert value prop before first MPQ

- tutor/src/models/user/menu.js
Otherwise it uses history.push and the router doesn't handle that url
> use a redirect to load the content analyst dashboard

- tutor/src/screens/performance-forecast/section.js
This fixes the value being passed to the ProgressBar component from
including a literal "cs.asString" to instead interpolating the value.
Ex: "Practice - cs.asString" becomes "Practice - 3.2 Vector Addition"
> fix aria label interpolation

- tutor/resources/styles/mixins/figures.scss
> use sans serif font for figures

- tutor/resources/styles/book-content/base.scss
- tutor/resources/styles/global/typography.scss
> use sans-serif font for table cells

- tutor/resources/styles/book-content/base.scss
- tutor/resources/styles/book-content/mixins.scss
- tutor/resources/styles/variables/book-content.scss
> remove drop cap style from paragraphs

- tutor/src/components/exercises/details.jsx
A particular render case doesn't pass the selectedSection prop, so
it's undefined when this equality check is run. This commit returns
early from componentDidUpdate if it's not present.
> fix selectedSection prop check

- tutor/specs/screens/assignment-builder/builder.spec.js
- tutor/src/screens/assignment-builder/ux.js
"All Sections" in the UI would be selected in cases it shouldn't, this fixes the check for what to render by changing `isShowingPeriodTaskings` to consider `canSelectAllSections` as well.
> fix section selector

- tutor/resources/styles/book-content/base.scss
Fixes links that would break anywhere, not just on spaces:
after:
> use break-word css rule

- tutor/specs/components/book-menu/__snapshots__/menu.spec.js.snap
- tutor/specs/screens/__snapshots__/qa-view.spec.jsx.snap
- tutor/src/components/book-menu/menu.jsx
Safari has [a flexbox bug](https://github.com/philipwalton/flexbugs#flexbug-9) that prevents it from using "flex" layout
After:
> put summary content inside div

- tutor/src/components/book-page.js
- tutor/src/components/media-preview.js
- tutor/src/components/tutor-popover.js
previously this only retained the text of a media preview which would throw away <b> and other tags inside it
> Fix media preview inner text links

- tutor/specs/screens/task/index.spec.js
- tutor/src/screens/task/index.js
- tutor/src/screens/task/ux.js
Previously we'd fetch the task every time it the task UI loaded, even if we'd fetched it before.  In that case the steps would already be loaded but we'd reload the task.
Doing so would cause a race between the task loading and the current step.  if the step loaded first, the task would reset it when it loaded, leaving the UI in a loading state.
this fixes the step load to only occurs after the task is finished loading, but also changes the task to only load if it wasn't already fetched.  I don't see any reason that we need to load it every time.
> Only fetch task if needed, wait for finish before step navigation

- tutor/resources/styles/book-content/base.scss
Previously only the body was sans, but we also want the headers as well
before:
after:
> set entire table font to use sans serif font stack

- tutor/src/screens/task/index.js
I still haven't figured out how to fix the loading forever bug.
> Fix no course message when task fails to load due to connection issues

- tutor/resources/styles/components/multi-select.scss
The will-change property being added by the dropdown library causes stange rendering behavior. Adding `transform: translateZ(0)` forces hardware acceleration on and somehow fixes the bug.
Chrome before:
Chrome after:
Firefox before:
Firefox after:
> Fix highlighter dropdown rendering issues in chrome and firefox

- tutor/src/components/multi-select.jsx
This prevents popper from trying to keep the dropdown onscreen, which could cause it to partially go offscreen.
Before:
After:
> prevent section select from partially going off screen

- tutor/specs/screens/assignment-builder/reading/review-selection.spec.js
- tutor/src/screens/assignment-builder/reading/review-selection.js
This is needed so they'll display any HTML markup
> use BookPartTitle to display page title in HW review

- tutor/resources/styles/components/notes/summary-page.scss
- tutor/resources/styles/mixins/tutor-modal.scss
- tutor/specs/screens/task/progress.spec.js
- tutor/specs/screens/task/reading.spec.js
- tutor/src/screens/task/milestones.js
- tutor/src/screens/task/progress.js
- tutor/src/screens/task/reading.js
- tutor/src/screens/task/styles/milestones.scss
Before:
After:
- Observes Milestones so we can pass index changes to Milestone
- Hoists PagingNavigation up to ReadingTask since the Overlay isn't used anymore
- Consolidates the new modal style into a mixin so it can be phased in
and eventually removed when it becomes the base style.
> move reading milestones into a modal

- tutor/src/components/notes/summary-page.jsx
- tutor/src/models/notes.js
When the last note in a section is removed, we need to remove it from the summary and selected sections lists
> reset summary and selection when deleting last note in a page

- shared/src/model/api.js
- tutor/src/components/notes/edit-box.jsx
If you changed the annotation in the textbox of an existing note, and then click Delete, an error would be thrown because the note would be deleted, but during unmounting, the annotation text would be different, firing off an update. This fixes the issue by checking the api for a deletion request (thanks @nathanstitt!)
> Fix note deletion throwing error

- tutor/resources/styles/components/notes/note.scss
- tutor/src/components/notes/inline-controls.jsx
- Changes the width and adds a dividing border to match the design comp
- Centers the tool over the first (or only) highlighted line by using getClientRects to position itself.
Before:
After:
> Improve highlighter popup tool

- tutor/specs/screens/grading-templates/__snapshots__/delete-modal.spec.jsx.snap
- tutor/specs/screens/grading-templates/delete-modal.spec.jsx
- tutor/src/screens/grading-templates/delete-modal.jsx
- tutor/src/screens/grading-templates/index.js
- Moves delete callback into a modal confirmation
- Makes edit modal close button match the others
> add delete confirmation to templates

- tutor/specs/screens/task/__snapshots__/breadcrumbs.spec.js.snap
- tutor/specs/screens/task/__snapshots__/external.spec.js.snap
- tutor/specs/screens/task/__snapshots__/homework.spec.js.snap
- tutor/specs/screens/task/__snapshots__/milestones.spec.js.snap
- tutor/specs/screens/task/__snapshots__/progress.spec.js.snap
- tutor/specs/screens/task/__snapshots__/reading.spec.js.snap
- tutor/specs/screens/task/__snapshots__/task-info.spec.js.snap
- tutor/specs/screens/task/index.spec.js
- tutor/specs/screens/task/steps/__snapshots__/exercise-free-response.spec.js.snap
- tutor/specs/screens/task/steps/__snapshots__/exercise.spec.js.snap
- tutor/specs/screens/task/steps/__snapshots__/failure.spec.js.snap
- tutor/specs/screens/task/steps/__snapshots__/nudge-message.spec.js.snap
- tutor/src/models/student-tasks/task.js
- tutor/src/screens/task/index.js
This moves the wait for practice tasks from the BE to the FE so the unicorn workers don't stay busy while waiting.
Goes with https://github.com/openstax/tutor-server/pull/1970
> Retry loading tasks that start with a placeholder step (practice tasks)

- tutor/specs/integration/assignments.spec.js
- tutor/src/screens/assignments/builder.js
- tutor/src/screens/assignments/controls.js
- tutor/src/screens/assignments/homework/exercise-controls.jsx
- tutor/src/screens/assignments/questions.js
- tutor/src/screens/assignments/ux.js
Adds the indicators from the top toolbar into the footer toolbar, and makes the buttons match the specs.
> add indicators to questions step footer

- tutor/src/screens/assignments/homework/add-exercises.jsx
- tutor/src/theme.js
I pulled over styles from the sass files into styled components — after the switch, we could eventually apply them directly to the exercise card components, but for now it uses the descendant class names. A little fragile but keeps from cloning the card component classes.
Also copied Bootstrap v4's default breakpoints into Theme to maintain an existing margin rule & set it up for future use.
> Put exercise questions back into columns

- shared/specs/factories/exercise.js
- tutor/scripts/test-server/backend/exercises.js
- tutor/specs/factories/exercise.js
- tutor/specs/integration/assignments.spec.js
- tutor/src/screens/assignments/homework/add-exercises.jsx
- tutor/src/screens/assignments/homework/cards.js
- tutor/src/screens/assignments/homework/exercise-controls.jsx
- tutor/src/screens/assignments/ux.js
Adds filtering for All / Multiple Choice / Written Response (Open Ended) question types to the assignment builder.
Due to multipart questions, the only reliable method I could find was to check the type of the first question in the list. As far as I can tell, it's not likely a multipart will ever contain mixed types, but if there's a better way let me know.
Example of narrowing it down to WR only:
With All or Multiple Choice selected, you'll always see MC at the top:
> Hook up question type filters

- tutor/src/screens/stats/table.jsx
This was missed when we updated the charts
> use new counts vs active on stats table

- tutor/specs/components/__snapshots__/checkbox-input.spec.js.snap
- tutor/specs/components/checkbox-input.spec.js
- tutor/src/components/checkbox-input.js
- tutor/src/components/radio-input.jsx
- tutor/src/screens/assignments/details.js
- tutor/src/screens/assignments/tasking.js
- Adds an orange checkbox (CheckboxInput) that can be used anywhere and should be accessible. 
- Fixes some alignment things with rendering period + date time fields
> Add custom checkbox and tweaks to details page

- tutor/src/components/book-menu/menu.jsx
- tutor/src/components/sections-chooser.jsx
With the new TOC the chapters do not have ids since they're not stored as a db record
Needed to go along with: https://github.com/openstax/tutor-server/pull/1966
> Sections sometimes lack ids, use alternate key

- tutor/resources/styles/components/plan-stats.scss
- tutor/resources/styles/global/buttons.scss
- tutor/specs/components/__snapshots__/date-time-input.spec.js.snap
- tutor/specs/components/__snapshots__/template-modal.spec.js.snap
- tutor/specs/components/plan-stats/index.spec.jsx
- tutor/specs/components/template-modal.spec.js
- tutor/specs/integration/assignments.spec.js
- tutor/src/components/date-time-input.js
- tutor/src/components/plan-stats/course-bar.jsx
- tutor/src/components/plan-stats/index.jsx
- tutor/src/components/template-modal.js
- tutor/src/models/task-plans/teacher/tasking.js
- tutor/src/screens/assignments/tasking.js
- tutor/src/screens/grading-templates/editors.js
- tutor/src/screens/teacher-dashboard/plan-details.jsx
Update Assignment Modal
- Use radio buttons for period toggle
- Add date time fields to change and save inline for period
- Update button styles
Update assignment DateTime fields
- Use setFieldValue in event to make sure the form visually reflects changes we made while running rules (like if the due date was set to before open date)
- Fix closes_at rule
General
- Added a btn-form-action in sass for those new big buttons we've started using.
- Made a TemplateModal component to DRY up that particular modal style
Side note: with both the above, I need to add a pass later that makes things like grading templates modal use them instead of duplicating styles.
As you can see from the below image, the metrics screen may need to be touched up now.
> update assignment modal, fix closes_at & general datetime fields

- tutor/src/screens/teacher-dashboard/plan-details.jsx
Using render is deprecated, so I switched it to a child callback function.
`Warning: <Formik render> has been deprecated and will be removed in future versions of Formik. Please use a child callback function instead. To get rid of this warning, replace <Formik render={(props) => …} /> with <Formik>{(props) => …}</Formik> tiny-warning.esm.js:11 `
> fix formik deprecation warning by switching render approach

- shared/src/components/icon.js
- tutor/src/screens/assignment-review/overview.js
- tutor/src/screens/assignment-review/scores.js
Added the available points text using some quite rudimentary addition, I need to go over the logic for real and put it into UX.
Added the state for if this can't be calculated due to different student question counts... as above,  not sure about the logic of this yet.
Refactored the existing score table triangles so they can support having tooltips. Added some placeholder text for now.
> WRM Assignment Review Tooltips

- tutor/scripts/test-server/backend/dashboard.js
- tutor/scripts/test-server/backend/task-plans.js
- tutor/specs/integration/assignment-review.spec.js
- tutor/specs/integration/course.spec.js
- tutor/specs/screens/student-dashboard/__snapshots__/dashboard.spec.jsx.snap
- tutor/specs/screens/teacher-dashboard/plan-details.spec.jsx
- tutor/src/components/plan-stats/index.jsx
- tutor/src/components/template-modal.js
- tutor/src/helpers/string.js
- tutor/src/routes.js
- tutor/src/screens/assignment-grade/ux.js
- tutor/src/screens/assignment-review/details.js
- tutor/src/screens/assignment-review/index.js
- tutor/src/screens/teacher-dashboard/plan-details.jsx
- All assignment types use a singular "View assignment" button that goes to the Details tab
- Metrics (question performance bars) aren't needed
Note: does not yet include logic to decide if the Grade button should be shown based on WRM question presence
> dashboard modal tweaks

- tutor/src/screens/teacher-dashboard/sidebar.js
Adds separator below Grading Templates link.
> add separator to dashboard

- shared/specs/components/__snapshots__/html.spec.js.snap
- shared/specs/components/html.spec.js
- shared/src/components/html.js
The media previews were rendered using reactdom and lack the context of their parent
https://github.com/openstax/tutor-js/blob/master/tutor/src/components/book-page.js#L305
> Support rendering html component without router context

- tutor/specs/components/__snapshots__/radio-input.spec.jsx.snap
- tutor/src/components/radio-input.jsx
- tutor/src/screens/grading-templates/editors.js
- Switch the block elements to use a bottom margin only
- Fix some missing border and radio background colors
- Preserve the space after the inline strong tag
> more template modal fixes

- tutor/src/models/task-plans/teacher/plan.js
Readings & HW require settings to have certain properties in order for it to be saved
> set default values for settings so it can be saved immediately

- shared/src/components/html.js
When we just checked it wasn't a link, we would also capture clicks on span and non anchor elements
> Check if click is on a link and not external

- tutor/src/screens/assignment-edit/details.js
`<a>` makes the modal to lose focus. Changing the **+ Add New Template** to a button and styling it accordingly.
> make '+ Add New Template' as a button. With '<a>' the modal loses focus.

- tutor/specs/components/__snapshots__/app.spec.jsx.snap
- tutor/specs/components/app.spec.jsx
- tutor/specs/components/my-courses.spec.jsx
- tutor/specs/models/user.spec.js
- tutor/specs/models/user/__snapshots__/menu.spec.js.snap
- tutor/specs/models/user/menu.spec.js
- tutor/specs/screens/new-course/course-name.spec.js
- tutor/specs/screens/new-course/course-numbers.spec.jsx
- tutor/specs/screens/new-course/index.spec.jsx
- tutor/specs/screens/new-course/select-course.spec.jsx
- tutor/specs/screens/new-course/select-dates.spec.jsx
- tutor/specs/screens/new-course/ux.spec.js
- tutor/specs/screens/new-course/wizard.spec.jsx
- tutor/src/components/my-courses/index.jsx
- tutor/src/components/my-courses/non-allowed-teacher.js
- tutor/src/models/user.js
- tutor/src/models/user/menu.js
- tutor/src/routes.js
- tutor/src/screens/new-course/ux.js
Only college, high_school and k12 should be given instructor access
Salesforce has a few others like "general" that shouldn't be able to teach
> restrict access to user types other than listed

- tutor/resources/styles/global/buttons.scss
- tutor/scripts/test-server/backend/task-plans.js
- tutor/specs/integration/assignment-review.spec.js
- tutor/src/screens/assignment-review/delete-modal.js
- tutor/src/screens/assignment-review/details.js
- tutor/src/screens/assignment-review/index.js
- tutor/src/screens/assignment-review/overview.js
- tutor/src/screens/assignment-review/ux.js
- tutor/src/screens/teacher-dashboard/plan-details.jsx
- Add delete assignment modal
- Rename `btn-form-action` to `btn-standard`. I didn't realize at first how much we'd be using these new button styles outside of forms, so I'm taking the time now to settle on this naming ("default" is already in use.) Should be generic enough and allow us to continue phasing in the new styles without overriding the existing "default" buttons.
> Delete modal in assignment review

- tutor/scripts/test-server/backend/grading-templates.js
- tutor/specs/integration/assignment-review.spec.js
- tutor/src/screens/assignment-edit/confirm-template-modal.js
- tutor/src/screens/assignment-edit/details-body.js
- tutor/src/screens/assignment-edit/ux.js
- tutor/src/screens/assignment-review/ux.js
- Adds a confirmation modal when changing grading template on an existing assignment
- Skip updating date times on an existing assignment when changing templates
- Assign updated plan values to `planScores` so we don't have to refetch (helps load + tests.)
- Don't allow adding a new template when editing existing assignment
> Confirm changing template

- tutor/specs/models/task-plans/teacher/plan.spec.js
- tutor/src/models/task-plans/teacher/plan.js
This wasn't being set at all but it wasn't noticed since clones would still succeed if the ecosystem hadn't changed
> set "cloned_from_id" property when cloning an assignment

- tutor/src/models/task-plans/teacher/plan.js
- tutor/src/models/task-plans/teacher/tasking.js
- tutor/src/screens/assignment-edit/confirm-template-modal.js
- tutor/src/screens/assignment-review/details.js
- tutor/src/screens/assignment-review/styles.scss
- tutor/src/screens/assignment-review/ux.js
- Fix z-index — the style wasn't actually getting used, this fixes making sure the modal backdrop displays on top of the 1st modal.
- Wait to render events that need planScores & editUX until it's ready
- Fix some recursion that was happening with the latest changes by hand picking and assigning values we pull from the edited plan.
- Only update tasking plan dates if the plan is new
- Break out "Assigned to" dates by period if they are different
> Wrm assignment review details

- shared/src/model/exercise.js
- tutor/scripts/test-server/backend/task-plans.js
- tutor/specs/factories/task-scores.js
- tutor/specs/integration/assignment-grade.spec.js
- tutor/specs/integration/assignment-review.spec.js
- tutor/src/models/exercises/exercise.js
- tutor/src/models/task-plans/teacher/plan.js
- tutor/src/screens/assignment-review/details.js
- tutor/src/screens/assignment-review/grading-block.js
- tutor/src/screens/assignment-review/index.js
- tutor/src/screens/assignment-review/ux.js
Adds the Grading Block in Assignment Details with logic to display 4 possible states based on if the exercises are all MCQs or mixed with WRM/OE, and if the due date is past or not. And hides the block on non-homework types.
There's only a basic test for now due to time with trying to set up test data. But I did include a start for getting open ended exercise factories loading from the test server backend. Can pick it up later and get build some specs based around those states mentioned above.
> WRM Grading Block

- package.json
- tutor/resources/styles/components/date-time-input.scss
- tutor/specs/components/__snapshots__/date-time-input.spec.js.snap
- tutor/specs/components/date-time-input.spec.js
- tutor/specs/integration/assignment-edit.spec.js
- tutor/src/components/date-time-input.js
- tutor/src/screens/assignment-edit/details-body.js
- tutor/src/screens/assignment-edit/tasking.js
- yarn.lock
1. The vertical separator between date and time is missing.
2. The time preview in top left should show the exact time being set.
3. It should show AM/PM instead of seconds
4. Add 01 and 59 also to the seconds option
5. Show the hours in a reverse order 12, 11, 10, 09 - preferred times since preferred due time are 9, 10, 11, 12 etc.
6. The arrows next to the month should be bigger at least 12 /16 px.
7. The confirmation button ‘Okay’ on the date and time modal is easy to miss and makes me wonder if we even need it.
8. The new D&T picker has a ‘now’ option, Update the helper text below ‘Assign’ to reflect that. New helper text-"To immediately open an assignment, select ‘now’ in the calendar."
> Wrm 930 date time picker style

- tutor/specs/integration/assignment-review.spec.js
- tutor/src/screens/assignment-review/details.js
- tutor/src/screens/assignment-review/index.js
- tutor/src/screens/assignment-review/ux.js
- tutor/src/screens/teacher-dashboard/plan-details.jsx
- Don't render Submission and Scores tabs for External and Event types
- Fix an issue with External type in the modal not going to assignment review
> Hide tabs for external and event types

- tutor/specs/screens/teacher-dashboard/sidebar.spec.js
- tutor/src/screens/teacher-dashboard/add-menu.jsx
- tutor/src/screens/teacher-dashboard/sidebar.js
Deleting an extra Grading Template link in the sidebar.
> delete grading templates in the sidebar

- shared/src/components/icon.js
- tutor/specs/integration/assignment-review.spec.js
- tutor/src/components/icons/extension.js
- tutor/src/helpers/background-wrapper.js
- tutor/src/models/task-plans/teacher/scores.js
- tutor/src/screens/assignment-edit/index.js
- tutor/src/screens/assignment-review/drop-questions.js
- tutor/src/screens/assignment-review/grant-extension.js
- tutor/src/screens/assignment-review/index.js
- tutor/src/screens/assignment-review/scores.js
- tutor/src/screens/assignment-review/ux.js
- Display when a student has been granted an extension
- Add a ContentWrapper to start adding min/max width layout requirements
- Display points or dashes based if the question has been graded, has been completed, was not completed before the due date, etc. Regarding the past due date, the BE will send 0 for `points` after the due date if the question wasn't answered, so we don't have to manually check for due dates, just `points`/`gradedPoints` presence.
- Add name order toggle
- Fix displaying "FR" displaying instead of "WRQ"
- Fix many places real values weren't being displayed yet
> Wrm scores fixes

- tutor/src/components/task-progress.js
- tutor/src/models/student-tasks/step.js
- tutor/src/screens/task/step/card.js
Add the available points in the task header progress table and question card.
> add available points in student task progress header

- tutor/src/components/course-period-select.js
- tutor/src/models/task-plans/teacher/scores.js
- tutor/src/screens/assignment-grade/index.js
- tutor/src/screens/assignment-review/grading-block.js
- tutor/src/screens/assignment-review/index.js
- Fix grade button not sending the period id, add optional params to grader prototypes
- Fix section dropdown showing all active periods instead of what was assigned. Might be a simpler way to filter than what's in the commit...
- Show gradeable count in the grade button
> Wrm grade and section fixes

- tutor/specs/components/__snapshots__/course-breadcrumb.spec.jsx.snap
- tutor/src/components/course-breadcrumb.jsx
- tutor/src/screens/assignment-grade/index.js
- tutor/src/screens/assignment-review/index.js
- tutor/src/screens/assignment-review/overview.js
- tutor/src/screens/grading-templates/index.js
- tutor/src/screens/teacher-gradebook/index.js
Consolidates these pages to use the breadcrumb for the title exclusively, and removes the size option since it's not really used.
Also moves the "This assignment is now open for grading." text to be aligned with the Grade button.
> Fix double title render and some small visual fixes

- tutor/src/screens/assignment-edit/ux.js
small fix. for events, closes_at should be the same as due_at since it is hidden from the ui.
> for events, set closes_at same as due_at

- tutor/src/screens/assignment-review/overview.js
Fixes not sending `availablePoints` when there were equal number of questions, causing the icon to be displayed instead of the points.
> fix displaying available points icon/value

- tutor/specs/factories/task-scores.js
- tutor/src/models/task-plans/teacher/scores.js
This field was unused and ambiguous so I took it out in the backend too.
> Removed late_work_fraction_penalty from student array in scores

- tutor/specs/integration/assignment-review.spec.js
- tutor/specs/screens/teacher-dashboard/plan-details.spec.jsx
- tutor/src/components/course-period-select.js
- tutor/src/components/plan-stats/index.jsx
- tutor/src/models/task-plans/teacher/plan.js
- tutor/src/models/task-plans/teacher/scores.js
- tutor/src/screens/assignment-grade/index.js
- tutor/src/screens/assignment-grade/ux.js
- tutor/src/screens/assignment-review/index.js
- tutor/src/screens/assignment-review/ux.js
- tutor/src/screens/teacher-dashboard/plan-details.jsx
- Consolidates some of the period options to only provide active periods that were assigned to.
- Fixes an issue with assignment review getting period data from scores api instead of the task plan api, which now allows the selector to render when a period doesn't have students.
- Fixes several period-selector issues with the plan stats/details modal that shows when you click a plan on the calendar.
> fix not displaying only active assigned periods

- tutor/src/screens/assignment-grade/ux.js
- tutor/src/screens/assignment-review/overview.js
- tutor/src/screens/assignment-review/ux.js
- Render graded response block to expanded question responses
- Add border to table cells
- Tweak some grade button styles, and only render them when the assignment is past due
I think there's still an issue to look into where the grade buttons are displaying with 0 remaining.
> Submission overview changes

- tutor/src/screens/assignment-review/drop-questions.js
- tutor/src/screens/assignment-review/ux.js
Might fix a bug on tutor-dev and is a good idea anyway.
Second api conditional on disabled to ensure it gets disabled while submitting to prevent double clicks... normally the isWaiting logic inside the component takes care of it, but didn't seem to be working in this case 🤔
> make drop questions button async

- tutor/src/screens/student-dashboard/status-legend.js
- tutor/src/screens/student-dashboard/task-info.js
- Always display the legend
- Make sure score is set when displaying provisional icon, because sometimes it's true from the backend for new, unworked assignments.
> Student dash fixes

- tutor/src/components/date-time-input.js
- tutor/src/models/task-plans/teacher/tasking.js
- tutor/src/screens/assignment-edit/details-body.js
- tutor/src/screens/assignment-edit/ux.js
- tutor/src/screens/assignment-review/ux.js
- Set originalDueAt when initializing a tasking plan, and check it when validating an existing record. This allows the assignment edit form to save things like name/description while considering the due date as untouched. If they change the due date during edit, normal validation will still occur.
- Only render active periods to be selected in the assignment builder.
- Deep clone the task plan when opening the assignment edit modal. This is to prevent the UI from immediately reflecting potentially temp changes because of computed values.
> Wrm assignment edit fixes

- tutor/src/screens/task/response-validation-ux.js
Fixes case where the response would be re-validated when the student was reviewing past work
> advance immediately if step cannot be updated

- tutor/src/components/error-monitoring/handlers.jsx
Message will start showing after BE PR is merged
Note that this is only a fallback for if the PATCH is sent... it won't prevent the modal from loading. A future PR will prevent the modal from loading by checking for open tasks in the FE.
> show message when grading template cannot be updated

- tutor/specs/integration/assignment-edit.spec.js
- tutor/src/components/error-monitoring/handlers.jsx
- tutor/src/screens/assignment-edit/builder.js
- tutor/src/screens/assignment-edit/details-body.js
- tutor/src/screens/assignment-edit/tasking.js
- tutor/src/screens/assignment-edit/ux.js
- Let formik handle setting the field (name="settings.external_url") via initialValues to prevent uncontrolled/controlled swap issue
- Block the field from being edited once a tasking plan is open.
- Add a handler for the unlikely case someone tries to update the plan when a tasking plan is open, but the front end didn't block it
> fix edit external url

- tutor/src/screens/assignment-edit/ux.js
This preserves the existing constraint while allowing the url to also be changed while creating a new, unsaved assignment that has an open date in the past.
Both screenshots are while creating a new assignment.
Before:
After:
> allow new unsaved assignments to set url when past open

- shared/src/components/question/answer.jsx
- tutor/src/components/homework-questions.js
- tutor/src/screens/assignment-review/overview.js
- tutor/src/screens/assignment-review/table-elements.js
- Fix the alignment of preview letter and answer
Before: 
After:
- Fix the student name in response to match baseline of response text.
- Don't render bottom border and margin for the last response.
Before:
After:
- Improve the alignment and margins of the response letters
Before:
After:
- Fix a regression with the scores table cells not being vertically-aligned due to a strange render issue with child flex box not being allowed to stretch to full-heigth inside the `display: table-cell`. `vertical-align: middle` doesn't seem like it should be needed and isn't ideal, but seems safe and gets it working quickly.
Before:
After:
> Fix some visual things

- tutor/specs/integration/assignment-review.spec.js
- tutor/specs/integration/teacher-gradebook.spec.js
- tutor/src/screens/teacher-gradebook/aggregate-result-cell.js
- tutor/src/screens/teacher-gradebook/min-max-result-cell.js
- tutor/src/screens/teacher-gradebook/settings-btn.js
- tutor/src/screens/teacher-gradebook/task-result-cell.js
- tutor/src/screens/teacher-gradebook/ux.js
Per https://github.com/openstax/tutor/issues/1057
Changes:
* the default display of gradebook to be percents
* Renames option to display percents to be "display as points"
* removes the "Arrange columns by points" option
> remove 'Arrange columns by points', use percents

- tutor/src/screens/assignment-review/overview.js
- Fix the Grade Answers flag displaying "0 NEW" when there aren't any remaining. (Long-term, maybe it should display the "Regrade" link instead, but the documentation needs to be double-checked.)
- Use `grader_points` and `grader_comments` instead of `published_points` and `published_comments` in the Submission Overview responses.
> Grade responses fixes

- tutor/src/screens/teacher-dashboard/sidebar.js
Fixes the alignment and adds some padding to make it an easier target to click/tap.
The wrapper shouldn't be necessary but I was having issues with styled-components not attaching to the TutorLink.
> fix the alignment of grading templates link

- tutor/src/models/task-plans/teacher/scores.js
- tutor/src/screens/assignment-review/homework-scores.js
In cases were the BE doesn't send `total_points` and `total_fraction` (due to extension or not due yet) we need to display `---`.
> Fix NaN after granting extension

- tutor/src/models/grading/templates.js
- tutor/src/screens/grading-templates/index.js
- tutor/src/screens/grading-templates/modals.jsx
Replaces `has_task_plans` with `has_open_task_plans`
> allow editing templates as long as task plans are not open

- tutor/src/screens/task/step/instructions.js
"Score for auto-graded questions (MCQs, 2-step questions)" becomes "Score for reading questions"
> simplify reading instructions for students

- tutor/src/models/task-plans/teacher/plan.js
Otherwise the BE may complain if the points
have changed from 1.0 to 1 due to how JS handles floats
Fixes bug identified in https://github.com/openstax/tutor/issues/1128
> ommit settings if task cannot be edited

- tutor/src/screens/task/response-validation-ux.js
- tutor/src/screens/task/step/exercise-free-response.js
Would happen because course wasn't set on response-validation-ux, but that code was only checked when re-editing a WRM question
> Fix isTeacher of 'undefined' bug

- tutor/src/screens/teacher-gradebook/task-result-cell.js
nil means the teacher shouldn't see the score yet
Fixes https://github.com/openstax/tutor/issues/1134
> Display --- when task feedback should be hidden

- tutor/src/screens/assignment-edit/tasking.js
Skip `onGradingTemplateUpdate` if `gradingTemplate` isn't available. This fixes an error that is throw when changing the open/due dates in External and Event types.
> fix external event date change

- tutor/src/models/student-tasks/step.js
The Media store holds html content so it can be used in the media popups.  reading steps weren't being added to it, causing the popups not to show up
> add reading content to flux media store

- tutor/resources/styles/book-content/base.scss
Content has added a 'tutor-textheavy' class to identify them
Fixes https://github.com/openstax/tutor/issues/777
before:
after:
> limit width of 1st column on "text tables"

- tutor/specs/helpers/time-mock.js
- tutor/specs/helpers/time.spec.js
- tutor/specs/screens/student-dashboard/__snapshots__/dashboard.spec.jsx.snap
- tutor/specs/screens/student-dashboard/dashboard.spec.jsx
- tutor/specs/screens/student-dashboard/event-row.spec.jsx
- tutor/specs/screens/student-dashboard/homework-row.spec.jsx
- Fixes the new failures that came from `tz.guess()` being used, should now always return 'America/Chicago'
- Fix a couple tests that only I've experienced as the only Pacific dev 😛 so now the test syncs to Alaska tz instead of Pacific
> Fix timezone tests

- tutor/src/components/tabs.jsx
- tutor/src/screens/assignment-review/index.js
Review index component was not waiting for the scores to be fetched so it will always render the page with just one tab.
> wait for scores to be fetched before checking if tab is available

- tutor/specs/components/__snapshots__/date-time-input.spec.js.snap
- tutor/specs/factories/teacher-task-plan.js
- tutor/specs/integration/assignment-edit.spec.js
- tutor/specs/models/task-plans/teacher/tasking.spec.js
- tutor/src/components/date-time-input.js
- tutor/src/models/course.js
- tutor/src/models/task-plans/teacher/tasking.js
- tutor/src/screens/assignment-edit/tasking.js
- In the calendar, disable the dates before the course start date
- In the calendar, disable the dates after the course end date
- Allow users to select any enabled date from the calendar
- If the date/time combination is not valid then show an error (See expected behavior above) Invision Screens for error messages: https://invis.io/V6XZPQ74ZBM
- If any of the day and time is not valid then disable the Save button
- When you edit assignment details for an assignment that is past due (or past close), the error state does not show up on the due date (or close date) unless the user makes a date edit
> Assignment dates

- exercises/specs/.eslintrc.js
- shared/specs/.eslintrc.js
- tutor/specs/.eslintrc.js
- tutor/specs/acceptance/.eslintrc.js
- tutor/specs/models/courses/offerings/previews.spec.js
- tutor/specs/screens/task/__snapshots__/event.spec.js.snap
- tutor/specs/screens/task/__snapshots__/exercise-task-header.spec.js.snap
- tutor/specs/screens/task/__snapshots__/external.spec.js.snap
- tutor/specs/screens/task/__snapshots__/homework.spec.js.snap
- tutor/specs/screens/task/__snapshots__/milestones.spec.js.snap
- tutor/specs/screens/task/__snapshots__/progress.spec.js.snap
- tutor/specs/screens/task/__snapshots__/reading.spec.js.snap
- tutor/specs/screens/task/steps/__snapshots__/exercise.spec.js.snap
- tutor/specs/screens/task/steps/__snapshots__/nudge-message.spec.js.snap
- tutor/src/models/course.js
- tutor/src/models/course/offerings/previews.js
- tutor/src/models/courses-map.js
- Only reuse active preview courses with the correct offering id that the user is teaching and are marked as reusable
- Added specs
https://github.com/openstax/tutor-server/pull/2136
> Conditions for reusing preview courses

- tutor/src/components/book-part-title.js
Prevents the elements can run together when constructing the label
before:
after:
> add margins to label and chapter-section

- tutor/src/screens/teacher-gradebook/table.js
I think I missed this when fixing the headings. Should make the result cells match the heading order (min first, max below.)
Before:
After:
> fix ordering of min/max rows to match the heading

- tutor/src/screens/teacher-gradebook/student-data-sorter.js
- tutor/src/screens/teacher-gradebook/ux.js
This resolves an issue with the gradebook columns becoming disordered when a student was granted an extension, as that causes the task `due_at` to be the extension date, not the original date. The BE already puts these into the correct order by default, so using that is a quick short term fix until we do a larger refactoring to use tasking plan ids to build the table.
> use default heading and result ordering from the BE

- tutor/specs/models/courses/offerings/previews.spec.js
- tutor/src/models/course/offerings/previews.js
- tutor/src/models/courses-map.js
previewCourse() now returns courses with should_reuse_preview: false (but prefers courses with should_reuse_preview: true) so we can still redirect to outdated courses if the API returns them.
isCreated() now returns true only for courses with should_reuse_preview: true so the FE will request a new course if should_reuse_preview is false.
> Fixed preview courses with should_reuse_preview: false

- tutor/specs/helpers/scores.spec.js
- tutor/specs/helpers/string.spec.js
- tutor/specs/screens/student-dashboard/__snapshots__/dashboard.spec.jsx.snap
- tutor/src/components/task-progress.js
- tutor/src/helpers/scores.js
- tutor/src/helpers/string.js
- tutor/src/models/scores/task-result.js
- tutor/src/models/task-plans/student/task.js
- tutor/src/models/task-plans/teacher/scores.js
- tutor/src/screens/assignment-grade/answer.js
- tutor/src/screens/assignment-grade/question.js
- tutor/src/screens/assignment-review/details.js
- tutor/src/screens/assignment-review/external-scores.js
- tutor/src/screens/assignment-review/homework-scores.js
- tutor/src/screens/assignment-review/overview.js
- tutor/src/screens/assignment-review/reading-scores.js
- tutor/src/screens/pre-wrm-scores-report/correctness-value.jsx
- tutor/src/screens/student-gradebook/table.js
- tutor/src/screens/task/step/instructions.js
- tutor/src/screens/task/step/wrq-status.js
- tutor/src/screens/teacher-gradebook/aggregate-result-cell.js
- tutor/src/screens/teacher-gradebook/min-max-result-cell.js
- tutor/src/screens/teacher-gradebook/table.js
- tutor/src/screens/teacher-gradebook/task-result-cell.js
- tutor/src/screens/teacher-gradebook/ux.js
- Moved all calculations for scores/points displays into a dedicated helper to help testability and isolate from any unrelated refactorings.
- Moved UNWORKED into the ScoresHelper.
`ScoresHelper.formatPoints(points)`
Formats points to have increased precision to 2 decimal places using the following rule: A minimum of 1, a maximum of 2, unless '0.0' (special case it as '0'.) Drop insignificant trailing 0s like in '.50'.
I used`Intl.NumberFormat` as it seemed to give us all that in a simple way (besides the 0 case.)
Value | Display
---- | ----
0.0 | 0
1 | 1.0
0.50 | 0.5
0.559 | 0.56
OLD:
NEW:
OLD:
NEW:
OLD:
NEW:
OLD:
NEW:
OLD | NEW
--- | ---
OLD | NEW
--- | ---
Our normal `asPercent` function doesn't work for the higher precision numbers we're sending down like `0.5549999999999999`. To …
> Increase displayed precision of points and scores

- exercises/src/components/tags/aplo.js
- exercises/src/components/tags/lo.jsx
Fixes https://github.com/openstax/tutor-js/pull/3176 which got rebased out somehow
> support either - or . as LO separator

- tutor/src/models/scores/task-result.js
- tutor/src/screens/pre-wrm-scores-report/correctness-value.jsx
Reverting this change (for Pre-WRM scores only) keeps old course scores the same.
> use lower precision for Pre-WRM scores

- shared/src/components/icon.js
- tutor/specs/helpers/scores.spec.js
- tutor/src/components/dropped-question.js
- tutor/src/components/icons/extension.js
- tutor/src/helpers/scores.js
- tutor/src/models/task-plans/teacher/scores.js
- tutor/src/screens/assignment-review/homework-scores.js
- tutor/src/screens/assignment-review/reading-scores.js
- tutor/src/screens/assignment-review/result-tooltip.js
- tutor/src/screens/assignment-review/table-elements.js
- tutor/src/screens/assignment-review/ux.js
- Adds datetime information to the extension tooltip
- Adds "UG" to mean Ungraded, "---" now only refers to not yet unattempted
- Adds red clock icon for responses that were submitted late
- Adds gray cell background for unattempted questions that were auto-assigned 0
- Updates table legend to include the above changes
- Show available points when there are different numbers of Tutor-assigned questions
- Improves table visuals by using border-collapse and cleaning up inconsistencies
> update homework scores table with detailed states and icons [Needs BE]

- tutor/src/models/task-plans/teacher/plan.js
- tutor/src/screens/teacher-dashboard/plan-label.jsx
- Fixes new flag (ex. "3 NEW") on the dashboard showing up before the plan is past due (checks for the earliest due date for the past due check.)
- Fixes an issue with `dateRanges` returning an incorrect due time of `11:59` regardless of the correct value (locally `3:50`). I suspect this is an issue with the date time initialization on that field, and for some reason computed doesn't see that the value has changed. Removing the computed here fixes the issue, I don't think there's any real side effect here besides a very minor performance hit.
Will need a backend change to start filtering `ungraded_step_count` to only include past due.
> Fix new flag before due

- tutor/specs/components/responsive.spec.js
- tutor/specs/screens/student-dashboard/__snapshots__/dashboard.spec.jsx.snap
- tutor/specs/screens/student-dashboard/__snapshots__/event-row.spec.jsx.snap
- tutor/specs/screens/student-dashboard/__snapshots__/homework-row.spec.jsx.snap
- tutor/src/components/responsive.js
- tutor/src/screens/student-gradebook/index.js
- tutor/src/screens/student-gradebook/table.js
- tutor/src/theme.js
- Updated the breakpoints to match the doc
- Changed the query for `desktop` to check `min-width` so styles applied to desktop will also apply to anything larger.
- Make the student scores responsive. Tried to keep duplication to a minimum, but did need to break out the responsive component for the different cell presentation, and it was a cinch to use, well done @nathanstitt!
------- | ------- | -------
> Responsive student scores

- tutor/specs/components/my-courses.spec.jsx
- tutor/src/components/my-courses/index.jsx
- tutor/src/models/user/menu.js
If a verified instructor is ONLY a student in a single course,
they were automatically redirected to it and skip the "my courses" listing.
Then in the course the "create a course" menu option was hidden
because they're a student in that course.
> Don't lock instructor to student course

- tutor/src/components/late-points-info.js
Uses ScoresHelper to increase the precision of the popup on the summary table for a student.
> use ScoresHelper to format points and late penalty

- tutor/resources/styles/components/date-time-input.scss
There's a difference in overflow implementation with flexbox between Firefox and Chrome: https://bugzilla.mozilla.org/show_bug.cgi?id=1108514#c2
I can't fix this with the `min-height: 0` trick because we don't easily control the html render coming from the date time component.
I'm targeting Firefox with `supports` instead of using `data-browser` because it's set on the wrapper div not the body (this popup is attached to body.)
> fix hour scroll not working in firefox

- tutor/resources/styles/book-content/base.scss
- tutor/specs/screens/task/steps/__snapshots__/end.spec.js.snap
- tutor/specs/screens/task/steps/__snapshots__/html-content.spec.js.snap
- tutor/specs/screens/task/steps/__snapshots__/reading.spec.js.snap
- tutor/src/components/icons/pagination.js
- tutor/src/screens/task/step/card.js
- Don't render the table scrollbar unless overflow occurs
- Fix an issue with the desktop video and interactive badge not having a right margin
Before | After
------------ | -------------
> Reading fixes

- shared/src/components/icon.js
- tutor/resources/styles/components/top-nav-bar.scss
- tutor/resources/styles/components/top-nav-bar/drop-down-menu.scss
- tutor/specs/components/__snapshots__/app.spec.jsx.snap
- tutor/specs/components/__snapshots__/tutor-layout.spec.js.snap
- tutor/specs/components/navbar/__snapshots__/actions-menu.spec.jsx.snap
- tutor/specs/models/user/__snapshots__/menu.spec.js.snap
- tutor/src/components/navbar/actions-menu.jsx
- tutor/src/components/navbar/menus.js
- tutor/src/components/navbar/support-menu.jsx
- tutor/src/components/navbar/user-menu.jsx
- tutor/src/components/tutor-layout.js
- tutor/src/models/user/menu.js
- Collapse separate menus into a single one at mobile size
- Change the displayed icons and ordering.
For example:
Old: 
New:
------------ | ------------- | -------------
Teacher side isn't specifically targeted for mobile improvements, but since they use a shared menu, here's how that looks:
Mobile | Desktop
------------ | -------------
> make navbar responsive

- tutor/specs/screens/student-dashboard/__snapshots__/dashboard.spec.jsx.snap
- tutor/specs/screens/student-dashboard/__snapshots__/event-row.spec.jsx.snap
- tutor/specs/screens/student-dashboard/__snapshots__/homework-row.spec.jsx.snap
- tutor/src/components/time.js
- tutor/src/helpers/time.js
- tutor/src/screens/task/exercise-task-header.js
- tutor/src/screens/task/reading-navbar.js
- tutor/src/screens/task/step/instructions.js
- tutor/src/screens/task/task-info.js
Loading the entire TZ set just for abbreviations is very large, and the browser can give us comprehensive info, so we've decided to change how we display time zone data on the student side.
- Remove the abbreviated time zone in the format
- Display detailed time info on hover, getting the offset from moment formatting ("Z") and the timezone name from `Intl.DateTimeFormat().resolvedOptions().timeZone`
This should also resolve the issue with times displaying as UTC when viewed with a timezone setting we don't have loaded.
Examples:
> Move TZ info to tooltips on the student side

- tutor/specs/components/__snapshots__/app.spec.jsx.snap
- tutor/specs/components/__snapshots__/my-courses.spec.jsx.snap
- tutor/specs/components/__snapshots__/tutor-layout.spec.js.snap
- tutor/src/components/my-courses/listings.jsx
- tutor/src/components/tutor-layout.js
Just some tiny tweaks here to the padding. Only unusual thing here is to special-case the mobile padding for the container and navbar to 16px to match the design doc.
Tablet:
Mobile:
> change padding of course listing on tablet and mobile

- tutor/resources/styles/components/top-nav-bar.scss
- Fix scroll behavior
- Fix menu height causing the menu to go behind iOS footer navbar
> fix mobile menu scroll and fix it being hidden behind ios navbar

- tutor/resources/styles/components/top-nav-bar.scss
- tutor/resources/styles/tutor.scss
- tutor/src/components/navbar/menus.js
- tutor/src/helpers/dom.js
- Add border between menu items (on desktop + tablet as well.)
- Fix icon sizes 
- Add helper to hide body overflow, fixes an issue with the mobile menu scrolling content underneath.
- Put the support menu at the bottom on mobile
- Prevent dropdown-dividers from stacking for some edge render cases.
> Fix mobile menu

- shared/specs/model/notifications.spec.js
- shared/src/model/notifications.js
`buildCallbackHandlers` in helpers/notifications has this:
```
missing_student_id: {
onAdd({ course }) {
return history.push(
Router.makePathname('changeStudentId', { courseId: course.id })
);
},
```
which may also not be needed?
> remove missing student id from notifications

- tutor/resources/styles/components/modals/terms.scss
> text align center the term title

- tutor/src/components/navbar/student-payment-bar.js
> change mobile payment bar z-index to be lower than the top navbar

- tutor/resources/styles/components/info-page.scss
- tutor/specs/components/__snapshots__/content-page.spec.js.snap
- tutor/specs/components/content-page.spec.js
- tutor/specs/components/payments/__snapshots__/manage.spec.jsx.snap
- tutor/src/components/accessibility-statement.jsx
- tutor/src/components/content-page.js
- tutor/src/components/header.js
- tutor/src/screens/student-gradebook/index.js
- tutor/src/screens/task/exercise-task-header.js
- Refactor `Header` component to be more generic and reusable, move HW task header styles into `ExercisesTaskHeader`
- Make Accessibility Statement page responsive
Desktop | Tablet | Mobile
------------ | ------------- | -------------
Changing the Header to be reusable creates some changes for a few screen headers:
Old | New
------------ | -------------
> Responsive accessibility statement

- tutor/specs/screens/teacher-dashboard/sidebar.spec.js
- tutor/src/helpers/string.js
- tutor/src/screens/assignment-edit/builder.js
- tutor/src/screens/assignment-edit/controls.js
- tutor/src/screens/assignment-edit/delete-btn.js
- tutor/src/screens/assignment-edit/details-body.js
- tutor/src/screens/assignment-edit/index.js
- tutor/src/screens/assignment-edit/ux.js
- tutor/src/screens/teacher-dashboard/add-menu.jsx
- tutor/src/screens/teacher-dashboard/styles/sidebar.scss
- In events and external assignment builder, the 'Add Details' label should be left-aligned with the text below.
- When adding an event, in the 'Add details' step, the label for the first text box should be Event name (and not Assignment name)
- When adding an External assignment, the page header in the builder should be Add external assignment
- When reviewing a draft assignment, the Delete button should be a white default button (like the 'Cancel' button next to it)
> minor fixes in add details step

- tutor/src/models/app.js
- tutor/src/models/app/pulse-insights.js
- tutor/src/models/user.js
reports data:
```
{
"role": "instructor",   // uses "isProbablyTeacher" which combines can_create_courses and self reported role.  It's what tours use
"is_new_user": true, // true if no past courses
"is_test_user": true, // from admin settings
"has_viewed_preview": false, // true if they have preview courses associated 
"courses": [
{
"subject": "biology_2e",  // this is the appearance code
"type": "real",  // or preview
"role": "teacher", // or student
"active": true,  // or preview
"enrollment": 17, // how many students are a member. if user is a student it will be -1 since we don't know
"enrollment_type": "links", // or las
"cost": false. // or true 
},
{
"subject": "college_physics",
"type": "real",
"role": "student",
"active": true,
"enrollment": -1,
"enrollment_type": "links", …
```
> add metrics to pulse insight data

- webpack.config.js
Rails sprockets gem will remove a manifest.json file
> rename manifest.json to assets.json

- .github/workflows/build.yml
CloudFront passes the path to s3 so to load `/assets/some.file` it's way easier if `some.file` is inside the `assets` dir in the bucket.
> Put files inside the "assets" dir in the s3 bucket

- shared/src/components/notifications/email.js
- tutor/resources/styles/global/notifications-bar.scss
Wasn't able to test locally, but it should look like this on mobile:
> fix the size of verify email on mobile

- tutor/resources/styles/components/modals/onboarding.scss
Small css changes for the free trial ended nag.
> add small heading changes in free trial activated and ended nag

- shared/resources/styles/components/notifications-bar.scss
- shared/src/components/notifications/email.js
- tutor/resources/styles/global/notifications-bar.scss
Fixes some mobile layout issues when displaying the verify pin text, and some small button and sizing changes to better work on mobile. The bar is now 8px taller than the invision spec, but this helps to visually contain the text when an error message + pin verify are both rendered as a stack. Adding `.content` is needed to adjust flexbox styles without affecting the dismiss button.
> Fix verify email

- tutor/src/components/task-progress.js
When a student submits an answer, visually mark the step as completed with a grey background in the overview table.
> mark completed steps with a grey background

- tutor/specs/models/user.spec.js
- tutor/src/models/user.js
The new structure will look like:
```
course_enrollment_types: "links"
course_roles: "teacher"
course_subjects: "college_physics;biology_2e;intro_sociology;ap_physics"
course_types: "real"
has_per_cost_course: false
has_viewed_preview: false
is_new_user: false
is_test_user: true
max_course_enrollment: 6
role: "instructor"
```
> flatten user metrics

- .github/workflows/build.yml
CloudFront will cache the files without the header, but if we want the browser to cache them too then the metadata must be set in S3
> Added Cache-Control to S3 files and exercises-js build task

- shared/resources/styles/components/question.scss
- tutor/src/screens/task/step/exercise-question.js
Other screens can be more compact and don't need lines to separate answers
Task screen:
Teacher review screen goes from:
To:
> Only display lines and extra spacing for tasks

- shared/src/components/exercise-badges/index.jsx
Will make it easier to view on mobile
> make entire badge the tooltip target

- tutor/specs/components/__snapshots__/radio-input.spec.jsx.snap
- tutor/src/components/radio-input.jsx
> use padding instead of margin for section selector on HW edit

- tutor/src/screens/assignment-review/grading-block.js
Set a minimum width + increase it based on how many digits are being displayed. Fixes a bug where a large class size to task completion ratio would cause the completion bar to not be wide enough.
> add min width to progress bar based on char display length

- tutor/resources/styles/components/modals/onboarding.scss
This way it has enough room to display buttons.
Goes along with https://github.com/openstax/ospayments/pull/221
> fill screen with payments modal on mobile

- tutor/src/components/late-points-info.js
- tutor/src/components/task-progress.js
We decided that it's clearer to the student to always see "Late penalty" even when the grading template has late work set to "Not accepted".
Also fixes an issue with the popover flashing on and off in Firefox by turning off pointer events on the popover.
> Rename not accepted to late work penalty

- shared/src/components/buttons/async-button.js
We don't rely on that in any FE code and it's surprising when it does occur like on the recent score export slowness
It's better to just keep spinning since the job hasn't yet failed
> remove auto timeout from async button

- tutor/resources/styles/book-content/splash-image.scss
> dispay `splash-video` as full width

- shared/src/components/exercise-identifier-link.js
> strip html from errata link

- tutor/src/models/student-tasks/step.js
https://sentry.cnx.org/openstax/tutor/issues/823167 occurs when we attempt to read from content when it hasn't yet fetched
> guard against content being undefined

- tutor/specs/integration/assignment-review.spec.js
- tutor/specs/screens/question-library/dashboard.spec.jsx
- tutor/src/components/add-edit-question/index.js
- tutor/src/components/add-edit-question/terms-of-use.js
- tutor/src/components/add-edit-question/ux.js
- tutor/src/screens/question-library/exercise-controls.jsx
- tutor/src/screens/question-library/exercises-display.jsx
- tutor/src/screens/question-library/exercises-footer.js
New footer in QL with terms of use for creating/editing a question:
> Ql terms of use footer

- tutor/src/components/add-edit-question/form/shared.js
- tutor/src/components/editor/index.js
It breaks responsive embed sizes
Before:
after:
> do not render editor pane as flexbox

- tutor/src/components/add-edit-question/form/general.js
- tutor/src/components/add-edit-question/form/shared.js
- tutor/src/components/add-edit-question/form/tags/index.js
- tutor/src/components/add-edit-question/index.js
- tutor/src/components/add-edit-question/ux.js
New 'Learn more' link added for both DOK and Blooms popover info in the add/edit question form.
> add link to the bloom and dk popover info

- package.json
- yarn.lock
This commit fixed the issue: https://github.com/openstax/perry-white/commit/8c62ecc778aeb867cf4cdb92bde9468a9b78edd7
Tutor renders the editor inside a bootstrap modal which has a handler that grabs the focus back whenever it's lost.  That's an issue for PerryWhite modals that render inside `body` by default.  I'd fixed the math to render inside the editor div, and had to do the same for link
> update perry-white to fix editor link modal focus

- tutor/src/components/add-edit-question/ux.js
When trying to create a WRQ, it shows the feedback tips modal because there is no feedback for a MCQ. It shouldn't show.
> only show feedback tip modal if form is MCQ

- shared/src/model/notifications/pollers.js
do not mutate lastPoll.  momentjs MUST DIE.  we've had so many bugs around accidentally mutating an instance
> fix bug with delayed polling

- tutor/src/screens/assignment-review/reading-scores.js
The extension icon wasn't getting passed the extension object, so the icon would render, but not the dates granted. This seems to have only affected the reading assignment table not homework.
Before:
After:
> fix extension icon in a reading assignment not showing dates

- tutor/src/components/add-edit-question/ux.js
CASE:
add/edit modal is opened -> question is filled without feedback -> try to publish -> show feedback tip -> feedback tip is closed -> tries to publish again -> do not show the feedback tip.
*If the user opens the add/edit modal again then the above logic is applied.
> only show the feedback tip modal once per question building

- tutor/src/components/exercises/details.jsx
- tutor/src/models/exercises.js
Otherwise details view gets out of order when the section changes
> sort exercises first by chapter-section, then user

- tutor/src/components/exercises/details.jsx
Missed another `questionType` prop to show the correct answer in the exercise details
> add the question type in exercise details

- tutor/src/components/add-edit-question/form/question.js
- tutor/src/components/add-edit-question/modals.js
- tutor/src/components/add-edit-question/ux.js
`@observable exercise` was deleted. This PR creates an `observable context` that tracks if the exercise that is being edited has a `context`.
> add-edit-context-fix

- tutor/specs/components/app.spec.jsx
- tutor/src/components/terms-modal.jsx
- tutor/src/models/user/terms.js
They weren't being fetched completely before which caused the terms modal to display with empty terms
> fetch terms when modal is showing

- .github/workflows/build.yml
- webpack.config.js
Merge at the same time as: https://github.com/openstax/tutor-deployment/pull/590
So CloudFront doesn't have to try both S3 and BE and we can actually use the replica bucket.
> Change the assets url to dist

- tutor/src/components/add-edit-question/ux.js
Update some of the inline error logic for options.
1. If the user enters two options, take out the inline error.
2. Check also if the user enters an option in option 3 or higher. It should show an inline error in option 1 if there is only 1 option.
3. Show only inline error in option 2 if option 1 is the only filled.
> fix add edit options inline error

- tutor/src/components/add-edit-question/ux.js
keep track of the feedback tip after the instructor clicks on the publish question button and stay in the modal.
> fix-feedback-tip-publish

- tutor/src/screens/grading-templates/index.js
Add 'https://openstax.secure.force.com/help/articles/FAQ/What-are-Grading-templates' as a "Learn More" link for the grading templates.
> add grading template learn more link

- tutor/resources/styles/book-content/base.scss
Thanks to @lwtchu for listening while I floundered on this for a bit 🤣 
changes:
to be:
> add margin between index items title and link

- tutor/scripts/test-server/backend.js
- tutor/scripts/test-server/backend/course-roster.js
- tutor/specs/e2e/course-roster.e2e.js
- tutor/specs/factories/course-roster.js
- tutor/specs/factories/user.js
- tutor/src/screens/course-roster/index.jsx
- tutor/src/screens/course-roster/remove-teacher.jsx
- tutor/src/screens/course-roster/teacher-roster.jsx
Previously they'd get an error when the course roster re-rendered and the current user was no longer an instructor
> Fix teacher removing themselves from course

- tutor/specs/components/my-courses.spec.jsx
- tutor/specs/models/user.spec.js
- tutor/src/components/my-courses/index.jsx
- tutor/src/models/user.js
The school type can be delayed, causing teachers to incorrectly see the "must be 4 year institution" message.
To work around that, if a teacher can't create courses for any reason and their account is newer than 1 day, we always show the "Pending Verification" message
> Display pending verification msg to locked out teachers for 1 day

- tutor/specs/components/my-courses.spec.jsx
- tutor/src/components/my-courses/index.jsx
While rare, a student can signup directly and not have any courses.  We only want to show the pending verification message to instructors
> do not display "pending verification" to students

- package.json
- yarn.lock
The locked version of playwright is incompatible with macOS 11.2, this bumps the version to one that is compatible.
> update playwright version

- tutor/src/screens/my-courses/dashboard/index.tsx
- tutor/src/screens/my-courses/dashboard/offering-block.tsx
- tutor/src/screens/my-courses/dashboard/use-displayed-offerings.tsx
- tutor/src/store/courses.ts
Disabled course item cards when in edit mode.
Persist the order of the offerings after a refresh.
> Manage subjects bug

- tutor/src/screens/course-roster/index.jsx
- tutor/src/screens/course-roster/styles.scss
Just a small UI change in the course roster screen.
> add new header to the course-roster

- tutor/scripts/test-server/backend/bootstrap.js
- tutor/specs/e2e/my-courses.e2e.ts
- tutor/specs/e2e/preview-courses.e2e.js
- tutor/src/screens/my-courses/new-teacher.tsx
- Add a factory offering that doesn't have an already created course — needed for the side panel to display.
- Fix some time outs and a bug with using `isEmpty` that was causing some failed expectations. Footer was refactored into a component while working on debugging that.
> fix preview course tests

- tutor/specs/e2e/my-courses.e2e.ts
- tutor/src/screens/my-courses/index.tsx
- tutor/src/screens/my-courses/new-teacher.tsx
We decided to clear the selected subject when typing a suggestion, and clear the suggestion when selecting a subject, so that only 1 primary button will be visible on screen at any time.
> clear subject when typing a suggestion

- tutor/specs/e2e/my-courses.e2e.ts
Remove the timeout, the default behavior does what we want
> remove timeout when expecting teacher screen selector

- tutor/src/models/subject-order.ts
- tutor/src/screens/my-courses/new-teacher.tsx
Fixes a bug where the subjects in the onboarding screen weren't displaying in the specific order we'd like, and also ensures the offerings within the subject are alphabetical.
> sort subjects by a specific order, sort offerings within subject alphabetically

- tutor/resources/styles/components/my-courses.scss
- tutor/src/screens/my-courses/dashboard/offering-block.tsx
- tutor/src/screens/my-courses/dashboard/preview-course.tsx
- Move preview card to end of list if it's in Resouces tab
- Make the entire preview card clickable
- Use a larger font size for description text
> move preview card to end, fix clickable area and font size

- tutor/specs/screens/new-course/ux.spec.js
- tutor/src/screens/new-course/ux.js
Moves to the term step if there is an `offeringId` preselected.
> Create course wizard bug

- tutor/src/screens/performance-forecast/section.js
Fixes HTML showing up on hover over the title. `section.title` is the HTML here.
> Remove title attribute from PF sections

- configs/test/jest.config.json
- tutor/specs/store/courses.spec.ts
- tutor/src/store/courses.ts
Previously it was returning unusable preview courses
> Use longest lasting preview course that is not expired

- tutor/src/helpers/contact.js
The `yarn lint` indentation rules for line continuations are weird. Example error email:
> Added user UUID, role and timestamp to error email

- tutor/resources/styles/components/my-courses.scss
- tutor/src/screens/my-courses/dashboard/preview-course.tsx
Just fixing css issue. I changed the name of a css class and it modified a little bit the course actions of the cards.
Current:
Fix:
> fix a regression by updating the class name of the preview course

- tutor/resources/styles/global/tooltip.scss
- tutor/src/components/buttons/save-practice.js
In a MPQ, the tooltip info runs out of space on the right when the browser window is small.
Moving the tooltip to the bottom fix this.
> MPP: move tooltip to bottom

- webpack.config.js
Watching node_modules causes consistent 20-40% CPU use while idling. It's possible this is only an issue that started with macOS Big Sur. From https://webpack.js.org/configuration/watch/#watchoptionsignored:
> For some systems, watching many files can result in a lot of CPU or memory usage.
> ignore node_modules to fix high idle cpu

- tutor/specs/e2e/add-edit-question.e2e.js
- tutor/specs/screens/question-library/dashboard.spec.jsx
- tutor/specs/screens/question-library/index.spec.jsx
- tutor/src/components/add-edit-question/form/index.js
- tutor/src/components/add-edit-question/index.js
- tutor/src/components/add-edit-question/modals.js
- tutor/src/components/add-edit-question/ux.js
- tutor/src/screens/question-library/dashboard.jsx
- tutor/src/screens/question-library/index.jsx
- tutor/src/screens/question-library/sections-chooser.jsx
- Store editor field state in localStorage. MobX's `autorun` handles firing the autosave when the observables change. A delay might be desirable in the future in case events need to debounce, but since it only occurs on blur or checking boxes, it seems to be performant.
- Set pageIds as a query param so that refreshing the page will put you on the same screen
- Fix a bug where if you started filling out MCQ options, but then switched the tab to Written-response and published, it would create the question as an MCQ, due to it still sending the `options` in the form.
AUTOSAVE_TTL is set to 15 minutes and used to help expired `signed_id`s from being used on uploaded images. AUTOSAVE_VERSION is used in case the form fields ever change significantly. In both cases, the validity (and …
> Add an autosave to the question library editor

- tutor/resources/styles/components/date-time-input.scss
- tutor/specs/e2e/teacher-gradebook.e2e.ts
It seems FireFox at some point in the last 6 months changed to match Chrome's behavior, so this scroll fix is no longer needed. Removing it fixes the scroll behavior.
> remove outdated scroll fix

- shared/resources/styles/components/exercise-preview/index.scss
- tutor/src/components/homework-questions.js
It's harder to see on the single line example, but the alignment is now on the baseline, so the answer letter baseline should match the answer text. For the checkmark alignment I just went with what felt right, easy to tweak.
This also fixes a FireFox-only bug in Submission Overview with the letter getting squashed when the adjacent text was long.
Before:
After:
Before:
After:
> Fix answer alignment

- shared/resources/styles/components/exercise-preview/index.scss
This fixes the font size of the preview text inside the exercises app. Using px here isn't ideal but refactoring the CSS is going to be a little more time intensive. The issue is that the base answer table font size in Exercises is set to 17px, so using rem here is an issue. I think longer term we should probably make Exercises use the same 10px font size so rems just work between shared components.
The Exercises preview is below. In Tutor there is no visual change due to 1.4rem == 14px.
> set feedback font size to px

- exercises/resources/styles/tags.scss
The card 1624 was for only CNX Feature, but it seems like we should do this for the CNX Module tag as well.
> allow deleting feature and module tags in exercises

- tutor/specs/factories/task-scores.js
These fields were incorrectly calculated and they are no longer sent by the backend.
We can fix the code and add them back if needed.
> Removed num_questions_dropped and points_dropped

- tutor/src/screens/question-library/dashboard.jsx
I think I missed this during a merge conflict, this should fix the pageIds not being set in the url when changing Question Library screens (like `http://localhost:3000/course/37/questions?pageIds=224%2C225%2C226`)
> fix pageids not being set when clicking Show Questions

- tutor/specs/components/tabs.spec.js
- tutor/src/components/tabs.jsx
Tabs can also be already rendered content
fixes bug introduced by https://github.com/openstax/tutor-js/commit/5c84c681ea6b9691212a4facd6b0ea300a2acbe1#diff-3a83cdd9fa8c2b67379e55b77cd3d446398446926613b5a8c0f88cd693d17d14
> only dasherize if tab is a string

- shared/specs/model/model.spec.ts
- shared/src/model.ts
- tutor/src/components/notes.js
- tutor/src/components/notes/edit-box.jsx
- tutor/src/components/notes/sidebar-buttons.jsx
Fixes updating existing notes that were returning true for `isNew` even though they had integer IDs, also fixes some MobX-related warnings.
> Fix notes/isNew

- tutor/src/components/homework-questions.js
- tutor/src/models/task-plans/teacher/scores.ts
Added gray background and blue triangle when the question is dropped. @nathanstitt Great idea to take size to factor the rem scale! Worked out really nicely 👍
> update question cards to show tooltip and color when dropped

- tutor/src/components/tours/custom/drop-any.tsx
- tutor/src/components/tours/step.js
Makes it so that when the screen size is very large, the arrows don't separate from the modal body.
> tour - fix some visual glitches that can occur when the screen size is very large

- tutor/src/models/grading/templates.ts
`task_plan_type` wasn't getting set, and `defaults` doesn't work anymore now that the fields have default values for TS.
> fix task_plan_type and initial values not getting assigned

- tutor/src/api.ts
- tutor/src/models/course/student.ts
- tutor/src/models/course/teacher.ts
- tutor/src/screens/course-roster/change-period.jsx
`stacked` was throwing an error and doesn't seem to be a prop on Nav anymore, so I removed it.
> fix dropping and changing sections in roster

- exercises/specs/components/tags/aplo.spec.js
- exercises/src/components/tags/aplo.jsx
Allows tags for AP Biology and Physics to contain 2 digits before the final period instead of the current 1.
**Examples:**
AP Biology
AP Physics
> allow two digits before final period in AP LO tag

- tutor/src/components/dropped-question.tsx
- tutor/src/models/task-plans/teacher/scores.ts
- tutor/src/screens/assignment-review/homework-scores.js
Need to look at the result and not the heading in that case
> Fixed the tooltip for dropped Tutor questions in scores

- tutor/specs/components/error-monitoring/server-error-message.spec.jsx
- tutor/src/components/error-monitoring/server-error-message.jsx
You can replicate by setting network offline, then switching months on the teacher calendar
> identify fetch failures and show message for them

- tutor/src/screens/my-courses/dashboard/create-course.tsx
No idea why we didn't have this check there already.  maybe it's always been broken?
> only show createCourse block to authorized users

- exercises/specs/components/__snapshots__/exercise.spec.js.snap
- exercises/src/components/exercise/question-format-type.jsx
- exercises/src/components/exercise/question.jsx
- Add a default answer when selecting multiple-choice, as the array count is used to determine if the question is multiple-choice and not open-response format.
- Disable the open-ended option when there are answers
> fix exercise format option switching

- package.json
- tutor/src/helpers/course-enrollment.tsx
- tutor/src/models/course.ts
- tutor/src/models/course/lms.ts
- tutor/src/models/types.ts
- tutor/src/screens/teacher-gradebook/ux.js
- yarn.lock
If a student's dropped before they do anything the `data` array on the student scores will be an array of null:
this commit has the fix:
https://github.com/nathanstitt/modeled-mobx/commit/8d3ef74039c679f150a293ae928a800e985a94e0
> Fix grade book blowing up when dropped student had no work

- shared/src/model/time.ts
- tutor/src/models/task-plans/teacher/plan.ts
- tutor/src/screens/assignment-edit/ux.js
- tutor/src/screens/teacher-dashboard/dashboard.js
- tutor/src/screens/teacher-dashboard/month.js
- tutor/src/screens/teacher-dashboard/past-assignments.jsx
- tutor/src/screens/teacher-dashboard/sidebar.js
I'm not sure why `clonedAttributes` was conditionally returning settings
It happened in this commit https://github.com/openstax/tutor-js/commit/6643bf8957e8df1b0f8932af4e012ba007acb6c2 which was part of the mass conversion. Doesn't seem like something that would have been automatically done though.
> Fix drag-n-drop past task plan onto calendar

- tutor/src/screens/assignment-edit/ux.js
The function was renamed during the `Time` change but it was still calling the old moment one.
> fix calling duration instead of interval

- shared/src/model/time.ts
- tutor/specs/global.d.ts
- tutor/specs/screens/course-settings/__snapshots__/details.spec.tsx.snap
- tutor/specs/screens/course-settings/details.spec.tsx
- tutor/src/screens/course-settings/course-details.js
Same bug as on student dashboard, was using moment to format a Time class 😭
> Fix course details dates

- shared/specs/model/time.spec.ts
- shared/src/model/time.ts
fixes displays like: "6 days 11 hours 37.51176666666667 minutes"
> use whole numbers and read as sentence

- shared/specs/model/time.spec.ts
- shared/src/model/time.ts
Is more compact, most users won't care about the hours/minutes until it's less than 1 day left
> improve humanized, show only most significant duration

- tutor/src/components/error-monitoring/handlers.jsx
This fixes the dialog triggering on every navigation (hideModal clears the errors array). A couple issues remain, however:
- The load animation for the preview course is not canceled (maybe that would be handled by the promise that ends up failing?)
- onOk doesn't seem to actually do anything, only onCancel seems to trigger. If the button's onClick is removed, then the dialog just stays open if you click OK
> Fixed "This Preview isn’t quite ready yet." spam

- tutor/specs/screens/assignment-edit/ux.spec.jsx
- tutor/src/screens/assignment-edit/ux.js
When clicking the calendar to create an assignment, you should go back to that month.
Creating an assignment for the sidebar, however, seems to always default to the current month, so that won't work (but if we want that to change, we can pick a date for sidebar assignments based on the selected month).
> When completing or cancelling assignment creation, send instructor back to selected month

- tutor/specs/screens/new-course/__snapshots__/sociology-3e-nudge.spec.js.snap
- tutor/specs/screens/new-course/sociology-3e-nudge.spec.js
- tutor/src/screens/new-course/index.jsx
- tutor/src/screens/new-course/sociology-3e-nudge.tsx
- tutor/src/screens/new-course/ux.js
Not sure if the message also shows up when cloning courses?
But we can't clone 2e into 3e so redirecting to a new course kind of makes sense in that case.
> Make Upgrade to Sociology 3e message a link to creating a new Sociology 3e course

- bin/test-unit
You get 1 process per core on your machine when running tests (half of that in watch mode), so you could easily run out of memory and crash with node defaults (1.4GB per process).
> Limit node memory before GC to 512MB per process

- tutor/src/screens/qa-view/exercise-card.jsx
2 changes:
- Exercises FE doesn't like `@draft` so remove that
- Replace /exercises/ with /exercise/ to fix the URLs without having to reimport the book
> Fix exercise edit URL

- tutor/src/components/icons/settings.js
- tutor/src/screens/teacher-gradebook/ux.js
Needed the same fix we used here to not use decorators: https://github.com/openstax/tutor-js/commit/e291bcb5437c0ce83d201390cb9d9d0981ffcb29#diff-f754107374b1d58878fd5b0f48eef125c35357bfc332033935a1ea2b4f0a3032R22
> Fix gradebook dropdowns

- tutor/src/screens/performance-forecast/teacher-student.js
fixes the bug with the student selector on the performance forecast
> bind onSelect to this so that props are in scope

- tutor/resources/styles/book-content/page.scss
> use break-word to prevent long urls and content from overspill

- shared/resources/styles/components/exercise-preview/index.scss
- tutor/resources/styles/components/exercise-preview.scss
don't mind the failed to load iframe, that's due to it not trusting localhost
> display interactives full-width in details view

- tutor/src/models/task-plans/teacher/plan.ts
- tutor/src/screens/assignment-review/ux.ts
Should make it so the "E" extension icon shows up immediately after saving the extensions, as the API gives us an update task plan in the response.
> update task plan extensions with api response data

- tutor/specs/screens/assignment-edit/ux.spec.jsx
- tutor/src/screens/assignment-edit/ux.js
According to the card, we always want to return to the date that is currently set as the due date, regardless of the assignment's default date. I suppose we can still use the default date as a fallback though.
> Always return to the calendar showing the assignment's due date

- tutor/specs/helpers/period.spec.js
- tutor/src/helpers/period.ts
https://caniuse.com/localecompare
`localeCompare()` is only weird for the decimal parts of numbers, when the decimal parts have different lengths.
I don't think we care very much about that case though.
> Use localeCompare in numeric mode for sorting course sections

- tutor/specs/components/icons/lock.spec.js
- tutor/src/components/icons/lock.js
- tutor/src/screens/task/step/card.js
- Added a lock icon to questions that have been graded or whose assignment is closed
- Made mobile-only back and forward arrows in question header not clickable in tablet and desktop modes
> Lock icon on question header

- shared/resources/styles/components/exercise-badges/index.scss
This style only exists on the Tutor side, but openstax-gray is exactly the same thing.
> Use $openstax-gray instead of $openstax-book-gray so exercises-js can compile

- tutor/src/screens/task/step/exercise-free-response.js
Fixes the spacing between the section number and title. Also adds a bit of vertical space between "last submitted at" and validator text.
| Old | New |
|--- | --- |
| ![image](https://user-images.githubusercontent.com/34174/133340696-643c7717-8660-4cb0-a079-948479917e76.png) | ![Screenshot 2021-09-14 at 15-00-06 OpenStax Tutor](https://user-images.githubusercontent.com/34174/133340550-fadcf0e5-6024-4c24-ac71-8f2fffd7aca4.png) |
> fix spacing of book name in validator response

- tutor/specs/e2e/add-edit-question.e2e.ts
- tutor/src/components/add-edit-question/ux.js
Fixes a bug that would allow for question text that contained the default editor html p tag to pass validation.
> fix question emptiness check by stripping tags

- tutor/src/components/buttons/save-practice.js
- tutor/src/models/practice-questions.ts
Repro:
- Save a question to practice
- Update the course ecosystem
- Old assignment shows the question as unsaved, and throws an error when clicking save (PracticeQuestions have to be unique by tasked_exercise_id)
This is caused by `AddEcosystemToCourse` running `RemapPracticeQuestionExercises`, which changes the saved exercise id to the new one in the new ecosystem. This PR has a fix for this by looking for the tasked_id instead.
> find saved question by tasked_id not exercise_id

- tutor/src/models/reference-book/node.ts
Strip out the span tags that get rendered on the add-edit form.
Before:
After:
> fix title text displaying span tags on add-edit form

- tutor/src/components/buttons/save-practice.js
Fix saving multipart questions to practice by looking for any of the group's tasked ids being saved.
> Fix saving multipart questions to practice 

- tutor/src/models/student-tasks/step.ts
- tutor/src/models/task-plans/teacher/scores.ts
- tutor/src/screens/assignment-review/overview.js
- tutor/src/screens/assignment-review/overview.tsx
Getting the group_type from the backend will allow us to separate the spaced practice questions and sort them to the bottom under a new "Spaced Practice" header.
> Sort spaced practice

- exercises/src/models/exercises.ts
- shared/src/model/exercise/tags-association.ts
'all' was being created as a tag on exercises because of serialization of the `@model` tags object. This is a quick fix to grab the array instead.
> Fix exercises tag

- Dockerfile
- bin/build
- bin/lint
- bin/serve
- bin/test
- bin/test-unit
- docker-compose.exercises.yml
- docker-quickstart.md
- exercises/specs/components/__snapshots__/exercise.spec.js.snap
- exercises/src/components/exercise/question.jsx
- package.json
- shared/specs/model/exercise/question.spec.ts
- shared/src/components/question/index.jsx
- shared/src/model/exercise/question.ts
- webpack.config.js
- yarn.lock
fixes openstax/ce#2138
This adds a new text input for summary solution type. It includes the summary solution type in the `collaborator_solutions` field by adding subtype discrimination based on `solution_type`. 
- Solutions entered into 'Detailed Solutions' should still have solution_type = 'detailed' 
- Solutions entered into 'Summary' should have solution_type = 'summary'
This also updates the docker files and bin scripts to simplify local testing.
> 2138 add summary

- exercises/specs/components/__snapshots__/exercise.spec.js.snap
- exercises/specs/components/exercise.spec.js
- exercises/src/components/exercise/tags.jsx
- exercises/src/components/tags/public-solution-subset.jsx
- exercises/src/components/tags/public-solutions.jsx
- exercises/src/models/exercises/exercise.ts
- New tag with dropdown that supports values `even` and `odd`
- Dropdown is only visible when question is multi-part and solutions are public
- Tag is optional: when it is not set, that means all solutions are public
- When conditions for the dropdown appearing are not met, the value for the tag should be cleared
> Add public solution subset
