- tutor/src/api/index.js
- tutor/src/models/app.js
- tutor/src/models/app/pulse-insights.js
- tutor/src/screens/lms-pair/app.js
I'm not sure how to tell if this is working, but it's does load the script and doesn't have any errors
> Add Pulse insights

- tutor/specs/models/courses/create.spec.js
- tutor/specs/screens/new-course/course-numbers.spec.jsx
- tutor/src/models/course/create.js
- tutor/src/screens/new-course/course-numbers.jsx
> display different error when numbers are too low

- tutor/src/components/buttons/teacher-become-student.js
- tutor/src/components/teacher-as-student-frame.js
- tutor/src/models/course/period.js
- tutor/src/screens/teacher-dashboard/index.jsx
clear the current role when loading teacher dashboard as a student
> don't attempt to re-load student tasks on back button

- tutor/src/api/index.js
- tutor/src/components/buttons/teacher-become-student.js
- tutor/src/models/course/period.js
- tutor/src/models/course/role.js
- tutor/src/models/task-plans/teacher.js
- tutor/src/screens/teacher-dashboard/index.jsx
The role needs to be set before the student dashboard loads, but should cleared and not be used when loading teacher dashboard
> adjust calls so current_role is set/unset properly

- tutor/specs/models/student-tasks/task.spec.js
- tutor/src/models/student-tasks/task.js
otherwise code can't find the task and errors abound 😭
> make sure inverseOf task is set on steps after load

- tutor/specs/components/__snapshots__/tutor-layout.spec.js.snap
- tutor/specs/models/user/__snapshots__/menu.spec.js.snap
- tutor/specs/models/user/menu.spec.js
- tutor/src/models/user/menu.js
The isAllowed checks must return false, not null/undefined
> dont' show research link when course is not present

- tutor/resources/styles/book-content/base.scss
- tutor/resources/styles/book-content/learning-objectives.scss
- tutor/src/components/book-page.js
- tutor/src/components/teacher-as-student-frame.js
Previously it was removed but AP books want it
> if present; display the LEARNING OBJECTIVES title

- tutor/src/components/navbar/actions-menu.jsx
- tutor/src/models/user/menu.js
> open research menu option in new tab, use TitleCase

- tutor/specs/models/courses/onboarding/index.spec.js
- tutor/src/models/course.js
- tutor/src/models/course/onboarding/index.js
Otherwise teacher nags are shown on the student desktop
> use student record for onboarding a teacher student

- shared/resources/styles/mixins/index.scss
- tutor/resources/styles/book-content/base.scss
- tutor/resources/styles/book-content/theming-mixins.scss
> Style table headings

- package.json
- tutor/specs/components/my-courses.spec.jsx
- tutor/specs/helpers/analytics.spec.js
- tutor/specs/models/course.spec.js
- tutor/specs/models/courses/onboarding/index.spec.js
- tutor/specs/models/user/menu.spec.js
- tutor/src/components/buttons/teacher-become-student.js
- tutor/src/components/my-courses/course.jsx
- tutor/src/components/my-courses/index.jsx
- tutor/src/components/navbar/best-practices-guide.jsx
- tutor/src/helpers/analytics.js
- tutor/src/models/course.js
- tutor/src/models/courses-map.js
- tutor/src/models/user/menu.js
- tutor/src/screens/performance-forecast/index.js
- tutor/src/screens/reference-book/ux.js
- tutor/src/screens/scores-report/assignment-header.jsx
- tutor/src/screens/scores-report/correctness-value.jsx
- tutor/src/screens/scores-report/export-controls.jsx
- tutor/src/screens/scores-report/external-cell.jsx
- tutor/src/screens/scores-report/homework-cell.jsx
- tutor/src/screens/scores-report/index.jsx
- tutor/src/screens/scores-report/nav.jsx
- tutor/src/screens/scores-report/overall-header.jsx
- tutor/src/screens/scores-report/reading-cell.jsx
- tutor/src/screens/scores-report/table.jsx
- tutor/src/screens/scores-report/ux.js
- tutor/src/screens/task/task-footer-controls.js
- yarn.lock
use currentRole instead of testing isTeacher everywhere
> Hide teacher controls when teacher-student views scores

- tutor/src/components/book-page.js
> only apply "splash" style to images wider than 400px

- tutor/resources/styles/book-content/mixins.scss
- tutor/resources/styles/components/exercises.scss
- tutor/specs/components/exercises/__snapshots__/sectionizer.spec.js.snap
- tutor/specs/components/exercises/sectionizer.spec.js
- tutor/specs/helpers/dates.spec.js
- tutor/specs/models/task-plans/teacher/tasking.spec.js
- tutor/src/components/exercises/sectionizer.jsx
- tutor/src/components/lms-info-card.js
- tutor/src/helpers/analytics.js
- tutor/src/helpers/dates.js
- tutor/src/helpers/task-plan.js
- tutor/src/models/reference-book.js
- tutor/src/models/task-plans/teacher/plan.js
- tutor/src/models/task-plans/teacher/tasking.js
- tutor/src/screens/assignment-builder/homework/add-exercises.jsx
- tutor/src/screens/assignment-builder/homework/exercise-controls.jsx
- tutor/src/screens/assignment-builder/ux.js
- tutor/src/screens/question-library/styles.scss
- tutor/src/screens/task/step/exercise-question.js
- tutor/src/screens/task/step/exercise.js
Rather than attempting to track down all the content, just treat all iframe that way
> Fix sims without "interactive" class in task steps

- tutor/specs/models/task-plans/teacher/tasking.spec.js
- tutor/specs/screens/assignment-builder/builder/tasking.spec.js
- tutor/src/components/tutor-input.js
- tutor/src/models/task-plans/teacher/tasking.js
- tutor/src/screens/assignment-builder/builder/tasking.js
We weren't enforcing open date being before the due and due being after open 😭
> Set min/max dates on taskings

- tutor/resources/styles/mixins/tutor-plans.scss
- tutor/specs/models/task-plans/teacher/tasking.spec.js
- tutor/specs/screens/assignment-builder/builder/tasking.spec.js
- tutor/specs/screens/assignment-builder/homework.spec.js
- tutor/specs/screens/assignment-builder/homework/exercise-controls.spec.js
- tutor/specs/screens/assignment-builder/mini-editor/editor.spec.js
- tutor/specs/screens/assignment-builder/reading.spec.js
- tutor/src/components/buttons/teacher-become-student.js
- tutor/src/components/tutor-input.js
- tutor/src/helpers/conditional-handlers.jsx
- tutor/src/models/course.js
- tutor/src/models/course/period.js
- tutor/src/models/task-plans/teacher/tasking.js
- tutor/src/routes.js
- tutor/src/screens/assignment-builder/builder/tasking.js
- tutor/src/screens/assignment-builder/index.js
- tutor/src/screens/assignment-builder/ux.js
- tutor/src/screens/teacher-dashboard/index.jsx
- tutor/src/screens/teacher-dashboard/plan-display.jsx
adds/subtracts a minute from the dates
> more fixes for tasking min max

- package.json
- shared/specs/components/icon.spec.js
- shared/src/components/icon.js
- tutor/specs/models/task-plans/teacher/tasking.spec.js
- tutor/specs/screens/assignment-builder/builder/set-time-as-default.spec.js
- tutor/specs/screens/assignment-builder/builder/tasking.spec.js
- tutor/specs/screens/assignment-builder/helpers.js
- tutor/src/components/tutor-input.js
- tutor/src/models/task-plans/teacher/plan.js
- tutor/src/models/task-plans/teacher/tasking.js
- tutor/src/screens/assignment-builder/builder/index.js
- tutor/src/screens/assignment-builder/builder/set-time-as-default.js
- tutor/src/screens/assignment-builder/builder/tasking.js
- tutor/src/screens/assignment-builder/external.js
- tutor/src/screens/assignment-builder/styles/builder.scss
- tutor/src/screens/assignment-builder/wrapper.js
- yarn.lock
> Restore the "set time as default" controls

- tutor/specs/components/navbar/student-pay-now-btn.spec.jsx
- tutor/specs/models/courses/onboarding/student-course.spec.js
- tutor/src/components/buttons/teacher-become-student.js
- tutor/src/components/navbar/student-pay-now-btn.jsx
- tutor/src/models/course/onboarding/student-course.js
- tutor/src/models/course/period.js
- tutor/src/models/course/student.js
- tutor/src/models/task-plans/teacher/tasking.js
makes ghost students comped and then hides all payment nags for them
> do not prompt ghost or comped students to pay

- shared/src/components/icon.js
- tutor/src/models/task-plans/teacher/past.js
- tutor/src/screens/assignment-builder/ux.js
- tutor/src/screens/teacher-dashboard/past-assignments.jsx
The course wasn't being set on them, causing errors
> Fix copying past assignments

- tutor/src/components/tutor-input.js
- tutor/src/models/task-plans/teacher/plan.js
- tutor/src/screens/assignment-builder/builder/tasking.js
- tutor/src/screens/assignment-builder/form.js
- tutor/src/screens/assignment-builder/mini-editor/editor.js
So @gregfitch can find them with his automated tests
> add id's to fields on assignment builder

- tutor/specs/screens/assignment-builder/builder/tasking.spec.js
- tutor/specs/screens/assignment-builder/helpers.js
- tutor/specs/screens/assignment-builder/homework.spec.js
- tutor/specs/screens/assignment-builder/homework/__snapshots__/exercises-table.spec.js.snap
- tutor/specs/screens/assignment-builder/homework/__snapshots__/review-exercises.spec.js.snap
- tutor/specs/screens/assignment-builder/homework/exercise-controls.spec.js
- tutor/specs/screens/assignment-builder/mini-editor/editor.spec.js
- tutor/specs/screens/assignment-builder/reading.spec.js
- tutor/src/components/exercises/details.jsx
- tutor/src/components/exercises/sectionizer.jsx
- tutor/src/components/tutor-input.js
- tutor/src/models/chapter-section.js
- tutor/src/models/course/onboarding/student-course.js
- tutor/src/models/task-plans/teacher/plan.js
- tutor/src/models/task-plans/teacher/tasking.js
- tutor/src/screens/assignment-builder/form.js
- tutor/src/screens/assignment-builder/homework/add-exercises.jsx
- tutor/src/screens/assignment-builder/styles/builder.scss
- tutor/src/screens/assignment-builder/ux.js
- tutor/src/screens/question-library/exercises-display.jsx
And comped teacher student to not throw error
> Fix sectionizer to hide non assignable in hw

- tutor/specs/screens/assignment-builder/builder/tasking.spec.js
- tutor/src/helpers/conditional-handlers.jsx
- tutor/src/models/course.js
- tutor/src/models/course/role.js
- tutor/src/screens/assignment-builder/builder/tasking.js
- tutor/src/screens/assignment-builder/ux.js
and also clear cached student data when becoming a student
> toggle periods in HW builder

- shared/specs/model/map.spec.js
- shared/src/model/api.js
- shared/src/model/map.js
- tutor/src/models/course.js
- tutor/src/models/course/role.js
- tutor/src/screens/task/ux.js
but when they are, also reset the API so they're re-fetched
> Don't reset tasks when they're viewed

- tutor/src/components/teacher-as-student-frame.js
- tutor/src/helpers/conditional-handlers.jsx
Otherwise components get confused when what was once a student now is not
> navigate to role become route vs just remove the role from a course

- tutor/src/models/app/pulse-insights.js
- tutor/src/models/feature_flags.js
> add feature flag for pulseinsights

- tutor/resources/styles/book-content/base.scss
- tutor/resources/styles/mixins/figures.scss
> remove italic style from captions

- tutor/resources/styles/book-content/base.scss
> remove italic font style from terms

- tutor/resources/styles/components/book-menu.scss
> use flex layout so title doesn't wrap

- tutor/src/components/sections-chooser.jsx
- tutor/src/models/reference-book/page.js
And also hide "Test Prep for AP® Courses" or "Science Practice Challenge Questions"
> use `displayedChapterSection` so that baked c/s has priority

- tutor/src/components/tutor-input.js
- tutor/src/models/task-plans/teacher/tasking.js
The shouldComponentUpdate logic was backward 😭
> fix due_at time input

- tutor/specs/components/enroll.spec.jsx
- tutor/specs/models/courses/enroll.spec.js
- tutor/src/models/course/enroll.js
This way it'll pickup on blanket terms (hopefully)
> fetch terms when enroll completes

- tutor/specs/components/terms-modal.spec.jsx
- tutor/src/components/terms-modal.jsx
- tutor/src/models/user.js
- tutor/src/models/user/terms.js
- tutor/src/screens/student-dashboard/index.jsx
and also add api pending condition to terms modal
> Fix student dashboard infinite loading

- tutor/specs/screens/student-dashboard/event-row.spec.jsx
- tutor/src/models/task-plans/student/task.js
- tutor/src/screens/student-dashboard/event-row.jsx
needs https://github.com/openstax/tutor-server/pull/1895
> display "only visible to instructors" message for non-open tasks

- tutor/specs/models/task-plans/student/task.spec.js
- tutor/src/models/task-plans/student.js
- tutor/src/models/task-plans/student/task.js
- tutor/src/screens/student-dashboard/event-row.jsx
- tutor/src/screens/student-dashboard/styles/task.scss
- tutor/src/screens/student-dashboard/teacher-pending-load.js
and also fix fast loading when waiting on an assignment
> Fix wording on teacher viewing student task and loading

- tutor/specs/components/modal-manager.spec.jsx
- tutor/specs/screens/new-course/__snapshots__/index.spec.jsx.snap
- tutor/specs/screens/new-course/index.spec.jsx
- tutor/src/components/modal-manager.jsx
- tutor/src/screens/new-course/index.jsx
There can only be a single TermsModal displayed at once
> fix new course wizard when teacher needs terms

- shared/src/model/networking.js
- shared/src/model/ui-settings.js
Currently happening with teacher01 on qa
> Clear ui settings when  ui_settings_is_too_long error occurs

- tutor/src/screens/task/index.js
- tutor/static-loading-screen.js
looks like the other was probably a bad copy-n-paste job
> update title for deleted task warning

- tutor/specs/components/onboarding/free-trial-ended.spec.jsx
- tutor/src/components/onboarding/free-trial-ended.jsx
> don't prompt for past payments

- .ignore
- tutor/specs/components/__snapshots__/tutor-layout.spec.js.snap
- tutor/src/components/enroll.jsx
- tutor/src/components/terms-modal.jsx
- tutor/src/components/tutor-layout.js
- tutor/src/models/course/enroll.js
To do so the requirement to be in a course is removed so now they'll show up everywhere
> Display terms before enrollment

- tutor/src/screens/student-dashboard/event-row.jsx
- tutor/src/screens/student-dashboard/styles/task.scss
> display border above the only visible notice

- tutor/specs/components/terms-modal.spec.jsx
- tutor/specs/models/user.spec.js
- tutor/src/components/terms-modal.jsx
- tutor/src/models/user.js
- tutor/src/models/user/terms.js
Also removes the user.unsignedTerms in favor of just User.terms.unsigned
> Fetch terms when needed and wait util they're present

- exercises/specs/models/exercises/exercise.spec.js
- exercises/src/models/exercises/delegation.js
- exercises/src/models/exercises/exercise.js
This line intentionally left blank (leave me alone Staxly)
> Allow exercises to be edited by copyright holders and delegates

- tutor/specs/components/my-courses.spec.jsx
- tutor/src/components/my-courses/listings.jsx
Due to a bug in the joyride library, adding a step after the tour starts causes it to stop rendering altogether
> remove preview tour

- tutor/src/components/page-title.js
- tutor/src/models/reference-book/page.js
- tutor/src/models/student-tasks/step.js
Otherwise AP physics will display the off-by-one verion
also needs https://github.com/openstax/tutor-server/pull/1908
> use baked chapter section for page title on reading steps

- tutor/src/screens/task/step/exercise.js
Since we can't seem to figure out how we're getting the "map of undefined" error when this component renders
> reload step and log results missing questions

- tutor/specs/factories/student-task.js
- tutor/specs/screens/student-dashboard/__snapshots__/dashboard.spec.jsx.snap
- tutor/specs/screens/student-dashboard/__snapshots__/homework-row.spec.jsx.snap
- tutor/specs/screens/student-dashboard/__snapshots__/reading-row.spec.jsx.snap
- tutor/specs/screens/student-dashboard/event-row.spec.jsx
- tutor/src/models/task-plans/student/task.js
- tutor/src/screens/student-dashboard/event-row.jsx
previously we showed them until the student clicked "hide"
> don't display deleted tasks that are not worked

- tutor/specs/screens/student-dashboard/progress-guide.spec.js
- tutor/src/screens/student-dashboard/progress-guide.js
method wasn't bound so couldn't access history
> fix view all topics button on student dashboard

- tutor/specs/screens/task/steps/__snapshots__/html-content.spec.js.snap
- tutor/specs/screens/task/steps/__snapshots__/reading.spec.js.snap
- tutor/src/models/tour/actions/open-dropdown-menu.js
- tutor/src/screens/task/step/continue-btn.js
and also don't run tour on closed menu
> fix tasks continue button

- tutor/specs/models/reference-book/ux.spec.js
- tutor/src/components/navbar/support-menu.jsx
- tutor/src/components/tours/spotlight.js
- tutor/src/models/reference-book/ux.js
- tutor/src/models/tour/actions/base.js
- tutor/src/models/tour/actions/open-actions-menu.js
- tutor/src/models/tour/actions/open-dropdown-menu.js
- tutor/src/models/tour/ride.js
- tutor/src/models/tour/step.js
* use history to redirect on reference view
* improve logic for moving between menus
> Keep menu open while tour is underway

- tutor/src/components/tours/conductor.jsx
- tutor/src/models/tour/ride.js
- tutor/src/tours/my-courses.json
- tutor/src/tours/teacher-calendar.json
Fixes the "Complete" button and makes the "Try a Preview" step not mask the screen
> Fix non-dismissible tours

- tutor/src/models/tour/context.js
- tutor/src/tours/page-tips-reminder.json
otherwise when a new tour becomes available due to user navigation it won't immediately show
> attempt to pick new ride anytime a new tour is available

- tutor/src/components/tours/custom/tips-now-or-later.jsx
- tutor/src/models/tour/context.js
Otherwise the "Page Tips" tour replays itself
> mark current tour complete and don't replay it when triggering

- tutor/specs/screens/task/ux.spec.js
- tutor/src/helpers/scroll-to.js
- tutor/src/screens/task/ux.js
The scroll was happening too soon,  it should have happened after the history is applied
> fix scrolling to MPQ when steps change

- tutor/resources/styles/book-content/base.scss
- tutor/resources/styles/book-content/theming-mixins.scss
> style blockquote more like CNX

- shared/src/components/scroll-to-top.js
- shared/src/index.js
- tutor/specs/components/course-page.spec.jsx
- tutor/specs/screens/surveys.spec.js
- tutor/src/components/course-page.jsx
- tutor/src/screens/assignment-builder/index.js
- tutor/src/screens/course-roster/index.jsx
- tutor/src/screens/new-course/index.jsx
- tutor/src/screens/performance-forecast/index.js
- tutor/src/screens/qa-view/index.jsx
- tutor/src/screens/scores-report/index.jsx
- tutor/src/screens/student-dashboard/index.jsx
- tutor/src/screens/task/index.js
- tutor/src/screens/teacher-dashboard/index.jsx
- tutor/src/screens/teacher-review-metrics/index.jsx
Fixes cases where something at bottom page is clicked and then screen doesn't scroll to top
> scroll browser window to top of page when screen renders

- tutor/specs/factories/book.js
- tutor/src/components/book-menu/menu.jsx
- tutor/src/components/book-page.js
- tutor/src/components/sections-chooser.jsx
- tutor/src/models/reference-book/chapter.js
- tutor/src/models/reference-book/page.js
- tutor/src/models/student-tasks/step.js
- tutor/src/screens/assignment-builder/ux.js
The BE will no longer send them
Goes along with https://github.com/openstax/tutor-server/pull/1912
> remove baked_chapter_section fields

- shared/src/model.js
- tutor/specs/screens/task/steps/__snapshots__/failure.spec.js.snap
- tutor/specs/screens/task/steps/failure.spec.js
- tutor/src/components/notes.js
- tutor/src/models/app/raven.js
- tutor/src/screens/task/step/failure.js
Update wording for saving and suggest going back
> Catch and display errors on task steps

- tutor/src/components/page-title.js
> indent second line of title so it's not under chapter/section

- tutor/src/screens/task/step/failure.js
> correct mispelled saving

- tutor/specs/models/app.spec.js
- tutor/src/helpers/dom.js
- tutor/src/models/app.js
Otherwise the bootstrap data may not be completly rendered and
JSON.parse will fail
> wait for document to become ready before booting app

- tutor/src/screens/assignment-builder/mini-editor/editor.js
- tutor/src/screens/teacher-dashboard/styles/sidebar.scss
Fixes for:
* text being reversed when hovering over the past assignments
* errors where not being displayed on the mini editor when publish was clicked
> Fixes for cloned assignments

- tutor/specs/components/exercises/__snapshots__/cards.spec.js.snap
- tutor/specs/screens/assignment-builder/homework/__snapshots__/add-exercises.spec.js.snap
- tutor/src/components/exercises/cards.jsx
- tutor/src/models/reference-book.js
- tutor/src/screens/assignment-builder/styles/homework/exercises.scss
- tutor/src/screens/question-library/exercises-display.jsx
Otherwise the "sectionizer" at the top has unclickable sections
> Do not attempt to display sections without exercises in QL

- tutor/src/components/tutor-input.js
- tutor/src/screens/assignment-builder/form.js
Otherwise the student dashboard gets really crazy trying to display it all
> Limit assignment description to 250 chars

- tutor/resources/styles/book-content/base.scss
> move table caption to bottom and adjust margins

- tutor/src/screens/assignment-builder/form.js
- tutor/src/screens/assignment-builder/homework.js
test for the exercise ids instead of the exercise's themselves since the exercises might not be loaded for past due
> Do not display error message on changing of feedback

- tutor/resources/styles/components/exercises.scss
- tutor/resources/styles/mixins/exercise-cards-column-layout.scss
- tutor/specs/screens/assignment-builder/homework/__snapshots__/review-exercises.spec.js.snap
- tutor/specs/screens/question-library/dashboard.spec.jsx
- tutor/src/components/exercises/details.jsx
- tutor/src/components/exercises/sectionizer.jsx
- tutor/src/models/chapter-section.js
- tutor/src/screens/assignment-builder/homework/exercise-controls.jsx
- tutor/src/screens/assignment-builder/index.js
- tutor/src/screens/assignment-builder/styles/homework/exercise-summary.scss
- tutor/src/screens/question-library/dashboard.jsx
- tutor/src/screens/question-library/sections-chooser.jsx
- tutor/src/screens/question-library/styles.scss
Leave sections selected when showing exercises and then adding more
> Retain same section selections on QL

- tutor/resources/styles/components/exercises.scss
- tutor/resources/styles/mixins/exercise-cards-column-layout.scss
- tutor/specs/screens/assignment-builder/homework.spec.js
- tutor/specs/screens/assignment-builder/homework/__snapshots__/choose-exercises.spec.js.snap
- tutor/specs/screens/assignment-builder/homework/__snapshots__/exercises-table.spec.js.snap
- tutor/specs/screens/assignment-builder/homework/__snapshots__/review-exercises.spec.js.snap
- tutor/specs/screens/assignment-builder/homework/exercise-controls.spec.js
- tutor/specs/screens/question-library/dashboard.spec.jsx
- tutor/src/components/chapter-section.js
- tutor/src/components/exercises/details.jsx
- tutor/src/components/exercises/sectionizer.jsx
- tutor/src/models/chapter-section.js
- tutor/src/models/task-plans/teacher/plan.js
- tutor/src/screens/assignment-builder/homework/choose-exercises.jsx
- tutor/src/screens/assignment-builder/homework/exercise-controls.jsx
- tutor/src/screens/assignment-builder/index.js
- tutor/src/screens/assignment-builder/styles/homework/exercise-summary.scss
- tutor/src/screens/assignment-builder/ux.js
- tutor/src/screens/question-library/dashboard.jsx
- tutor/src/screens/question-library/sections-chooser.jsx
- tutor/src/screens/question-library/styles.scss
This will hopefully make everything match up
> count MPQ steps individually so counts match breadcrumbs

- tutor/resources/styles/book-content/base.scss
Make all content be the same size by moving rule up
> change font size on book content

- tutor/specs/screens/task/__snapshots__/reading.spec.js.snap
- tutor/specs/screens/task/homework.spec.js
- tutor/specs/screens/task/reading.spec.js
- tutor/src/models/student-tasks/step.js
- tutor/src/models/student-tasks/task.js
- tutor/src/screens/task/step/exercise.js
Otherwise the type can change but it's content will not, causing exercises to not have steps
> reset content and fetched status when steps are reused

- exercises/specs/components/__snapshots__/exercise.spec.js.snap
- exercises/src/components/exercise/attachments/attachment.jsx
it didn't work because assets aren't really deletable
> remove delete icon on assets

- tutor/specs/components/__snapshots__/tutor-layout.spec.js.snap
- tutor/src/components/navbar/actions-menu.jsx
Also use new `useHistory` hook instead of `withRouter` HOC
> Use Dropdown.Item component so menu will close after click

- tutor/specs/models/user/__snapshots__/menu.spec.js.snap
- tutor/src/components/navbar/actions-menu.jsx
- tutor/src/models/user/menu.js
some urls need to set the window.location so the browser will reload the page
> support redirecting to url vs pushing onto history

- tutor/specs/models/courses/onboarding/student-course.spec.js
- tutor/src/models/course/onboarding/student-course.js
- tutor/src/models/task-plans/student.js
- tutor/src/screens/student-dashboard/index.jsx
otherwise updates aren't displayed when student finishes an assignment
> re-fetch tasks whenever student dashboard is loaded

- tutor/specs/components/notes/summary-page.spec.js
- tutor/src/components/notes/sections-filter.jsx
- tutor/src/components/notes/summary-page.jsx
- tutor/src/models/notes.js
Before it was still using chapter.section so it couldn't select pages
> fix summary page to select page when it changes

- tutor/resources/styles/components/notes/summary-page.scss
- tutor/specs/screens/assignment-builder/homework/__snapshots__/review-exercises.spec.js.snap
- tutor/specs/screens/assignment-builder/homework/review-exercises.spec.js
- tutor/specs/screens/task/ux.spec.js
- tutor/src/components/navbar/actions-menu.jsx
- tutor/src/components/notes/sections-filter.jsx
- tutor/src/helpers/conditional-handlers.jsx
- tutor/src/screens/assignment-builder/homework/exercises-table.jsx
- tutor/src/screens/assignment-builder/homework/review-exercises.jsx
- tutor/src/screens/task/ux.js
* Don't render `undefined` in note summary section picker
* count MPQ steps individually in HW review screen
* set a data-item attribute on menu options for testing
> A few release fixes

- tutor/resources/styles/book-content/base.scss
- tutor/resources/styles/book-content/theming-mixins.scss
> display learning objectives/chapter outline title

- shared/src/model/exercise.js
- shared/src/model/exercise/question.js
This requires the editor to affirmatively make a selection for format
> do not set a default format for exercise questions

- tutor/specs/components/__snapshots__/app.spec.jsx.snap
- tutor/specs/components/__snapshots__/tutor-layout.spec.js.snap
- tutor/src/models/user/menu.js
as requested in https://github.com/openstax/tutor-js/issues/2753
> update help url to search for tutor topics

- shared/src/components/icon.js
- tutor/specs/components/tabs.spec.js
- tutor/src/components/course-periods-nav.jsx
- tutor/src/components/tabs.jsx
- tutor/src/screens/course-roster/index.jsx
- tutor/src/vendor.js
if the section being deleted was the last one the tabs would throw an error, preventing deletion
> Fix deleting sections

- tutor/resources/styles/components/tutor-input.scss
- tutor/src/components/tutor-input.js
- tutor/src/screens/assignment-builder/builder/index.js
- tutor/src/screens/assignment-builder/ux.js
* don't allow selecting all periods if any are unchecked
* retain due_at date when switching
> fix dates when toggling between all and partial sections

- tutor/specs/models/user/__snapshots__/menu.spec.js.snap
- tutor/src/components/navbar/actions-menu.jsx
- tutor/src/models/user/menu.js
> set data-name to be cloneCourse so it can be targeted in tests

- tutor/src/models/app/pulse-insights.js
Use the sample window.pi type code to match rex/cnx
> Update pulse-insights code

- tutor/src/screens/course-roster/delete-period.jsx
otherwise the delete modal will switch to showing a different period
> don't update period while deletion is ongoing

- tutor/specs/screens/assignment-builder/ux.spec.js
- tutor/src/screens/assignment-builder/ux.js
If any periods are deleted the length will not match
> Check period ids on taskings instead of just length

- tutor/resources/styles/book-content/base.scss
- tutor/resources/styles/book-content/theming-mixins.scss
Reverts openstax/tutor-js#2789
Bio 2e has some content that didn't work well
> Revert "display learning objectives/chapter outline title"

- tutor/src/models/user/menu.js
research analytics menu was broken
> set redirect flag so menu option will not use router

- tutor/src/components/navbar/actions-menu.jsx
- tutor/src/models/user/menu.js
> open RAD link in new tab/window

- tutor/specs/components/book-menu/__snapshots__/menu.spec.js.snap
- tutor/specs/screens/__snapshots__/qa-view.spec.jsx.snap
- tutor/src/models/reference-book/chapter.js
- tutor/src/models/reference-book/ux.js
regardless of baked status, chapter is not a page
> chapters never have content

- tutor/specs/components/__snapshots__/tutor-layout.spec.js.snap
- tutor/specs/components/error-monitoring/handlers.spec.jsx
- tutor/specs/components/error-monitoring/index.spec.js
- tutor/src/components/error-monitoring/handlers.jsx
- tutor/src/components/error-monitoring/index.jsx
Use withRouter and inject for reference to router and course, context is has been removed causing the goToDesktop call to fail
> Fix navigation to desktop after receiving "no practice" message

- tutor/resources/styles/mixins/figures.scss
> set figure captions to be sans font

- tutor/src/screens/task/ux.js
Seems to work in manual testing...
> Attempt to prevent students from skipping placeholder steps while they reload

- tutor/src/screens/task/response-validation-ux.js
will allow us to debug multiple attempts a bit better
> add a timestamp to validation payload

- tutor/src/screens/stats/chart.js
- tutor/src/screens/stats/index.jsx
display values from https://github.com/openstax/tutor-server/pull/1936
> break apart reading/homework task plans, add nudge stats

- tutor/specs/helpers/test-router.js
- tutor/specs/screens/task/__snapshots__/breadcrumbs.spec.js.snap
- tutor/specs/screens/task/__snapshots__/external.spec.js.snap
- tutor/specs/screens/task/__snapshots__/homework.spec.js.snap
- tutor/specs/screens/task/__snapshots__/reading.spec.js.snap
- tutor/specs/screens/task/homework.spec.js
- tutor/specs/screens/task/milestones.spec.js
- tutor/specs/screens/task/progress.spec.js
- tutor/specs/screens/task/reading-progress.spec.js
- tutor/specs/screens/task/reading.spec.js
- tutor/specs/screens/task/steps/__snapshots__/exercise-free-response.spec.js.snap
- tutor/specs/screens/task/steps/reading.spec.js
- tutor/specs/screens/task/ux.spec.js
- tutor/src/screens/task/ux.js
Otherwise the history gets two entries and tasks steps don't load
> Don't push new pathname into history when it matches current path

- tutor/resources/styles/global/misc.scss
- tutor/resources/styles/variables/colors.scss
- tutor/specs/components/__snapshots__/related-content-link.spec.js.snap
- tutor/specs/components/__snapshots__/sections-chooser.spec.jsx.snap
- tutor/specs/components/book-menu/__snapshots__/menu.spec.js.snap
- tutor/specs/components/exercises/__snapshots__/cards.spec.js.snap
- tutor/specs/components/notes/__snapshots__/summary-popup.spec.js.snap
- tutor/specs/screens/__snapshots__/qa-view.spec.jsx.snap
- tutor/specs/screens/assignment-builder/__snapshots__/select-sections.spec.js.snap
- tutor/specs/screens/assignment-builder/homework/__snapshots__/add-exercises.spec.js.snap
- tutor/specs/screens/assignment-builder/homework/__snapshots__/choose-exercises.spec.js.snap
- tutor/specs/screens/assignment-builder/homework/__snapshots__/review-exercises.spec.js.snap
- tutor/specs/screens/question-library/__snapshots__/dashboard.spec.jsx.snap
- tutor/specs/screens/task/steps/__snapshots__/footer.spec.js.snap
- tutor/src/components/chapter-section.js
And also make observable just in case we want it to re-render if a chapter-section changes
> convert chapter-section component to use styled components

- tutor/src/models/reference-book/ux.js
- tutor/src/screens/task/page-content-ux.js
Otherwise the rewrite book link can't find it and links are incorrect
> set courseId on book ux

- package.json
- tutor/src/components/notes.js
- yarn.lock
highlighter update includes https://github.com/openstax/highlighter/pull/22
> update highlighter, ignore self-mutations

- tutor/specs/screens/__snapshots__/stats.spec.js.snap
- tutor/src/models/stats.js
- tutor/src/screens/stats/chart.js
- tutor/src/screens/stats/index.jsx
- tutor/src/screens/stats/table.jsx
> link charts together, add text table

- tutor/resources/styles/book-content/base.scss
- tutor/resources/styles/global/misc.scss
This way they'll be styled in exercises as well
> style blockquotes globally

- tutor/src/models/course/offerings/term.js
- tutor/src/screens/new-course/select-dates.jsx
The term models will be different instances if the ux re-fetches the offering
> test for selected term using it's attributes

- tutor/resources/styles/book-content/questions.scss
> remove larger font size

- tutor/src/screens/reference-book/section-title.jsx
- tutor/src/screens/reference-book/styles/navbar.scss
Content will occasionally have <i> or <b> tags
Goes with https://github.com/openstax/tutor-server/pull/1941
> render HTML inside of unit/chapter/section/page titles

- shared/src/components/icon.js
- tutor/resources/styles/components/multi-select.scss
- tutor/specs/components/__snapshots__/multi-select.spec.jsx.snap
- tutor/specs/components/__snapshots__/sections-filter.spec.jsx.snap
- tutor/specs/components/multi-select.spec.jsx
- tutor/specs/components/sections-filter.spec.jsx
- tutor/src/components/multi-select.jsx
- tutor/src/components/notes/sections-filter.jsx
- Add support for 2 columns if more than 20 items
- Add helpers for selecting all or none
- Fix closeAfterSelect
- Add scrolling for longer lists
- Update checkbox colors and size
- Remove the bold style coming from ChapterSection
> update MultiSelect and SectionsFilter

- configs/test/jest.setup.js
- shared/src/model/api.js
- tutor/specs/screens/task/__snapshots__/milestones.spec.js.snap
- tutor/specs/screens/task/__snapshots__/progress.spec.js.snap
- tutor/specs/screens/task/__snapshots__/reading.spec.js.snap
- tutor/specs/screens/task/milestones.spec.js
- tutor/specs/screens/task/ux.spec.js
- tutor/src/models/student-tasks/step.js
- tutor/src/screens/task/ux.js
The code was calling markViewed as soon as it loaded the first step, and then the step wouldn't fetch because save was in progress
> Fix first step displaying loading state forever

- tutor/specs/components/exercises/__snapshots__/cards.spec.js.snap
- tutor/specs/screens/assignment-builder/homework/__snapshots__/add-exercises.spec.js.snap
- tutor/specs/screens/assignment-builder/homework/__snapshots__/choose-exercises.spec.js.snap
- tutor/src/components/exercises/cards.jsx
- tutor/src/screens/performance-forecast/chapter.js
- tutor/src/screens/performance-forecast/section.js
use BookPartTitle to display chapter/section titles.  This is needed so they'll display any HTML markup
> Render HTML markup in exercise selector and performance forecast

- tutor/src/screens/task/milestones.js
The step title can also have html
> always render html in milestones

- tutor/specs/screens/assignment-builder/footer/save-button.spec.js
- tutor/src/screens/assignment-builder/footer/save-as-draft.jsx
- tutor/src/screens/assignment-builder/footer/save-button.jsx
- tutor/src/screens/assignment-builder/ux.js
otherwise it's clickable but has no effect
> disable save & draft button when assignment can't be saved

- exercises/src/models/search.js
This way the current exercise will still be shown
> adjust current page when page size changes

- exercises/src/models/search.js
Otherwise you can't switch per-page size if you're on the first page
> Add one to exercise index so it's never 0

- tutor/src/models/task-plans/teacher/plan.js
otherwise a 422 occurs because there's nothing to do
> require at least one tasking plan

- exercises/src/components/search/clause.jsx
- exercises/src/models/search.js
Otherwise pagination doesn't make sense if not enough pages are returned
> Reset search page back to 1st when filter changes

- tutor/src/components/notes/summary-page.jsx
- tutor/src/components/paging-navigation.jsx
Found a few more spots in testing
> Render or strip html in page titles

- bin/lint
- tutor/src/models/grading/templates.js
- tutor/src/screens/grading-templates/card.js
- tutor/src/screens/grading-templates/editors.js
- tutor/src/screens/grading-templates/index.js
also don't return early with modal, instead render it along with cards
> Connect api, add field validations

- tutor/src/models/grading/templates.js
With this, creating and updating should be working
> set in template map after create, convert to/from floats

- shared/src/components/icon.js
- tutor/specs/components/__snapshots__/number-input.spec.js.snap
- tutor/specs/components/__snapshots__/radio-input.spec.jsx.snap
- tutor/specs/components/__snapshots__/select.spec.jsx.snap
- tutor/specs/components/radio-input.spec.jsx
- tutor/specs/components/select.spec.jsx
- tutor/src/components/number-input.js
- tutor/src/components/radio-input.jsx
- tutor/src/components/select.jsx
- tutor/src/models/grading/templates.js
- tutor/src/screens/grading-templates/editors.js
- tutor/src/screens/grading-templates/index.js
- tutor/src/theme.js
Updates the modal and NumberInput styles, and adds RadioInput and Select.
There are some alignments and other things I'd like to finish up later, but this should get us fairly close to the final look so we can test API things.
> WRM radio component and modal styles

- tutor/src/screens/teacher-dashboard/add-assignment-popup.js
This feels slightly hacky because it I think it could be solved by sending styles to popper config instead, but I wasn't able to get the override working.
> Fix calendar popup

- tutor/specs/screens/grading-templates/__snapshots__/card.spec.js.snap
- tutor/specs/screens/grading-templates/card.spec.js
- tutor/src/api/index.js
- tutor/src/components/radio-input.jsx
- tutor/src/models/grading/templates.js
- tutor/src/screens/grading-templates/card.js
- tutor/src/screens/grading-templates/index.js
- tutor/src/theme.js
> replace stub text with template values

- tutor/scripts/test-server/backend.js
- tutor/scripts/test-server/backend/grading-templates.js
- tutor/specs/factories/grading-template.js
- tutor/src/screens/grading-templates/card.js
- tutor/src/screens/grading-templates/link.js
a simple one for now, we can add to as needed
> Add cypress test for WRM branch

- cypress/support/commands.js
- tutor/scripts/test-server/backend.js
- tutor/scripts/test-server/backend/grading-templates.js
- tutor/specs/.eslintrc.js
- tutor/specs/components/__snapshots__/radio-input.spec.jsx.snap
- tutor/specs/components/__snapshots__/select.spec.jsx.snap
- tutor/specs/components/__snapshots__/time-input.spec.js.snap
- tutor/specs/components/radio-input.spec.jsx
- tutor/specs/components/select.spec.jsx
- tutor/specs/components/time-input.spec.js
- tutor/specs/integration/grading-templates.spec.js
- tutor/specs/models/grading/__snapshots__/templates.spec.js.snap
- tutor/specs/screens/grading-templates/__snapshots__/card.spec.js.snap
- tutor/src/components/number-input.js
- tutor/src/components/radio-input.jsx
- tutor/src/components/select.jsx
- tutor/src/components/time-input.js
- tutor/src/models/grading/templates.js
- tutor/src/screens/grading-templates/card.js
- tutor/src/screens/grading-templates/editors.js
There's still a few unknowns that we'll need to confer with Dante about but most are now saving
> Connect template edit fields to model

- tutor/specs/components/__snapshots__/time-input.spec.js.snap
- tutor/src/components/time-input.js
- tutor/src/models/grading/templates.js
Updates the default fields with what's listed in the behavior doc.
> make default fields match behavior doc

- tutor/specs/screens/grading-templates/__snapshots__/card.spec.js.snap
- tutor/src/screens/grading-templates/card.js
> add some spacing between card rows

- README.md
@jivey take a look at these and suggest updates if they don't work for you or you discover anything omitted
> document cypress commands

- tutor/src/screens/assignments/builder.js
- tutor/src/screens/assignments/chapters.js
- tutor/src/screens/assignments/details.js
- tutor/src/screens/assignments/questions.js
- tutor/src/screens/assignments/review.js
- tutor/src/screens/assignments/ux.js
Gets the screens stepping forward and backward, some basic styles, and adds some non-working form controls to get it going.
Interested to hear your thoughts about the wrapper AssignmentBuilder holding the styled-components and importing what's needed into each step 🤔
> add basic wrapper component and forward/backward

- tutor/src/components/book-page.js
Goes along with https://github.com/openstax/tutor-server/pull/1954
> don't display media preview for footnote that points to itself

- tutor/specs/screens/new-course/__snapshots__/course-name.spec.js.snap
- tutor/specs/screens/new-course/__snapshots__/course-numbers.spec.jsx.snap
- tutor/src/components/notes.js
- tutor/src/screens/new-course/course-name.jsx
- tutor/src/screens/new-course/course-numbers.jsx
- tutor/src/screens/new-course/ux.js
Otherwise the enter attempts to submit the form and reloads the page
> Proceed to next step of new course wizard when enter is pressed

- shared/src/model/map.js
- tutor/specs/integration/assignments.spec.js
- tutor/src/screens/assignments/builder.js
- tutor/src/screens/assignments/details.js
- tutor/src/screens/assignments/index.js
- tutor/src/screens/assignments/step.js
- tutor/src/screens/assignments/ux.js
connect API to model.  needs https://github.com/openstax/tutor-js/pull/2885 for the cypress tour disable command
> WRM: connect form to ux and validate

- package.json
- tutor/resources/styles/components/date-time-input.scss
- tutor/resources/styles/tutor.scss
- tutor/specs/components/__snapshots__/date-time-input.spec.js.snap
- tutor/specs/components/date-time-input.spec.js
- tutor/src/components/date-time-input.js
- tutor/src/screens/assignments/details.js
- yarn.lock
> Add date & time input

- tutor/src/screens/assignments/builder.js
- tutor/src/screens/assignments/chapters.js
- tutor/src/screens/assignments/details.js
- tutor/src/screens/assignments/homework/add-exercises.jsx
- tutor/src/screens/assignments/homework/choose-exercises.jsx
- tutor/src/screens/assignments/homework/exercise-controls.jsx
- tutor/src/screens/assignments/homework/exercises-table.jsx
- tutor/src/screens/assignments/homework/review-exercises.jsx
- tutor/src/screens/assignments/homework/selections-tooltip.jsx
- tutor/src/screens/assignments/index.js
- tutor/src/screens/assignments/questions.js
- tutor/src/screens/assignments/review.js
- tutor/src/screens/assignments/select-sections.js
- tutor/src/screens/assignments/ux.js
- tutor/src/theme.js
Brings over a lot from the main builder to get questions & review rendering. There's probably some unneeded stuff that can be trimmed in another pass.
> get all steps rendering in new builder

- tutor/scripts/test-server/backend.js
- tutor/scripts/test-server/backend/exercises.js
- tutor/scripts/test-server/backend/readings.js
- tutor/specs/factories/exercise.js
- tutor/specs/integration/assignments.spec.js
- tutor/specs/integration/grading-templates.spec.js
- tutor/src/screens/assignments/ux.js
- tutor/src/screens/assignments/validations.js
Adds a validation class with custom logic for each step
> Validate each step and conditionally enable continue button

- tutor/src/screens/stats/index.jsx
Goes along with https://github.com/openstax/tutor-server/pull/1971
> use new courses/students/instructor instead of cumulative counts

- tutor/specs/integration/assignments.spec.js
- tutor/src/models/reference-book/page.js
- tutor/src/screens/assignments/actions.js
- tutor/src/screens/assignments/builder.js
- tutor/src/screens/assignments/points.js
- tutor/src/screens/assignments/step.js
- tutor/src/screens/assignments/ux.js
- tutor/src/screens/assignments/validations.js
Moves the steps and actions into separate classes from the main UX to segregate the logic
> WRM Steps and actions

- tutor/scripts/test-server/backend/bootstrap.js
- tutor/scripts/test-server/backend/exercises.js
- tutor/scripts/test-server/backend/task-plans.js
- tutor/specs/integration/assignments.spec.js
- tutor/specs/models/task-plans/teacher/tasking.spec.js
- tutor/src/api/index.js
- tutor/src/models/task-plans/teacher/plan.js
- tutor/src/models/task-plans/teacher/tasking.js
- tutor/src/screens/assignments/details.js
- tutor/src/screens/assignments/step.js
- tutor/src/screens/assignments/tasking.js
- tutor/src/screens/assignments/ux.js
Needs some UX work to get into columns properly and style labels
> enable section toggle and set dates using selector

- tutor/specs/components/__snapshots__/date-time-input.spec.js.snap
- tutor/src/components/date-time-input.js
- tutor/src/screens/assignments/builder.js
- tutor/src/screens/assignments/details.js
- tutor/src/screens/assignments/new-tooltip.js
- tutor/src/screens/assignments/styles.scss
- tutor/src/screens/assignments/tasking.js
- tutor/src/theme.js
Adds date time selector styles + styles for general builder and section selectors. Also adds "new" tooltips.
> add styling to assignment builder date time and section selectors

- tutor/src/screens/assignments/builder.js
- tutor/src/screens/assignments/details.js
> Make instructions a textarea

- tutor/resources/styles/components/course-roster.scss
- tutor/scripts/test-server/backend.js
- tutor/scripts/test-server/backend/courses.js
- tutor/specs/integration/assignments.spec.js
- tutor/src/components/radio-input.jsx
- tutor/src/components/timezone-modal.js
- tutor/src/screens/assignments/change-timezone.js
- tutor/src/screens/assignments/details.js
- tutor/src/screens/assignments/new-tooltip.js
- tutor/src/screens/course-roster/styles.scss
- tutor/src/screens/course-settings/index.jsx
Also fix zindex and overlap issues with the tooltips.
> move timezone modal into a reusable component, add to assignment builder

- tutor/scripts/test-server/backend/grading-templates.js
- tutor/specs/integration/assignments.spec.js
- tutor/src/screens/assignments/details.js
- tutor/src/screens/assignments/ux.js
- tutor/src/theme.js
Adds the template modal to the assignment builder, allowing newly created templates to be selected at assignment during create and edit.
> Hook up add new template within builder

- package.json
- shared/src/model/exercise.js
- tutor/src/models/exercises.js
- tutor/src/models/task-plans/teacher/plan.js
- tutor/src/routes.js
- tutor/src/screens/assignments/index.js
- tutor/src/screens/grading/details.js
- tutor/src/screens/grading/index.js
- tutor/src/screens/grading/overview.js
- tutor/src/screens/grading/scores.js
- tutor/src/screens/grading/styles.scss
- tutor/src/screens/grading/ux.js
- yarn.lock
Doesn't really do anything yet other than display the exercises in a table.  Needs styling as well
> add bare-bones grading screen

- tutor/resources/styles/variables/book-content.scss
no screenshot since we don't have the book yet.  The colors will probably be tweaked further once we have content
> add appearance code for entrepreneurship

- tutor/resources/styles/components/choices-listing.scss
- tutor/specs/models/courses/offerings.spec.js
- tutor/specs/screens/new-course/__snapshots__/select-dates.spec.jsx.snap
- tutor/specs/screens/new-course/select-dates.spec.jsx
- tutor/src/components/choices-listing.jsx
- tutor/src/models/course/offerings/offering.js
- tutor/src/screens/new-course/select-dates.jsx
- tutor/src/screens/new-course/styles.scss
> Disable new courses past this summer

- tutor/specs/integration/assignments.spec.js
- tutor/specs/models/task-plans/teacher.spec.js
- tutor/specs/models/task-plans/teacher/tasking.spec.js
- tutor/specs/screens/assignment-builder/homework.spec.js
- tutor/specs/screens/assignment-builder/homework/add-exercises.spec.js
- tutor/specs/screens/assignment-builder/homework/choose-exercises.spec.js
- tutor/specs/screens/assignment-builder/mini-editor/editor.spec.js
- tutor/specs/screens/assignment-builder/reading.spec.js
- tutor/src/models/task-plans/teacher/plan.js
- tutor/src/models/task-plans/teacher/tasking.js
- tutor/src/screens/assignment-builder/form.js
- tutor/src/screens/assignments/points.js
- tutor/src/screens/assignments/ux.js
- tutor/src/screens/grading/ux.js
Enables saving homeworks, needs https://github.com/openstax/tutor-server/pull/1988
> Set exercises with array of points

- tutor/resources/styles/components/exercise-preview.scss
- tutor/src/helpers/string.js
- tutor/src/screens/assignments/points.js
> style points display to more closely match mockup

- tutor/src/components/book-menu/menu.jsx
> Remove duplicate chapterSection, fix padding for items not in menu

- shared/src/components/icon.js
- tutor/specs/factories/task-plan-stats.js
- tutor/src/models/course/student.js
- tutor/src/models/scores/task-result.js
- tutor/src/models/task-plans/teacher/plan.js
- tutor/src/models/task-plans/teacher/stats.js
- tutor/src/screens/grading/exercise-type.js
- tutor/src/screens/grading/overview.js
- tutor/src/screens/grading/scores-data-sorter.js
- tutor/src/screens/grading/scores-ux.js
- tutor/src/screens/grading/scores.js
- tutor/src/screens/grading/ux.js
- tutor/src/theme.js
needs quite a bit of styling and not sure what to put for some of the fields yet
> Add scores to WRM 

- tutor/src/components/course-period-select.js
- tutor/src/components/homework-questions.js
- tutor/src/components/template-modal.js
- tutor/src/screens/assignment-edit/points.js
- tutor/src/screens/assignment-review/index.js
- tutor/src/screens/assignment-review/overview.js
- tutor/src/screens/assignment-review/scores.js
- tutor/src/theme.js
More of a snapshot, but something for me to refine and build on when adding more of the spec features in there.
> update questions and table styles

- tutor/specs/factories/offering.js
- tutor/specs/models/courses/onboarding/preview.spec.js
- tutor/specs/screens/new-course/__snapshots__/select-course.spec.jsx.snap
- tutor/src/components/onboarding/display-preview-message.js
- tutor/src/components/onboarding/nags.js
- tutor/src/models/course.js
- tutor/src/models/course/offerings/index.js
- tutor/src/models/course/offerings/offering.js
- tutor/src/models/course/offerings/previews.js
- tutor/src/models/course/onboarding/preview.js
> Use preview_available flag, display a custom message on them

- tutor/src/screens/assignment-review/scores.js
> add table definitions

- tutor/specs/helpers/analytics.spec.js
- tutor/specs/models/user/__snapshots__/menu.spec.js.snap
- tutor/specs/screens/teacher-dashboard/header.spec.jsx
- tutor/src/helpers/analytics.js
- tutor/src/helpers/routes-and-destinations.js
- tutor/src/models/user/menu.js
- tutor/src/routes.js
- tutor/src/screens/gradebook/sorting-icon.js
- tutor/src/screens/gradebook/student-data-sorter.js
- tutor/src/screens/gradebook/table.js
- tutor/src/screens/gradebook/task-result-cell.js
- tutor/src/screens/gradebook/ux.js
- tutor/src/screens/teacher-dashboard/header.jsx
- tutor/src/screens/teacher-dashboard/plan-details.jsx
Hooks up the sort icons and type/points column views
> Sort rows and re-arrange columns

- tutor/src/screens/assignment-review/scores.js
- tutor/src/theme.js
> add triangle display for dropped and extension states

- tutor/specs/screens/new-course/__snapshots__/select-dates.spec.jsx.snap
- tutor/src/components/book-page.js
- tutor/src/screens/new-course/select-dates.jsx
Otherwise you get multiple entries in browser history and back button doesn't work correctly
> Don't update browser history after initial scroll

- shared/specs/model/notifications/pollers.spec.js
- shared/src/model/notifications/pollers.js
Otherwise it won't update until the next scheduled poll
> poll immediatly when document becomes visible

- shared/src/components/icon.js
- tutor/resources/styles/global/buttons.scss
- tutor/specs/components/__snapshots__/course-breadcrumb.spec.jsx.snap
- tutor/src/components/course-breadcrumb.jsx
- tutor/src/components/course-period-select.js
- tutor/src/components/search-input.js
- tutor/src/screens/assignment-review/index.js
- tutor/src/screens/assignment-review/overview.js
- tutor/src/screens/assignment-review/scores-ux.js
- tutor/src/screens/assignment-review/scores.js
- tutor/src/screens/gradebook/controls.js
- Adds a `lg` size option for the course breadcrumbs component so we can reuse it here as well with the slightly different presentation
- Get the period selector dropdown toggle styles a little closer to the spec.
- Adds assignment score search and buttons
- Adds overview Grade button (added a new sass entry for this since we'll be using it in other places later) and grading state text
> update assignment review nav

- shared/src/components/question/answer.jsx
- tutor/src/components/homework-questions.js
- tutor/src/screens/assignment-review/overview.js
Adds styles for questions and their responses, and groups responses by the answer.
> Question Review styles

- tutor/specs/components/__snapshots__/date-time-input.spec.js.snap
- tutor/src/components/date-time-input.js
- tutor/src/primitives.js
- tutor/src/screens/assignment-review/grant-extension.js
- tutor/src/screens/assignment-review/overview.js
- tutor/src/screens/assignment-review/scores.js
- tutor/src/screens/assignment-review/ux.js
- tutor/src/vendor.js
> Add extension modal

- tutor/src/models/task-plans/teacher/scores.js
- tutor/src/screens/assignment-review/details.js
- tutor/src/screens/assignment-review/ux.js
- tutor/src/theme.js
> setup most of the assignment review details screen

- shared/src/components/question/answers-table.jsx
- tutor/specs/factories/task-scores.js
- tutor/src/components/question-preview.jsx
- tutor/src/models/task-plans/teacher/scores.js
- tutor/src/screens/assignment-review/drop-questions.js
- tutor/src/screens/assignment-review/scores.js
- tutor/src/screens/assignment-review/ux.js
It isn't saving the drops yet but is displaying at least
> Start of drop questions modal

- tutor/src/screens/grading-templates/editors.js
Style changes to the Grading template: "Select Assignment Type" modal
Card: https://app.zenhub.com/workspaces/openstax-tutor-560aef617a763234615d6a0f/issues/openstax/tutor/881
> update select grading template assignment type modal

- tutor/src/components/course-page.jsx
- tutor/src/models/grading/templates.js
- tutor/src/screens/grading-templates/index.js
- Set some initial template values based on type
- Update landing page text and some styles (don't know the URL for the link yet...)
> Landing page fixes

- tutor/specs/components/__snapshots__/number-input.spec.js.snap
- tutor/specs/integration/grading-templates.spec.js
- tutor/src/components/number-input.js
- tutor/src/components/time-input.js
- tutor/src/screens/grading-templates/editors.js
- fix displaying incorrect instructions on homework type
- change placeholder text by type
- extends ranges and adds stepping by 5
- make disabled number input value hidden
> grading template form fixes

- tutor/specs/integration/grading-templates.spec.js
- tutor/src/screens/grading-templates/editors.js
Thought about putting this into NumberInput, but feels better at this level in case we need NumberInput to support commas or other formats in the future.
> Only accept digits in number input

- tutor/specs/components/__snapshots__/time-input.spec.js.snap
- tutor/specs/integration/grading-templates.spec.js
- tutor/src/components/time-input.js
Bypasses a bug when selecting hour 12 by directly using the 24 hour values in the option.
> Fix time select bug

- tutor/specs/integration/assignment-review.spec.js
- tutor/src/screens/assignment-edit/preview-tooltip.js
- tutor/src/screens/assignment-review/details.js
- tutor/src/theme.js
> add grading template preview to assignment review

- shared/src/components/html.js
- tutor/src/components/navbar/context.js
- tutor/src/components/tutor-layout.js
- tutor/src/screens/qa-view/index.jsx
- tutor/src/screens/qa-view/ux.js
- tutor/src/screens/reference-book/index.jsx
- tutor/src/screens/reference-book/ux.js
When back button was clicked you could end up with main tutor content but reference book navbar
> Reset navbar when going from ref book to main tutor

- tutor/specs/components/onboarding/__snapshots__/preview-only-warning.spec.jsx.snap
- tutor/specs/components/onboarding/__snapshots__/second-session-warning.spec.jsx.snap
- tutor/specs/components/tours/custom/__snapshots__/instructor-welcome-to-tutor.spec.jsx.snap
- tutor/src/components/onboarding/free-trial-activated.jsx
- tutor/src/components/onboarding/free-trial-ended.jsx
- tutor/src/components/onboarding/preview-only-warning.jsx
- tutor/src/components/onboarding/second-session-warning.jsx
- tutor/src/components/tours/custom/common.jsx
- tutor/src/components/tours/custom/instructor-welcome-to-tutor.jsx
- tutor/src/models/course/onboarding/preview.js
- tutor/src/models/course/ux.js
Tutor's planning to be mostly free for next semester
> Hide create course and cost messages

- tutor/src/screens/assignment-edit/builder.js
- tutor/src/screens/assignment-edit/index.js
> add breadcrumbs in assignment builder

- tutor/specs/factories/task-scores.js
- tutor/specs/integration/assignment-grade.spec.js
- tutor/src/helpers/string.js
- tutor/src/models/task-plans/teacher/scores.js
- tutor/src/screens/assignment-grade/student.js
- tutor/src/screens/assignment-grade/ux.js
- tutor/src/screens/assignment-review/overview.js
- tutor/src/screens/assignment-review/scores.js
- tutor/src/screens/assignment-review/ux.js
- tutor/src/screens/gradebook/weights-ux.js
The scores api's layout has changed slightly, causing breaking
> Fix assignment review

- package.json
- shared/src/components/staxly-animation.js
- tutor/specs/components/__snapshots__/enroll.spec.jsx.snap
- tutor/specs/components/exercises/cards.spec.js
- tutor/specs/helpers/images-complete.spec.js
- tutor/specs/models/user/menu.spec.js
- tutor/src/helpers/images-complete.js
- tutor/src/models/user/menu.js
- tutor/static-loading-screen.js
Also some bug fixes from sentry
> remove research analytics menu option

- package.json
- tutor/resources/styles/components/exercise-preview.scss
- tutor/scripts/test-server/backend/task-plans.js
- tutor/scripts/test-server/backend/tasks.js
- tutor/specs/factories/task-scores.js
- tutor/specs/integration/assignment-edit.spec.js
- tutor/src/api/index.js
- tutor/src/models/task-plans/teacher/grade.js
- tutor/src/models/task-plans/teacher/scores.js
- tutor/src/screens/assignment-grade/student.js
- tutor/src/screens/assignment-grade/ux.js
- tutor/src/screens/task/ux.js
- tutor/src/screens/teacher-dashboard/plan-details.jsx
also adds rudimentary support for saving and returning them in the mock
data.  Once the UI is capable of showing already graded questions,
we should be able to test that they're saved
> WMR: Save grades after the teacher inputs them

- tutor/src/helpers/background-wrapper.js
- tutor/src/screens/assignment-edit/builder.js
- tutor/src/screens/assignment-edit/index.js
- tutor/src/screens/assignment-grade/index.js
- tutor/src/screens/assignment-review/index.js
- tutor/src/screens/gradebook/index.js
Fixes the assignment builder no longer being centered.
> fix builder alignment by bounding child wrapper divs of background

- tutor/src/screens/assignment-review/ux.js
is failing for a brand new assignment in a course that has no students on dev server
> deal with missing period stats

- tutor/scripts/test-server/backend/task-plans.js
- tutor/specs/integration/assignment-review.spec.js
- tutor/src/api/index.js
- tutor/src/components/homework-questions.js
- tutor/src/components/toasts/scores-published.js
- tutor/src/models/task-plans/teacher/tasking.js
- tutor/src/models/toasts.js
- tutor/src/screens/assignment-review/details.js
- tutor/src/screens/assignment-review/drop-questions.js
- tutor/src/screens/assignment-review/grant-extension.js
- tutor/src/screens/assignment-review/index.js
- tutor/src/screens/assignment-review/scores.js
- tutor/src/screens/assignment-review/ux.js
- Make question styles match spec, connect Edit icon to redirect to edit screen
- Connect Publish scores button to API
- Remove the download icon (for now?)
- Add hover tooltips to toolbar buttons
> Connect publish scores to API, fix question styles, add tooltips

- tutor/specs/integration/assignment-review.spec.js
- tutor/src/models/task-plans/teacher/tasking.js
- tutor/src/screens/assignment-review/details.js
- tutor/src/screens/assignment-review/grading-block.js
- tutor/src/screens/assignment-review/index.js
- tutor/src/screens/assignment-review/overview.js
- tutor/src/screens/assignment-review/publish-scores.js
- tutor/src/screens/assignment-review/scores.js
- tutor/src/screens/assignment-review/ux.js
- Update grading block header based on if Grading button is being shown
- Add extra states based on Gradeable answers and Publishable scores
- Don't render edit button if past open date
> update publish button and grading block states + some other review area tweaks

- tutor/src/screens/gradebook/table.js
> fix gradebook minmax row ordering

- tutor/src/api/index.js
- tutor/src/models/task-plans/teacher/plan.js
- tutor/src/models/task-plans/teacher/scores.js
- tutor/src/screens/assignment-review/details.js
- tutor/src/screens/assignment-review/grant-extension.js
- tutor/src/screens/assignment-review/overview.js
- tutor/src/screens/assignment-review/ux.js
- tutor/src/screens/teacher-dashboard/plan-details.jsx
The button wasn't actually saving the selections previously
> save when grant extension button is clicked

- package.json
- shared/src/components/icon.js
- tutor/specs/screens/task/__snapshots__/exercise-task-header.spec.js.snap
- tutor/specs/screens/task/__snapshots__/homework.spec.js.snap
- tutor/specs/screens/task/exercise-task-header.spec.js
- tutor/specs/screens/task/steps/__snapshots__/end.spec.js.snap
- tutor/specs/screens/task/steps/__snapshots__/html-content.spec.js.snap
- tutor/specs/screens/task/steps/__snapshots__/reading.spec.js.snap
- tutor/specs/screens/task/steps/exercise-free-response.spec.js
- tutor/src/components/task-progress.js
- tutor/src/components/tutor-layout.js
- tutor/src/helpers/string.js
- tutor/src/screens/assignment-edit/homework/cards.js
- tutor/src/screens/task/breadcrumbs.js
- tutor/src/screens/task/exercise-task-header.js
- tutor/src/screens/task/homework.js
- tutor/src/screens/task/response-validation-ux.js
- tutor/src/screens/task/step/card.js
- tutor/src/screens/task/step/exercise-free-response.js
- tutor/src/screens/task/step/exercise-question.js
- tutor/src/screens/task/step/exercise.js
- tutor/src/screens/task/step/question-stem.js
- yarn.lock
Adding new design for homework progress. Need to add the points the user got for each step.
> Wrm 969 stuent assignment breadcrumbs

- tutor/src/models/scores/task-result.js
- tutor/src/screens/student-gradebook/table.js
- tutor/src/screens/student-gradebook/ux.js
What is left are the icons and the legend. And some CSS in the header. The rest, including the functionality, is done.
> Wrm stud gb design

- tutor/specs/components/__snapshots__/checkbox-input.spec.js.snap
- tutor/specs/components/__snapshots__/radio-input.spec.jsx.snap
- tutor/src/components/checkbox-input.js
- tutor/src/components/radio-input.jsx
- tutor/src/models/task-plans/teacher/dropped_question.js
- tutor/src/models/task-plans/teacher/scores.js
- tutor/src/screens/assignment-review/drop-questions.js
- tutor/src/screens/assignment-review/ux.js
- tutor/src/theme.js
- Allow changing the allocation after dropping
- Wire up the points values and add submit validation state
- Get everything looking like the visual specs
> Drop Questions modal changes

- tutor/resources/styles/components/modals.scss
- tutor/resources/styles/components/modals/error.scss
- tutor/specs/integration/assignment-edit.spec.js
- tutor/specs/models/grading/__snapshots__/templates.spec.js.snap
- tutor/specs/models/task-plans/teacher/tasking.spec.js
- tutor/specs/screens/grading-templates/__snapshots__/card.spec.js.snap
- tutor/specs/screens/grading-templates/__snapshots__/delete-modal.spec.jsx.snap
- tutor/src/components/error-monitoring/handlers.jsx
- tutor/src/components/error-monitoring/index.jsx
- tutor/src/components/homework-questions.js
- tutor/src/components/plan-stats/index.jsx
- tutor/src/helpers/conditional-handlers.jsx
- tutor/src/models/grading/templates.js
- tutor/src/models/task-plans/teacher/plan.js
- tutor/src/models/task-plans/teacher/tasking.js
- tutor/src/screens/assignment-edit/homework/choose-exercises.jsx
- tutor/src/screens/assignment-edit/index.js
- tutor/src/screens/assignment-edit/points.js
- tutor/src/screens/assignment-edit/questions-overview.js
- tutor/src/screens/assignment-edit/step.js
- tutor/src/screens/grading-templates/card.js
- tutor/src/screens/grading-templates/editors.js
- tutor/src/screens/grading-templates/index.js
- tutor/src/screens/grading-templates/link.js
- tutor/src/screens/teacher-dashboard/plan-details.jsx
A bunch of fixes for bugs found during the last round of testing
> WRM fixes II

- tutor/specs/models/task-plans/teacher/tasking.spec.js
- tutor/specs/models/user/__snapshots__/menu.spec.js.snap
- tutor/src/models/user/menu.js
- tutor/src/screens/student-gradebook/index.js
- tutor/src/screens/teacher-gradebook/set-weights-modal.js
- tutor/src/screens/teacher-gradebook/table.js
- tutor/src/screens/teacher-gradebook/ux.js
- tutor/src/screens/teacher-gradebook/weights-ux.js
- yarn.lock
small gradebook fixes:
1. The excel export is still downloading the old format (I checked after deployment)
2.  When changing the course avg weight, the course avg doesn't get updated upon clicking save in the modal. Currently it updates only on refreshing the page. Needs to update the avg on save.
3. Class average and min. and max. scores should show triple dash if data is not available (not NaN, as currently displaying)
4. Clicking on an assignment header should open the Assignment page for that assignment
> Wrm 994 gradebook fixes

- tutor/specs/factories/task-scores.js
- tutor/src/models/task-plans/teacher/scores.js
- tutor/src/screens/assignment-review/scores.js
- tutor/src/screens/assignment-review/ux.js
- Show calculated total averages
- Fix some table CSS issues
- Navigate to task when clicking user name
> Wrm score table averages

- tutor/specs/components/__snapshots__/date-time-input.spec.js.snap
- tutor/specs/components/date-time-input.spec.js
- tutor/src/components/date-time-input.js
- tutor/src/components/icons/extension.js
- tutor/src/components/icons/info.js
- tutor/src/models/task-plans/teacher/scores.js
- tutor/src/screens/assignment-edit/tasking.js
- tutor/src/screens/assignment-review/grant-extension.js
- tutor/src/screens/assignment-review/scores.js
- tutor/src/screens/assignment-review/ux.js
> Grant extension modal fixes

- tutor/src/models/task-plans/teacher/scores.js
- tutor/src/screens/assignment-review/overview.js
- tutor/src/screens/assignment-review/ux.js
- Make question ordering match the headings order
- Display WRQ responses when expanding the card
- Display dashes if something needs to be graded in the heading, show the total completed
- Open the first card on load
> Submission overview fixes

- tutor/src/models/task-plans/teacher/scores.js
Missed this import when fixing the merge conflict.
> import get

- tutor/src/components/icons/extension.js
- tutor/src/models/scores/task-result.js
- tutor/src/models/task-plans/student/task.js
- tutor/src/screens/student-gradebook/index.js
- tutor/src/screens/student-gradebook/table.js
Adding the icons and legend for student gradebook.
> Wrm student gradebook final

- tutor/src/components/homework-questions.js
- tutor/src/models/task-plans/teacher/scores.js
- tutor/src/routes.js
- tutor/src/screens/assignment-grade/ux.js
- tutor/src/screens/assignment-review/overview.js
> show average score and grade button that navigates to specific question

- tutor/src/components/homework-questions.js
- tutor/src/models/task-plans/teacher/scores.js
- tutor/src/routes.js
- tutor/src/screens/assignment-grade/ux.js
- tutor/src/screens/assignment-review/overview.js
- tutor/src/screens/assignment-review/ux.js
Clicking question header scrolls the question into view and expands the responses.
> Scroll question into view

- tutor/resources/styles/components/date-time-input.scss
- tutor/specs/components/__snapshots__/course-breadcrumb.spec.jsx.snap
- tutor/src/components/course-breadcrumb.jsx
- tutor/src/components/text.js
- tutor/src/models/task-plans/teacher/plan.js
- tutor/src/screens/assignment-edit/details-body.js
- tutor/src/screens/assignment-edit/tasking.js
- tutor/src/screens/assignment-edit/ux.js
- tutor/src/screens/assignment-review/details.js
a few fixes for https://github.com/openstax/tutor/issues/1006
> Fixes for assignment editor

- tutor/src/models/task-plans/teacher/scores.js
- tutor/src/screens/assignment-edit/tasking.js
- tutor/src/screens/student-dashboard/cells.js
> Tweak a few wrm things

- tutor/src/components/homework-questions.js
- tutor/src/models/task-plans/teacher/scores.js
- tutor/src/screens/assignment-review/publish-scores.js
> Hide publish scores on non-gradable assignments

- tutor/specs/screens/task/steps/__snapshots__/html-content.spec.js.snap
- tutor/specs/screens/task/steps/__snapshots__/reading.spec.js.snap
- tutor/src/screens/task/step/continue-btn.js
- tutor/src/screens/task/step/exercise-free-response.js
small fixes in student assignments
> Wrm 1009 student assignment fixes

- tutor/src/models/task-plans/teacher/scores.js
- tutor/src/screens/assignment-grade/question.js
Needs https://github.com/openstax/tutor-server/pull/2079 to fix readings
> Fixed question average scores and "out of X" in the grader screen

- shared/src/model/exercise.js
- tutor/src/models/task-plans/teacher/plan.js
As specified in the WRM behavior doc
> Set the default points for WRQ questions to 2.0

- tutor/specs/models/task-plans/student/task.spec.js
- tutor/specs/screens/student-dashboard/__snapshots__/dashboard.spec.jsx.snap
- tutor/specs/screens/student-dashboard/__snapshots__/event-row.spec.jsx.snap
- tutor/specs/screens/student-dashboard/__snapshots__/homework-row.spec.jsx.snap
- tutor/src/models/task-plans/student/task.js
- tutor/src/screens/student-dashboard/cells.js
- tutor/src/screens/student-dashboard/event-row.jsx
- tutor/src/screens/student-dashboard/status-legend.js
- Show step progress for homework
- Show extension icon
- Add some spacing in the columns and fix some alignment issues
> Wrm student fixes

- tutor/src/screens/student-gradebook/table.js
- tutor/src/screens/teacher-gradebook/aggregate-result-cell.js
- tutor/src/screens/teacher-gradebook/min-max-result-cell.js
1. Fix NaN value in class average.
2. Check if task is undefined when getting the min or max score.
> check if task is undefined first

- tutor/src/screens/assignment-grade/questions-bar.js
- tutor/src/screens/assignment-review/scores.js
> fix a typo and add clarifying word to setting

- tutor/src/models/grading/templates.js
- tutor/src/screens/assignment-review/scores.js
Converts late work text to "Per day" and "Per assignment" instead of "Daily" and "Immediately"
> fix late work display text

- tutor/src/screens/teacher-gradebook/aggregate-result-cell.js
- tutor/src/screens/teacher-gradebook/min-max-result-cell.js
- tutor/src/screens/teacher-gradebook/table.js
- tutor/src/screens/teacher-gradebook/task-result-cell.js
- tutor/src/theme.js
> displaying student status for an external assignment in the gradebook

- tutor/src/models/task-plans/teacher/scores.js
- tutor/src/screens/assignment-review/external-scores.js
- tutor/src/screens/assignment-review/index.js
- tutor/src/screens/assignment-review/scores-data-sorter.js
- tutor/src/screens/assignment-review/ux.js
Needs : https://github.com/openstax/tutor-server/pull/2085
> get external assignment scores table ready

- tutor/specs/components/__snapshots__/app.spec.jsx.snap
- tutor/specs/models/courses/offerings.spec.js
- tutor/specs/screens/new-course/__snapshots__/select-course.spec.jsx.snap
- tutor/specs/screens/new-course/__snapshots__/select-dates.spec.jsx.snap
- tutor/specs/screens/new-course/select-dates.spec.jsx
- tutor/src/models/course/offerings/offering.js
- tutor/src/screens/new-course/select-dates.jsx
- tutor/src/screens/new-course/styles.scss
This reverts commit 1b2e024941cf6fe340a9f5721a13c5d176185536.
> re-enable creating fall/winter 2020 courses

- tutor/src/components/lms-info-card.js
- tutor/src/routes.js
- tutor/src/screens/assignment-review/ux.js
- tutor/src/screens/teacher-dashboard/plan-details.jsx
"View Assigmment" button in the assignment details modal should go to the period selected.
> Wrm 1050 assignment modal

- tutor/specs/integration/course.spec.js
- tutor/specs/models/course.spec.js
- tutor/src/components/date-time-input.js
- tutor/src/models/exercises.js
- tutor/src/models/scores/task-result.js
- tutor/src/models/task-plans/teacher/plan.js
- tutor/src/models/task-plans/teacher/scores.js
- tutor/src/screens/assignment-grade/ux.js
- tutor/src/screens/assignment-review/details.js
- tutor/src/screens/assignment-review/drop-questions.js
- tutor/src/screens/assignment-review/grant-extension.js
Fixes https://github.com/openstax/tutor/issues/1049
> more WRM fixes

- tutor/src/screens/task/index.js
this was omitted in the last pr
> go to first unworked step, or instructions

- tutor/src/models/task-plans/teacher/scores.js
We can just use the ungraded_step_count if needed instead.
> Removed unused questions_need_grading field

- tutor/src/models/task-plans/teacher/plan.js
- tutor/src/screens/assignment-grade/questions-bar.js
- tutor/src/screens/assignment-review/grant-extension.js
- tutor/src/screens/teacher-dashboard/plan-details.jsx
> Display Grade/Regrade button using new BE fields

- tutor/src/components/error-monitoring/handlers.jsx
> render messaging when unable to delete the last grading template of type

- tutor/src/screens/assignment-review/details.js
> block editing the questions edit button instead of assignment edit

- tutor/src/screens/assignment-review/overview.js
- Don't render the question footer if it's multiple choice
- Move the grade button to the right
> More submission overview fixes

- tutor/src/components/course-period-select.js
- tutor/src/models/task-plans/teacher/plan.js
- tutor/src/models/time.js
- tutor/src/screens/assignment-edit/builder.js
- tutor/src/screens/assignment-edit/clone/editor.js
- tutor/src/screens/assignment-edit/details-body.js
- tutor/src/screens/assignment-edit/ux.js
> A few fixes to the cloned assignment builder

- tutor/src/screens/task/step/instructions.js
> Fixed typo

- exercises/specs/components/__snapshots__/exercise.spec.js.snap
- exercises/specs/components/tags/__snapshots__/book-selection.spec.js.snap
- exercises/specs/components/tags/__snapshots__/books.spec.js.snap
- exercises/src/components/tags/book-selection.jsx
Per request from the content team
> Added Entrepreneurship, renamed K-12 Physics to HS Physics

- tutor/src/models/scores/task-result.js
- tutor/src/screens/pre-wrm-scores-report/late-work.jsx
all old assignments are past_due, but that doesn't mean they're late.
> fix late triangles on old scores report

- tutor/src/helpers/conditional-handlers.jsx
- tutor/src/screens/pre-wrm-scores-report/weights-ux.js
They should get the new gb regardless of pre wrm state
> Always show students the new grade book, not the old scores

- tutor/specs/screens/grading-templates/__snapshots__/card.spec.js.snap
- tutor/specs/screens/grading-templates/card.spec.js
- tutor/src/models/course.js
- tutor/src/models/grading/templates.js
- tutor/src/screens/assignment-review/index.js
- tutor/src/screens/grading-templates/card.js
- tutor/src/screens/grading-templates/index.js
Otherwise they'll mess with the scores for those courses
> Don't allow creation or modification of pre-wrm grading templates

- tutor/src/screens/student-gradebook/ux.js
- tutor/src/screens/teacher-gradebook/aggregate-result-cell.js
- tutor/src/screens/teacher-gradebook/min-max-result-cell.js
- tutor/src/screens/teacher-gradebook/student-data-sorter.js
- tutor/src/screens/teacher-gradebook/ux.js
Fixes several more spots that were missed
> Use published points and score in grade books

- tutor/src/screens/assignment-review/details.js
> question edit is disabled after *open* date

- tutor/specs/screens/task/response-validation-ux.spec.js
- tutor/src/models/student-tasks/step.js
- tutor/src/screens/task/response-validation-ux.js
- tutor/src/screens/task/step/continue-btn.js
- tutor/src/screens/task/step/exercise-free-response.js
- tutor/src/screens/task/step/exercise-question.js
- tutor/src/screens/task/step/wrq-status.js
- tutor/src/screens/task/ux.js
And change button to read "Next"
> don't update step when teacher is reviewing

- shared/src/model/api.js
- tutor/scripts/test-server/backend/task-plans.js
- tutor/specs/factories/task-scores.js
- tutor/src/screens/assignment-review/ux.js
Otherwise the data is out of date
> refetch scores after questions are dropped

- tutor/src/screens/assignment-review/details.js
> fix typo: OpenStax Beta Tutor -> OpenStax Tutor Beta

- tutor/src/screens/task/step/instructions.js
Fixes "questions" not being possessive
> questions -> question's

- tutor/src/screens/assignment-review/homework-scores.js
- tutor/src/screens/assignment-review/reading-scores.js
- tutor/src/screens/assignment-review/table-elements.js
mostly just copying definitions around
> share comment table elements, ellipsis for long names

- tutor/src/components/homework-questions.js
- tutor/src/models/task-plans/teacher/scores.js
- tutor/src/screens/assignment-review/details.js
- tutor/src/screens/assignment-review/overview.js
- Filter out Tutor questions in Details tab
- Show a letter for the Tutor questions based on sorted index
> Fix tutor questions

- tutor/src/components/icons/extension.js
- tutor/src/screens/assignment-review/grant-extension.js
- tutor/src/screens/assignment-review/ux.js
and also fix the logic for if students are selected
> Make extension modal an observed component

- exercises/resources/styles/global/defaults.scss
> change z-index of stacked modals

- tutor/src/components/homework-questions.js
- tutor/src/models/task-plans/teacher/scores.js
- tutor/src/screens/assignment-review/overview.js
- After some discussion it was decided to remove question number and lettering Tutor questions, making the card heading "OpenStax Tutor Selection"
- Make the "Question" header text for reading questions bold
> Change question headers

- tutor/src/components/toasts/reload.jsx
- tutor/src/models/app.js
- tutor/src/models/feature_flags.js
* Add support for force reloading to dashboard when feature flag is set from BE settings
> Code for pre-wrm release

- tutor/src/models/student-tasks/step.js
- tutor/src/models/student-tasks/task.js
The student task should only use the published points
and doesn't need to do any math when computing them
Fixes this:
Into the correct:
> only use the published fields for calculations

- tutor/src/screens/assignment-review/ux.js
Refetch scores after granting extension so the table gets updated with the new calculations.
> refetch scores after granting extension

- tutor/src/screens/assignment-review/grant-extension.js
Fixes the value checked in Grant Extension's due date validation.
> fix due date validation being before close date

- tutor/src/models/task-plans/teacher/tasking.js
- tutor/src/screens/assignment-edit/tasking.js
Otherwise the the hour and minute will always be what the template specifies
> don't adjust time to match template when set manually

- tutor/src/models/scores/task-result.js
- tutor/src/screens/pre-wrm-scores-report/correctness-value.jsx
Using `published_scores` and `published_points` in pre-wrm course score reports.
> use published_points and published_score in pre-wrm-score-report

- tutor/src/models/task-plans/teacher/plan.js
the BE will remove any extensions not sent in the array
> preserve existing extensions when granting new

- tutor/specs/factories/scores.js
- tutor/src/models/task-plans/teacher/scores.js
- tutor/src/screens/assignment-review/homework-scores.js
- tutor/src/screens/assignment-review/ux.js
Only show in % format and treat HW & Readings identically for display
> use fractional_points field for average scores

- tutor/specs/models/grading/__snapshots__/templates.spec.js.snap
- tutor/specs/screens/grading-templates/__snapshots__/modals.spec.jsx.snap
- tutor/src/screens/assignment-edit/details-body.js
- tutor/src/screens/assignment-edit/preview-tooltip.js
- tutor/src/screens/assignment-edit/tasking.js
Use 1.4rem and #424242 for fields in the assignment builder.
> make builder fields consistent for font size and color

- tutor/src/screens/task/step/instructions.js
- tutor/src/theme.js
Fixes the `TypeError: Cannot read property 'background' of undefined`
from https://github.com/openstax/tutor/issues/1131
> set heading color for practice, deal with unknowns

- .gitignore
- shared/resources/styles/mixins/index.scss
- tutor/src/screens/assignment-edit/homework/cards.js
Use flex. Column-width not working properly in Safari.
Before: 
After:
> Wrm fix assignment builder

- tutor/src/screens/assignment-review/grant-extension.js
- tutor/src/screens/assignment-review/ux.js
If a student is dropped, don't show them in the scores table and grant extension modal.
> Filter out dropped students from scores

- tutor/src/theme.js
fixes border color being undefined
> alias page_practice colors to equal homework

- tutor/src/models/task-plans/teacher/plan.js
- tutor/src/screens/task/step/instructions.js
- tutor/src/theme.js
> Fix practice_worst, add practice instructions

- tutor/specs/screens/assignment-edit/ux.spec.jsx
- tutor/src/screens/assignment-edit/actions.js
- tutor/src/screens/assignment-edit/ux.js
Otherwise plans on a past ecosystem may break
> always send ecosystem id when fetching for assignment

- tutor/resources/styles/book-content/base.scss
> add margin around titles

- tutor/resources/styles/book-content/typography.scss
> add text-align:right style for "right" class

- exercises/specs/components/__snapshots__/exercise.spec.js.snap
- exercises/src/components/exercise/question.jsx
WIP, needs to hide it if it's a MPQ
> Display question stimulus

- tutor/resources/styles/book-content/base.scss
> move captions down a bit, style titles inside them

- tutor/api/user.json
- tutor/specs/components/my-courses.spec.jsx
- tutor/specs/factories/user.js
- tutor/specs/models/user.spec.js
- tutor/src/components/error-monitoring/handlers.jsx
- tutor/src/models/app.js
- tutor/src/models/user.js
needs https://github.com/openstax/tutor-server/pull/2124
> add school_location to isAllowedInstructor check

- tutor/specs/screens/task/__snapshots__/event.spec.js.snap
- tutor/specs/screens/task/__snapshots__/exercise-task-header.spec.js.snap
- tutor/specs/screens/task/__snapshots__/external.spec.js.snap
- tutor/specs/screens/task/__snapshots__/homework.spec.js.snap
- tutor/specs/screens/task/__snapshots__/milestones.spec.js.snap
- tutor/specs/screens/task/__snapshots__/progress.spec.js.snap
- tutor/specs/screens/task/__snapshots__/reading.spec.js.snap
- tutor/specs/screens/task/__snapshots__/task-info.spec.js.snap
- tutor/specs/screens/task/steps/__snapshots__/exercise.spec.js.snap
- tutor/specs/screens/task/steps/__snapshots__/failure.spec.js.snap
- tutor/specs/screens/task/steps/__snapshots__/nudge-message.spec.js.snap
- tutor/src/components/buttons/publish-scores.js
- tutor/src/models/task-plans/teacher/scores.js
- tutor/src/screens/assignment-grade/questions-bar.js
- tutor/src/screens/assignment-grade/ux.js
- tutor/src/screens/assignment-review/grading-block.js
- tutor/src/screens/assignment-review/homework-scores.js
- tutor/src/screens/assignment-review/publish-scores.js
We've decided it should be hidden unless there are scores to publish
> only display publish button for ungraded scores

- tutor/src/components/no-students-message.js
- tutor/src/screens/assignment-review/index.js
> render no student message when showing a period without enrollments

- tutor/src/components/book-menu/menu.jsx
- tutor/src/components/book-page.js
- tutor/src/components/book-part-title.js
- tutor/src/components/exercises/cards.jsx
- tutor/src/components/notes/summary-page.jsx
- tutor/src/components/page-title.js
- tutor/src/components/sections-chooser.jsx
- tutor/src/screens/assignment-edit/homework/cards.js
- tutor/src/screens/assignment-edit/reorder.js
- tutor/src/screens/assignment-edit/select-sections.js
- tutor/src/screens/performance-forecast/chapter.js
- tutor/src/screens/performance-forecast/section.js
- tutor/src/screens/reference-book/book-title.jsx
- tutor/src/screens/reference-book/section-title.jsx
- tutor/src/screens/reference-book/styles/navbar.scss
Content can set the entire title or we have to build it if it's plain text
> either construct or display book part titles as-is

- tutor/src/components/checkbox-input.js
- tutor/src/screens/assignment-review/grant-extension.js
- tutor/src/screens/assignment-review/ux.js
- Change some layout and checkbox inputs to match the design doc
- Add a search field (need a separate student list here otherwise the scores UI under the modal changes as well while searching.)
> update extensions modal with search and design changes

- tutor/src/components/book-part-title.js
Some content has it in places that lack a os-number making it looks strange
> remove : from os-divider

- exercises/specs/components/tags/aplo.spec.js
- exercises/src/components/tags/aplo.js
> Updated the regex and helper text for APLO tags

- tutor/src/models/user.js
> Don't block instructors if they end up with unknown_school_location or undefined

- tutor/src/components/book-part-title.js
- tutor/src/screens/task/ux.js
Sometimes steps get removed when there's not a replacement for placeholders
> choose another step if the current one is invalid

- tutor/specs/integration/student-task.spec.js
- tutor/src/models/student-tasks/task.js
- tutor/src/screens/task/index.js
- tutor/src/screens/task/ux.js
When placeholder steps are removed the current step might become invalid
> redirect to first unworked when step is removed

- tutor/specs/models/reference-book/node.spec.js
- tutor/src/models/reference-book/node.js
> extract and test title text

- tutor/resources/styles/book-content/base.scss
> bold table title in eship

- tutor/src/models/user.js
Maybe we should have made just a flag come from the BE...
> Allow home school users in Tutor

- shared/specs/helpers/fake-window.js
- tutor/specs/components/responsive.spec.js
- tutor/src/components/responsive.js
Switches between desktop, tablet and mobile
Breakpoints may need tweaked, i'm not sure what's been specced for them
> a responsive view switcher component

- tutor/specs/integration/assignment-review.spec.js
- tutor/src/components/no-students-message.js
- tutor/src/models/exercises.js
- tutor/src/models/task-plans/teacher/plan.js
- tutor/src/models/task-plans/teacher/scores.js
- tutor/src/screens/assignment-edit/ux.js
- tutor/src/screens/assignment-review/details.js
- tutor/src/screens/assignment-review/index.js
- tutor/src/screens/assignment-review/overview.js
- tutor/src/screens/assignment-review/ux.js
Choose between popup details only editor and redirect to full editor depending on task plan open status.
Also load questions for overview tab from task plan so they'll always show up regardless of enrollment status
> use single assignment edit button

- tutor/specs/components/__snapshots__/tutor-layout.spec.js.snap
- tutor/src/components/app.jsx
- tutor/src/components/impersonation-warning.js
- tutor/src/components/tutor-layout.js
- tutor/src/models/app.js
Needs https://github.com/openstax/tutor-server/pull/2155
> display red warning bar when impersonating a user

- tutor/src/screens/assignment-review/reading-scores.js
- tutor/src/screens/assignment-review/table-elements.js
- tutor/src/screens/assignment-review/ux.js
- tutor/src/screens/teacher-gradebook/index.js
> Rd assignment scores performance

- tutor/specs/screens/student-dashboard/__snapshots__/dashboard.spec.jsx.snap
- tutor/specs/screens/student-dashboard/__snapshots__/event-row.spec.jsx.snap
- tutor/specs/screens/student-dashboard/__snapshots__/homework-row.spec.jsx.snap
- tutor/src/screens/student-dashboard/cells.js
- tutor/src/screens/student-dashboard/dashboard.jsx
- tutor/src/screens/student-dashboard/event-row.jsx
- tutor/src/screens/student-dashboard/events-panel.jsx
- tutor/src/screens/student-dashboard/status-legend.js
- tutor/src/screens/student-dashboard/styles/card.scss
- tutor/src/screens/student-dashboard/styles/dashboard.scss
- tutor/src/screens/student-dashboard/styles/task.scss
- tutor/src/screens/student-dashboard/this-week-panel.jsx
> Student course dashboard responsiveness

- tutor/specs/components/__snapshots__/related-content-link.spec.js.snap
- tutor/specs/components/__snapshots__/sections-filter.spec.jsx.snap
- tutor/specs/helpers/string.spec.js
- tutor/specs/screens/task/steps/__snapshots__/footer.spec.js.snap
- tutor/src/components/notes/sections-filter.jsx
- tutor/src/components/paging-navigation.jsx
- tutor/src/components/related-content-link.js
- tutor/src/helpers/string.js
> fix areas where html titles were showing

- tutor/src/theme.js
Updated these to match the mobile and tablet number changes.
> fix only.mobile and only.tablet breakpoint numbers

- tutor/src/screens/task/response-validation-ux.js
And only save if there's changes to save
> Only display re-submit if it was submitted before

- tutor/specs/integration/assignment-edit.spec.js
- tutor/src/screens/assignment-review/reading-scores.js
1. Add missing legend.
2. Make the Completed, Correct, Incorrect cells wider.
> Rd assignment scores missing legend

- tutor/specs/components/__snapshots__/tutor-layout.spec.js.snap
- tutor/specs/screens/task/steps/__snapshots__/end.spec.js.snap
- tutor/specs/screens/task/steps/__snapshots__/html-content.spec.js.snap
- tutor/specs/screens/task/steps/__snapshots__/reading.spec.js.snap
- tutor/src/components/navbar.js
- tutor/src/components/task-progress.js
- tutor/src/components/tutor-layout.js
- tutor/src/screens/task/exercise-task-header.js
- tutor/src/screens/task/step/card.js
> Mobile hide navbar

- tutor/src/screens/task/step/exercise-free-response.js
- tutor/src/screens/task/step/nudge-message.js
> hw nude responsiveness

- shared/resources/styles/components/question.scss
- tutor/resources/styles/book-content/base.scss
- tutor/src/components/paging-navigation.jsx
- tutor/src/screens/task/step/exercise-question.js
- Fix an issue with tables that are too wide by having them scroll on the X axis.
- Answer on MCQs becomes Submit
- Fix a padding issue on MCQ answer bubble letters in mobile Safari
> More responsive reading assignment changes

- tutor/specs/integration/student-task.spec.js
- tutor/specs/screens/task/steps/__snapshots__/end.spec.js.snap
- tutor/specs/screens/task/steps/__snapshots__/html-content.spec.js.snap
- tutor/specs/screens/task/steps/__snapshots__/reading.spec.js.snap
- tutor/src/components/task-progress.js
- tutor/src/screens/task/exercise-task-header.js
- tutor/src/screens/task/step/card.js
Mobile:
Tablet:
Fix max-width of task card:
> Hw overview responsiveness

- tutor/src/components/late-points-info.js
- tutor/src/screens/task/milestones.js
- tutor/src/screens/task/progress.js
> Responsive assignment overview

- tutor/specs/screens/task/response-validation-ux.spec.js
- tutor/specs/screens/task/steps/__snapshots__/exercise.spec.js.snap
- tutor/specs/screens/task/steps/exercise-question.spec.js
- tutor/specs/screens/task/steps/exercise.spec.js
- tutor/src/screens/task/response-validation-ux.js
- tutor/src/screens/task/step/exercise-free-response.js
- tutor/src/screens/task/ux.js
And only save text when it's changed
> Only disable free response button when it's blank

- exercises/resources/styles/variables.scss
- shared/resources/styles/mixins/questions.scss
- tutor/resources/styles/book-content/base.scss
- tutor/resources/styles/book-content/index.scss
- tutor/resources/styles/book-content/mixins.scss
- tutor/resources/styles/book-content/page.scss
- tutor/resources/styles/components/notes/note.scss
- tutor/resources/styles/mixins/performance-forecast.scss
- tutor/resources/styles/variables.scss
- tutor/src/components/header.js
- tutor/src/screens/performance-forecast/index.js
- tutor/src/screens/performance-forecast/student.js
- tutor/src/screens/performance-forecast/styles.scss
- tutor/src/screens/performance-forecast/styles/heading.scss
- tutor/src/screens/performance-forecast/styles/responsive.scss
- tutor/src/screens/performance-forecast/teacher-student.js
- tutor/src/screens/performance-forecast/teacher.js
- tutor/src/screens/performance-forecast/weaker-panel.js
- tutor/src/screens/student-dashboard/styles/progress-guide.scss
- tutor/src/screens/task/exercise-task-header.js
> Pf responsiveness

- tutor/specs/components/__snapshots__/related-content-link.spec.js.snap
- tutor/specs/screens/task/steps/__snapshots__/footer.spec.js.snap
- tutor/src/components/related-content-link.js
Small indentation fix for task nudges
> fix small margin in the nudge message

- tutor/resources/styles/components/modals/onboarding.scss
> styling for onboarding nag

- exercises/resources/styles/variables.scss
- shared/resources/styles/mixins/questions.scss
- tutor/resources/styles/book-content/base.scss
- tutor/resources/styles/book-content/index.scss
- tutor/resources/styles/book-content/mixins.scss
- tutor/resources/styles/book-content/page.scss
- tutor/resources/styles/components/notes/note.scss
- tutor/resources/styles/components/payments.scss
- tutor/resources/styles/mixins/performance-forecast.scss
- tutor/resources/styles/variables.scss
- tutor/specs/components/payments/__snapshots__/manage.spec.jsx.snap
- tutor/specs/screens/task/steps/__snapshots__/end.spec.js.snap
- tutor/src/components/buttons/back-button.js
- tutor/src/components/header.js
- tutor/src/components/payments/manage.jsx
- tutor/src/helpers/backInfo.js
- tutor/src/models/user/menu.js
- tutor/src/screens/performance-forecast/index.js
- tutor/src/screens/performance-forecast/student.js
- tutor/src/screens/performance-forecast/styles.scss
- tutor/src/screens/performance-forecast/styles/heading.scss
- tutor/src/screens/performance-forecast/styles/responsive.scss
- tutor/src/screens/performance-forecast/teacher-student.js
- tutor/src/screens/performance-forecast/teacher.js
- tutor/src/screens/performance-forecast/weaker-panel.js
- tutor/src/screens/student-dashboard/styles/progress-guide.scss
- tutor/src/screens/task/exercise-task-header.js
> Manage payment screen responsiveness

- tutor/resources/styles/components/tours.scss
- tutor/src/models/tour/actions/base.js
- tutor/src/models/tour/actions/hover-exercise.js
Discovered that 'el' getter was broken and exercise card class was incorrect
> Fix tour on QL cards

- tutor/resources/styles/components/modals/terms.scss
- tutor/resources/styles/variables.scss
- tutor/src/components/terms-modal.jsx
> add responsiveness to the term screen

- tutor/specs/components/__snapshots__/change-student-id.spec.jsx.snap
- tutor/specs/components/__snapshots__/enroll.spec.jsx.snap
- tutor/src/components/change-student-id.jsx
- tutor/src/components/enroll/student-id.jsx
Missed these changes earlier on #3237
> remove asterisk and other messaging around required

- tutor/src/models/appearance_codes.js
- tutor/src/screens/qa-view/appearance-selector.js
- tutor/src/screens/qa-view/ecosystem-selector.jsx
- tutor/src/screens/qa-view/exercise-card.jsx
- tutor/src/screens/qa-view/exercises.jsx
- tutor/src/screens/qa-view/styles.scss
- tutor/src/screens/qa-view/ux.js
Adds the drop-down to set appearance code, adds the context to exercise preview
> Add appearance_code, display context

- tutor/specs/components/__snapshots__/app.spec.jsx.snap
- tutor/specs/components/__snapshots__/tutor-layout.spec.js.snap
- tutor/specs/components/payments/__snapshots__/manage.spec.jsx.snap
- tutor/specs/models/user/__snapshots__/menu.spec.js.snap
- tutor/src/models/user/menu.js
Specifically needed for the payments screen but would be good to have elsewhere
> Always add "MyCourses" to menu

- tutor/src/components/time.js
- tutor/src/helpers/time.js
> remove timezone offset

- tutor/resources/styles/book-content/base.scss
- tutor/specs/components/payments/__snapshots__/manage.spec.jsx.snap
- tutor/specs/screens/task/steps/__snapshots__/end.spec.js.snap
- tutor/specs/screens/task/steps/__snapshots__/html-content.spec.js.snap
- tutor/specs/screens/task/steps/__snapshots__/reading.spec.js.snap
- tutor/src/components/header.js
- tutor/src/components/paging-navigation.jsx
- tutor/src/screens/task/exercise-task-header.js
- tutor/src/screens/task/step/card.js
- Fix an issue with table width
- Remove spacing between HW table and card content
- Remove extra spacing on reading exercise card
- Fix z-index of mobile footer letting popup content appear above
> mobile reading fixes

- tutor/specs/screens/student-dashboard/__snapshots__/dashboard.spec.jsx.snap
- tutor/specs/screens/student-dashboard/__snapshots__/event-row.spec.jsx.snap
- tutor/specs/screens/student-dashboard/__snapshots__/homework-row.spec.jsx.snap
- tutor/src/screens/student-dashboard/cells.js
> remove break-all text style

- tutor/src/flux/performance-forecast.js
- tutor/src/screens/student-dashboard/progress-guide.js
Don't use the placeholder value on student dashboard
> Only display bars that have "real" clues

- tutor/specs/components/__snapshots__/app.spec.jsx.snap
- tutor/specs/components/__snapshots__/tutor-layout.spec.js.snap
- tutor/src/components/navbar/menus.js
Restore original ordering, will consider switching it at end of semester
> switch actions and help menu order

- tutor/resources/styles/components/modals/onboarding.scss
> fix trial-activated nag responsiveness

- tutor/resources/styles/components/top-nav-bar.scss
- tutor/specs/components/payments/__snapshots__/manage.spec.jsx.snap
- tutor/specs/screens/task/steps/__snapshots__/end.spec.js.snap
- tutor/src/components/payments/manage.jsx
- tutor/src/helpers/backInfo.js
- tutor/src/models/purchases.js
Changes the padding on the table on different sizes
> Adjust payments management screen 

- .github/workflows/healthcheck.yml
- tutor/scripts/health-checks/create-assignment.js
- tutor/scripts/health-checks/login.js
- tutor/specs/components/__snapshots__/app.spec.jsx.snap
- tutor/specs/components/__snapshots__/tutor-layout.spec.js.snap
- tutor/src/components/navbar.js
- tutor/src/components/navbar/nav.js
- tutor/src/components/navbar/student-pay-now-btn.jsx
- tutor/src/components/navbar/student-payment-bar.js
- tutor/src/components/tutor-layout.js
- tutor/src/models/window-size.js
- tutor/src/theme.js
> add 2nd toolbar with mobile pay info and button

- tutor/src/components/payments/manage.jsx
"refunding" must be observable Otherwise the component won't re-render when its set
> Fix request refund button

- tutor/resources/styles/components/tours/value-prop.scss
- tutor/specs/components/__snapshots__/course-breadcrumb.spec.jsx.snap
- tutor/specs/components/__snapshots__/tutor-layout.spec.js.snap
- tutor/specs/components/tours/custom/__snapshots__/instructor-welcome-to-tutor.spec.jsx.snap
- tutor/specs/models/tour/step.spec.js
- tutor/specs/screens/student-dashboard/__snapshots__/dashboard.spec.jsx.snap
- tutor/specs/screens/student-dashboard/__snapshots__/homework-row.spec.jsx.snap
- tutor/src/components/responsive.js
- tutor/src/components/tours/custom/common.jsx
- tutor/src/models/tour/step.js
- tutor/src/models/window-size.js
- tutor/src/tours/student-dashboard.json
This also skips the new student tour after the initial "Welcome" modal. Steps can be skipped by breakpoint by adding "mobile", "tablet" or "desktop" to a disabledBreakpoints array in the step, which will cause isViewable to be false.
----- | ----- | -----
> Responsive welcome screen

- shared/src/api/action-adapter.js
- shared/src/api/collections.js
- shared/src/model/api.js
- tutor/scripts/test-server/backend/courses.js
- tutor/scripts/test-server/backend/grading-templates.js
- tutor/scripts/test-server/backend/task-plans.js
- tutor/scripts/test-server/backend/tasks.js
- tutor/src/api/index.js
So requests don't get blocked by parental control
Hopefully I got them all
> Replaced all PATCH requests with PUT

- tutor/src/helpers/analytics.js
> add google tag manager

- shared/resources/styles/components/notifications-bar.scss
- tutor/resources/styles/global/notifications-bar.scss
- tutor/specs/components/__snapshots__/app.spec.jsx.snap
- tutor/specs/components/__snapshots__/tutor-layout.spec.js.snap
- tutor/src/components/tutor-layout.js
- Reduces the font size and general notification bar size on tablet and mobile
- Increases the dismiss icon size on desktop (from Invision specs)
- Tweaks the alignment of the mobile-menu and user-menu in the navbar to better align with notification dismiss icon and other dashboard content
----- | ----- | -----
> Responsive notification bar changes

- tutor/src/models/task-plans/teacher/scores.js
- tutor/src/screens/assignment-grade/answer.js
- tutor/src/screens/assignment-grade/ux.js
1. Disable the points and comments text field area if the student has an extension in the future.
2. Show a tooltip of when the instructor can grade the student.
> 403 extension grading

- .github/workflows/build.yml
- README.md
- bin/build
- package.json
- tutor/specs/models/app.spec.js
- tutor/src/models/app.js
- webpack.config.js
- yarn.lock
I might have to switch to building on push to test...
> Added build workflow

- .github/workflows/build.yml
- README.md
> Don't try to set s3 object ACL

- bin/build
it's needed by the sensible build scripts
> restore rev-manifest generation

- .github/workflows/build.yml
The S3 command was receiving the RELEASE_VERSION env var instead of the build command
> Make sure the build command receives the RELEASE_VERSION env var

- webpack.config.js
Goes along with https://github.com/openstax/exercises/pull/294
> only allow tutor to use multiple entry points

- tutor/src/screens/performance-forecast/chapter.js
- tutor/src/screens/performance-forecast/student.js
- tutor/src/screens/performance-forecast/teacher-student.js
> filter out sections that have non-real clues

- tutor/resources/styles/components/payments.scss
- tutor/specs/components/__snapshots__/tutor-layout.spec.js.snap
- tutor/src/components/navbar/student-pay-now-btn.jsx
- tutor/src/components/tutor-layout.js
- tutor/src/models/payments.js
> hide payment bar when user is taking an assignment

- shared/resources/styles/components/notifications-bar.scss
- shared/src/components/notifications/email.js
- shared/src/model/notifications/pollers.js
- tutor/resources/styles/global/notifications-bar.scss
Fixes not displaying the full verify email text on desktop.
> Fix mobile verify text

- tutor/specs/integration/student-task.spec.js
- tutor/src/helpers/string.js
- tutor/src/screens/task/response-validation-ux.js
- tutor/src/screens/task/step/exercise-free-response.js
1. Show red border color in the response text area input.
2. Show word info error message.
3. Disable Submit button.
> 500 word limit

- tutor/specs/screens/student-dashboard/__snapshots__/dashboard.spec.jsx.snap
- tutor/specs/screens/student-dashboard/__snapshots__/event-row.spec.jsx.snap
- tutor/specs/screens/student-dashboard/__snapshots__/homework-row.spec.jsx.snap
- tutor/specs/screens/student-dashboard/event-row.spec.jsx
- tutor/src/screens/student-dashboard/event-row.jsx
- tutor/src/screens/student-dashboard/task-info.js
Add a link to the score number in the dashboard so students can click on it and go to their scores screen.
> Add gradebook link to the score number in dashboard

- tutor/src/screens/assignment-review/index.js
Fixes the grading block button that was not doing anything when they were clicked.
> Fix grading block buttons

- tutor/specs/integration/assignment-edit.spec.js
- tutor/specs/integration/assignment-review.spec.js
- tutor/src/screens/assignment-edit/controls.js
- tutor/src/screens/assignment-edit/ux.js
Disable if:
1. No title is given to the assignment
2. Dates are incorrect
3. Assignment is published
> Disable save draft button

- tutor/src/models/task-plans/teacher/plan.js
- tutor/src/screens/question-library/index.jsx
- tutor/src/screens/teacher-dashboard/index.jsx
- tutor/src/screens/teacher-dashboard/plan-details.jsx
> Show sections assigned in the plan details modal

- exercises/specs/components/__snapshots__/exercise.spec.js.snap
- exercises/src/components/tags/blooms.jsx
> remove invalid bloom level 7

- tutor/src/components/homework-questions.js
- tutor/src/screens/assignment-review/details.js
- tutor/src/screens/assignment-review/overview.js
- tutor/src/screens/assignment-review/section-link.js
- tutor/src/screens/assignment-review/ux.js
- tutor/src/screens/teacher-dashboard/plan-details.jsx
> Show assigned sections in details overview

- tutor/src/components/homework-questions.js
- tutor/src/screens/assignment-review/details.js
- tutor/src/screens/assignment-review/overview.js
- tutor/src/screens/assignment-review/section-link.js
> show exercise tags on question, fix course id link

- tutor/resources/styles/components/modals.scss
- tutor/specs/screens/task/index.spec.js
- tutor/src/components/course-not-found-warning.js
- tutor/src/helpers/conditional-handlers.jsx
- tutor/src/models/student-tasks/task.js
- tutor/src/screens/reference-book/index.jsx
- tutor/src/screens/task/index.js
- tutor/src/screens/task/practice.js
- tutor/src/screens/task/step/failure.js
Also updates the message to address 2 cases if they're not a member of course, or maybe they are a member but the material is sensitive.
> Display course not found warning

- exercises/specs/components/__snapshots__/exercise.spec.js.snap
- exercises/src/app.jsx
- exercises/src/components/exercise/question-format-type.jsx
- exercises/src/components/tags/question-type.jsx
- exercises/src/components/tags/single-dropdown.jsx
- exercises/src/components/tags/wrapper.jsx
- shared/src/model/exercise.js
- shared/src/model/exercise/question.js
Disable changing the controls when doing so would make question invalid
> OpenEnded questions must be of type practice

- tutor/src/screens/assignment-review/reading-scores.js
Before due date:
After due date:
> fix total scores in RD assignment

- tutor/src/models/student-tasks/task.js
- tutor/src/screens/task/exercise-task-header.js
For practice tasks, the due and closes dates are null
> don't use date when it's null, hide it on header

- tutor/src/models/task-plans/teacher/dropped_question.js
- tutor/src/models/task-plans/teacher/scores.js
- tutor/src/screens/assignment-grade/answer.js
- tutor/src/screens/assignment-grade/question.js
- tutor/src/screens/assignment-grade/questions-bar.js
- tutor/src/screens/assignment-grade/ux.js
Show that the question was dropped in the grader screen.
* Requires BE change: https://github.com/openstax/tutor-server/pull/2207
> Grader dropped questions

- tutor/specs/components/exercises/details.spec.jsx
- tutor/specs/factories/index.js
- tutor/src/components/exercises/details.jsx
- tutor/src/models/task-plans/teacher/scores.js
happened because the previous page would be undefined in the unmount
> Fix "no chapter for undefined" bug

- tutor/resources/styles/components/paging-navigation.scss
- tutor/resources/styles/components/top-nav-bar.scss
- tutor/specs/components/__snapshots__/paging-navigation.spec.jsx.snap
- tutor/specs/screens/reference-book/index.spec.js
- tutor/src/components/notes/summary-toggle.jsx
- tutor/src/components/paging-navigation.jsx
- tutor/src/screens/reference-book/page-navigation.jsx
- tutor/src/screens/reference-book/styles.scss
> add responsiveness to the Browse my book screen

- tutor/src/screens/assignment-review/overview.js
- tutor/src/theme.js
> change color of header

- webpack.config.js
Feel free to change the key from `version` to anything you want to call it if you want to make it more explicit
> Added release version to assets manifest

- tutor/src/models/task-plans/teacher/plan.js
Otherwise it'll attempt to republish over and over when updating
> reset is_publish_requested to false after saving

- tutor/src/screens/teacher-gradebook/index.js
> add flex-flow column for gradebook table container

- tutor/specs/components/notes/__snapshots__/note-card.spec.js.snap
- tutor/specs/components/notes/__snapshots__/summary-popup.spec.js.snap
- tutor/specs/components/notes/note-card.spec.js
- tutor/specs/screens/task/steps/__snapshots__/footer.spec.js.snap
- tutor/src/components/book-part-title.js
- tutor/src/components/notes/note-card.js
- tutor/src/components/notes/summary-popup.jsx
It was rendering HTML
Before:
After:
> Fix title on notes popup print window

- tutor/specs/screens/question-library/index.spec.jsx
- tutor/src/screens/question-library/index.jsx
Otherwise the view may display exercises for previously viewed courses
> clear exercises when qa view mounts

- exercises/index.js
The old method would fail wit the new script tags, due to the doc already being ready when the script executed.
> Fix loading exercises

- exercises/specs/components/__snapshots__/exercise.spec.js.snap
- exercises/specs/components/exercise.spec.js
- exercises/specs/components/tags/__snapshots__/aplo.spec.js.snap
- exercises/specs/components/tags/__snapshots__/books.spec.js.snap
- exercises/specs/components/tags/__snapshots__/cnx-mod.spec.js.snap
- exercises/specs/components/tags/__snapshots__/lo.spec.js.snap
- exercises/src/components/exercise/tags.jsx
- exercises/src/components/tags/books.jsx
- exercises/src/components/tags/science-practice.js
- exercises/src/components/tags/single-dropdown.jsx
- exercises/src/components/tags/wrapper.jsx
- shared/src/model/exercise/tag-association.js
> Ex science practice tag

- tutor/src/screens/teacher-gradebook/ux.js
This way it'll match the other places where names are shown
> Default gradebook to being last_name,first_name

- tutor/src/models/task-plans/teacher/scores.js
- tutor/src/screens/assignment-review/homework-scores.js
do not include dropped students in average score and fix also the average score when a question is dropped.
> fix average score

- tutor/specs/screens/task/homework.spec.js
- tutor/src/screens/practice-questions/ux.js
- tutor/src/screens/question-library/index.jsx
- tutor/src/screens/task/assignment-closed-banner.js
- tutor/src/screens/task/homework.js
- tutor/src/screens/task/reading-navbar.js
- tutor/src/screens/task/step/exercise-question.js
- tutor/src/screens/task/ux.js
* Clear exercises store when viewing practice and leaving QL view
* Don't show save practice button when user is a teacher
* Don't mention answering questions on closed bar when user is a teacher
> A few fixes for release

- tutor/src/screens/teacher-gradebook/average-info-modal.js
> remove mention of HW from reading weights explanation

- tutor/specs/screens/task/steps/__snapshots__/end.spec.js.snap
- tutor/specs/screens/task/steps/__snapshots__/html-content.spec.js.snap
- tutor/specs/screens/task/steps/__snapshots__/reading.spec.js.snap
- tutor/src/screens/task/step/card.js
- tutor/src/screens/task/styles.scss
> Fix a few styling issues with video task steps

- tutor/src/helpers/analytics.js
so we can query teacher/student counts
> record course role as a custom dimension in GA

- shared/resources/styles/components/exercise-preview/index.scss
- tutor/src/screens/question-library/index.jsx
> Align choices label on exercise cards

- tutor/specs/components/sections-chooser.spec.jsx
- tutor/specs/screens/question-library/dashboard.spec.jsx
- tutor/src/components/exercises/cards.jsx
- tutor/src/components/sections-chooser.jsx
- tutor/src/components/tri-state-checkbox.jsx
- tutor/src/screens/question-library/sections-chooser.jsx
- tutor/src/theme.js
> Ql choose section

- tutor/resources/styles/book-content/mixins.scss
- tutor/resources/styles/book-content/splash-image.scss
- tutor/resources/styles/components/paging-navigation.scss
- tutor/specs/screens/task/steps/__snapshots__/end.spec.js.snap
- tutor/specs/screens/task/steps/__snapshots__/html-content.spec.js.snap
- tutor/specs/screens/task/steps/__snapshots__/reading.spec.js.snap
- tutor/src/components/book-page.js
- tutor/src/screens/task/step/card.js
- tutor/src/screens/task/ux.js
Treats them the same as the "splash" images
> display splash-video in task steps full-width

- tutor/src/components/book-page.js
- tutor/src/screens/task/page-content-ux.js
- tutor/src/screens/task/styles.scss
otherwise they open in reference view on the same tab and you can't navigate back easily
> display preview for footnotes, open in new tab

- tutor/src/models/app/pulse-insights.js
Identify user and set data before getting surveys
> Send user uuid to pulse-insights, fix order

- .eslintrc.js
- package.json
- yarn.lock
Fixes "TypeError: Cannot read property 'range' of null" error that I was
recieving locally and on github actions.  Not sure why others
didn't get it though.
> replace babel-eslint with @babel/eslint-parser

- configs/test/mocks.js
- package.json
- tutor/specs/integration/assignment-review.spec.js
- tutor/src/components/add-edit-question/form/question.js
- tutor/src/components/add-edit-question/form/shared.js
- tutor/src/components/add-edit-question/ux.js
- tutor/src/components/dropdown.js
- tutor/src/components/editor/index.js
- tutor/src/components/editor/runtime.js
- tutor/src/screens/demo/editor.js
- yarn.lock
> Add html editor to questions

- tutor/src/api/index.js
I moved exclusions to a new route so that we can have a nice resource-y route for the teacher-created exercises. (Needs the latest BE add/edit branch.)
> move exclusions to a new exercises/exclude route

- configs/test/jest.setup.js
- package.json
- tutor/src/components/add-edit-question/form/general.js
- tutor/src/components/add-edit-question/form/question.js
- tutor/src/components/add-edit-question/form/shared.js
- tutor/src/components/add-edit-question/ux.js
- tutor/src/components/editor/index.js
- tutor/src/components/editor/runtime.js
- tutor/src/theme.js
- yarn.lock
> Add HTML editing to all fields w/limited commands

- shared/specs/components/exercise-preview/__snapshots__/index.spec.js.snap
- shared/src/components/exercise-preview/controls-overlay.js
- shared/src/components/icon.js
- tutor/resources/styles/components/exercise-preview.scss
- tutor/resources/styles/components/exercises.scss
- tutor/src/components/exercises/details.jsx
- tutor/src/screens/question-library/exercises-display.jsx
> Update sidebar action styles

- tutor/src/components/add-edit-question/form/index.js
- tutor/src/components/add-edit-question/form/question.js
- tutor/src/components/add-edit-question/form/shared.js
- tutor/src/components/add-edit-question/ux.js
fix some of the css fixes after adding the editor for options and feedback.
> Add edit form fixes

- package.json
- shared/specs/components/exercise-preview/__snapshots__/index.spec.js.snap
- shared/src/components/exercise-preview/controls-overlay.js
- tutor/resources/styles/components/html.scss
- tutor/src/components/add-edit-question/form/question.js
- tutor/src/components/add-edit-question/ux.js
- tutor/src/components/editor/runtime.js
- yarn.lock
also adjusts sizing and controls on editor
> Save images when uploaded

- exercises/specs/components/__snapshots__/exercise.spec.js.snap
- shared/resources/styles/components/exercise-preview/index.scss
- shared/resources/styles/components/question.scss
- shared/specs/components/exercise-preview/__snapshots__/index.spec.js.snap
- shared/src/components/exercise-preview/controls-overlay.js
- shared/src/components/exercise-preview/index.jsx
- tutor/resources/styles/components/exercises.scss
- tutor/specs/components/exercises/__snapshots__/preview.spec.js.snap
- tutor/src/components/exercises/details.jsx
- tutor/src/screens/question-library/exercises-display.jsx
- Adds author and section link to footer
- Updates padding and text styles to match Figma (besides the location of the side controls)
- Fixes null icon issue
> More question detail updates

- tutor/specs/screens/assignment-edit/homework/__snapshots__/exercise-controls.spec.jsx.snap
- tutor/specs/screens/assignment-edit/homework/exercise-controls.spec.jsx
- tutor/src/components/exercises/homework-exercise-filters.js
- tutor/src/screens/assignment-edit/homework/cards.js
- tutor/src/screens/assignment-edit/homework/choose-exercises.jsx
- tutor/src/screens/assignment-edit/homework/exercise-controls.jsx
- tutor/src/screens/assignment-edit/homework/selections-tooltip.jsx
- tutor/src/screens/assignment-edit/index.js
- tutor/src/screens/assignment-edit/questions.js
- tutor/src/screens/assignment-edit/ux.js
- tutor/src/screens/question-library/exercise-controls.jsx
- tutor/src/screens/question-library/exercises-display.jsx
> Add edit assignment builder

- tutor/resources/styles/components/html.scss
- tutor/src/components/add-edit-question/terms-of-use.js
- tutor/src/components/add-edit-question/ux.js
- tutor/src/components/checkbox-input.js
- tutor/src/components/terms-modal.jsx
- tutor/src/models/user.js
- tutor/src/models/user/terms.js
Goes along with https://github.com/openstax/tutor-server/pull/2228
> fetch and display terms and conditions 

- exercises/specs/components/preview/__snapshots__/controls.spec.jsx.snap
- shared/specs/model/exercise.spec.js
- shared/src/components/exercise-preview/controls-overlay.js
- shared/src/model/exercise.js
- tutor/specs/screens/task/__snapshots__/exercise-task-header.spec.js.snap
- tutor/specs/screens/task/__snapshots__/homework.spec.js.snap
- tutor/specs/screens/task/__snapshots__/milestones.spec.js.snap
- tutor/specs/screens/task/__snapshots__/reading.spec.js.snap
- tutor/specs/screens/task/steps/__snapshots__/exercise-free-response.spec.js.snap
- tutor/specs/screens/task/steps/__snapshots__/exercise.spec.js.snap
- tutor/specs/screens/task/steps/__snapshots__/nudge-message.spec.js.snap
- tutor/specs/screens/task/steps/__snapshots__/question-stem.spec.js.snap
- tutor/src/api/index.js
- tutor/src/models/exercises.js
- tutor/src/models/exercises/exercise.js
- tutor/src/screens/question-library/exercises-display.jsx
Goes along with https://github.com/openstax/tutor-server/pull/2229
> support delete exercises

- tutor/src/components/add-edit-question/form/index.js
- tutor/src/components/add-edit-question/index.js
- tutor/src/components/add-edit-question/modals.js
- tutor/src/components/add-edit-question/ux.js
> Add edit preview

- tutor/src/models/exercises/exercise.js
- tutor/src/screens/assignment-edit/homework/choose-exercises.jsx
- tutor/src/screens/question-library/exercises-display.jsx
Do not show the copy and edit action in Reading questions
> Reading no copy edit

- tutor/src/components/add-edit-question/form/question.js
show context info if the exercise has a context link.
> Add edit context info

- exercises/specs/components/__snapshots__/exercise.spec.js.snap
- shared/src/components/icon.js
- tutor/specs/screens/assignment-edit/homework/__snapshots__/exercise-controls.spec.jsx.snap
- tutor/src/components/add-edit-question/form/general.js
- tutor/src/components/add-edit-question/form/index.js
- tutor/src/components/add-edit-question/form/question.js
- tutor/src/components/add-edit-question/form/shared.js
- tutor/src/components/add-edit-question/form/tags/index.js
- tutor/src/components/add-edit-question/form/topic.js
- tutor/src/components/add-edit-question/ux.js
- tutor/src/components/dropdown.js
- tutor/src/screens/assignment-edit/homework/exercise-controls.jsx
UI Fixes in the Add/Edit question form
> Add edit UI fixes

- tutor/src/components/add-edit-question/form/general.js
- tutor/src/components/add-edit-question/ux.js
Needed for the backend api to pick up the param
> annonymize -> anonymize to match api param name

- exercises/specs/components/__snapshots__/exercise.spec.js.snap
- shared/resources/styles/components/exercise-preview/index.scss
- shared/specs/components/exercise-preview/__snapshots__/index.spec.js.snap
- shared/src/components/exercise-badges/index.jsx
- shared/src/components/exercise-preview/controls-overlay.js
- shared/src/components/exercise-preview/index.jsx
- tutor/specs/components/exercises/__snapshots__/preview.spec.js.snap
- tutor/specs/screens/assignment-edit/homework/__snapshots__/exercise-controls.spec.jsx.snap
- tutor/src/components/add-edit-question/ux.js
- tutor/src/components/exercises/homework-exercise-filters.js
- tutor/src/components/exercises/no-exercises-found.jsx
- tutor/src/screens/assignment-edit/homework/choose-exercises.jsx
- tutor/src/screens/assignment-edit/homework/exercise-controls.jsx
- tutor/src/screens/question-library/exercise-controls.jsx
- tutor/src/screens/question-library/exercises-display.jsx
- tutor/src/screens/question-library/sections-chooser.jsx
- tutor/src/screens/question-library/styles.scss
> Add edit card view fixes

- shared/resources/styles/components/exercise-preview/index.scss
- tutor/resources/styles/components/exercise-preview.scss
Fixes sidebar buttons in question details view by targeting the class name instead of the tag.
> fix sidebar button css targeting for details view

- tutor/src/components/add-edit-question/form/question.js
- tutor/src/components/add-edit-question/form/shared.js
Align the two step label, and make the question text a min height of 80px, the rest of the editor is 40px.
> add-edit-form-visual-fixes

- tutor/specs/components/exercises/details.spec.jsx
- tutor/src/components/add-edit-question/ux.js
- tutor/src/components/exercises/cards.jsx
- tutor/src/components/exercises/details.jsx
- tutor/src/components/exercises/homework-exercise-filters.js
- tutor/src/models/app.js
- tutor/src/models/exercises.js
- tutor/src/models/exercises/exercise.js
- tutor/src/screens/assignment-edit/homework/choose-exercises.jsx
- tutor/src/screens/question-library/exercises-display.jsx
Sort should be:
* My questions
* Co-teachers’ questions
* OST questions
* OST community
> Sort exercises by how closely related to user they are

- tutor/src/components/add-edit-question/form/general.js
- tutor/src/components/add-edit-question/ux.js
- tutor/src/models/exercises.js
Exclude checkbox logic was incorrect, it would only show up on other teacher exercises, it should be present on any exercise that isn't owned by current user
Also fixes authorship selection dropdown. it should only be enabled on a new exercise
> Show exclude checkbox

- tutor/src/screens/question-library/exercise-controls.jsx
- tutor/src/screens/question-library/exercises-display.jsx
> Hide filtering controls in details view

- bin/build
- tutor/resources/styles/book-content/base.scss
> Display page title on reference sections

- tutor/src/components/sections-chooser.jsx
- tutor/src/screens/question-library/sections-chooser.jsx
> Ql sections chooser UI fix

- tutor/src/screens/assignment-edit/homework/choose-exercises.jsx
- tutor/src/screens/question-library/exercises-display.jsx
it was missed in the HW builder's detail view
> add add/copy action in both card/detail views

- tutor/src/models/exercises.js
- tutor/src/screens/assignment-edit/homework/choose-exercises.jsx
- tutor/src/screens/question-library/exercises-display.jsx
> Switch to card view after deleting in details

- package.json
- yarn.lock
Include fix to render all popups inside the editor frame
> update perry-white to 0.3.0

- tutor/src/components/add-edit-question/terms-of-use.js
> update add-edit terms agree checkbox text

- tutor/specs/integration/assignment-edit.spec.js
- tutor/src/models/app/raven.js
- tutor/src/screens/assignment-edit/homework/cards.js
- tutor/src/screens/assignment-edit/ux.js
Previously we weren't using ux.displayedExercises which checks that and a few other good things
> Hide excluded exercises in HW builder

- shared/src/components/exercise-preview/index.jsx
- tutor/resources/styles/components/exercises.scss
- tutor/specs/components/__snapshots__/paging-navigation.spec.jsx.snap
- tutor/specs/screens/question-library/dashboard.spec.jsx
- tutor/src/components/exercises/details.jsx
- tutor/src/components/icons/pagination.js
- tutor/src/components/paging-navigation.jsx
- tutor/src/screens/question-library/exercise-controls.jsx
> move the action controls outside of the exercise card details

- exercises/specs/components/__snapshots__/exercise.spec.js.snap
- shared/resources/styles/components/exercise-preview/index.scss
- shared/src/components/exercise-preview/index.jsx
- shared/src/components/question/index.jsx
> fix preview info displaying on exericse

- tutor/specs/components/my-courses.spec.jsx
- tutor/specs/components/my-courses/__snapshots__/pending-verification.spec.jsx.snap
- tutor/specs/components/my-courses/pending-verification.spec.jsx
- tutor/src/api/index.js
- tutor/src/components/my-courses/pending-verification.jsx
> update verbiage; poll for faculty verification

- exercises/specs/components/__snapshots__/exercise.spec.js.snap
- exercises/src/components/tags/books.jsx
- exercises/src/components/tags/science-practice.js
- exercises/src/components/tags/single-dropdown.jsx
This handles more than one book selected with the Science practice tag.
1. Shows Science Practice tag if at least the AP Physics or AP Bio is selected.
2. Removes tag if AP books are removed and their science practice value is selected.
> Exercise science practice fix

- exercises/specs/components/__snapshots__/exercise.spec.js.snap
- exercises/src/components/exercise/question-format-type.jsx
Change the "Require Choice" label to "Two-Step Question".
Add also an info popover for two-step questions.
> Exercise multiple choice label

- exercises/src/models/exercises.js
Was missing the number to construct the url from
> (exercises) Fix saving draft exercise 

- exercises/specs/components/__snapshots__/exercise.spec.js.snap
- exercises/src/components/exercise/tags.jsx
- exercises/src/components/tags/assignment-type.jsx
- exercises/src/components/tags/question-type.jsx
- exercises/src/models/exercises.js
- shared/specs/components/exercise-preview/__snapshots__/index.spec.js.snap
- shared/specs/factories/exercise.js
- tutor/src/screens/qa-view/styles.scss
> Rename conceptual/recall to reading/homework and make multi-select

- tutor/jest-playwright.config.js
- tutor/lms-pair.js
- tutor/scripts/test-server/backend.js
- tutor/specs/e2e/add-edit-question.e2e.js
- tutor/specs/helpers/dom.spec.js
- tutor/specs/models/app.spec.js
- tutor/specs/screens/lms-pair/index.spec.js
- tutor/src/helpers/dom.js
- tutor/src/models/app.js
- tutor/src/screens/lms-pair/app.js
Reading it from the dom means it's cached and hitting backbutton would
use stale data.
Plus we're about to make index.html a static file which means it
couldn't be delivered like that anyway
> read bootstrap data from api endpoint

- babel.config.js
- package.json
- tutor/src/models/app/raven.js
- yarn.lock
* "cannot add button after initialization" is from SF
* ChunkLoadError is due to client losing internet
> update sentry and filter out a few errors

- .github/workflows/build.yml
I kept the build file because maybe it's useful to know the build succeeds? But if you don't want it you can just delete the file.
> Don't upload built assets to S3 (done elsewhere)

- exercises/src/components/exercise/attachments/attachment.jsx
before images are linked to an exercise they lack a URL
> don't render unsaved images

- shared/specs/model/exercise/question.spec.js
- shared/src/model/exercise/question.js
- tutor/src/models/student-tasks/step.js
- tutor/src/screens/task/step/exercise-free-response.js
This way the FE behaviour matches what the back-end does. In the case where the tag is mis-applied we need to be in sync
> look at answers to detect multi-choice vs tag

- tutor/specs/e2e/course-settings.e2e.js
- tutor/src/components/toasts/course-settings-saved.js
- tutor/src/models/app.js
- tutor/src/models/course/offerings/index.js
- tutor/src/screens/course-settings/course-details.js
- tutor/src/screens/course-settings/delete-course-button.js
was stopping tutor from booting
> Add bootstrap for offerings

- configs/test/jest.e2e.js
- package.json
- tutor/jest-playwright.config.js
- tutor/specs/components/__snapshots__/app.spec.jsx.snap
- tutor/specs/components/__snapshots__/invalid-page.spec.jsx.snap
- tutor/specs/components/__snapshots__/tutor-layout.spec.js.snap
- tutor/specs/components/onboarding/expired-preview-warning.spec.jsx
- tutor/specs/components/onboarding/preview-only-warning.spec.jsx
- tutor/specs/components/onboarding/second-session-warning.spec.jsx
- tutor/specs/e2e/add-edit-question.e2e.js
- tutor/specs/e2e/assignment-review.e2e.js
- tutor/specs/e2e/course-settings.e2e.js
- tutor/specs/e2e/helpers.ts
- tutor/specs/e2e/my-courses.e2e.ts
- tutor/specs/global.d.ts
- tutor/src/routes.js
- yarn.lock
one of them was a legit failure, we had the url for it set to '/dashboard` vs `courses`
> Fix my-courses specs

- cypress/support/commands.js
- tutor/specs/acceptance/dashboard.spec.js
- tutor/specs/acceptance/my-courses.spec.js
- tutor/specs/e2e/course-roster.e2e.js
- tutor/specs/integration/dashboard.spec.js
- tutor/specs/integration/grading-templates.spec.js
- tutor/specs/screens/new-course/ux.spec.js
- tutor/src/components/toasts/reload.jsx
- tutor/src/helpers/conditional-handlers.jsx
- tutor/src/routes.js
- tutor/src/screens/course-roster/remove-teacher.jsx
- tutor/src/screens/course-settings/delete-course-button.js
- tutor/src/screens/lms-pair/ux.js
- tutor/src/screens/new-course/ux.js
Render the new courses UI for teacher
> My courses route

- package.json
- tutor/scripts/test-server/backend/bootstrap.js
- tutor/specs/components/__snapshots__/tutor-layout.spec.js.snap
- tutor/specs/courses-test-data.js
- tutor/specs/e2e/my-courses.e2e.ts
- tutor/specs/e2e/preview-courses.e2e.ts
- tutor/src/components/side-panel.tsx
- tutor/src/components/tutor-layout.js
- tutor/src/screens/my-courses/new-teacher.tsx
- tutor/src/theme.js
- yarn.lock
> Preview course side panel

- tutor/src/components/side-panel.tsx
I meant to use `fixed` here instead of `absolute` so it will scroll with the page.
> use fixed position for side panel

- tutor/src/components/toasts/reload.jsx
- tutor/src/routes.js
- tutor/src/screens/my-courses/dashboard/addSubjectDropdown.tsx
The reload toast for current code uses /courses
Also a few other minor tweaks
> Add redirect for old url /dashboard

- tutor/specs/e2e/my-courses.e2e.ts
- tutor/specs/models/app.spec.js
- tutor/src/models/app.js
- tutor/src/screens/my-courses/index.tsx
- tutor/src/store/bootstrap.ts
- tutor/src/store/offering.ts
We were not setting the offering bootstrap data.
> setting up the offering boostrap data in redux

- tsconfig.json
- tutor/src/screens/my-courses/dashboard/addSubjectDropdown.tsx
- tutor/src/screens/my-courses/dashboard/index.tsx
- tutor/src/screens/my-courses/index.tsx
- tutor/src/store/courses.ts
- types/index.d.ts
and fixes bug where displayed offering ids would be empty even if the user had courses
> Show not-verified screen

- tutor/src/components/tutor-layout.js
- tutor/src/models/course.js
- tutor/src/store/offering.ts
QA has several courses without it
> Don't blow up if course is missing appearance_code

- exercises/specs/components/__snapshots__/exercise.spec.js.snap
- exercises/src/components/exercise/preview.jsx
- shared/specs/components/exercise-preview/__snapshots__/index.spec.js.snap
- shared/src/components/exercise-preview/index.jsx
- tutor/specs/components/exercises/__snapshots__/preview.spec.js.snap
> display correctness; questionType==teacher-preview

- .eslintrc.js
- shared/src/components/notifications/system.js
- tutor/specs/e2e/my-courses.e2e.ts
- tutor/src/components/loadable-item.js
- tutor/src/components/navbar/actions-menu.jsx
- tutor/src/components/time.js
- tutor/src/components/youtube.js
- tutor/src/flux/qa-exercise-data-filter.js
- tutor/src/routes.js
- tutor/src/screens/grading-templates/card.js
- tutor/src/screens/my-courses/dashboard/create-course.tsx
- tutor/src/screens/my-courses/dashboard/index.tsx
- tutor/src/screens/my-courses/dashboard/offering-block.tsx
- tutor/src/screens/my-courses/dashboard/preview-course.tsx
- tutor/src/screens/my-courses/new-teacher.tsx
- tutor/src/screens/new-course/ux.js
- tutor/src/screens/performance-forecast/statistics.js
- tutor/src/screens/pre-wrm-scores-report/student-data-sorter.js
- tutor/src/screens/teacher-gradebook/min-max-result-cell.js
- tutor/src/screens/teacher-gradebook/student-data-sorter.js
- tutor/src/store/offering.ts
and only show the preview/create when the offering has that availability indicated
> Only display available offerings

- tutor/scripts/test-server/backend.js
- tutor/scripts/test-server/backend/bootstrap.js
- tutor/scripts/test-server/backend/course-roster.js
- tutor/scripts/test-server/backend/courses.js
- tutor/scripts/test-server/backend/dashboard.js
- tutor/scripts/test-server/backend/exercises.js
- tutor/scripts/test-server/backend/grading-templates.js
- tutor/scripts/test-server/backend/offerings.js
- tutor/scripts/test-server/backend/performance-forecast.js
- tutor/scripts/test-server/backend/performance.js
- tutor/scripts/test-server/backend/readings.js
- tutor/scripts/test-server/backend/suggest.js
- tutor/scripts/test-server/backend/task-plans.js
- tutor/scripts/test-server/backend/tasks.js
- tutor/scripts/test-server/backend/terms.js
- tutor/scripts/test-server/frontend.js
- tutor/scripts/test-server/index.js
- tutor/scripts/test-server/log.js
- tutor/scripts/test-server/role-from-args.js
- tutor/scripts/test-server/time-now.js
- tutor/specs/e2e/assignment-review.e2e.js
- tutor/specs/e2e/helpers.ts
This will reset all modifications so changes don't bleed over from one spec to another
> add resetState for e2e specs

- tutor/src/screens/my-courses/new-teacher.tsx
the old code did some pretty intricate role/course stuff to make
the FE match the new BE state, but it's probably best to just reload
> reload page after joining a preview

- tutor/scripts/test-server/backend/courses.js
- tutor/specs/e2e/create-course.e2e.ts
- tutor/specs/screens/lms-pair/__snapshots__/index.spec.js.snap
- tutor/specs/screens/new-course/__snapshots__/wizard.spec.jsx.snap
- tutor/specs/screens/new-course/ux.spec.js
- tutor/src/screens/my-courses/dashboard/create-course.tsx
- tutor/src/screens/new-course/index.jsx
- tutor/src/screens/new-course/ux.js
- tutor/src/screens/new-course/wizard.jsx
Also do the same thing from the my-courses page where we need to reload after create course
> fix create course wizard's final step

- tutor/resources/styles/variables/book-content.scss
- tutor/src/screens/my-courses/dashboard/preview-course.tsx
- tutor/src/screens/my-courses/dashboard/view-course.tsx
- Align the preview ellipsis with the regular course card one
- Update book covers to pass AA. The course header uses the same sass vars, so it updates these as well. (The colors may need to be tweaked later, as the source color doc used gradients instead of a single background color.)
> course card fixes

- tutor/resources/styles/variables/tutor-bootstrap.scss
- tutor/specs/e2e/course-settings.e2e.js
- tutor/src/models/course/teacher.js
- tutor/src/screens/course-settings/delete-course-button.js
Allow the instructor to delete a course even if there are students enrolled. Show a warning message in the delete modal.
PS. Waiting for the BE change to pass the role_id instead of the roster_id to "remove" the teacher from the course.
> change new UI for dropping of a course

- tutor/resources/styles/components/my-courses.scss
- tutor/specs/factories/offering.js
- tutor/src/screens/my-courses/dashboard/resource.tsx
- tutor/src/screens/my-courses/dashboard/view-course.tsx
- Make the entire resource card clickable
- Update the padding and font styles from figma
> update resource card link and styles

- tutor/resources/styles/variables/book-content.scss
> update book colors

- tutor/specs/components/__snapshots__/tutor-layout.spec.js.snap
- tutor/specs/components/onboarding/__snapshots__/expired-preview-warning.spec.jsx.snap
- tutor/src/components/navbar/menus.js
- tutor/src/components/onboarding/expired-preview-warning.jsx
> remove create a course button from the top right of preview course

- tutor/src/screens/my-courses/dashboard/preview-course.tsx
- tutor/src/store/api.ts
catching the errors in the redux api calls using the flux error handlers.
> No preview bug

- configs/test/jest.e2e.js
- package.json
- tutor/scripts/test-server/frontend.js
- tutor/specs/e2e/course-settings.e2e.ts
- tutor/specs/e2e/helpers.ts
- tutor/specs/factories/bootstrap.js
- tutor/specs/factories/course-roster.js
- tutor/specs/models/task-plans/teacher/plan.spec.js
- tutor/src/models/course.js
- tutor/src/screens/course-settings/delete-course-button.js
- tutor/src/screens/course-settings/index.jsx
- yarn.lock
needed so that all the stores/models get updated without the course
> reload page after leaving course

- tutor/specs/e2e/course-settings.e2e.ts
- tutor/src/screens/course-settings/delete-course-button.js
> update delete course modal message

- tutor/src/screens/my-courses/dashboard/offering-block.tsx
Updates "Free resources integrated with your book" resources text description to "Free resources available for your book".
> update resources card description

- tutor/src/screens/my-courses/new-teacher.tsx
> add ap-disclaimer in the subject selection for new users

- exercises/specs/components/__snapshots__/exercise.spec.js.snap
- shared/specs/components/exercise-preview/__snapshots__/index.spec.js.snap
- shared/specs/factories/exercise.js
- shared/src/components/exercise-preview/index.jsx
- shared/src/model/exercise/tag.js
- tutor/specs/components/exercises/__snapshots__/preview.spec.js.snap
- tutor/specs/e2e/question-library.e2e.ts
- tutor/src/components/sections-chooser.jsx
> Exercise ap tags

- exercises/src/components/tags/multi-select.js
- shared/specs/model/exercise.spec.js
- shared/src/model/exercise/tag-association.js
the assignment-type tag was passing `null` to replaceType
> fix removing last assignment type

- exercises/specs/components/__snapshots__/exercise.spec.js.snap
- exercises/src/components/exercise/attachments/chooser.jsx
I tried to write a spec for this but file uploads are crazy to mock 😭
> always show embed url, even if exercise is unsaved

- tutor/src/models/chapter-section.ts
Minimum to get `yarn test tutor tutor/specs/models/chapter-section.spec.ts` passing but not sure if this `instanceof` check is the right way to think about this in Typescript, feedback appreciated! :)
> fix chapter section spec

- tutor/specs/components/my-courses.spec.jsx
Fix in quotes since it's mostly fixed by removing teacher-specific checks.  This spec should be moved to a student dashboard one at some point.
> "fix" my courses spec

- exercises/src/models/exercises/exercise.ts
- exercises/src/models/search.ts
- shared/specs/model/model.spec.ts
- shared/src/model.ts
- shared/src/model/exercise/question.ts
- shared/src/model/exercise/solution.ts
- shared/src/model/exercise/tags-association.ts
- tutor/specs/models/user.spec.ts
- tutor/specs/models/user/menu.spec.ts
- tutor/src/models/course.ts
- tutor/src/models/course/offerings/offering.ts
- tutor/src/models/course/roster.ts
- tutor/src/models/exercises/exercise.ts
- tutor/src/models/notes.ts
- tutor/src/models/reference-book.ts
- tutor/src/models/reference-book/node.ts
- tutor/src/models/scores/period.ts
- tutor/src/models/scores/student.ts
- tutor/src/models/student-tasks/step-group.ts
- tutor/src/models/student-tasks/step.ts
- tutor/src/models/task-plans/teacher/plan.ts
- tutor/src/models/task-plans/teacher/scores.ts
- tutor/src/models/task-plans/teacher/stats.ts
- tutor/src/models/tour.ts
- tutor/src/models/user.ts
- tutor/src/models/user/terms.ts
Sets the property to a typed observable array
> rename extendedArray to "array", use for defaults

- tutor/src/screens/teacher-dashboard/styles/plan.scss
> External Assignments calendar accessibility contrast

- tutor/src/screens/teacher-dashboard/header.jsx
- tutor/src/screens/teacher-dashboard/styles/header.scss
> fix no sections message UI

- tutor/src/screens/assignment-edit/details-body.js
- tutor/src/screens/assignment-edit/tasking.js
- tutor/src/screens/teacher-dashboard/sidebar.js
Remove:
1. New label in teacher dashboard sidebar.
2. In assignment builder: Grading Template & Close Date.
> remove the New icon 

- tutor/src/models/reference-book/node.js
Previous version was also matching "Types of Resources"
> look for only suggested resources

- package.json
- shared/src/model/time.ts
- tutor/specs/screens/teacher-dashboard/dashboard.spec.js
- tutor/specs/screens/teacher-dashboard/month.spec.js
- tutor/specs/screens/teacher-dashboard/past-assignments.spec.jsx
- tutor/src/helpers/time.js
- tutor/src/screens/teacher-dashboard/dashboard.js
- tutor/src/screens/teacher-dashboard/month-title-nav.jsx
- tutor/src/screens/teacher-dashboard/month.js
- tutor/src/screens/teacher-dashboard/past-assignments.jsx
- tutor/src/screens/teacher-dashboard/sidebar.js
- yarn.lock
something weirds still going on with router params. will need to use
browser to debug further
> fix teacher dashboard

- tutor/specs/components/__snapshots__/app.spec.jsx.snap
- tutor/specs/components/app.spec.jsx
- tutor/specs/components/change-student-id.spec.jsx
- tutor/specs/components/course-nag.spec.jsx
- tutor/specs/components/enroll.spec.jsx
- tutor/specs/components/lms-info-card.spec.jsx
- tutor/specs/components/navbar/background-toasts.spec.jsx
- tutor/specs/components/navbar/student-pay-now-btn.spec.jsx
- tutor/specs/components/navbar/support-menu.spec.jsx
- tutor/specs/components/notes/__snapshots__/summary-popup.spec.js.snap
- tutor/specs/components/notes/summary-popup.spec.js
- tutor/specs/components/onboarding/expired-preview-warning.spec.jsx
- tutor/specs/components/payments/manage.spec.jsx
- tutor/specs/components/toasts/lms.spec.js
- tutor/specs/components/toasts/scores.spec.js
- tutor/specs/components/tours/anchor.spec.jsx
- tutor/specs/components/tours/conductor.spec.jsx
- tutor/src/components/lms-info-card.js
- tutor/src/components/payments/panel.jsx
- tutor/src/helpers/enroll.tsx
Some of these aren't fully passing but have some of the other changes we need, maybe it'll be easier to discuss and fix after.
> Mobx upgrade components

- tutor/specs/components/__snapshots__/related-content-link.spec.js.snap
- tutor/specs/components/__snapshots__/tutor-layout.spec.js.snap
- tutor/specs/components/obscured-page.spec.js
- tutor/specs/components/related-content-link.spec.js
- tutor/specs/components/tutor-layout.spec.js
- tutor/src/components/obscured-page/overlay-registry.js
I think the https://github.com/openstax/tutor-js/compare/mobx-upgrade...mobx-upgrade-components?expand=1#diff-d114b20bd042defe6d88ed69ef6a36f8ef6c813bea3472428599a1ad6246b3e5 snapshot was broken originally, it rendering the chapter name and number seems like what it should be storing.
> update more component specs

- tutor/src/screens/grading-templates/index.js
> Grading template margins

- exercises/specs/components/__snapshots__/exercise.spec.js.snap
- exercises/specs/components/tags/lo.spec.js
- exercises/src/components/tags/books.jsx
- exercises/src/components/tags/lo.jsx
The error now shows up immediately when a new LO is added since the value doesn't match the pattern, but what do you think?
> Added different LO patterns for World History

- tutor/src/components/add-edit-question/ux.js
- tutor/src/models/course.ts
- tutor/src/models/course/teacher-profile.ts
Teacher Exercise/Question form renders now, Publish doesn't seem to work yet.
> get teacher exercise form rendering

- shared/src/api/request.ts
- tutor/src/helpers/time.js
- tutor/src/models/task-plans/teacher/plan.ts
- tutor/src/screens/assignment-review/grant-extension.js
- Fix updating an existing task plan. `settings` was being passed as null (BE doesn't like that,) so I filtered out undefined/null values with `identity`.
- Fix the plan details popup, use Luxon token for 3-letter day of week ('Wed', 'Thu')
> Fix plan update

- tutor/specs/models/course.spec.ts
- tutor/src/api.ts
- tutor/src/models/course.ts
- tutor/src/screens/course-settings/course-details.js
- Fixes the method and path for updating course
- I had to filter out the LMS setting even though it was sent as false — the backend throws an error about the setting change not being allowed.
> fix course update method and sending lms setting when unchanged

- tutor/specs/e2e/course-settings.e2e.ts
- tutor/src/components/tabs.jsx
course-settings will pass once https://github.com/openstax/tutor-js/pull/3585 is merged.
> update course settings to use new backend

- tutor/specs/components/__snapshots__/tutor-layout.spec.js.snap
- tutor/src/components/ghost-button.tsx
- tutor/src/components/tours/custom/common.jsx
- tutor/src/components/tours/custom/drop-question-relocated.tsx
- tutor/src/components/tours/custom/index.js
- tutor/src/components/tours/step.js
- tutor/src/models/tour/context.ts
- tutor/src/screens/assignment-review/homework-scores.js
- tutor/src/theme.js
- tutor/src/tours/drop-any.json
- tutor/src/tours/index.js
> Drop any ghost button

- tutor/src/api.ts
- tutor/src/components/navbar/center-controls.jsx
- tutor/src/models/task-plans/student.ts
- tutor/src/screens/task/reading-milestones-toggle.js
Otherwise teacher-as-student will load teacher json and never render student tasks
> student dashboard needs to include role

- tutor/src/screens/assignment-review/drop-question-modal.tsx
- tutor/src/screens/assignment-review/ux.ts
Fixes to make the change state work properly (for the Save button) on the drop question modal.
> refactor checking for changed dropped question

- tutor/src/models/task-plans/teacher/scores.ts
This should hopefully handle all corner cases for when the algorithm drops Tutor questions.
> More fixes related to Tutor question headings to handle questions dropped by the algorithm

- tutor/src/models/user.ts
currentCourses may not be created on the global scope since course also imports user
> read currentCourses from method

- tutor/src/components/tours/custom/drop-any.tsx
- tutor/src/components/tours/custom/index.js
- tutor/src/components/tours/step.js
- tutor/src/screens/assignment-review/homework-scores.js
- tutor/src/screens/assignment-review/overview.js
- tutor/src/tours/drop-any.json
> add new drop question button tour

- tutor/src/components/dropped-question.tsx
- tutor/src/components/homework-questions.js
- tutor/src/components/task-progress.js
- tutor/src/models/student-tasks/step.ts
- tutor/src/models/task-plans/teacher/scores.ts
- tutor/src/screens/assignment-grade/questions-bar.js
- tutor/src/screens/assignment-review/homework-scores.js
- tutor/src/screens/assignment-review/overview.js
- tutor/src/screens/assignment-review/reading-scores.js
- tutor/src/screens/task/milestones.js
- Improve resultForHeading and make studentResponses use it
- Hopefully fixed all teacher-side blue triangles
> Teacher-side blue triangles

- shared/src/model/toasts.ts
- tutor/specs/helpers/context.js
- tutor/specs/helpers/course-enrollment.tsx
- tutor/src/api.ts
- tutor/src/components/enroll/invalid-code.jsx
- tutor/src/components/navbar/menus.js
- tutor/src/components/toasts.ts
- tutor/src/components/tutor-layout.js
- tutor/src/helpers/course-enrollment.tsx
This way all the Tutor toasts will be sure to be included
> fix toasts and enrollment

- tutor/specs/models/course.spec.ts
- tutor/src/models/courses-map.ts
- tutor/src/screens/assignment-review/drop-question-icon.tsx
- tutor/src/screens/assignment-review/overview.js
* Hide drop question icon when course is not active
* Choose latest preview course
> A few more drop-question fixes

- shared/src/api/request.ts
- tutor/src/helpers/payments.tsx
Some api methods like onboarding say they're content type json but have
empty body
> only attempt to parse body if it's present

- package.json
- yarn.lock
When multi-part steps are worked they weren't being grouped properly
> Update modeled mobx to fix bug with task steps

- tutor/specs/screens/task/steps/exercise-free-response.spec.js
- tutor/src/components/dropped-question.tsx
- tutor/src/models/response_validation.ts
- tutor/src/screens/assignment-review/homework-scores.js
- tutor/src/screens/assignment-review/reading-scores.js
- tutor/src/screens/my-courses/dashboard/preview-course.tsx
- tutor/src/screens/task/response-validation-ux.js
When the validation was correct it was being over-riden by the default false
also fixes a bug with preview courses selection were it was possible a old expired preview would be selected
> Fix response validation 

- tutor/src/components/preview-side-panel.tsx
- tutor/src/components/side-panel.tsx
- tutor/src/components/tutor-layout.js
- tutor/src/helpers/chat.ts
@dkhowala and designed via slack screenshots and this is what we came up with:
> add chat button to preview course popout panel

- tutor/src/screens/assignment-review/ux.ts
Get the drop question modal offscreen as soon as visible items are updated
> adjust code to hide modal earlier

- tutor/src/helpers/background-wrapper.js
1100px is too wide to force on everyone
> allow content to shrink to 900px wide

- tutor/src/screens/assignment-review/table-elements.js
> move late icon to left

- tutor/src/components/dropped-question.tsx
- tutor/src/components/homework-questions.js
- tutor/src/models/task-plans/teacher/scores.ts
> Fix display of dropped questions tooltip on hw score

- tutor/src/models/task-plans/teacher/scores.ts
- tutor/src/screens/assignment-review/overview.js
> Fixed points behavior for dropping Tutor questions in the submission overview

- tutor/specs/e2e/soc3e.e2e.ts
- tutor/src/models/course/offerings.ts
- tutor/src/models/course/offerings/offering.ts
- tutor/src/screens/teacher-dashboard/index.jsx
- tutor/src/screens/teacher-dashboard/sociology-3e-banner.tsx
Adds the blue banner announcing 3e if it not yet available in the offerings. We'll probably use the methods setup in this for the announcement modal(s).
> add sociology 3e banner on 2e dashboard

- shared/src/model/exercise/answer.ts
correctness in particular needs to be null.
it was failing this check: https://github.com/openstax/tutor-js/blob/main/shared/src/components/question/answer.jsx#L24
> don't set a default value for properties

- tutor/src/helpers/chat.ts
This will allow SF admins to modify the tutor chat experience separately from CNX
> update chat ids

- exercises/specs/components/__snapshots__/exercise.spec.js.snap
- exercises/src/components/exercise/tags.jsx
- exercises/src/components/tags/public-solutions.jsx
- exercises/src/models/exercises/exercise.ts
The field is not being set on create. It looks like the data to be sent is fine, but the API call stuff is completely broken somewhere (due to mobx upgrade?) and a blank body is being sent.
Haven't managed to test edit yet because the editor is also completely broken due to mobx.
> Public solutions

- tutor/src/models/course/offerings.ts
- tutor/src/screens/my-courses/dashboard/add-subject-dropdown.tsx
- tutor/src/screens/my-courses/dashboard/use-displayed-offerings.tsx
We should display blocks for past courses even if the offering is no longer avail
> consider all offerings to display

- tutor/specs/components/__snapshots__/related-content-link.spec.js.snap
- tutor/specs/components/related-content-link.spec.js
- tutor/specs/screens/task/steps/__snapshots__/footer.spec.js.snap
- tutor/src/components/book-part-title.js
- tutor/src/components/buttons/browse-the-book.jsx
- tutor/src/components/related-content-link.js
- tutor/src/helpers/analytics.js
- tutor/src/models/reference-book.ts
Links to intro pages had `undefined` in them
> Fixed related content for intro pages, etc

- tutor/specs/components/time.spec.js
- tutor/specs/screens/student-dashboard/__snapshots__/dashboard.spec.jsx.snap
- tutor/specs/screens/student-dashboard/__snapshots__/event-row.spec.jsx.snap
- tutor/specs/screens/student-dashboard/__snapshots__/homework-row.spec.jsx.snap
- tutor/src/components/time.js
Moment doesn't know how to parse the date if it's already an instance of the Time class
> use Time class vs moment

- tutor/src/screens/my-courses/dashboard/index.tsx
> move add subject dropdown to the top

- exercises/specs/components/__snapshots__/exercise.spec.js.snap
- exercises/src/components/exercise/preview.jsx
- shared/src/model/exercise.ts
This way we can identify why exercises may appear twice in the search results
> Draft ribbon

- tutor/src/screens/teacher-gradebook/ux.js
And protect access so it won't fail when null while api is fetching
> read currentPeriodScores.students from one spot

- exercises/specs/components/__snapshots__/exercise.spec.js.snap
- exercises/specs/components/exercise.spec.js
- exercises/src/components/exercise/preview.jsx
- exercises/src/components/preview.jsx
- exercises/src/components/search.tsx
- exercises/src/models/search.ts
- exercises/src/ux.ts
- shared/src/model/exercise.ts
goes along with https://github.com/openstax/exercises/pull/332
> Render context along with exercise preview

- shared/specs/model/time.spec.ts
- shared/src/model/time.ts
Otherwise luxon complains (as it should) and humanize fails
> fix date interval to always end after start

- exercises/specs/components/search/book-sections.spec.jsx
- exercises/src/components/search/book-sections.tsx
- tutor/specs/screens/course-settings/__snapshots__/details.spec.tsx.snap
- tutor/specs/screens/course-settings/details.spec.tsx
Maybe you guys can give me some pointers on how to test the stuff... the test works but it prints a warning because something blows up in the component's constructor... I couldn't get mocking to work to fix it either.
> Handle books with units in the book section search

- .github/workflows/test.yml
- tutor/specs/components/__snapshots__/task-progress.spec.js.snap
- tutor/specs/components/task-progress.spec.js
- tutor/src/components/task-progress.js
> Don't render "Not yet graded" popup for incomplete steps

- shared/specs/components/exercise-preview/__snapshots__/index.spec.js.snap
- shared/specs/components/exercise-preview/index.spec.js
- shared/src/components/exercise-preview/index.jsx
> Display indication that exercises have public solutions in the tags

- .eslintrc.js
- tutor/specs/helpers/time-mock.ts
- tutor/specs/models/course.spec.ts
- tutor/specs/models/task-plans/teacher/plan.spec.ts
- tutor/specs/models/tour/ride.spec.ts
- tutor/specs/models/tour/step.spec.ts
- tutor/specs/screens/task/exercise-task-header.spec.js
Not sure if it matters, but I saw it as a recommendation to avoid memory leaks...
> Restore all jest mocks after use

- tutor/src/screens/assignment-review/grant-extension.js
Fixes the grant extension due date being broken
> fix moment object being used in comparison

- tutor/resources/styles/variables/book-content.scss
looks like I must have been searching for `history` and typed into document 😭
> fix typo in soc3 appearance code

- tutor/resources/styles/components/date-time-input.scss
- tutor/src/helpers/time.js
- tutor/src/screens/assignment-edit/index.js
- tutor/src/screens/assignment-edit/styles.scss
- #### Fixed time display: 
- #### Fixed OK button style
Old:
New:
> fix time formatting token and time picker OK button style

- tutor/specs/components/__snapshots__/checkbox-input.spec.js.snap
- tutor/src/components/add-edit-question/form/general.js
- tutor/src/components/checkbox-input.js
- tutor/src/components/timezone-modal.js
- tutor/src/models/task-plans/teacher/tasking.ts
- tutor/src/screens/assignment-review/grant-extension.js
- tutor/src/screens/assignment-review/reading-scores.js
- **Fix a bug that prevented sections from being rechecked during assignment creation**
- **Fix checkbox alignment issues**
Before | After
-- | --
- **Make the bottom toolbar of reading table use the same components as homework so they are visually consistent** 
Before | After
-- | --
> Checkbox & reading scores icon bug fixes

- tutor/specs/factories/index.ts
- tutor/specs/models/courses/period.spec.ts
- tutor/src/models/course/period.ts
Also added a unit test for CoursePeriod save()
> Fix duplicate sections appearing on the roster when renaming

- tutor/specs/e2e/student-dashboard.e2e.ts
- tutor/specs/e2e/teacher-gradebook.e2e.ts
Teacher gradebook seemed to just work after unskipping
> Fix dashboard specs

- tutor/resources/styles/components/top-nav-bar/drop-down-menu.scss
- tutor/resources/styles/variables/colors.scss
to match the student view frame color
> Changed the lock icon color in the menu to Tutor's teal

- tutor/specs/models/task-plans/teacher/grade.spec.ts
- tutor/src/components/error-monitoring/handlers.jsx
- tutor/src/models/task-plans/teacher/grade.ts
- tutor/src/models/task-plans/teacher/scores.ts
- tutor/src/screens/grading-templates/card.js
- tutor/src/screens/grading-templates/editors.js
To handle error cases such as having 2 tabs open and grading at the same time as submitting a new answer.
> Echo back attempt number when grading questions

- tutor/specs/components/icons/lock.spec.js
- tutor/src/components/icons/lock.js
- tutor/src/screens/task/step/card.js
Reopening since multiple-attempts got force-pushed and the merge was lost.
> New lock icon

- tutor/specs/components/__snapshots__/task-progress.spec.js.snap
- tutor/specs/components/task-progress.spec.js
- tutor/src/components/task-progress.js
- Added not-yet-graded icon
- Adjusted popover positioning
- Fixed console warnings due to the "graded" attribute being passed to the DOM
> Added not-yet-graded icon to assignment page

- tutor/specs/screens/task/steps/__snapshots__/instructions.spec.js.snap
- tutor/specs/screens/task/steps/instructions.spec.js
- tutor/src/screens/task/step/instructions.js
To ask Devika: should we do something different if the assignment has only MCQs or only WRQs?
> Instructions page update for multiple attempts

- tutor/specs/e2e/add-edit-question.e2e.ts
- tutor/src/components/add-edit-question/form/question.js
- tutor/src/components/add-edit-question/ux.js
- Make "Detailed Solutions" in an MCQ optional
- Make "Answer Key" in a WRM required
> Update detailed solutions

- tutor/specs/components/my-courses.spec.jsx
- tutor/src/components/my-courses/index.tsx
This should hopefully fix scenario 2 in https://app.zenhub.com/workspaces/openstax-tutor-560aef617a763234615d6a0f/issues/openstax/tutor/1738
> reload the page if the course fetch errors

- exercises/specs/components/search/__snapshots__/clause.spec.jsx.snap
- exercises/specs/components/search/clause.spec.jsx
- exercises/src/components/search/clause.jsx
- exercises/src/models/search.ts
For: https://github.com/openstax/unified/issues/1984
New frontend dropdown filters for format and solutions_are_public
> Added new frontend dropdown filters for the new options added in the backend

- tutor/specs/components/payments/__snapshots__/manage.spec.jsx.snap
- tutor/specs/screens/course-settings/__snapshots__/student-access.spec.jsx.snap
- tutor/src/components/payments/manage.jsx
- tutor/src/components/toasts/lms.jsx
- tutor/src/screens/course-settings/student-access.jsx
> Added more missing help links

- exercises/specs/components/__snapshots__/exercise.spec.js.snap
- exercises/src/components/exercise/tags.jsx
- exercises/src/components/tags/aacn.jsx
- exercises/src/components/tags/nclex.jsx
- exercises/src/components/tags/nursingBooks.js
- exercises/src/components/tags/single-dropdown.tsx
- shared/src/model/exercise/tag.ts
- shared/src/model/exercise/tags-association.ts
For: https://github.com/openstax/unified/issues/2458
- Adds 2 new fields to create nursing tags, visible only when a nursing book is selected
- AACN takes values similar to an LO, NCLEX is just yes/no. Both are optional. There can be multiple AACN tags.
> Nursing tags

- shared/src/components/question/index.jsx
- Still joins all content_html together by solution_type
- Only supports 'detailed' and 'summary' solution types
> Add summary to preview

- exercises/specs/components/__snapshots__/exercise.spec.js.snap
- exercises/specs/components/tags/__snapshots__/book-selection.spec.js.snap
- exercises/specs/components/tags/__snapshots__/books.spec.js.snap
- exercises/src/components/tags/book-selection.jsx
fixes https://github.com/openstax/ce/issues/2189
> add College Success Concise
