openstax/tutor-js

- .gitignore
- Gulpfile.coffee
- index.html
- package.json
- style/tutor.less
This also pins the version of `flux-react` because in newer versions Action arguments are also deep-cloned.
> refactor dist files to be in /dist dir

- api/tasks/4
- api/user/tasks
- src/api.coffee
- src/components/all-steps.cjsx
- src/components/breadcrumbs.cjsx
- src/components/exercise-multiple-choice.cjsx
- src/components/exercise.cjsx
- src/components/html.cjsx
- src/components/katex-mixin.coffee
- src/components/question.cjsx
- src/components/step-mixin.cjsx
- src/components/task-step.cjsx
- src/components/task.cjsx
- src/flux/answer.coffee
- src/flux/helpers.coffee
- src/flux/task-step.coffee
- src/flux/task.coffee
- style/question.less
- style/tutor.less
- test/task-store.spec.coffee
This should handle the 4 different states an Exercise can be in:
1. `not(free_response)`: Show the question stem and a text area
2. `free_response and not(answer_id)`: Show stem, your free_response, and the multiple choice options
3. `correct_answer_id`: review how you did and show feedback (if any)
4. `task.is_completed and answer` show your answer choice but no option to change it
Student is presented with a free response:
clicks "Continue" and is shown their answer plus Multiple choice options:
Clicks "Continue" and is shown a review for the question:
Clicks "Continue" and is sent to the next Step:
Clicks a completed step and sees the review page:
> Exercise states

- api/tasks/4
- api/user/tasks
- src/api.coffee
- src/components/index.cjsx
- src/components/task.cjsx
- src/flux/helpers.coffee
- src/flux/task.coffee
No UI changes.
The completing an exercise requires 2 calls to the backend (for now):
1. `PUT /tasks/123/steps/234/completed`
2. `GET /tasks/123` (TaskStep now contains the `correct_answer_id` and optional `feedback_html`)
Ideally, it would be a single `PATCH /tasks/123/steps/234` with `{is_completed: true}` which would return the `correct_answer_id` and optional `feedback_html` inside the JSON.
To get the mockup data to work correctly I added an additional `HACK_LOCAL_STEP_COMPLETION` to know tutor-js is fetching mock data and should "emulate" the TaskStep completion.
> Reload task after complete

- src/components/task-plan/reading.cjsx
No UI changes really, just the switch from  /readings to /readings/:id once the publish button is clicked
> adding in route changing once publish button is submitted

- src/api.coffee
- src/components/task-plan/reading.cjsx
- src/flux/helpers.coffee
- src/flux/task-plan.coffee
No UI changes.
For another PR:
- save should handle new and existing objects
- API should check `Store.isNew` and decide on POST vs PATCH (like Backbone does)
- refactor `freshLocalId()`
> Refactor create code to handle multiple creations and types

- Gulpfile.coffee
- src/api.coffee
- src/components/task-plan/reading.cjsx
- src/flux/helpers.coffee
- src/flux/task-plan.coffee
- src/flux/task.coffee
- test/all-tests.coffee
- test/crud-store.spec.coffee
no UI changes.
This is useful for `PATCH` to only send the unsaved changes and for “Cancel” buttons or confirm dialogs when moving away from a page.
Each CRUD Store now has `.isChanged(id)`, `.getChanged(id)` and a `.get(id)` contains a combination of the unchanged fields and the locally changed ones.
Each CRUD Actions set now has an internal `._change(id, obj)`.
> WIP keep track of unsaved changes in the stores

- package.json
- src/components/task/breadcrumbs.cjsx
No UI changes.
flux-react 2.5 and 2.6 both remove the listener but still fire (bug in their code)
> downgrade flux-react

- src/api.coffee
- src/components/index.cjsx
- src/components/task-step/all-steps.cjsx
- src/components/task-step/exercise-multiple-choice.cjsx
- src/components/task-step/index.cjsx
- src/components/task-step/step-mixin.cjsx
- src/components/task/breadcrumbs.cjsx
- src/components/task/index.cjsx
- src/flux/helpers.coffee
- src/flux/task-step.coffee
- src/flux/task.coffee
No UI changes.
- moves most of the actions from the TaskStore into the TaskStepStore
- since TaskSteps no longer need the parent Task id, the methods do not need to be on TaskStore
- cleans up the TaskStep models a bit (but more is needed)
This should make the following stories a little easier:
- defaulting to the correct step when opening a Task
- rendering Practice problems
> Move actions from TaskStore to TaskStepStore

- src/components/task-plan/reading-stats.cjsx
- src/router.coffee
- style/reading-stats.less
- style/tutor.less
This PR renders progress bars for course overall, current_pages and spaced_pages.  It is currently not rendering periods.  Percent change is calculated on spaced_pages based on previous_attempt.
current issues:
1) the way either bootstrap progressbar or react-bootstrap calculates percentage width is causing smaller segments to overflow:
2) the overall course stats needs stat: 'not started' and/or an accurate total_count to render the progress bar properly.
> reading stats - adjusted progress bars, added spaced practice

- src/api.coffee
No UI Change (except that UI now works again ; )
fixes the `GET /steps/[Object object]` error @Fredasaurus encountered when backend changed what was returned from `PUT /steps/1/completed`
> fix malformed URL when completing a step

- Gulpfile.coffee
- src/components/task-plan/reading.cjsx
- src/flux/toc.coffee
- src/router.coffee
- test/all-tests.coffee
- test/components/reading-plan.spec.coffee
No UI changes.
This adds a couple unit tests for a ReadingPlan. Should be useful for making more unit tests
**Notes:**
- To test a Component I needed to refactor out part of it that used the `Router.State` mixin
- had to add classes to buttons to test if they were disabled
> add unit tests for ReadingPlan

- src/components/task-plan/teacher-task-plans-listing.cjsx
this adds a link to the stats page for corresponding readings in list:
> added stat page link to task plans list

- src/components/confirm-leave-mixin.cjsx
- src/components/task-plan/reading.cjsx
No UI Changes.
When refactoring to add unit tests I failed to manually test the reading to make sure transitions still worked.
> Move mixins out of ReadingComponent

- api/courses/1/plans.json
- src/flux/teacher-task-plan.coffee
- test/teacher-task-plan-store.spec.coffee
Used to be an empty reading list when using `tutor-server` because the JSON format was different.
> update the expected JSON format for the list of plans

- test/crud-store.spec.coffee
3 tests added in crud-store spec
> tests for crud store for extending the crudstore and using the _loaded function

- src/components/task-plan/reading-stats.cjsx
- src/components/task-plan/reading.cjsx
- src/components/task-plan/teacher-task-plans-listing.cjsx
Backend is not returning previous attempt data (%changed since last attempted this question) so making it optional.
Also, removed the 2nd progress bar which was occasionally being wrapped
> previous attempt info is optional

- test/crud-store.spec.coffee
continuation of #69, tests for when
- `_loaded` does not exist
- `_loaded` returns `falsy`
> adding tests for when _loaded is not defined or returns falsy

- style/question.less
Renders only 1 math formula instead of 2:
New:
Old:
> hide MathJax rendered from MathML generated by katex

- package.json
No UI Changes.
One of the packages requiring react is complaining
> temporarily pin react exactly for peer dependencies

- .travis.yml
No UI Changes.
Also, don't have travis cache `node_modules` since that seemed to be causing problems with PRs. Maybe we should pin all the packages and just periodically update them.
> print package versions after failure

- api/tasks/4.json
- package.json
- src/components/question.cjsx
- src/components/task-step/exercise-multiple-choice.cjsx
- src/components/task-step/index.cjsx
- src/components/task/index.cjsx
- src/flux/task.coffee
- style/task-step.less
- style/tutor.less
- test/components/helpers/task/checks.coffee
- test/components/helpers/task/index.coffee
- test/components/task.spec.coffee
This adds a "Refresh My Memory" button to the question review screen.  If the button is selected it displays the last reading that was shown prior to the question so that the student can review the source material.
In order to hook up the button to navigate to the prior reading, I needed the "goToStep" callback from the main Task view, which is how the breadcrumbs navigate.  Unfortunately, this change rippled out through various panels before it could get to ExerciseReview.  It would seem to be more React like if we had a "navigation state" data structure that could be shared, and each would render appropriately based on it.
If there's agreement on that, I'll rework to use that method.
> Try Another / Refresh my Memory / Move On question review buttons

- .gitignore
- src/components/task-step/ends.cjsx
- src/components/task/breadcrumbs.cjsx
- src/components/task/crumb-mixin.cjsx
- src/components/task/index.cjsx
- src/flux/task.coffee
- style/calendar.less
- style/task-step.less
- style/tutor.less
- test/all-tests.coffee
- test/components/helpers/task/actions.coffee
- test/components/helpers/task/checks.coffee
- test/components/task-homework.spec.coffee
- test/components/task.spec.coffee
Using star now but can easily switch for something else.
> Allow navigation through homework questions by showing all breadcrumbs

- src/api.coffee
- src/flux/time.coffee
- test/all-tests.coffee
- test/time.spec.coffee
No UI changes.
adds a `TimeStore.getNow()` which returns a `Date` representing the current **server** time.
> add store for getting current server time

- src/components/task-plan/homework.cjsx
- src/components/task-plan/select-topics.cjsx
- style/homework.less
Before:
After:
Note: Section numbers are also styled, although are not shown with the default data.
> Style Homework Add Problems Modal

- src/flux/student-dashboard.coffee
- test/components/student-dashboard.spec.coffee
Correct a bug that I introduced where the "&" symbol would prepended to the teacher names even if there was only one teacher.  I had the extra lines in the code, but must have somehow rebased over or otherwise discarded them somewhere along the line :(
Before:
After:
> Fix display of single teacher's name

- src/components/student-dashboard/dont-forget-panel.cjsx
- style/icons/all.less
- style/student-dashboard.less
This is closer to what the mockup shows.  I also discovered that the "Don't Forget" panel was still using it's own css vs the new icon based methods and corrected it with the new xlg size
Before:
After:
> Make the large icons a bit larger, add an xlg size for the "don't forget" panel

- src/components/course-calendar/duration.cjsx
- test/components/course-calendar.spec.coffee
Ranges are meant to be for block scheduling.
This unfortunately hides some fancy (and tested!) code showing calendar ranges.
I commented the code in case there is a better way to turn it off for now
> Remove ranges from the calendar

- src/components/student-dashboard/dont-forget-panel.cjsx
- src/components/student-dashboard/homework-row.cjsx
- src/components/student-dashboard/upcoming-panel.cjsx
- src/flux/student-dashboard.coffee
No UI changes other than how tasks are selected for which panel
Fixes for: 
* Only Homeworks that are due on past weeks can be recovered/feedback viewed
* Simplify store pastDueEvents method to remove the "options" hash, add upcomingEvents method
* Upcoming events panel should start at next week, use the new upcomingEvents method on the store.
> Student dashboard fixes

- coffeelint.json
No UI Changes.
Lint errors will now cause Travis to cry.
And now I need to go through and fix `no_unnecessary_double_quotes`
> change lint warnings to errors

- src/components/student-dashboard/homework-row.cjsx
- src/components/student-dashboard/reading-row.cjsx
No UI changes.
This connects the "View Feedback" link to the tasks, where the feedback will be shown since the task is past due.
I also discovered and fixed a bug where I'd used preventDefault instead of stopPropagation on the links.  No idea why I did that, and am not sure why/how preventDefault was even working, but stopPropagation is the behavior we want on them.
> Connect student dashboard "view feedback" links

- src/components/learning-guide-chart.coffee
- src/flux/app-config.coffee
- test/all-tests.coffee
- test/app-configuration.spec.coffee
No UI changes
Created a new AppConfigStore that has a `getAssetsHost` and `urlForResource` methods and configures the learning-guide to load it's assets using it.
Feedback welcomed on how `getAssetsHost` auto-detects the host and if that's a good idea or not.  We could also set it explicitly as when the app's loaded in the index.html files as part of a "Bootstrap" type call.
> Auto detect the host & port for loading resources

- src/components/task/index.cjsx
* Clicking continue should go to next step, as opposed to first incomplete step.
This change is especially apparent if you go to step 3 for example, and try to continue.
Previously, the continue would take you to the first incomplete step, which may be step 1 or step 6.
* Step 1 if you're in a homework and skipped to step 3 without completing step 1
* Step 6 if you're in a reading and you have completed up to step 5 but are going back to step 3 to review.
Now, it should take you to step 4.
There is currently a problem with the backend where it doesn't expect us to complete exercise more than once (i.e. when we change an answer and then click continue).  I am discussion with @Dantemss about this and other edge cases around this.
> Continue task behavior

- src/components/course-calendar/duration.cjsx
When returning from HW or iReading builder the calendar would be blank:
> fix calendar reloading when returning from screen

- src/components/student-dashboard/event-row.cjsx
- src/components/task/index.cjsx
- src/router.cjsx
Adds a stepIndex param to the route and updates it when breadcrumb is clicked.  The new parameter is then used for jumping to the first step of a task on the dashboard.
The index is 1 based so that the URL parameter matches the text on the breadcrumb button.
> Go to first step in task, update url on bc click

- resources/styles/components/student-dashboard/dashboard.less
- resources/styles/components/student-dashboard/panel.less
- resources/styles/components/student-dashboard/task.less
- src/components/student-dashboard/dashboard.cjsx
- src/components/student-dashboard/event-row.cjsx
- src/components/student-dashboard/events-panel.cjsx
* Text on big header fit into div and not overflow
* turn down opacity on background image to 0.05
* a bit smaller font for All Past Work
* less padding for panel header
* remove padding from panel bottom
* lighter border between rows, border at top
* Add Progress and Due labels
> Dashboard styles from Fred

- src/components/html.cjsx
- src/components/katex-mixin.coffee
I believe the MathJax Typeset call is what's causing the "Invariant Violation" exceptions in the task steps.  If it's disabled, the exceptions no longer occur. 
As part of that investigation, I discovered that the MathJax.Hub.Queue call's arguments were specified incorrectly.  The element should be given as part of the array.  Since it wasn't specified property, Mathjax is actually typsetting the entire document.  http://docs.mathjax.org/en/latest/queues.html#using-queues (*search for Typeset*)
Unfortunately, this does not correct the "Invariant Violation".  Even with this fix, MathJax still causes them.  When I set a breakpoint on the dom tree before the call, I see multiple mutations being performed, but they all appear to be inside the html of the Html component, so React shouldn't …
> Only render katex nodes with Mathjax

- src/components/html.cjsx
As pointed out by the awesome @pandafulmanda - MathJax creates multiple elements outside the container that it's working on.
If we remove them after MathJax does it's thing, the "Invariant Violation" exceptions no longer occur.
> Clean up stray elements created by MathJax

- resources/styles/components/task-step/reading/book-content/index.less
- src/components/task-step/all-steps.cjsx
I discovered that the overlay was leaving a blank area where it should have been due to the use of relative positioning adjustment.
Also put a check in to make sure the ui-overlay element isn't generated more than once.
Before:
After:
> Fixes for reading overlay

- src/flux/task-plan.coffee
No UI changes.
Removing settings when a task plan is a homework so settings don't get sent to the backend.
> Removing task plan settings when type is homework

- resources/styles/components/task-step/reading/book-content/index.less
And are not styled.  This gives up identifiying them by class
and assumes that all li elements inside a .learning-objectives
are objectives.
Also add 2rem of indentation to MathJax so it looks neater.  The MathJax styling conflicts with the flex alignment on the list, causing it to be moved to a new line.  Since flex box is the only way to get the list to vertically space the elements equally I think that's the best we can do.
Before:
After:
> Some objectives lack .ost-learning-objective-def

- resources/styles/old/global/icons.less
- src/helpers/policies/policies.coffee
Technically, this should never be shown as a `?` since upcoming breadcrumbs in ireading are hidden
> personalized steps in readings

- resources/styles/components/student-dashboard/dashboard.less
In dff52431d24dc0449fb9e8f090dab8d76bfe5593, `.panel > .panel-heading` gained a `border: 2px solid @tutor-secondary-light` rule, causing the dashboard to look like:
This removes it
> Remove border from dashboard panel headings

- src/components/pinned-header-footer-card/index.cjsx
> tweaks around scroll and pinning behaviour

- resources/styles/components/task-step/reading/book-content/index.less
Ensures a para that has drop-caps effect applied is tall enough so that the drop-caps don't descend into it's sibling elements.
Before:
After:
> Set minimum height for p elements with drop caps

- src/components/task-plan/footer.cjsx
- test/components/homework/homework-plan.spec.coffee
> Plan Footer - Cancel button and homework logic

- resources/styles/components/task-plan/homework/exercises.less
- src/components/task-plan/homework/exercises.cjsx
> Exercise Card Styles and Tag Display

- resources/styles/components/task-plan/homework/exercise-summary.less
- src/components/task-plan/homework/exercise-summary.cjsx
> Exercise summary Styles

- src/components/katex-mixin.coffee
No UI Changes.
Allows the exercise builder to still work when there are katex parser errors
> catch Katex parser errors

- src/components/task-plan/homework.cjsx
- src/components/task-plan/reading.cjsx
No UI changes
Adding in date parsing to the homework and ireading builders when the calendar passes in a date.  See here: http://stackoverflow.com/questions/19289086/updated-invalid-date-in-firefox-javascript
> Firefox date fix

- resources/styles/components/task-step/all-steps.less
- resources/styles/components/task-step/ends.less
- src/components/task-step/all-steps.cjsx
- src/components/task-step/ends.cjsx
- src/components/task-step/exercise/index.cjsx
- src/components/task-step/exercise/modes.cjsx
- src/components/task/breadcrumb.cjsx
- try it, it's pretty kewl!
- first problem leave may jump if you are not scrolled past a certain point :disappointed:
Abruptly continues to next problem
shows review screen for completed problem until user clicks continue
> Improvements on homework review page

- src/components/course-calendar/month.cjsx
It wasn't sticking because it was not checking the dropdown's addDate state
Closing as soon as we mouse enter into the box for the selected date.
Stays open because it's checking the actual addDate that the dropdown has set with the date of the box that got mouse enteredededed
> fix calendar add task popover

- src/api.coffee
The simplest thing that could possibly work.  I'm also a fan of making a `Tutor.boot()` method that could initialize this.
> Read CSRF token from meta tag, send with requests

- Gulpfile.coffee
Fonts are being stored in the main dist directory on production but the css is loading them from dist/fonts
WIP until I can verify on vagrant
> Add fonts directory to production build in correct directory

- resources/styles/components/student-dashboard/dashboard.less
- resources/styles/global/navbar.less
- resources/styles/global/tutor-material.less
On screenshots, pointer is hovering on Learning Guide.
Before:
I think this should also correct the orange background from showing on the testing site, but's hard to be sure since we can't replicate locally.
> Fix random orange color appearing on dashboard

- src/flux/helpers.coffee
When the network times out or is otherwise interrupted the status is 0, indicating "no status".
http://stackoverflow.com/questions/3825581/does-an-http-status-code-of-0-have-any-meaning/26451773#26451773
This is the root cause of the task-steps becoming un-navigable  after a network timeout.  To test, you can load up the task steps, shut down the server, and then attempt to click on a breadcrumb.
> Don't delete cached data when no reply is received

- resources/styles/components/course-calendar/header.less
- resources/styles/components/course-calendar/index.less
- resources/styles/components/course-calendar/month.less
- resources/styles/components/student-dashboard/dashboard.less
- resources/styles/global/tutor-booksplash-background.less
- resources/styles/tutor.less
- src/components/course-calendar/header.cjsx
- src/components/student-dashboard/dashboard.cjsx
- src/components/task-plan/teacher-task-plans-listing.cjsx
- src/flux/course.coffee
- src/flux/student-dashboard.coffee
With cursor hovered over `Add  iReading`:
> Style teacher calendar like the student dashboard

- src/api.coffee
- src/flux/time.coffee
- test/time.spec.coffee
Fix for cases where the server returns 500 or other error which also means it sends a null server time.
> Error checking on timestore set when it originates from a string

- resources/styles/global/navbar.less
- resources/styles/global/tutor-material.less
- src/components/navbar/index.cjsx
Looks like the material design added some default styling that overrode our defaults
Before:
After:
> Fix colors and sign out option on navbar menu

- resources/styles/tutor.less
This was moved into reading/interactive.less where it's included from reading.less
> Remove reference to non-existant interactive file

- index.coffee
- index.html
- src/components/html.cjsx
No UI Changes (except that MathJax should load and work).
Paired with https://github.com/openstax/tutor-server/pull/318
Source: http://docs.mathjax.org/en/latest/configuration.html?highlight=authorinit#configuring-mathjax-after-it-is-loaded
> delay loading MathJax until configured

- resources/styles/book-content/base.less
- resources/styles/book-content/mixins.less
- resources/styles/book-content/watch-physics.less
- resources/styles/book-content/worked-examples.less
- resources/styles/components/task-step/index.less
- resources/styles/components/task-step/reading/interactive.less
- resources/styles/components/task-step/video.less
- resources/styles/variables.less
Fixes an assortment of problems that crop up when the screen is narrower
than around 1000px.  Sims and video were particularly bad
Before:
After:
As discovered by @kevinburleigh75 with his tiny screen.
> Center video and collapse padding on small screens

- src/flux/student-dashboard.coffee
Going from the dashboard to answering some questions and then back to the dashboard did not update the list of events. It does now
> student dashboard no longer caches tasks

- index.coffee
- src/components/html.cjsx
- src/helpers/mathjax.coffee
Seems to fix:
- dashboard -> learning guide
- initial load of the calendar
but @nathanstitt's code for cleaning up MathJax elements might be cleaner and good to include anyway
> fix some invariant errors caused by MathJax

- src/components/course-calendar/add-menu-mixin.cjsx
No UI changes, smoother experience from calendar to builder
> use transition to instead of full page reload for adding homeworks and readings from calendar

- resources/styles/book-content/base.less
- resources/styles/book-content/mixins.less
- resources/styles/book-content/worked-examples.less
WIP until @Fredasaurus lets us know what they should look like.  Right now I'm styling them the same as a sub-title element.
> Style the title for worked-example solutions blocks

- resources/styles/book-content/base.less
- resources/styles/book-content/fun-in-physics.less
- resources/styles/book-content/links-to-physics.less
- resources/styles/book-content/mixins.less
- resources/styles/book-content/work-in-physics.less
- resources/styles/global/scaffold.less
- resources/styles/tutor.less
- resources/styles/variables.less
Image without `tutor-ui-horizontal-img` class:
Image with:
> Set IReading images to max-width 100%

- src/components/task-plan/homework.cjsx
- src/components/task-plan/homework/exercise-summary.cjsx
Still need to hide footer when publish is enabled.
> New Homework Summary Bar

- resources/styles/book-content/base.less
Fixes bug where .splash element wasn't resizing it's children to be 100% width
> Move .splash specifier below others for precedence

- resources/styles/global/forms.less
Styling was cascading down to all titles and paragraphs inside a note causing everything to appear italic.
> Remove italic styling from notes

- src/components/pinned-header-footer-card/index.cjsx
Fixes issue with Dashboard and learning guide always scrolling after visiting the a task
Identified during discussion on #353 
The original code was only remembering a single class to remove, but added several other classes.  This just remembers whatever the `body` had on mount and then restores it on unmount.
> reset the body's classlist on unmount

- resources/styles/mixins.less
- src/components/task-step/ends.cjsx
- src/components/task-step/step-mixin.cjsx
Saw this problem when checking through all the panels to make sure I'd hadn't messed anything up
Moved task name and due date out of each step panel and into the fixed footer
> fix practice end panel, fix duplicated details on homework review

- resources/styles/global/navbar.less
Override's a media query that bootstrap material design uses to set the height to 50px on `(max-width: 1199px)`
Before (screen width 900px):
After:
> Set fixed height of navbar

- src/components/task-step/exercise/modes.cjsx
Will talk to BE about related_content have info, but this is good to prevent trying to refresh something that is not refreshable
Always show "Refresh My Memory" with "Try Another" even when there is not related content to refresh with
> only show refresh my memory when we can

- resources/styles/components/pinned-header-footer-card/index.less
- resources/styles/components/task-plan/homework.less
- resources/styles/components/task/index.less
- src/components/pinned-header-footer-card/index.cjsx
- src/components/task-plan/homework.cjsx
handles different header heights for pinned containers
working on handling header height changes properly
a different take on #368 
For example when breadcrumbs fill into a new row
> Margin on container should be based on headerHeight

- resources/styles/components/course-calendar/plan.less
> alpha: show both lines of a plan label when active

- resources/styles/book-content/base.less
Before:
After:
Does anyone know of a good flex box less mixin?  I think this bit of styling would benefit from it since it now has both -ie and -webkit prefixes.
> Specify -webkit prefixes for chapter headings

- resources/styles/components/task-step/exercise/index.less
Unfortunately, images on exercises are just a IMG tag without a class or wrapping element so more specific selection isn't possible.
The `margin: @auto` bit isn't strictly needed, but it makes some larger images look better since they have equal margin on both sides rather than just a slightly larger white space on the right.
Before:
After:
> Center and disable text wrapping on exercise images

- package.json
- resources/styles/components/tutor-input.less
- resources/styles/global/forms.less
- resources/styles/tutor.less
- src/components/tutor-input.cjsx
Just as I was starting to fork the component in order to add something like this, I discovered that they've just added a new `dayComponent` prop that allows you to render the dates yourself.
> Display and style past dates on date picker

- resources/styles/components/reference-book/page.less
- resources/styles/global/maths.less
> Reference book styling fixes

- resources/styles/components/task-step/step-mixin.less
- src/components/task-step/exercise/modes.cjsx
- test/components/helpers/task/checks.coffee
> stop footer-buttons from breaking to new line next to details

- resources/styles/components/task-plan/builder.less
- src/components/task-plan/builder.cjsx
- src/components/task-plan/index.cjsx
- src/components/task-plan/plan-mixin.coffee
- src/components/tutor-input.cjsx
- src/flux/task-plan.coffee
If the "All  Periods" checkbox is checked, the periods are hidden and any updates to the dates are copied to all the periods.
If dates are set while the checkbox is checked, all taskings are set to the date.
When the checkbox is unchecked and then checked, the tastings dates are compared and the "global" date inputs are updated if all taskings have the same opens_at/due_at
> "All Periods" checkbox support

- src/router.cjsx
Ideally we could redirect on this to the `courses/<id>t/t/calendar` url but React router doesn't seem to support that.
> Specify default handler for courses/<id> url

- resources/styles/global/tutor-booksplash-background.less
- resources/styles/global/typography.less
The main issue was that the :before block was missing a height, which IE defaulted to 0.
The rest is tweaks so it displays identically in both IE and chrome/firefox/safari.
> Fix "booksplash" banner so it displays in IE

- src/components/navbar/admin-link.cjsx
- src/components/navbar/index.cjsx
The navbar wasn't being updated if the user store load finished after it was rendered.  This allows the admin button to update independently the way the username component does.
> Admin link component that updates with user store

- src/components/task-plan/builder.cjsx
- src/components/task-plan/reading.cjsx
- src/components/tutor-input.cjsx
The earliest date for opens_at date is today, and due date should be the value of the opens_at date.
Also fixes the bug when un-selecting/re-selecting a period, and silences some missing key React warnings.
Not much UI change, other than past date selection is now disabled (screenshot taken on the 25th):
> Adjust starting dates for HW builder 

- resources/styles/global/react-datepicker.less
Fixes a bug on deployed code.
`@import "...css";` by default keeps the `@import` directive instead of including the CSS file in the minified `tutor.css` file.
> date picker CSS was not being included

- resources/styles/book-content/base.less
- src/components/book-content-mixin.cjsx
- src/components/html.cjsx
- src/components/reference-book/navbar.cjsx
- src/components/reference-book/page.cjsx
Oops, the `BookContentMixin` was required by reference book pages component, but not inserted into the `mixins` array.
This also tweaks the image `onload` function to only scale a `tutor-ui-horizontal-img` up to full width if it's naturalWidth is more than 450px.  That prevents small images being blown up and looking jaggy.
Before:
After:
> Apply image sizing logic to reference book pages

- src/components/task-step/all-steps.cjsx
Not sure why it wasn't on Readings originally, or how it ever worked since when they lacked it. The only thing I can think of is that task steps where not using the Readings component in the past?
Works now at least:
> Add booksplash to Readings component (was on Interactives)

- resources/styles/global/maths.less
- src/helpers/mathjax.coffee
This corrects the height of the mathjax spans.
Before:
After:
This also removes call to `cleanMathArtifacts` on startup.  I'd noticed that occasionally I'd see a "this.queue is undefined" exception when the page was reloaded in chrome but hadn't been able to find the source of the error.  Mathjax continued to render fine, so I didn't pay it too much attention.  When debugging the mathjax positioning I loaded in Firefox where it occurred more often and was able to find it originating from the cleanup call.
> Fix mathjax exercise answer rendering height

- src/components/task-teacher-review/breadcrumbs.cjsx
since the plan metrics/review page is being linked to from perf report and calendar, "Back to Calendar" no longer makes sense.  instead, back can take us to the appropriate one
> make back button on review got back to perf report or calendar as appropriate

- src/flux/exercise.coffee
With the new Biology content, the LO tag can be called either `lo` or `aplo`, and the tag's name field no longer contains the description.
The exercise builder has JS errors without this when it attempts to find a LO tag and cannot
> Correct tag usage to accommodate Biology content

- src/components/performance.cjsx
When reviewing an individual iReading begin at the first step rather than the last completed step.
> start at the first step when reviewing

- src/components/performance.cjsx
- src/flux/helpers.coffee
Performance report was not loading for 2 reasons:
- an assumption was made on the initial id (set to `"1"` but rarely true)
- the CRUD store assumed stored things were objects, not Arrays
> Perf report fix

- resources/styles/global/maths.less
This changes the text in Mathjax from using it's built-in STIXGeneral-Regular font:
To use lato:
Unfortunately, the difference isn't very apparent on the screenshots.  Viewing them at full-size is a bit better but it's still not a big change.
If we want to spend more time on this, Mathjax does provide a method to import the Lato font so it knows about it's glyph data and can render everything with it.  http://docs.mathjax.org/en/latest/font-support.html  has the details.
> Force Mathjax text elements to use lato font-family

- src/components/course-periods-nav.cjsx
- src/components/task-plan/reading-stats.cjsx
- src/flux/task-plan-stats.coffee
- test/components/course-periods-nav.spec.coffee
Course nav bar will only show as many stats as available on plan stats
There may be some backend or some frontend issues during plan creation for the full bug to be fixed, but this will work once the stats json only returns for as many periods are assigned the plan
> handle when not all periods are assigned a task plan

- api/courses/1/readings.json
- resources/styles/components/reference-book/index.less
- resources/styles/components/reference-book/navbar.less
- resources/styles/components/reference-book/page.less
- resources/styles/components/reference-book/slide-out-menu.less
- resources/styles/variables.less
- src/components/reference-book/navbar.cjsx
- src/components/reference-book/reference-book.cjsx
- src/components/reference-book/slide-out-menu.cjsx
- src/components/reference-book/toc.cjsx
- test/components/helpers/utilities.coffee
- test/components/reference-book.spec.coffee
This changes the drop down menu on the reference book to slide in from the side.
The icon on the top navbar toggles depending on the menu's state.
The menu behaves in two different ways depending on the screen width.   1350pixels wide was chosen as the break point since the page width is 1,000px and the menu is 300.
If the page is narrower than 1350px, the menu slides over the page content and is dismissed once a link on it is clicked.
If the screen is wider than 1350px appears on the left and pushes the page content and the "previous page" control to the right.  It remains visible when links on it are clicked.
> Slide out menu for reference book

- resources/styles/components/course-calendar/month.less
- src/components/course-calendar/duration.cjsx
> A few calendar bugs

- resources/styles/book-content/base.less
- resources/styles/book-content/fun-in-physics.less
- resources/styles/book-content/glossary.less
- resources/styles/book-content/index.less
- resources/styles/book-content/link-to-learning.less
- resources/styles/book-content/links-to-physics.less
- resources/styles/book-content/mixins.less
- resources/styles/book-content/note.less
- resources/styles/book-content/visual-connection.less
- resources/styles/book-content/watch-physics.less
- resources/styles/book-content/work-in-physics.less
- resources/styles/book-content/worked-examples.less
- resources/styles/components/reference-book/page.less
- resources/styles/components/reference-book/toc.less
- src/components/book-content-mixin.cjsx
- src/components/reference-book/navbar.cjsx
- src/components/reference-book/page.cjsx
- src/components/reference-book/toc.cjsx
Mainly biology related but fixes a few bugs also.  Namely it:
* Adds uniform padding to the book content container element vs the individual elements setting their margins.
* Fixes the intro image overlay from not appearing on chapter_sections.
* Adds highlighting to the current page being displayed on the table of contents
This is an interesting one.  Should the teacher always have content, or should I not style the misconception if it immediately follows `ost-teacher` ?
> Book content styles

- src/components/tutor-input.cjsx
stops course calendar from switching to starting to monday after viewing the datepicker as well
> make date picker on plan builder start on Sunday

- resources/styles/components/student-dashboard/dashboard.less
Believe it was overwriting the earlier correct no-repeat in some browsers since we've had a bug report saying the background was repeating.  Chrome & Firefox both seemed to handle it fine though.
> Don't specify invalid 'background-repeat: none;' on browse the book icon

- resources/styles/book-content/note.less
Otherwise they'll float alongside vertical images
Before/After:
> Clear float on note type elements

- api/courses/1/dashboard.json
- src/flux/student-dashboard.coffee
- test/components/student-dashboard.spec.coffee
Since the student dashboard shouldn't know about them at all, just set the store's methods to filter them out.
> Events that are un-opened should not be worked

- src/components/course-calendar/month.cjsx
- src/components/tutor-input.cjsx
Otherwise, moment locale will be messed up and the dashboard cal suffers as a result, for example.
react-datepicker [sets global locale](https://github.com/Hacker0x01/react-datepicker/blob/master/src/calendar.jsx#L44-L49) and causes moment to be confused
1. load builder
2. cancel
3. the dashboard is :cry: 
3. YAY!
> restore locale settings when done with react-datepicker.

- src/components/course-data-mixin.cjsx
- src/components/html.cjsx
- src/components/reference-book/reference-book.cjsx
- src/components/student-dashboard/dashboard.cjsx
- src/components/task-plan/teacher-task-plans-listing.cjsx
- src/components/task-step/all-steps.cjsx
For iReading, reference book, calendar, and dashboard as data-attributes -- ```data-title``` and ```data-category```, following pattern set up by @nathanstitt for dashboard and calendar.
So that theming for content can happen following the same pattern for book-content.  As per discussion with @helenemccarron, this should allow us to do our theming something like this:
```less
// A mixin to style book content from CNX
.tutor-book-content() {
@reading-ui-banner-height: 40px;
padding: 0 @tutor-card-body-padding-horizontal @tutor-card-body-padding-vertical @tutor-card-body-padding-horizontal;
display: block;
@import './mixins';
@import './base';
@import './splash-image';
// type specific styling comes last so it can override the above styles
@import './link-to-learning';
@import …
```
> course data can pass title and category onto elements

- resources/styles/global/tutor-booksplash-background.less
- src/components/student-dashboard/dashboard.cjsx
Removes the default color from the booksplash, which was set to the physics.  I think this is the cause of the "shows physics colors, then rapidly switches to biology on load" bug.
Also fixes spacing on a 1024 wide display:
Before/after
> A few student dashboard style tweaks

- resources/styles/components/reference-book/page-navigation-controls.less
- resources/styles/components/reference-book/page.less
- resources/styles/components/reference-book/slide-out-menu.less
Noticed this and just decided to quickly see if it could be changed
> prev and next nav should now grow and shrink with the menu slide out

- src/components/course-calendar/plan-details.cjsx
Oops. A bug I introduced from changing the button for external plans
> put review metrics button back in

- src/components/learning-guide/progress-bar.cjsx
Replaces old title method that was hit or miss on if it would display:
With a tooltip component:
> Add "Click to practice" tooltip to practice buttons

- src/components/pinned-header-footer-card/index.cjsx
was causing homework builder to have errors and get stuck at problems selection.
> fix the builder's confusion around the sticky header

- src/components/tutor-input.cjsx
Fixes #513
The value passed to isValid is a momentjs instance, which
can't be compared using > < operators.  This switches to
the isBefore and isAfer methods with the granularity set to day.
Also if false was returned from the date picker, the min property
would be used.  However if the min property is a plain date object
it would lack the .format method which was later called on it.
> Fix "value.format is not a function" bug

- resources/styles/components/performance/index.less
- src/components/performance/external-cell.cjsx
- src/components/performance/index.cjsx
- src/components/performance/quick-external-stats.cjsx
- src/components/task/viewing-as-student-name.cjsx
Broke when trying to make header for external task with linkToSummary.
Does not linkToSummary for header.  Instead, should show plan text clicked counts.
> handle external tasks in perf report properly

- resources/styles/components/task-step/step-footer-mixin.less
- resources/styles/components/task/details.less
- resources/styles/components/task/index.less
- src/components/task-step/step-footer-mixin.cjsx
- src/components/task/details.cjsx
late icon was showing in both, and also info icon was in between due date and late icon
> fix late styling for reading task footer -- don't show

- src/components/course-settings/add-student.cjsx
- src/components/task-plan/builder.cjsx
- src/components/tutor-input.cjsx
removing ```value={@props.value}``` from ```input``` because whenever ```@props.value``` was updating from the parent scope, the re-rendering of the input element would force the cursor to the right all the time
Seems to behave like normal now.  I also checked the behavior of the Add Student form in Course Settings and it preserves student info if you close the form without saving, as intended.
> fix input cursor to right bug

- src/components/task-plan/footer.cjsx
Now the publish button won't show a spinner when saving and the save as draft button won't show a spinner when publishing.  
Though maybe we should disable actions when either are occurring? @philschatz
> Spinners on one button at a time

- src/components/task-plan/builder.cjsx
- src/components/tutor-input.cjsx
- src/helpers/time.coffee
calendar was messing up again when the one datepicker opening would set the locale globally. when switching to individual periods, new datepickers would mount and pick up the wrong locale to reset to.  the current locale needs to be able to be passed in from the parent
> half calendar issue is haunting us

- resources/styles/components/course-settings.less
- src/components/course-settings/period-roster.cjsx
- test/components/course-settings.spec.coffee
WIP until it's decided if the "Tutor ID" column should be removed and if the link to it on the menu should be changed to read "Student Roster" or something else.
> Remove Add, Delete and PW reset actions

- package.json
- resources/styles/components/performance/index.less
Also updates fixed-data-table to 0.4.1, which includes a bug fix for the scrollbars appearing on top of the row headers.
> Display assignment names with an ellipsis when they're too long for the column

- package.json
- src/components/learning-guide/guide.cjsx
- src/components/learning-guide/practice-by-type-button.cjsx
- src/components/student-dashboard/practice-buttons.cjsx
- src/components/student-dashboard/progress-guide.cjsx
- src/flux/learning-guide.coffee
- test/all-tests.coffee
- test/components/helpers/component-testing.coffee
- test/components/learning-guide/practice-by-type-button.spec.coffee
- test/components/student-dashboard/practice-buttons.spec.coffee
When BL doesn't return any pages the button needs to be aware of that and not attempt the practice.
**Note:** This adds a new component rendering helper, and also imports the sinon mocking library.  suggestions are welcome on whether this is a good idea or how it could be improved.  My goals with the helper are to allow testing a component with as little effort as possible.
> Fix practice buttons that lead to empty practice sets.

- src/components/book-content-mixin.cjsx
The dataset attribute isn't supported by IE 10 and it's use without a `?` guard was causing an "Unable to get property 'type' of undefined or null reference” exception.
> Use getAttribute instead of dataset

- api/courses/1/students.json
- src/components/course-settings/period-roster.cjsx
- test/components/course-settings.spec.coffee
When students are removed from a course they are marked inactive, but up until this PR that has had no effect in the FE.   https://github.com/openstax/tutor-server/pull/530 adds an `active` property to the student JSON in the roster.  This PR filter out all inactive students from the roster -- later the FE can choose to show them differently so we can enable reactivation of students (undropping them).
> Hides all inactive students

- src/flux/task-plan.coffee
- src/helpers/task.coffee
- test/task-helpers.spec.coffee
> Sort HW builder's chapter sections so they appear in order

- src/components/task-plan/footer.cjsx
- src/components/task-plan/teacher-task-plans-listing.cjsx
- src/flux/helpers.coffee
- src/flux/teacher-task-plan.coffee
- test/components/helpers/calendar/actions.coffee
- test/components/helpers/calendar/checks.coffee
- test/components/helpers/calendar/index.coffee
When a large task is deleted, it takes the BE quite awhile to process the network request.  This causes problems due to how our flux stores are setup.  The sequence is:
* The delete action fires, which fires off the request to the BE and sets the store's asyncStatus = DELETING
* Teacher browses around, while the delete xhr request is still pending.  The data is still present in the store and shows on the calendar.
* xhr delete finally completes and than we finally delete the task from the store
Other options for this might be to delete the task from the store immediately when we fire the delete action to the BE.  This would stop the task from showing up, but if the delete failed we wouldn't be able to "resurrect" the task very easily.
> Filter out tasks that are being deleted from calendar

- src/components/course-settings/period-roster.cjsx
The student's role number was displayed in the roster with "Tutor ID" as the heading -- this number is not useful to the teacher.  However, the "deidentifier" is -- it can be used to talk about students over insecure channels like email without divulging names.  This PR replaces the role with the deidentifier.
I also added a tooltip, which probably could use styling if we even want to keep it.  
I also removed the "Period: Period 1" heading that duplicates the name in the tab.
I'm totally fine if no one wants this PR :-)
> Replaced 'Tutor ID' role # in roster with deidentifier

- resources/styles/components/question.less
- resources/styles/mixins.less
- resources/styles/variables/colors.less
- src/components/question.cjsx
- src/components/task-plan/homework/exercises.cjsx
- src/components/task-step/exercise/modes.cjsx
- test/all-tests.coffee
- test/components/question.spec.cjsx
TODO:
Homework Builder:
Multiple choice question.  The same component is used for both readings, homeworks, and practice exercise. The UID is displayed identically on them all.
> Show exercise uid on HW builder

- resources/styles/components/course-settings.less
- resources/styles/global/buttons.less
- resources/styles/tutor.less
- src/components/course-settings/period-roster.cjsx
- src/components/icon.cjsx
- src/flux/roster.coffee
This adds the add and remove student actions back to the course settings screen.  Reset password is still left as disabled.
> Restore course roster add/remove student actions

- src/components/task-plan/builder.cjsx
Changed field labels in plan builders.
> Updating label for description field

- src/components/task-plan/builder.cjsx
- src/components/task-plan/footer.cjsx
- src/flux/task-plan.coffee
Disables publish, save, cancel and delete in the plan footer when either saving or publishing.
> Disabling actions on plan footer

- src/flux/task.coffee
- test/task-store.spec.coffee
Past due-ness used to be based on whether current time is after the due DATE.  However, this is changed now that we have a set due time.  Use due time as opposed just due DATE.
Note: Need to use task due date to compare because other determining whether something is past due will be dependent on whether someone has worked a task.
> fix when task is due, breadcrumbs should show correct or incorrect status

- src/components/reference-book/exercise.cjsx
- src/components/reference-book/page.cjsx
- src/components/reference-book/toc.cjsx
- test/components/reference-book.spec.coffee
Corrects bug where a link to a chapter such as 7.2 was clicked but the table of contents menu wouldn't show it because it was below the scroll area.
> Scroll reference ToC so the entry for the current page is visible

- src/components/course-calendar/duration.cjsx
- src/components/course-calendar/plan.cjsx
> Fix various bugs to do with plan publishing and clicking on plans

- src/components/task-plan/homework/exercises.cjsx
- src/components/task-plan/reading.cjsx
> Disallow actions after plan is visible

- src/components/course-settings/drop-student.cjsx
- src/components/course-settings/period-roster.cjsx
- src/components/icon.cjsx
- src/flux/current-user.coffee
- test/all-tests.coffee
- test/components/icon.spec.cjsx
- test/components/navbar.spec.coffee
- test/current-user-store.spec.coffee
* Renames Delete action to be Drop
* Renames the link to be "Course Roster"
* Removes the add student button
* Fixes a dumb bug in the Icon component and adds a spec so it doesn't re-occur.
> Course Roster changes

- resources/styles/book-content/base.less
- resources/styles/book-content/context-mixins.less
- resources/styles/book-content/hs-physics/grasp-check.less
- resources/styles/book-content/hs-physics/index.less
- resources/styles/book-content/index.less
- resources/styles/book-content/learning-objectives.less
- resources/styles/book-content/note.less
- resources/styles/book-content/theming-mixins.less
- resources/styles/book-content/variables.less
- resources/styles/components/question.less
- resources/styles/components/reference-book/page.less
- resources/styles/components/task-step/all-steps.less
Allowing for I-Reading specific styles. Added context-mixin for now.
TODO: full refactor, see napkin note https://github.com/openstax/napkin-notes/blob/master/phil/s016-book-styling-refactor.md
*Screenshots not available*
Removed grey background on all notes in the iReading view, removed extra padding within notes, excluded tips-for-success to display as regular notes in the iReading view. 
Reference book new styles:
bullets to match iReading + theming mixin for colors
Removed numbered list-styles for footnotes
Tightened up question styles
Tightened up learning objectives styles
Restyled grasp checks
> Adding iReading specific styles

- src/router.cjsx
Calendar now preserves scroll position as expected
> ignore router default scroll behavior when viewing plan stats on calendar

- src/components/reference-book/exercise.cjsx
I left a question mark in there from when we were switching jsons back from the absolute url to the queries url
> exercises werent rendering because oops

- resources/styles/components/course-calendar/month.less
- resources/styles/components/reference-book/page.less
- resources/styles/mixins.less
- src/components/book-content-mixin.cjsx
- src/components/chapter-section-mixin.cjsx
- src/components/reference-book/index.cjsx
- src/components/reference-book/navbar.cjsx
- src/components/reference-book/page.cjsx
- src/components/reference-book/reference-book.cjsx
- src/components/reference-book/slide-out-menu.cjsx
- src/components/reference-book/toc.cjsx
- src/components/task-plan/chapter-section.cjsx
- src/components/task-step/all-steps.cjsx
- src/flux/reference-book.coffee
- src/router.cjsx
This way the title will always match the selected entry
With chapter 7 selected, before:
After:
> Match title displayed to selected entry from ToC

- src/components/reference-book/index.cjsx
When trying to renderLoading, it was trying to render the page despite not having received cnxId as a prop from it's parent yet
> fixes trying to load without cnxId as props on ref book page

- resources/styles/components/course-calendar/index.less
- src/components/course-calendar/duration.cjsx
- src/components/course-calendar/plan.cjsx
> shows when plan opens on plan label

- resources/styles/book-content/ap-bio/ap-connection.less
Remove the top border on in AP Connection on title that was still displaying. 
Fixed an alignment issue in Firefox for the first letter of the paragraph
> Fix for issues in AP Connection 

- src/components/reference-book/reference-book.cjsx
show/hide teacher edition link will now show even when transitioning from `/book/:courseId`
> course listing listeners werent binding due to return

- src/components/student-dashboard/this-week-panel.cjsx
Luckily the store grabs all events for the week so at least this was
showing all the events, but was confusing for the title to be incorrect.
Snapshot taken on Aug 6th:
> Fix date range on dashboard this week panel

- resources/styles/book-content/base.less
- resources/styles/book-content/splash-image.less
- src/components/book-content-mixin.cjsx
- src/helpers/dom.coffee
- test/all-tests.coffee
- test/dom-helpers.spec.coffee
Somewhere along the line the figure's stopped automatically being 100% wide.  This broke the image expansion since their 100% width would be constrained by the size of the figure.
This changes the JS logic to walk up the tree to the figure and apply the full-width classes to it, and then sets the styles to match.
It does so by adding a new "DOM" helper with an implementation of jQueries `.closest`
> Set figure's that contain an appropriate sized image to 100% width

- src/components/tutor-input.cjsx
* Only shows part of the content.
* Still only shows part of the content
* Surprise!  You do have a description here
* Shows all content on load
* textarea height updates as change happens still
> textarea shows textarea values right on open for builder, as opposed to waiting till a change

- index.coffee
- src/api.coffee
- src/components/navbar/index.cjsx
- src/flux/course-listing.coffee
- src/flux/current-user.coffee
- src/helpers/conditional-rendering.coffee
- src/helpers/dom.coffee
- src/router.cjsx
- test/dom-helpers.spec.coffee
In order to restrict access to a given route, the app needs to know what course roles the user has very early in it's lifecycle. 
The BE PR [#562](https://github.com/openstax/tutor-server/pull/562) provides it to the app via json data enclosed in a script tag.  This will allow the app to continue to function even if the tag isn't provided for some reason, such as running locally.
There's a few other advantages to bootstrapping the stores this way.
* The FE needs to make two less XHR requests when it's loaded.
* The "Flash of un-styled content" issue no longer occurs on the reference view. Currently if the view is loaded it will first display using the standard book colors and then switch to the appropriate physics or biology colors once the course store loads.
* The navbar displays the …
> Restrict rendering to routes based on user role

- resources/styles/components/task/breadcrumbs.less
- resources/styles/mixins.less
- resources/styles/old/global/icons.less
- src/components/breadcrumb/breadcrumb-mixin.cjsx
- src/components/breadcrumb/index.cjsx
- src/components/task/breadcrumbs.cjsx
discussed with @Fredasaurus  and this is our temporary solution
> Handling  too many breadcrumbs

- api/courses/1/guide.json
- api/user/courses/1/guide.json
- resources/styles/components/learning-guide.less
- resources/styles/components/learning-guide/statistics.less
- resources/styles/global/debug-toggle.less
- resources/styles/tutor.less
- src/components/app.cjsx
- src/components/learning-guide/chapter-section-type.coffee
- src/components/learning-guide/chapter.cjsx
- src/components/learning-guide/guide.cjsx
- src/components/learning-guide/progress-bar.cjsx
- src/components/learning-guide/section.cjsx
- src/components/learning-guide/statistics.cjsx
- test/components/learning-guide/practice-button.spec.coffee
- test/components/learning-guide/progress-bar.spec.coffee
- test/components/learning-guide/section.spec.coffee
This updates the FE to handle the additional CLUE values that the BE is now sending.
The Performance Forecast will now only hide the bar if the `sample_size_interpretation` is `below`.  
It now has a secret debug option that will display all the values for debugging.  The option is an invisible pi symbol [ [background](https://www.google.com/search?client=safari&rls=en&q=the+net+pi+symbol&ie=UTF-8&oe=UTF-8) ] at the bottom left corner of the screen.  It's normally transparent, but turns grey when the mouse is hovered over it.  When clicked, display of all CLUE values is toggled.
@Fredasaurus any thoughts on the debug option?
> New clue attribute with all elements of data

- resources/styles/book-content/note.less
Fix wrapping issues within moving man. This also fixes wrapping issues within notes in IE11
> Fix the notes not wrapping properly in moving man + IE11 note text wrap issues

- src/components/learning-guide/chapter.cjsx
- src/components/learning-guide/guide.cjsx
- src/components/learning-guide/progress-bar.cjsx
- src/components/learning-guide/section.cjsx
- src/components/learning-guide/student.cjsx
- src/components/learning-guide/teacher-student.cjsx
- src/components/learning-guide/teacher.cjsx
- src/components/learning-guide/weaker-panel.cjsx
- src/components/learning-guide/weaker-sections.cjsx
- src/components/student-dashboard/progress-guide.cjsx
- test/components/learning-guide/progress-bar.spec.coffee
Allow the teacher and student components to set a value for the # of samples needed to render the progress bar.  If the value given is exceeded the bar will render regardless of what the clue's sample_size_interpretation value is.
> Add sampleSizeThreshold property to progress bar

- src/components/learning-guide/progress-bar.cjsx
- test/components/learning-guide/progress-bar.spec.coffee
The "no data" message should be shown if the sample_size was below the
threshold, not above it. Lukily the interpetation had to also be 'below'
otherwise the no-data message would be shown all the time
> Fix incorrect logic when evaluating sample size limit

- resources/styles/components/course-calendar/plan.less
- src/components/course-calendar/duration.cjsx
- src/components/course-calendar/month.cjsx
- src/components/course-calendar/plan-display.cjsx
- src/components/course-calendar/plan-label.cjsx
- src/components/course-calendar/plan.cjsx
Order does not matter
Spacing tweaked and improved as well
Changes are based on the idea that the plan should be one component, even if it's being displayed by 2 or more elements due to splitting over weeks.  Displays are then their own component, concerned only with handling the display of the plan.
Before, there could be multiple plan components per actual plan, and this required syncing hover and clicked state across components with [janky direct element maniputation](https://github.com/openstax/tutor-js/blob/master/src/components/course-calendar/plan.cjsx#L149-L173)  as opposed to now with [a shared state update on the plan which passes down to the displays](https://github.com/openstax/tutor-js/blob/bug/calendar-plan-details-mistrigger/src/components/course-calendar/plan.cjsx#L122-L132 …
> Fix plan label not opening details when there's 2 that represent that plan

- resources/styles/book-content/questions.less
> Prevent text wrapping on exercise images

- src/components/resize-listener-mixin.cjsx
- src/components/task/breadcrumbs.cjsx
Component was confused about it's size, so it would sometimes shrink things initially when it didn't need to.  It would size appropriate on window resize or next crumb update.
> fix mis-sizing of component from resize listener

- src/components/learning-guide/progress-bar.cjsx
- src/components/learning-guide/weaker-sections.cjsx
- src/components/student-dashboard/dashboard.cjsx
- src/components/student-dashboard/progress-guide.cjsx
- src/flux/learning-guide.coffee
Previously sections were discarded from appearing in the weaker areas of the performance forecast if the `sample_size_interpretation == 'below'`.  We then changed the section to also use the sample_size but failed to update the logic for picking weaker sections.
This moves the logic into the LearningGuide store and uses that for the sections as well.  Now sections should be more likely to appear in the "weaker areas" panel.
> Use sample size for choosing weaker sections

- src/components/task-plan/builder.cjsx
- src/flux/task-plan.coffee
Fix for changing from individual periods to all periods in the task plan builder.  It was not working before.
* save a task plan with only one period selected as the date
* open it  up from the calendar again, try to save it with all periods
* **Before**: Saves with the original period info
* **Now**: Saves with all periods as expected
> Fix changing from individual periods

- src/components/course-calendar/duration.cjsx
- src/components/course-calendar/plan-details.cjsx
@Fredasaurus  would this work?
> plan is only editable if no due date is before today

- resources/styles/components/tutor-dialog.less
- src/components/tutor-dialog.cjsx
As discussed in #644 this moves the buttons to the left and switches their order so that the OK button appears first
> Move buttons to left and show OK first

- src/components/task-step/exercise/modes.cjsx
When try another happens afterwards, task is marked as past due, performance report says student is in progress, score is changed, etc.  These are not expected behaviors.
> no try another for past due because that will cause problems

- src/components/navbar/account-link.cjsx
- test/components/navbar/account-link.spec.coffee
Regarding issue:  https://www.pivotaltracker.com/n/projects/1156756/stories/101144278
This time not check unsaved state since it's a new window/tab being opened.
> My Account link open in new tab/window

- src/components/tutor-input.cjsx
Without this, IE 10 users have to click the tiny space under the label and before the line.
IE 10 doesn’t support the “pointer-events: none” style
so the label grabs the click and it doesn’t fall through to the input.
> Focus input when label is clicked for IE 10

- src/components/book-content-mixin.cjsx
1. Clicking on link
1. After link is clicked, focuses on targeted figure, on same page/tab
* see link in bottom right hand corner of previous SS.  shows properly formed reference book link
1. Clicking on link
1. After link is clicked, opens to figure in new tab
* not properly linked because link does not get processed
> Links in ref book and iReadings need some updates

- src/components/task-plan/homework.cjsx
- src/components/task-plan/plan-mixin.coffee
- src/components/task-plan/reading.cjsx
- src/components/task-plan/select-topics.cjsx
- src/flux/task-plan.coffee
No UI changes, just allows for cancel when selection problems or readings.
From testing previous to this sprint: https://www.pivotaltracker.com/story/show/101136084
Homework problems and reading selections do not clear upon cancel
1. Selection
1. After cancel
1. Selection
1. After cancel
1. Selection
1. After cancel
1. Selection
1. After cancel
> Fixing cancel on select problems/readings

- resources/styles/book-content/ap-bio/ap-connection.less
- resources/styles/book-content/base.less
- resources/styles/book-content/index.less
- resources/styles/book-content/learning-objectives.less
- resources/styles/book-content/note.less
- resources/styles/book-content/splash-image.less
- resources/styles/book-content/theming-mixins.less
- resources/styles/components/reference-book/navbar.less
- resources/styles/global/navbar.less
- resources/styles/old/global/buttons.less
- src/components/reference-book/navbar.cjsx
A grab bag of reference view and interactive reading styles. Apologies for the breadth.
1. Moving the title overlay below the image. Also now accommodates two line titles.
2. Changing the alpha of Physics LOs to make them easier to read on blue background.
3. Making the spacing after the Chapter intro sections consistent.
4. Creating styles for key terms.
5. Styling the show teacher content into button.
6. Adding Key Terms styles for all content
> Intro pages, chapter titles, key terms, show teacher content

- src/components/book-content-mixin.cjsx
- src/components/task-plan/chapter-section.cjsx
- test/all-tests.coffee
- test/components/book-content-mixin.spec.coffee
Sometimes the when ref book router params do not have courseId, they just have bookId.  
No need to look it up in that case.
> Fix JS exception when navigating reference book

- src/components/course-calendar/month.cjsx
- src/components/course-calendar/plan-display.cjsx
- src/components/course-calendar/plan.cjsx
- src/components/task-plan/plan-mixin.coffee
- src/flux/plan-publish.coffee
- test/components/course-calendar.spec.coffee
Fixes [13, 17, 25](https://docs.google.com/spreadsheets/d/1P0eq49e7u1uM3SUI9pULo7EQYZIJt1KLOOfBidHdFSY/edit#gid=1446311939)
1. Publish a plan
1. Allow it to finish publishing
1. Click on plan
1. Click on 'Edit'
1. Click browser's back
* if you can catch it, the plan momentarily is a draft, but will change to published quickly
* Plans don't line up with weeks on calendar, and stats don't open
* call stack error yelling from console
1. at this point, IE 11 in a VM will also get stuck with plan in draft state.
Clicking the browser's back on step 5 should bring you back to the calendar with the plan's details open.  There is no flash of the plan as a draft, and calendar will be lined up right, and the URL should show as plan details view state.
1. Plan on publish would always open to current …
> Prevents call stack issues from publishing, view stats, going to edit view, and then hitting the back button

- src/components/course-calendar/plan.cjsx
- test/components/course-calendar.spec.coffee
- test/components/helpers/calendar/checks.coffee
Also, update specs to prevent this regression
1. make a plan
1. save as draft
1. click on plan from calendar
* bugged: doesn't do anything, updates route
* fixed: takes you to edit page for plan
> fix where draft was not linking to edit from calendar

- src/components/task-plan/external/index.cjsx
- src/components/task-plan/footer.cjsx
- src/components/task-plan/homework.cjsx
- src/components/task-plan/plan-mixin.coffee
- src/components/task-plan/reading.cjsx
- src/flux/task-plan.coffee
- src/flux/toc.coffee
trying to use router.goBack would cause problems sometimes in edge cases where:
1. teacher deletes a plan
1. teacher then creates a new plan
1. teacher publishes or cancels
* sometimes would cause a 404 as it attempts to go back to calendar, but to the deleted planId's route
* for whatever reason, go back is tracked to the wrong route.
This PR aims to fix this issue by:
1. building calendar back route manually from due_at and plan id information
1. pulling leaving builder functions from publish, save, delete, cancel, etc. to use the central `@goBackToCalendar` function
1. using same cancel function for both X close button and Cancel button in builder footer
1. fixing the resets to be plan specific and use a copy of the plan initially loaded from the server since plan local store gets …
> don't using router go back.  manually build out calendar return route from plan info

- src/components/performance/absent-cell.cjsx
- src/components/performance/index.cjsx
When a student is dropped or transfered to a different period, future
assignements will not have any data.  The student should still
appear in the report but not display any information for the assignments
they didn't participate in.
BE PR: https://github.com/openstax/tutor-server/pull/608
Note the assignments "No Atticus" and "No Lily"  They were assigned after Atticus was dropped from the period, and Lily was transferred to it.
> Render blank cell when no assignment data is present

- src/components/app.cjsx
- src/components/buttons/back-button.cjsx
- src/components/task-step/ends.cjsx
- src/flux/transition.coffee
- src/helpers/routes-and-destinations.coffee
- test/components/helpers/component-testing.coffee
- test/components/task-plan/footer.spec.coffee
This changes the history to only remember routes that can be safely
returned to.
The Back button's helper methods are also modified so that it will only
load the last paths from history that was for a screen other than the
current one.
> Change history to only remember selected routes

- src/components/task-plan/external/index.cjsx
- src/components/task-plan/footer.cjsx
- src/components/task-plan/homework.cjsx
- src/components/task-plan/index.cjsx
- src/components/task-plan/plan-mixin.coffee
- src/components/task-plan/reading.cjsx
- src/components/task-plan/teacher-task-plans-listing.cjsx
- src/flux/task-plan.coffee
- test/components/task-plan/footer.spec.coffee
the older, calmer sister PR to #660 ![calmer?](http://ak-hdl.buzzfed.com/static/enhanced/terminal05/2012/10/11/16/anigif_enhanced-buzz-18508-1349987162-9.gif)
1. publish a plan that opens in the future
1. view and edit
1. click delete
* at this point, the previous PR neglected to take the user back to the calendar without plan id in route
* It only accounted for drafts, and drafts that were being deleted, and avoided the plan id route for those specific cases, as intended
* this really aint no thang since it doesn't cause any 404's though since loading the deleted plan and plan stats is not actually triggered
1. click browser back
* **this is where things start to go wrong.** back to plan edit route will trigger an api hit for the deleted plan
* another back will trigger an api hit for …
> prevent trying to load plan that has been requested for deletion -- prevents the 404

- src/components/task-teacher-review/crumb-mixin.cjsx
yay we get step number now!  FE sorts before displaying...and things seem to work!  BE openstax/tutor-server#597
* question order in review does not match assign order.  it is sorted by page, and then assign order
> yay sort by average step number

- src/api.coffee
- src/components/navbar/server-error-monitoring.cjsx
- src/components/task/index.cjsx
- src/flux/app.coffee
so we take it and flip and reverse it.  just once though.  targeted at [69](https://docs.google.com/spreadsheets/d/1P0eq49e7u1uM3SUI9pULo7EQYZIJt1KLOOfBidHdFSY/edit#gid=1446311939) wherein `422` happens and the last attempted action needs to be repeated before student can continue task
also, captures info about the request.  SS shows spoofed url to force error
1. Before error trigger
1. Spoofed error
1. after closing modal, page reloads and app state is consistent with fresh server load
* In this example, the multiple answer choice patch caused the server error, and so the answer was never saved.  The FE reflects that after the forced reload.
Also, I have yet to achieve the same `422` during an exercise as during doomsday to try this with that.
> Try one mo' gain if server throws an error

- src/components/book-content-mixin.cjsx
Fixes [21](https://docs.google.com/spreadsheets/d/1P0eq49e7u1uM3SUI9pULo7EQYZIJt1KLOOfBidHdFSY/edit#gid=620238128)
* reference link is wrong for reading step of reading task
> fix the reading covers links on a reading step

- src/components/navbar/server-error-monitoring.cjsx
- src/flux/app.coffee
Sets a "reloaded" query parameter after the dialog is displayed and
dismissed.
That paramter is checked when a server error is encounterd and skipped
if present
First show:
Second time:
> Only display dialog once

- src/flux/task-plan.coffee
1. start adding a brand **new** plan
1. select to make due dates different periods
1. change due date for at least one of the periods
1. switch back to "All periods"
* this calls the `TaskPlanStore.getMinDueAt` which was the culprit
1. try to save as draft or publish
* BE yells at you with a `422`
* you'll see in the modal that FE is trying to submit a moment obj as due_at
should be fixed with this PR.
> fixes when we would accidentally submit a moment date obj to BE

- src/components/task-step/step-mixin.cjsx
A task step should not be continued while it's state is saving or
loading. The earlier code was checking the isSaving state, but wasn't
passing it onto the AsyncButton.
This should prevent the sequence that occurs occasionally where:
1. user clicks on a choice
* An async save is initiated, but due to network conditions, phase of the moon, etc. it's delayed
2. a short time later, user clicks continue button
* A async save to mark step completed is sent.
* Due to the save from step 1 being delayed this arrives before the answer is recorded.
3. Server error occurs.
With this code, the continue button will be disabled until each network request completes, which will disallow further network requests to be initiated.
> Disable continue button when saving

- src/components/task-plan/builder.cjsx
- src/components/task-plan/homework.cjsx
- src/components/task-plan/homework/exercise-summary.cjsx
- src/components/task-plan/homework/exercises.cjsx
- src/components/task-plan/plan-mixin.coffee
- src/components/task-plan/reading.cjsx
- src/flux/task-plan.coffee
1. start building a new homework or reading
1. change start date to today
1. click publish
* at this point, the "Add Reading" or "Select Problems" disappear
* errors show up as well
* start date picker becomes disabled
* this gets you stuck
* There was another bug as well, hidden within.  If you click "Publish", and later finish building your assignment, and click "Save as Draft", your plan will actually publish instead.
On step 3,
* you should be able to edit all aspects on the plan, despite open date being past
* will be unable to change plan details, except for
* Name
* Description
* Due dates
* everything editable
* everything editable
* should not let you edit anything
* should have a back to calendar button
> Plan editability

- src/components/late-icon.cjsx
- src/components/performance/cell-status-mixin.cjsx
- src/components/performance/homework-cell.cjsx
- src/helpers/task.coffee
- test/all-tests.coffee
- test/components/performance/homework-cell.spec.coffee
- test/components/performance/reading-cell.spec.coffee
The homework cells in the performance report had a bug where they would display "Incomplete" if the task was worked late, regardless of the completion status.
Note the display for Alden, Isobel, and Bernhard in the HW column
Before:
After:
> Fix performance report homework status

- src/components/course-settings/drop-student.cjsx
- src/components/learning-guide/teacher-student.cjsx
- src/components/name.cjsx
- src/components/performance/name-cell.cjsx
- src/components/task/viewing-as-student-name.cjsx
- test/all-tests.coffee
- test/components/name.spec.coffee
When student's are created, their name field (which contains the combined name), may be blank. If it is we need to display the first and last name fields.
Prevents uglyness like:
> Use first and last name if name field isn't present

- src/components/task-plan/builder.cjsx
1. create a new assignment
1. choose to set individual period dates
1. change a open date
1. change a due date
1. switch to all periods again
1. fill out whatever else is needed, but don't touch any of the dates stuff
1. try to save or publish
* you should get a 422
Steps 3 and 4's order does not matter
* The FE attempts to create a minimum due date from the common open date, but there was no common open date at the time we try to create the minimum due date.
> dont try to set a min due date for all periods before a common opens_at is set for all periods

- src/components/task-step/exercise/modes.cjsx
- src/flux/task-step.coffee
- test/task-step-store.spec.coffee
Actually says, "Loading another..." as opposed to just "Loading..."
> update recovered status only when the newly generated recovery step is loaded

- index.coffee
This is the main bug that prevented IE 9 from running.  `document.body.appendChild` was being called before the document was ready, causing an exception.
While I know we don't want to support IE9, I'm wondering if we should wait for the document to be ready before we startup?  It seems like it'd be good practice and I'm mildly surprised it hasn't bitten us in other browsers as well.
> Wait for DOMContentLoaded before running app

- resources/styles/components/question.less
Change the answers-answer to fit within a grasp-check. 
Removed width: 100% from the answer(); mixin. 
Fixes the grasp check answers overflowing
Shouldn't impact:
> Fix grasp-check answers

- src/components/task-plan/builder.cjsx
- test/all-tests.coffee
- test/components/helpers/task-plan.coffee
- test/components/task-plan/builder.spec.coffee
To reproduce on master:
1. Create a new reading
2. Click on individual periods (note that no due dates are set)
3. Click on all periods (note that due date is now set to minimum due date)
4. Save (will not save as due date in the store is not set), and will not show a validation message
Fixed functionality:
1. Create new reading
2. Click on individual periods (note that no due dates are set)
3. Click on all periods (note that due date is now not set)
4. Save (will now show validation message)
TODO: Still adding in some specs.
> Fix error when clicking on individual periods

- package.json
- src/components/course-calendar/duration.cjsx
- src/components/course-calendar/month.cjsx
- src/components/task-plan/builder.cjsx
- src/flux/task-plan.coffee
- src/helpers/time.coffee
- test/all-tests.coffee
- test/helpers/time.spec.coffee
sync the teacher calendar and builder to one timezone that may not the teacher's local timezone -- now defaulted to US/Central
Talked to BE briefly about providing us the "course timezone" even though it's always central right now.  It will be good preparation for when course timezone can be changed.  However, this PR will be an improvement even without a BE change.
> handle timezones with courses

- src/components/student-dashboard/event-row.cjsx
- src/components/student-dashboard/events-panel.cjsx
When screen was between 1,000 & 800px wide, The expanded status's like "10/12 answered (I)" take up too much space,
while the description always seems to have space to spare
Before:
After:
> Enlarge student dashboard progress column

- resources/styles/components/learning-guide/heading.less
- resources/styles/components/learning-guide/responsive.less
- resources/styles/components/learning-guide/teacher-student.less
- src/components/learning-guide/teacher-student.cjsx
> Fix performance report back button overlapping with heading

- resources/styles/components/student-dashboard/panel.less
- resources/styles/components/student-dashboard/task.less
Fixes a few styling issues I noticed when working on #720.
When the screen is narrow, the progress and due columns collapse under
the description.  In that case the line height needs to be adjusted so
it doesn't double the row height
Before:
After:
> Customize student dashboard styles for narrow screens

- src/components/scores/index.cjsx
Regarding task: https://www.pivotaltracker.com/story/show/102331780
Performance report was sorting case-sensitive, now will sort properly:
before:
after:
> perf report sort names case-insensitive

- src/components/task-step/all-steps.cjsx
If someone selects "open in new tab" from the menu, the browser doesn't
receive any events and the code can't mark the step as completed.
No UI changes other than the menu doesn't appear.  Tested in Chrome/Firefox/Safari.  Will test IE later.
> Disable right-click context menu on external assignments

- resources/styles/components/question.less
- resources/styles/components/task-step/exercise/index.less
- resources/styles/mixins.less
- src/components/task-step/exercise/modes.cjsx
- src/components/task-teacher-review/exercise.cjsx
The teacher review screens and the student free-response steps were lacking the exercise uid.
> Show uid everywhere an exercise is displayed

- resources/styles/global/typography.less
Add -webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale; to Merriweather
> Anti-aliasing merriweather

- package.json
No UI changes other than `npm` commands will no longer complain about "license should be a valid SPDX license expression"
> Use SPDX identifier for license

- resources/styles/book-content/target.less
- resources/styles/components/task-step/all-steps.less
- resources/styles/components/task-step/external.less
- resources/styles/mixins.less
Converts the less styles to a mixin and shares it between book-content
and the external tasks.
This also shrinks the indicator a bit to make it only 80% of the text size.
Before:
After:
> Show new tab indicator on external tasks

- src/components/task-plan/builder.cjsx
- src/components/tutor-input.cjsx
- src/flux/task-plan.coffee
- src/flux/time.coffee
- test/components/task-plan/builder.spec.coffee
Fixing the bug described here: https://www.pivotaltracker.com/n/projects/1156756/stories/103133164
The bug was due to calling setDueAt and setOpensAt with a date object instead of a moment.  It should be able to handle both now.
Also adding in some specs.
> Fixing builder set date

- resources/styles/components/html.less
- resources/styles/components/question.less
- resources/styles/components/task-step/exercise/index.less
- resources/styles/mixins.less
- resources/styles/tutor.less
Table styles are missing for free response, they are in multiple choice portion
after changing the mixin to be a base one with variations in a separate mixin
> show distractors and style free response tables

- webpack.config.coffee
Looks like #730 and #728 had a subtle conflict where #730 expected the webpack's entry config to have a `.tutor` prefix, but #728 removed it.
> Use .tutor for the webpack config's entry configuration

- src/components/reference-book/index.cjsx
- src/components/reference-book/navbar.cjsx
- src/components/reference-book/page-shell.cjsx
- src/components/reference-book/page.cjsx
- src/components/reference-book/reference-book.cjsx
- src/components/reference-book/slide-out-menu.cjsx
- src/components/reference-book/teacher-content-toggle.cjsx
- src/components/reference-book/toc.cjsx
- src/flux/course.coffee
- src/flux/reference-book.coffee
- src/router.cjsx
- test/components/reference-book.spec.coffee
This is a step towards repurposing the reference view components for QA in #747 
It removes all the logic for getting the ecosystem from a courseId into the shell so the main component can be wrapped by different components.
As a side effect of the extraction, I think it also fixes the same bugs that #753, fixes #754
> Remove courseId and router references from reference view

- src/components/task-teacher-review/exercise.cjsx
...  when the question does not have free response portion
"No Student Text Responses" still only shows on questions that have a free response portion
> dont show view student responses button

- test/config/test-runner.coffee
Made an error when the code was translated into a runner class and didn't convert the sentinel variable checks into an instance var
> Fix test runner starting up multiple copies

- webpack.config.coffee
I'm not sure why this broke now, it's always been set to "/dist/" since we went to webpack.  Suddenly the url in stylesheets was having it pre-pended though.
> Use relative path for assets in stylesheets

- resources/styles/components/task-plan/homework.less
- src/components/task-plan/homework/exercises.cjsx
Updating how the loading indicator looks to fix the double loading indicators described here: https://www.pivotaltracker.com/n/projects/1156756/stories/104015042
> HW Review Page Loading Indicator

- resources/styles/components/task-plan/homework/exercises.less
- src/components/task-plan/homework/exercises.cjsx
Displays the question feedback to the teacher when they select exercises.  Will also be displayed on QA view since it shares the mixin as part of #782 
I'm undecided if the indent should match the question or be increased (as shown in screenshot)..  I felt like it might be confused as part of the question if it matched, even though it is displayed as grey.
> Display feedback for exercise question choices

- src/helpers/mathjax.coffee
On the Teacher and QA views of exercises, mathjax was being invoked
several hundred times (twice per each answer on each question).  This modifies it so it will
only perform once pass on the entire document.  There was a concern about seeing flicker as it renders but I don't observe any.  
Before Mathjax was taking 4,627ms to switch from section 2.0 to 2.1 of physics in qa view.  Both timings were taken after a full page reload.
With a single pass the time drops to 85ms
> Speedup Mathjax processing on a pages with many HTML components

- resources/styles/components/task-plan/homework.less
Making the HW loading indicator position fixed so that when user scrolls, it'll stay in place.
> HW Loader Positioning

- src/components/task-plan/builder.cjsx
- src/flux/task-plan.coffee
- src/helpers/time.coffee
- test/components/task-plan/builder.spec.coffee
> Fix open date when opening with due_at equals to tomorrow or today

- test/components/helpers/task/checks.coffee
- test/components/media-preview.spec.coffee
- test/components/tutor-popover.spec.cjsx
there is no such thing as `be.falsy` in chai -- it's [`to.not.be.ok`](https://github.com/chaijs/chai/blob/6d0ae350974aa20d8e903c6b84bbb9ce4d05f435/test/expect.js#L40-L41)
> to be falsy should be not.be.ok

- resources/styles/components/reference-book/page.less
Kajal thought it'd be best displayed in this fashion so that it's not missed way at the bottom of the content.
> Display reference view ecosystem spy mode info as a pseudo footer 

- src/components/book-content-mixin.cjsx
- src/components/scroll-to.cjsx
- src/components/task-step/step-with-reading-content.cjsx
Links media to book instead of no link and empty selector warning
> link from reading to book

- src/components/task-plan/plan-mixin.coffee
after hitting cancel while editing any existing plan and then going back to look at it
after hitting cancel while editing any existing plan and then going back to look at it
> reset specific plan on edit cancel

- src/components/task-plan/builder.cjsx
- src/flux/task-plan.coffee
Fix for: https://www.pivotaltracker.com/story/show/105018176
~~And also found a bug recently introduced where adding a new homework from the button on the calendar was setting a due at.~~  Nevermind, looks like someone put in the same fix that I did already.
Before fix:
After fix:
> Setting open date maximum on builder

- src/components/course-calendar/duration.cjsx
- src/components/task-plan/teacher-task-plans-listing.cjsx
why is the draft in the middle of the two multi-day/multi-row plans?
1. last published at
1. end time
1. start time
such that the two multi-day/multi-row plans stack adjacently
> looking for ways to improve calendar code

- src/components/bind-store-mixin.cjsx
This was added a long time ago to try to fix invariant errors, which we later discovered needed to be fixed other ways.  It looks like it's not good for performance, and taking it out doesn't seem to break stuff, so I say we take it out.
> take out adding and removing event listeners on updates

- resources/styles/components/course-listings.less
- src/components/course-listing.cjsx
- src/flux/course.coffee
This uses the new `catalog_offering_identifier` from https://github.com/openstax/tutor-server/pull/721 to style course.
This also adds some margin between the courses, To me it looked strange when there were two courses with the same colors right beside one another.
TODO:
Displays ellipsis when text is to long to fit
> Stop using course title for styling

- resources/styles/book-content/base.less
Occasionally there's a large image that isn't inside a figure.  In that
case we need a default rule that stops it from extending past the container.
Before:
After:
> Set image max-width to 100% on book-content styles

- resources/styles/components/task-plan/homework/exercises.less
- src/components/task-plan/homework/exercises.cjsx
Moves the control below the card so it doesn't select the exercise when its clicked.
I experimented with `stopPropagation` but it would only work if the checkbox itself was clicked, not the label. Clicks on the label would still trigger exercise selection callback event though they were above it on the dom tree.  Puzzlingly, clicks on the label would have the panel title as it's target, which makes no sense since that's not an ancestor of the label.  After awhile I gave up and figured we should just implement the mockup ;)
> Move control for displaying feedback below the card

- api/courses/1/students.json
- src/api.coffee
- src/flux/roster.coffee
This PR corresponds with https://github.com/openstax/tutor-server/pull/783
GET /api/courses/:course_id/students is changed to 
GET /api/courses/:course_id/roster 
and format updated to contain students and teacher join url.
> Roster endpoint rename

- resources/styles/components/cc-dashboard/index.less
- resources/styles/tutor.less
- src/api.coffee
- src/components/cc-dashboard/index.cjsx
- src/components/course-listing.cjsx
- src/flux/cc-dashboard.coffee
- src/flux/course.coffee
- src/router.cjsx
Still need to do in a separate PR:
> Concept Coach Teacher Dashboard

- resources/styles/components/cc-dashboard/index.less
- src/components/cc-dashboard/index.cjsx
- src/components/course-listing.cjsx
- src/components/task-plan/teacher-task-plans-listing.cjsx
> Concept coach tweaks

- src/flux/current-user.coffee
- test/components/navbar/user-actions-menu.spec.coffee
Hopefully we can use the same method to allow/disallow other options as well if we need to.
> Remove performance forecast from CC courses

- resources/styles/qa.less
- src/components/qa/book-link.cjsx
- src/components/qa/index.cjsx
- src/components/qa/view-book.cjsx
The two id's are usually identical, so this wasn't noticed until now.  In places the QA view was using the book id, when it should have been using the ecosystem_id.
I also noted that the "Available Books" menu was confusing when there were multiple ecosystems using books with the same title.  I added the version to the list in order to distinguish them.
> Fix QA view loading when book_id differs from ecosystem_id

- resources/styles/components/scores/index.less
- src/components/scores/index.cjsx
> Student Scores - revise labels

- resources/styles/components/course-listings.less
- resources/styles/components/reference-book/page.less
- resources/styles/components/student-dashboard/dashboard.less
- resources/styles/components/task-step/all-steps.less
- resources/styles/global/tutor-booksplash-background.less
- src/components/course-data-mixin.cjsx
- src/flux/course.coffee
As part of https://github.com/openstax/tutor-server/pull/853 the BE will be sending a `appearance_code` attribute on courses.  The code will default to the offering but can be set on a per-course basis if needed.
Should be merged in connection with BE pr.
> Use appearance code from BE for styling courses

- src/components/course-settings/roster.cjsx
- src/components/no-periods.cjsx
- src/components/scores/index.cjsx
- src/helpers/conditional-rendering.coffee
- src/router.cjsx
> Show message when no periods

- resources/styles/components/cc-dashboard/index.less
- src/components/cc-dashboard/dashboard.cjsx
- src/flux/cc-dashboard.coffee
Putting this at the bottom of the dashboard progress table, it shouldn't show up on the blank dashboard.
> Legend for hidden chapters/sections

- resources/styles/components/cc-dashboard/index.less
Per @Fredasaurus, this should align the text so the space at the bottom of the `g` equals the top of the `A`
> Tweak line-height to move text up vertically

- src/helpers/routes-and-destinations.coffee
regarding: 
https://www.pivotaltracker.com/story/show/109830470
https://www.pivotaltracker.com/story/show/103940100
Back button from review metrics in plan stats:
Back button from scores review:
> Review Metrics Back Button - fixed route

- src/components/navbar/account-link.cjsx
Because it's more reliable than window.open.  Accounts was also testing for the existence of `window.opener`, (which has been corrected).
No UI changes, but:
> Use a link with target=_blank for account profile

- src/components/scores/index.cjsx
This setting could increase horizontal scrolling performance when a large number of columns are present, by only rendering visible.
> Student Scores - Faster horizontal scrolling

- src/components/scores/index.cjsx
IE setting the table to 0 width initially, and didn't display anything until the window was resized
> IE fix for 0 width:  wait to measure table size, and set min

- resources/styles/variables/colors.less
Somehow `college_physics` & `micro_economics` were listed twice.
> Remove appearance codes that were duplicated

- src/components/cc-dashboard/section-progress.cjsx
Relates to: https://www.pivotaltracker.com/n/projects/1156756/stories/109459654
Limits completed percentage to be no greater than 100.  I think the source of the error is on the backend though.  I'm just adding this front end piece to protect from the broken UI.
> Limit completed percentage to 100

- resources/styles/components/scores/index.less
- src/components/scores/index.cjsx
Student id label was shifting / column flexing unnecessarily.
> Student Scores - fixed spacing on student id column and label

- .eslintrc
- .gitignore
- lint-cjsx-files.sh
- package.json
`coffeelint` does not lint `cjsx` files and even for `coffee` files it does not find unused vars.
This adds a `npm run lint-cjsx` which compiles the `cjsx` files individually and then runs `eslint` on each.
> :art: find unused vars in cjsx files

- resources/styles/components/performance-forecast/guide-key-mixin.less
- resources/styles/components/performance-forecast/heading.less
- resources/styles/components/performance-forecast/responsive.less
https://www.pivotaltracker.com/story/show/100222354
https://www.pivotaltracker.com/story/show/100222352
Adjusted header wrap and spacing for narrower screens.
> Performance Forecast - Adjusted header wrap and spacing when screen width narrow.

- package.json
- src/components/task-plan/teacher-task-plans-listing.cjsx
- test/components/helpers/calendar/checks.coffee
- test/components/task-plan/builder.spec.coffee
especially important around the first of the month since travis runs on a different timezone, that used to confused what month the tests should be rendering the calendar in when converting string dates back to moment date objects
Also includes commit for pinning `flux-react` to 2.6.6 so that travis can install to completion.
The tests will now pass on travis for this PR today, but still not all pass for travis on another branch around this time.
* `moment` upgrade from `2.10.6` to `2.11` is causing lots of problems.  This PR pins to `moment@~2.10` for now.
* `flux-react@2.6.7` requires `react@0.14.0` which we are not ready for either.  Pinning to `flux-react@2.6.6`
* various other test updates in this pr addresses the normal weird time dependent test failures we were getting
Looked into …
> use date preserving helper function to handle calendar tests

- src/components/task-step/exercise.cjsx
This was allowing `Try Another` to be clicked multiple times and cause 422
> fix try another showing as 'Loading' when recovering starts

- package.json
This update fixes the popover positioning bug present in ie and firefox, pertaining to:
https://www.pivotaltracker.com/story/show/109985726
Requires that openstax-react-components peerDependencies be updated to 0.23.0
Have been testing and I found no issues due to changes in framework so far.
react-bootstrap changelog of issue:
- [66e41a4](../../commit/66e41a4) [fixed] Fix scroll top calculation for overlays
Refs #922
> Update react bootstrap

- src/components/buttons/async-button.cjsx
This fix is ported over from openstax/react-components#31, and will basically be deprecated after #925 as that will move to using the shared `async-button` that will have the same fix.
There was intermittent cases in which the continue button would disappear during exercises.  This was due to a request taking too long to return (> 30 secs allotted by the `asyncButton`) and the button trying to render it's failed state, which it could not do without this fix.
> continue button fix no more disappearing

- src/flux/current-user.coffee
Currently the help link points to the appropriate site help for either CC or Tutor *when there is a course displayed*.  It defaults to the Tutor help link.  This fails for situations such as the course chooser or if the user doesn't have any courses.
This PR adds additional checks to the "no current course" case.  It then checks all the courses and will link to Tutor help only if any of the courses are a non Concept Coach course.
> Link to CC help if the current course isn't Tutor

- src/components/course-listing.cjsx
Note, this uses `.replace()` vs `window.location.href=` since `.replace()` doesn't leave an entry in the history.  I think that'd be the best behavior here.
> Redirect to webview if a single course CC student

- resources/styles/components/task-plan/homework/exercises.less
- src/components/task-plan/homework/exercises.cjsx
For pivotal ticket: https://www.pivotaltracker.com/story/show/109743900
Before: 
After:
> Fix for long summaries in exercises table

- .gitignore
- .travis.yml
- package.json
- test/config/karma-coverage.config.coffee
Adds coveralls.io reporting.
Also, changes Travis to use `npm run ci` instead of `npm test` so folks can locally run just the tests (not `gulp prod`)
refs #931
> add coveralls

- src/flux/cc-dashboard.coffee
Before: 
After:
I think this PR is pretty urgent, sometimes, the dashboard will be showing the wrong data based on which period is selected initially.  See the hansolo prod user for the bug.
> Concept Coach Dashboard Period Ordering

- src/components/task/index.cjsx
- src/flux/task.coffee
- test/components/task.spec.coffee
The actual bug is that if `steps.length is 1` then 0 is always returned, which causes `setStepKey` in [task/index](https://github.com/openstax/tutor-js/blob/master/src/components/task/index.cjsx#L37) to always display the first step.
After looking at the method closer it appears to me that most of it wasn't needed though.
`getCurrentStepIndex` method (at top of file) returns the index of the first non-completed step, or -1 if not found. It seems to me that that's exactly what we want to return here.  I've tested this and it seems to be correct.
Note that breadcrumbs are not displayed on a "intro only assignment" since it has only a single step. That's disabled by the check to `TaskStore.isSingleStepped(id)` in [task/index.cjsx](https://github.com/openstax/tutor-js/blob/master/src/component …
> Fix infinite continue button on an intro-only assignment

- src/api.coffee
- src/components/book-content-mixin.cjsx
- src/components/media-preview.cjsx
- src/flux/app.coffee
- src/flux/media.coffee
- src/flux/reference-book-page.coffee
- test/components/media-preview.spec.coffee
* silent 404 for media preview links
* make media selectors more picky
* pass through original href if needed
[ticket](https://www.pivotaltracker.com/story/show/113027561), worked with @inconceivablevizzini
look, no 404s!
> silent 404 for media preview links

- Gulpfile.coffee
This was introduced in #916 . If `MINIFY=false npm run build` is run (for testing a local instance in Selenium) the `tutor.css` file was being saved as `tutor.min.css` and so it was missing.
> Selenium: fix missing CSS file when building locally to run selenium

- resources/styles/components/media-preview.less
- src/components/media-preview.cjsx
- src/components/tutor-popover.cjsx
Image `max-width` was not working in [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=975632).  See #977 for full details.
This was causing two problems:
* image was floating outside of the width of popover sometimes or made the popover overflow unnecessarily
* popover would flash in and out because the `mouseEnter` and `mouseLeave` would get called repeated as the popover would cover the link where the mouse was hovering
Additionally, Maths was looking weird.  See [this ticket](https://www.pivotaltracker.com/story/show/112930795) for additional details.
This PR addresses the above issues by:
* making `span` styling more specific within the popover
* manually detecting if image's `width` should be adjusted to fit
* checking if mouse has left both the link and the popover on …
> media preview sizing

- src/components/cc-dashboard/section.cjsx
- test/components/cc-dashboard/dashboard.spec.coffee
For: https://www.pivotaltracker.com/story/show/113020969
Before we weren't differentiating between the section not having spaced practice performance, and if the spaced practice was 0.
Before:
After:
> Show 0% spaced practice bar

- test-integration/helpers/calendar.coffee
- test-integration/helpers/cc-dashboard.coffee
- test-integration/helpers/course-select.coffee
- test-integration/helpers/reading-builder.coffee
- test-integration/helpers/reference-book.coffee
- test-integration/helpers/scores.coffee
- test-integration/helpers/test-element.coffee
- test-integration/helpers/user.coffee
- test-integration/scores.coffee
- test-integration/task.coffee
When paired with #970 this provides a bunch of extra logging.
The issue I was initially diagnosing was why publishing an assignment sometimes worked and sometimes did not.
The problem was that when you click an item in the calendar a popup may or may not appear depending on the state of the `task-plan`. The test was waiting for a button to appear but it never appeared.
Thoughts on this approach @openstax/tutor-fe ?
Atom search/replace string used: `\.get\((.*)\)\.click\(\)` and `.click($1)`
refs #931
> Selenium: replace .get().click() with just .click()

- src/components/task/index.cjsx
- src/flux/task.coffee
Regression for external crumbs came from #963, this addresses [this ticket](https://www.pivotaltracker.com/story/show/113636529)
> make crumbs not show for external tasks with only one step

- .gitignore
- test-integration/helpers/calendar.coffee
- test-integration/helpers/course-select.coffee
- test-integration/helpers/describe.coffee
- test-integration/helpers/reading-builder.coffee
- test-integration/helpers/test-element.coffee
- test-integration/helpers/user.coffee
- test-integration/scores.coffee
Changes the syntax to `courseSelect.el.courseByType('physics').click()` instead of `courseSelect.el.courseByType.click('physics')`
Keeps a deprecation warning in _just in case_.
Thoughts @openstax/tutor-fe @openstax/test ? refs #931
> Refactor how selenium TestElement elements are called

- .gitignore
- package.json
- test-integration/helpers/describe.coffee
- test-integration/helpers/user.coffee
- webpack.config.coffee
This injects the JS built by webpack with coverage recording and then the selenium mocha tests extract the coverage data out at the end of each test using the `__coverage__` global that `istanbul` fills. refs #931
**[Example coverage Report](https://openstax.github.io/tutor-js/coverage/lcov-report/)**
Run `npm run test-integration`. This command:
1. builds the JS files with coverage recording sprinkled in
2. serves the files at `http://localhost:8000`
3. runs selenium tests while recording coverage information to `/coverage-selenium.json`
4. generates an HTML and `.lcov` report in `/coverage/`
Thoughts @openstax/tutor-fe ?
> Selenium: add code coverage for selenium tests

- package.json
- scripts/validate-package-json.js
Validates that we are using exact versions when including 3rd-party npm packages in the `package.json` file.
I was thinking of adding it to `gulp` but I'm hoping we can finally get rid of gulp. Maybe this should be ported to the other repos? (if merged)
Thoughts @openstax/tutor-fe ?
> validate the versions of packages in package.json

- api/ecosystems.json
- api/exercises.json
- resources/styles/qa.less
- src/components/exercise-card.cjsx
- src/components/qa/exercise-card.cjsx
- src/components/qa/exercises.cjsx
- src/components/task-teacher-review/exercise.cjsx
- src/flux/exercise.coffee
- test/components/exercise-card.spec.coffee
- test/components/qa/exercises.spec.coffee
Needs to be merged & deployed along with BE PR: https://github.com/openstax/tutor-server/pull/986 
Notice that I'm displaying a pseudo text entry box (which is really just a styled div).  When I just hid the questions it wasn't easy to tell the 2-step exercises apart from one with a very short question.
> QA view: show all tags, two step filter, and question id

- Gulpfile.coffee
- resources/styles/components/course-settings.less
- resources/styles/components/scores/table-cc.less
- resources/styles/mixins.less
- resources/styles/mixins/tutor-modal.less
- src/components/course-periods-nav.cjsx
- src/components/course-settings/roster.cjsx
regarding task: https://www.pivotaltracker.com/story/show/112365737
added tooltips, ellipsis and scale/wrap to tabs to allow for longer names and more periods
> Student Scores: adds tooltips, ellipsis and scale/wrap to tabs

- test-integration/README.md
- test-integration/calendar.coffee
- test-integration/cc-dashboard.coffee
- test-integration/exhaustive/calendar.coffee
- test-integration/exhaustive/reference-book.coffee
- test-integration/helpers/calendar.coffee
- test-integration/helpers/reading-builder.coffee
- test-integration/helpers/reference-book.coffee
- test-integration/helpers/scores.coffee
- test-integration/helpers/student-dashboard.coffee
- test-integration/helpers/task.coffee
- test-integration/scores.coffee
- test-integration/simple.js
- test-integration/student/dashboard.js
- test-integration/task-plan/cleanup.coffee
- test-integration/task-plan/draft.coffee
- test-integration/task-plan/publish.coffee
- test-integration/task.coffee
Sometimes a helper would export:
- just the helper (ie `Calendar`)
- `{Calendar}`
- `{CalendarHelper}`
- `{CalendarHelper, CalendarPopupHelper, verify}`.
This makes it export just the helper and the subhelper (if you need it it can be referred to by `new Calendar.Popup(test)`) and removes the `Helper` part in the class name
> Selenium: Simplify helper namespace

- api/courses/1/plans/POST.json
- resources/styles/components/course-calendar/plan.less
- src/api.coffee
- src/flux/helpers.coffee
- src/flux/job.coffee
- src/flux/plan-publish.coffee
- src/helpers/job.coffee
- src/helpers/plan.coffee
- test/components/course-calendar/plan.spec.coffee
- test/flux/plan-publish.spec.coffee
- test/helpers/job.spec.coffee
* match updated data structure where `publish_job` is an object, and the `publish_job_uuid` is `publish_job.id`
* add a way to customize API fails
* 404 of jobs should not trigger modal
* should load as the latest state and show on calendar as failed
matches BE openstax/tutor-server#997
> Teacher Calendar: Fix publishing status

- test-integration/helpers/ui/test-element.coffee
- test-integration/helpers/utils/wait.coffee
@philschatz, @openstax/tutor-fe  heheh is this too much?  I kinda like that it means the structure of the `for`'s will remain in sync but it make's it less readable.  Although, with `_for`, pulling out the `shouldBeVisible` from the `locator` and making a `forHidden` would be easier and less copy and paste
base branch is #1000
> Selenium: reduce for's repeated code

- resources/styles/mixins.less
- src/components/course-periods-nav.cjsx
- src/components/course-settings/roster.cjsx
- fixed non-period tab styling conflict causing student dashboard tabs to appear transparent
- adjusted trouble flag placement for longer/truncated period names
fixes #1005
> Dashboard tab transparent fix, tab trouble flag adjustment for long names

- test-integration/helpers/ui/scores.coffee
- test-integration/helpers/ui/test-element.coffee
- test-integration/helpers/utils/wait.coffee
- test-integration/scores.coffee
Amendment to #996
Move `expects` out to `scores` spec, uses `for` waits as opposed hard timeouts
> Export button single step test

- resources/styles/components/task-plan/homework/exercises.less
For: https://www.pivotaltracker.com/n/projects/1156756/stories/109743900
I've made the image fit the width of the box, I think it's better than hiding the image.  Also, the overflow for text is fixed as well.
Before:
https://www.pivotaltracker.com/file_attachments/57298699/download
After:
> Fix overflow on exercises table

- src/api.coffee
Followup to #1015 which had it set incorrectly.
It needs to be set as the 4th argument to apiHelper, not as an option on the third
> Set displayError: false option on notifications properly

- src/components/scores/concept-coach-cell.cjsx
- src/components/scores/index.cjsx
sort/display completed column by correct value
> CC Student Scores - fixed sort on completed column

- resources/styles/components/task-plan/homework/exercises.less
- src/components/task-plan/homework/exercises.cjsx
https://www.pivotaltracker.com/story/show/109743900
This PR removes images from the summary table.
> HW Builder: Remove images in summary table

- src/helpers/policies/utils.coffee
To accompany openstax/tutor-server#1023 and #1021 
Will display feedback as expected for homework where feedback is immediately available, and will continue to on to next question without doing so if feed back is only available after feedback.
> Display exercise feedback when is_feedback_available is set

- package.json
We pulled in the full version of lodash In https://github.com/openstax/tutor-js/commit/dc8d3b43fc1442cfe578a45b1d74669a9bc7c465#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 but required 4.5.1.  `react-calendar` is set to "^2.4.1", but somehow the calendar has required and using 4.5.1 on production.
The issue is that calendar uses `_.pick` with a function to choose the props for components  https://github.com/freiksenet/react-calendar/blob/0.4.0/src/propTypes.js#L170-L180.  Apparently lodash no longer supports using a function to pick the properties, it now has a `pickBy` method for that.
The end result is that the `onClick` property is discarded and not added to Days on the calendar, causing the popover menu to not display on a click.
This simply downgrades lodash but perhaps it'd be better to …
> Downgrade lodash to version compatible with calendar

- test-integration/README.md
- test-integration/helpers/index.coffee
- test-integration/helpers/ui/task-builder.coffee
- test-integration/student/dashboard.js
- test-integration/task-plan/cleanup.coffee
- test-integration/task-plan/draft.coffee
- test-integration/task-plan/publish.coffee
Since the helper creates both Reading and Homeworks it's better named as Task
Note, there's currently one spec failure:
```
1) CC Student Scores hovers tooltip info popover:
AssertionError: expected '' to include 'Correct Attempted Total possible'
```
I'm not sure if that's a side effect of my courses loaded or what, but don't see how it could be related to the rename.
> Selenium: rename ReadingBuilder to TaskBuilder

- package.json
- resources/styles/components/task-step/all-steps.less
- resources/styles/global/menus.less
- src/components/navbar/user-actions-menu.cjsx
- src/components/task-step/concept-coach-end.cjsx
- src/components/task/breadcrumbs.cjsx
- src/components/task/crumb-mixin.cjsx
**Review for review  otherwise**
Related to [CC: Marketing request: When teacher views student HW summary, it should look the same as when the student views their HW summary.](https://www.pivotaltracker.com/story/show/110131688)
> Fix teacher coach hw summary breadcrumb styles

- src/components/qa/exercise-card.cjsx
- test/components/qa/exercises.spec.coffee
If an exercise doesn't have any tags, it would fail the `_.every` check
> Fix bug where untagged exercises would not render in QA view

- package.json
- src/flux/reference-book-exercise.coffee
Based off the [commit currently on QA](https://github.com/openstax/tutor-js/compare/cd550ac47525462fc079978dbadf0770ea0a1449...hotfix/ref-book-exercises).
the way tags work have changed a little bit, and the FE needs to adjust in reference book when querying for multiple exercises.
Depends on https://github.com/openstax/react-components/pull/58
> format multiple exercise query properly when it comes to double quotes

- package.json
- resources/styles/components/scores/export.less
- resources/styles/components/scores/index.less
- src/components/scores/export.cjsx
- src/components/scores/index.cjsx
- src/flux/scores-export.coffee
**Not based off master**
Off of 1eae2eb, current production
Export job status will be checked 3600 times every second (1 hour) before stopping the check, and the async button will not check for timeout until 1 hour has passed once the job starts
For bug [Concept Coach Export fails](https://www.pivotaltracker.com/story/show/118647541)
> start with extend both export checking times and async button timeouts to an hour

- resources/styles/components/exercise-preview.less
- resources/styles/components/questions-dashboard.less
- resources/styles/mixins/exercise-card-hover-styles.less
- resources/styles/tutor.less
- src/components/icon.cjsx
- src/components/questions/dashboard.cjsx
- src/components/questions/index.cjsx
- src/components/questions/questions-controls.cjsx
- src/components/questions/questions-list.cjsx
- src/components/questions/section-questions.cjsx
- src/components/questions/sectionizer.cjsx
- src/components/questions/unsaved-dialog.cjsx
- test/components/questions/dashboard.spec.coffee
cc @rvnewell 
Tweaks are:
* remove UX design test toggle, use chosen column style.
* fix column style to not break across columns
* bring green header all the way to top after question selection
* select reading type by default
* more white padding on header, less on green
* icon should be i and superscript, and show popover on click
* "Report an error" should be tutor blue link style
* Match hover blue from mockup
* exclude/include icon larger with smaller text
* Concept Coach specific wording when displaying for a CC course
* Display warning dialog when navigating away with unsaved exercise exclusions, and when canceling
* Keep save/cancel button on screen after save, but change button to read "Saved"
CC Wording:
Dialog:
> grab bag of style tweaks for Question Library

- resources/styles/global/menus.less
- resources/styles/global/navbar.less
This enables the question library and fixes a positioning bug I noticed with the dropdown menu.
Before:
After:
> Enable QuestionLibrary, fix dropdown menu vertical position

- src/flux/task-plan.coffee
is feedback immediate was not being defaulted to false in the json that was being sent for publishing.  new tasks were being set as immediate when the drop down's on change did not fire
> is feedback immediate fix

- index.coffee
- package.json
- resources/styles/global/notifications-bar.less
- resources/styles/tutor.less
- src/helpers/notifications.coffee
As part of https://github.com/openstax/tutor-server/pull/1099 the BE is sending notices that should be immediately displayed .
Components PR: https://github.com/openstax/react-components/pull/74
Also fixes unrelated bug where material design styles where leaking into the email verification box.
All notice types:
> Display notices from flash key of bootstrap data

- resources/styles/components/task/index.less
- resources/styles/components/task/progress.less
- resources/styles/global/buttons.less
- resources/styles/global/navbar.less
- src/components/task/index.cjsx
- src/components/task/progress/arrow.cjsx
- src/components/task/progress/index.cjsx
- src/components/task/progress/panel.cjsx
- src/flux/task.coffee
- test-integration/helpers/ui/task.coffee
- test-integration/helpers/ui/user.coffee
- test-integration/task.coffee
- test/components/helpers/task/checks.coffee
- test/components/task.spec.coffee
New progress bar for readings, see screenshots below.  I still need to finish tests, and I'm putting the keyboard events in another PR.
> Progress bar for readings

- src/components/course-settings/cc-enrollment-code.cjsx
As of https://github.com/openstax/tutor-server/pull/1122 it's numeric, not words
> Remove "two-word" from enrollment code help messages

- resources/styles/components/course-calendar/header.less
The add assignment button label was shifting all the way to the left, and the height changing, when selected.
> fixed opened add assignment button styling

- package.json
- resources/styles/components/exercises.less
- resources/styles/components/questions-dashboard.less
- src/components/exercises/cards.cjsx
- src/components/exercises/details.cjsx
- src/components/questions/exercise-controls.cjsx
- src/components/questions/exercises-display.cjsx
- src/components/task-plan/homework/add-exercises.cjsx
- src/components/task-plan/homework/exercise-controls.cjsx
This:
* Keeps controls visible but allows them to scroll when scrolling up to top
* Removes the details / card view toggle from control bars
* Colors "Back to card view link grey"
* Fixes regression where the controls bar background was transparent instead of white
* Fixes sectionizer controls in HW builder so it updates and can jump to a section
* Pulls in exercise preview update from react-components for the feature flags
@rvnewell is preparing a few more tweaks to the icons, but I think they'll be fairly stand alone, we can go ahead and merge this
> HW / QL details view tweaks

- src/components/task-plan/builder.cjsx
- src/flux/task-plan.coffee
For: https://www.pivotaltracker.com/story/show/121087051
This adds a parameter to the set period function in the flux store.  This way, when the dates are updated, the defaultPlan of the store is only updated when the component is loaded, not when it's updated.
This is why the plan wasn't marked as changed, and the confirm dialog was not showing when cancelling the task plan changes.
> Set Period Default Plan

- src/api.coffee
- src/flux/task.coffee
BE just removed this in https://github.com/openstax/tutor-server/pull/1135, so no reason keeping it around
> Remove unused and now non-existent tasks endpoint

- package.json
for when a snapshot was taken. It currently only logs when the URL changes.
So, if you load a page while recording, click clear, and then do something, the current URL is not in the log.
Also, I was thinking of adding another feature to recordo: a checkbox to exclude AJAX responses. Currently, when you load the Student Scores, it's a big honking JSON response which isn't terribly useful for devs.
Thoughts?
> update version of recordo to log the current URL

- src/components/student-dashboard/event-row.cjsx
- src/components/student-dashboard/events-panel.cjsx
- src/components/task-plan/builder/index.cjsx
- src/components/time.cjsx
The student dashboard said all due times were 7:00am, and task builder said similar
> Remove hardcoded open/close time from instructions

- src/api.coffee
- src/components/questions/sections-chooser.cjsx
- src/components/task-plan/homework.cjsx
- src/components/task-plan/homework/loading-exercises-mixin.cjsx
https://www.pivotaltracker.com/story/show/121532729
Needs https://github.com/openstax/tutor-server/pull/1142
This should take care of HW spinning forever after ecosystem updates. Might need a different PR to prevent people from selecting exercises then unselecting their pages, which I think will also mess up the display.
> Fixed HW spinning forever after ecosystem update

- src/components/tutor-input.cjsx
regarding: https://www.pivotaltracker.com/story/show/121087871
tutor-date-input allowed bypassing the datepicker with manual input, which broke the animated label state.
> Datepicker fix label overlap when invalid date manually entered

- src/components/task-plan/builder/tasking.cjsx
...unless it is visible to students
1. Switching from all periods to individual
2. Uncheck a period.
Now you are stuck with period 2 being disabled and you cannot re-check it.
> period should be enabled for checking and unchecking

- .editorconfig
Most text editors support this file. See https://atom.io/packages/editorconfig
> add editorconfig for formatting files

- src/api.coffee
- src/flux/task-plan.coffee
unchanged tasking plans should not be sent to server side -- this would cause additional problems when updating a title when past due for example
related to [changing open assignment description](https://www.pivotaltracker.com/n/projects/1156756/stories/121531359) on past due plans, related to this BE PR openstax/tutor-server#1148
> Be able to change open assignment description and title without 500 error

- src/flux/task-plan.coffee
…by the default setting of is_feedback_immediate when dropdown select is untouched.  however, server side was returning the expected `is_feedback_immediate` value for whatever the last save was
Amendment to fix for [Unable to change when feedback appears](https://www.pivotaltracker.com/n/projects/1156756/stories/121620619)
the problem with #1112 is that if you never touch the dropdown, the `is_feedback_immediate` defaults to `true` despite the UI suggesting that it will be set to `false`.  This means if that you do not touch the dropdown, all homeworks will default to  `is_feedback_immediate: true`.
Why does this need to be set on `_change`?  because of this: https://github.com/openstax/tutor-js/blob/master/src/api.coffee#L138
The payload when `TaskPlanActions.save` is triggered is …
> the plan's server returned is_feedback_immediate being overwritten

- src/components/exercises/cards.cjsx
- src/components/task-plan/homework/add-exercises.cjsx
Scrolling was extremely sluggish when the control was clicked.  I traced it back to the card view was re-rendering excessively because the pure render wasn't having any effect.
Using `_.isEqual` seems to work well and improves performance considerably.
> Fix clicking scrolling to section on sectionizer click in HW builder

- resources/styles/components/task-plan/builder.less
- resources/styles/components/tutor-input.less
- src/components/task-plan/builder/date-time.cjsx
- src/components/task-plan/builder/index.cjsx
- src/components/task-plan/builder/tasking-date-times.cjsx
- src/components/task-plan/footer.cjsx
- src/components/tutor-input.cjsx
- src/flux/task-plan.coffee
- src/helpers/plan.coffee
> Various builder bugs

- src/components/task-plan/homework/add-exercises.cjsx
The highlight mask on HW builder wasn't being applied since the 'is-selected' flag isn't part of the card view props for homework like it is on QL
> Fix exercise selection highlighting

- src/components/scores/index.cjsx
fixed NaN when overall_average_score is missing.  A period with all readings may not return this property.
> Student Scores - fixed NaN

- src/components/scores/absent-cell.cjsx
- src/components/scores/table.cjsx
regarding: https://www.pivotaltracker.com/story/show/121986485
when student assignment data is null (if a student moves and is unassigned), absent cell will render with either split (hw) or single (external, reading), based on the heading type.
> Scores - fixed absent cell type displaying incorrectly

- src/components/task-plan/builder/index.cjsx
- src/flux/task-plan.coffee
This fixes a bug where the HW builder would have invisible errors when validating.  The sequence to trigger was:
* Have some differing default times set for periods
* Load the builder 
* Note that individual periods are displayed at the start
* switch to "All Periods" and set the end date
* set title and add some exercises (this can be done at any time)
* attempt to publish
Nothing would happen because the opens_at wasn't set on the taskings, because that date was never manipulated.
> Set defaults when switching from periods to combined

- resources/styles/book-content/note.less
Previously we decided against this since the weird blank element makes it obvious that the content needs updating, but Sociology is missing them all, making it impossible to fix by release.
before:
after:
> Hide missing note title pseudo element

- src/components/reference-book/page-shell.cjsx
- src/components/reference-book/page.cjsx
Made `ReferenceBookPage` use `LoadableItem` so it wouldn't try to render them before they were loaded.  For a partial history of the investigation, see https://www.pivotaltracker.com/n/projects/1156756/stories/121528127
> Fix for pages trying to render before loaded

- resources/styles/components/task-plan/builder.less
- src/components/task-plan/builder/tasking-date-times.cjsx
- src/flux/task-plan.coffee
- test/components/task-plan/builder/index.spec.coffee
Pivotal: https://www.pivotaltracker.com/story/show/123488831
This needs some UX love, if we want the same date, we'll need to show error message for when they enter the wrong time.  See screenshots below.
> This allows the same date to be set in the builder

- resources/styles/components/course-calendar/month.less
- src/components/loadable-item.cjsx
- src/components/task-plan/teacher-task-plans-listing.cjsx
- src/flux/plan-publish.coffee
- src/flux/teacher-task-plan.coffee
Includes
* extend plan publish status checking
* make is loading or load range specific for calendar so that load calendar can show for each new month range being loaded
* for you, @Dantemss, this will add the month to month loading effect where appropo.
> calendar related fixes

- src/components/course-calendar/plan-details.cjsx
- src/components/loadable-item.cjsx
- src/components/loadable.cjsx
- src/components/media-preview.cjsx
- src/components/qa/index.cjsx
- src/components/task/viewing-as-student-name.cjsx
loadable item was triggering load AFTER `componentDidUpdate` and then only triggering a load when certain props had been loaded.  it seems like this trigger should happen sooner -- i.e. right when the component will receive the props.  this change should make things feel snappier and also decrease extra re-renderings due to first rendering since props updated and then rendering again once the store is loaded and emits a change
there are also stylistic updates -- putting methods on `@` and using `_.partial` from common practices that have developed since this was first written
_Hey, we release soon,
so this is crazy.
But here's this pr.
So merge it, maybe?_
> Fixes Loadable indicator so it re-renders less often (formerly "hey...so...")

- src/components/task/index.cjsx
Pivotal ticket: https://www.pivotaltracker.com/story/show/124223571
Scrolls the reading to the top when going to the next or previous:
> Reading Scroll To Top

- resources/styles/book-content/base.less
Pivotal: https://www.pivotaltracker.com/story/show/121865049
Regular drop caps should still work:
References drop caps aren't there anymore:
> References Drop Cap Styles

- api/ecosystems/1/readings.json
- api/exercises.json
- src/components/exercises/cards.cjsx
- src/components/task-plan/homework/add-exercises.cjsx
- src/flux/exercise.coffee
- src/flux/toc.coffee
- test/components/course-calendar/plan.spec.cjsx
- test/flux/exercise.spec.coffee
- test/flux/toc.spec.coffee
If the TOC store had multiple ecosystems, the first match would be returned for a given chapter_section.  
This would mean that sometimes the incorrect books section titles were displayed in QL/HW Builder if the teacher switched courses.
> Load section title only for current ecosystem

- resources/styles/components/icon.less
- resources/styles/components/task-plan/reading-stats.less
- resources/styles/tutor.less
- src/components/icon.cjsx
- src/components/plan-stats/course-bar.cjsx
Since average isn't really what it's calculating and it didn't match student scores.  Adds a info icon with additional explanation.
Quick metrics:
full metrics version:
> change label from "Average" to "Percent Complete" on teacher review

- src/components/course-settings/period-roster.cjsx
isPeriodEmpty now uses period.id instead of activeTab.id
> Course Settings - fix CC Roster not showing students

- resources/styles/book-content/note.less
- resources/styles/components/task-step/all-steps.less
the bootstrap responsive-embed class was broken when it was the last-child by the explicit setting of padding-bottom, and then the iframe wasn't sized properly to fit
Before the video was invisible, after it's:
> Fix iframe display when wrapped by embed-responsive

- src/components/exercises/sectionizer.cjsx
Pivotal: https://www.pivotaltracker.com/story/show/122202725
Fix for chapter section label being obscured when scrolling up.  I doubled the scroll top offset, because when scrolling up, both pinned headers show up.  See gif below:
> Question Library Scroll

- src/components/course-listing.cjsx
- src/components/student-dashboard/index.cjsx
- test/components/course-listing.spec.coffee
- test/components/student-dashboard.spec.coffee
I don't think there are any UI changes
> Moving redirect logic for concept coach students

- resources/styles/components/task-step/all-steps.less
This adds css rules for what to do when an interactive iframe is not inside an interactive-step.  In this case the content will be inset with thick padding in the card, and so an iframe would be wider than the content.  This makes sure it centers itself in the whole card's width.
To test, one can change `stimulus_html` in `step-id-9-1.json` to have this value:
`"<div data-type=\"note\" data-has-label=\"true\" id=\"hookes_law_5_3_2\" class=\"note watch-physics\" data-label=\"\">\n<div data-type=\"title\" class=\"title\">Watch Physics: 5.3 Elasticity:  Stress, and Strain</div>\n<div data-type=\"media\" id=\"fs-id1169085779740\" data-alt=\"Link to lab simulation tool on masses and springs.\">\n<iframe width=\"660\" height=\"371.4\" src=\"https://www.openstaxcollege.org/l/02sprigmasst\"></ifra …
> Embedding Interactives

- src/components/course-listing.cjsx
- src/flux/course.coffee
- test/components/course-listing.spec.coffee
We were only checking the first role before, which was causing the error seen here: https://www.pivotaltracker.com/story/show/126045715
Now we check all roles, and give priority to the teacher.
> Updating role checking on course listing

- src/flux/tasking.coffee
- test/flux/tasking.spec.coffee
Pivotal Ticket: https://www.pivotaltracker.com/story/show/126241577
Since we updated the builder to allow same dates for the open date and due date, we weren't checking if the due time was had already passed before.  This PR adds that check, along with an error message, and some unit tests.  
@openstax/ux see screenshot below for error message.  Please let me know if that wording is acceptable.
> Add check for due time past in the builder

- resources/styles/global/navbar.less
> Fixes the main nav bar's bottom border not drawing all the way across.

- resources/styles/components/task-step/all-steps.less
- resources/styles/components/task-step/ends.less
This puts the standard `.note` styling around question-contexts.
It did look like this:
https://www.pivotaltracker.com/file_attachments/65386851/download?inline=true
Whereas it should look like this:
http://jdy18n.axshare.com/#p=hw_student_view_alt_1
What is should look like now:
> Question Context Styling

- resources/styles/book-content/theming-mixins.less
Pivotal: https://www.pivotaltracker.com/story/show/121865049
I missed a color style that should be fixed in this commit:
> Updating drop cap first letter color rule

- resources/styles/book-content/splash-image.less
- resources/styles/components/task-step/video.less
regarding https://www.pivotaltracker.com/story/show/124155601
splash-video(s) in readings and refbook were not visible due to 0 width.
> Book Content - splash videos not visible

- resources/styles/components/questions-dashboard.less
- src/components/questions/exercises-display.cjsx
- src/flux/exercise.coffee
- test/flux/exercise.spec.coffee
previously it was counting exclusions on all the modules that were loaded, which wasn't very accurate
Also adjusts the wording on the dialog from updated mockup
> Compare exercise excluded count against the modules it belongs to

- src/components/task-plan/plan-mixin.coffee
- src/components/tutor-dialog.cjsx
Changes the confirm-cancel dialog when cancelling a unsaved changes to a homework assignment so it's less confusing.
https://www.pivotaltracker.com/n/projects/1156756/stories/100222306/comments/144332063
Before:
After:
> Text changes for Homework Builder's cancel dialog

- src/components/course-settings/roster.cjsx
- src/components/course-settings/view-archived-periods.cjsx
- src/components/tabs-with-children.cjsx
- src/flux/period.coffee
- test/components/course-settings/roster.spec.coffee
Previously the tab index wouldn't be updated so the contents wouldn't match the tab name after archiving. Unarchiving had the same bug
> Switch tab from period after archiving

- resources/styles/components/cc-dashboard/index.less
- src/components/cc-dashboard/section-progress.cjsx
Made the logic so it doesn't round down to 0% when it's not 0% and doesn't round up to 100% when it's not 100%.
I also needed to make some styling changes so small percentages were legible.
Before:
After:
> CC no rounding for 0% and 100%

- src/components/course-calendar/duration.cjsx
Check the order of each plan and sets the height of week's days based on
the higest plan order. 
Turns this:
Into:
> Calculate height of days based on max plan order

- src/components/course-settings/roster.cjsx
- src/components/tabs-with-children.cjsx
Fixed a problem where after archiving a section (period) on Concept Coach's "Course and Settings Roster" page, it would select the next appropriate period but still show it as unselected.  This would get super confusing when adding a period later or unarchiving a period, because the old selected tab index would be highlighted, but it wouldn't be showing that tab's data.
> Fix for CC Course and Settings and Roster tabs keeping bad state

- resources/styles/components/exercises.less
- src/components/questions/exercise-controls.cjsx
Removes the type tab buttons from the toolbar in Question Library for Concept Coach and maintains the centering when they're not there.  (It also fixes the centering of that pagination block in the middle, but shhh...)
https://www.pivotaltracker.com/n/projects/1156756/stories/126084281
> CC QL no longer shows filter buttons

- src/components/task-step/ends.cjsx
The bug was that when a teacher was reviewing a finished reading assignment and got to the end, the "Back to Dashboard" button would link back to the student's dashboard, which would result in a 403 error when followed.  This makes sure to check whether it's a teacher or a student when naming the action.
> Fixed teacher clicking "Back to Dashboard" from reviewing reading assignment

- resources/styles/components/reference-book/navbar.less
- resources/styles/components/reference-book/page.less
- src/components/reference-book/index.cjsx
- src/components/reference-book/teacher-content-toggle.cjsx
- test/components/reference-book/teacher-content-toggle.spec.coffee
This checks the page DOM for `.os-teacher` and will display the link as inactive with a popover explaining why.
> De-activate teacher content link when no teacher content exists

- api/courses/1/dashboard.json
- package.json
- src/components/task-step/exercise.cjsx
- src/components/task/index.cjsx
- src/flux/task.coffee
- src/flux/tasking.coffee
- test/components/student-dashboard.spec.coffee
Fixes:
* for the last part, after parts have been "completed", the controls for submitting again were on the footer, making for an inconsistent and confusing UI since the controls for previous parts were right underneath the parts they were for
* Additionally, it was unclear whenever the last part would be being updated, since it had no async button to display it's state underneath.
* This was fixed with
* "Submit" being displayed for un-completed parts, with a "Next Question" button displaying separately on footer.
* After "Submit" or all parts are completed, the part's submit's button would not be shown.
* Active "Next Question" button will show async state -- "Saving" -- when individual parts are updated and saved afterwards.
* When MPQ is incomplete, saving will show async state on …
> Details of MPQ UI

- src/components/task-plan/builder/time-zone-settings-link.cjsx
This was missed when the link was added.
> Add tooltip to HW builder course timezone change

- src/components/task-teacher-review/breadcrumbs.cjsx
- src/components/task-teacher-review/crumb-mixin.cjsx
- src/components/task-teacher-review/exercise.cjsx
- src/components/task-teacher-review/index.cjsx
- src/components/task-teacher-review/review.cjsx
Fixed
also cleaned up code pulled content formatting logic into one place instead of re-building it in multiple places
> Teacher review navigation logic

- resources/styles/components/questions-dashboard.less
- resources/styles/components/task-plan/homework/exercise-summary.less
- resources/styles/variables/colors.less
- resources/styles/variables/tutor-bootstrap.less
- src/components/icon.cjsx
- src/components/questions/dashboard.cjsx
- src/components/questions/exercises-display.cjsx
- src/components/questions/help.cjsx
- src/components/questions/sections-chooser.cjsx
Tutor top bar  (spacing is shown as-is directly after section choice):
Tutor second bar:
CC top bar:
CC bottom bar:
> Update CC & Tutor QL help text

- src/helpers/task.coffee
Made it so the late-work progress for reading assignments is calculated with the steps instead of exercises to be consistent with non-late work.
https://www.pivotaltracker.com/n/projects/1156756/stories/125233391/comments/145060321
Before:
After:
> Fix: Reading progress does not match up when accepting late score

- resources/styles/components/student-dashboard/task.less
- src/components/student-dashboard/event-row.cjsx
- src/components/task-step/exercise.cjsx
- src/flux/student-dashboard.coffee
- src/flux/task.coffee
- test/components/student-dashboard.spec.coffee
- test/components/student-dashboard/event-row.cjsx
For: https://www.pivotaltracker.com/story/show/125339771
Allows students to click into the deleted task.  I still need to finish up some logic inside the exercise itself to hide certain things, and there's a backend PR out for that as well.
> Allow students to view deleted readings and homeworks

- src/components/app.cjsx
- src/components/breadcrumb/index.cjsx
- src/flux/course.coffee
Depends on https://github.com/openstax/react-components/pull/102
Adds the 'is-college' and 'is-high-school' classes on root element for switching icons and styles
is no longer based off production
> Use college specific icons

- resources/styles/components/task-step/all-steps.less
Removes the special offset for sims that are inside `.note` elements because there is no longer any special styling for notes.
https://www.pivotaltracker.com/n/projects/1156756/stories/110780416/comments/145290063
> Fix: Offset sim inside note

- resources/styles/global/maths.less
Remove the `lato` specification
> Switch mathjax back to using it's default font

- src/components/task-plan/footer.cjsx
https://www.pivotaltracker.com/n/projects/1156756/stories/121533153
> Homework builder's info icon only shows in the right context

- tutor/resources/styles/components/course-settings.less
- tutor/resources/styles/components/performance-forecast/index.less
- tutor/resources/styles/components/scores/index.less
- tutor/resources/styles/components/student-dashboard/dashboard.less
- tutor/resources/styles/components/task-plan/reading-stats.less
- tutor/resources/styles/mixins.less
Fixes the bug by implementing a slightly new tab design that should be consistent across all these kinds of tabs.
https://www.pivotaltracker.com/n/projects/1156756/stories/127656737
Verify no change for:
> Fixes weird tabs in Performance Forecast and implements new design

- shared/resources/styles/components/exercise-preview/index.less
- shared/src/components/exercise-preview/index.cjsx
- tutor/resources/styles/components/exercise-preview.less
- tutor/resources/styles/qa.less
> Hide LO tags for college courses

- tutor/resources/styles/book-content/index.less
- tutor/resources/styles/global/misc.less
- tutor/resources/styles/qa.less
- tutor/resources/styles/tutor.less
We were only hiding them on book content before, which was reference view and reading steps, not on exercises, or exercises with book context.
> Hide QR codes globally, except on QA view

- tutor/src/components/book-content-mixin.cjsx
- tutor/src/flux/media.coffee
alternative to #1248.  fixes the problem by:
* being stricter about what types of links are considered media links
* this will prevent selectors like `#hello/you/thing` from being considered media to process. Therefore, `\` should no longer get into the selector in the `getMedia` function
* wraps the `querySelector` function in a try catch to prevent any other invalid selectors from throwing uncaught exceptions
* include `.ost-exercise` as an exercise selector for exercise rendering/embedding
> Fix media link select

- tutor/src/components/task-step/all-steps.cjsx
Pivotal ticket: https://www.pivotaltracker.com/story/show/127913061
Fixes clicking on withdrawn external assignments by removing the backend call when they click on the link.
> Fix for withdrawn external assignments

- tutor/src/flux/scores.coffee
regarding: https://www.pivotaltracker.com/story/show/127670097
average_score is sometimes undefined; this was causing an error in the latework averages update
> Scores - "Use this score" for an assignment bug

- tutor/src/components/course-calendar/duration.cjsx
There were different edge cases that would cause problems seen [here](https://www.pivotaltracker.com/story/show/127275267) and [here](https://www.pivotaltracker.com/story/show/127915967).
Specifically, when multiple plans overlap on common day, kinda transitively, like this:
Plan 1 - Sunday, **Monday**, **Tuesday**
Plan 2 - **Monday**, **Tuesday**, _Wednesday_
Plan 3 - _Wednesday_, Thursday
the calendar was not accounting for when groups of plans like this amounted to more than 5 rows and needed more space on the calendars.
> Fix calendar events escaping the week they should be in

- tutor/src/components/task-plan/plan-mixin.cjsx
- tutor/src/flux/task-plan.coffee
fixes [ The message "Open times cannot be edited..." appears the second time you try to edit the assignment ](https://www.pivotaltracker.com/n/projects/1156756/stories/127671629).
the builder states were not being updated after load
> builder states were not being updated on load

- shared/src/components/exercise-preview/index.cjsx
- tutor/src/components/questions/exercises-display.cjsx
- tutor/src/flux/exercise.coffee
- tutor/test/flux/exercise.spec.coffee
Before the exercise exclusion code would examine all the sections an exercise was in.  This changes it to only examine certain modules (the one's displayed) when it decides whether to display the warning message or not.
I also found a CSS bug with how the layout mask was displayed, and moved it so it fills the entire card now.
> Only examine current sections for min-exclusions

- shared/src/model/notifications.coffee
- shared/test/model/notifications.spec.coffee
accounts_api setting already includes "api" path
fixes:
> Remove duplicate api from accounts URL

- shared/index.cjsx
- shared/src/model/ui-settings.coffee
- tutor/api/courses/1/practice/POST.json
- tutor/api/courses/2/practice/POST.json
- tutor/api/steps/step-id-6-4.json
- tutor/api/tasks/6.json
- tutor/api/tasks/Practice-Course-1.json
- tutor/resources/styles/components/task-step/all-steps.less
- tutor/resources/styles/components/task-step/ends.less
- tutor/src/api.coffee
- tutor/src/components/index.cjsx
- tutor/src/components/task-step/all-steps.cjsx
- tutor/src/components/task-step/ends.cjsx
- tutor/src/components/task-step/exercise.cjsx
- tutor/src/components/task-step/placeholder.cjsx
- tutor/src/flux/course.coffee
- tutor/src/flux/helpers.coffee
- tutor/src/flux/practice.coffee
- tutor/src/flux/task-step.coffee
- tutor/test/components/helpers/task/checks.coffee
- tutor/test/components/practice.spec.coffee
Follow up to #1286 
Also, there was a bug hiding all along --
If practice returned a 404 for a course, that course would basically be removed from the client side -- see how it's missing from the course list? -- and the user would have to reload.
User gets redirected to dashboard if there are no practices
Not ideal from a user experience perspective, but not broken.
I think ideally, clicking the practice button would have a async like "Creating Practice" animation before redirecting to the practice if available, or showing a message of being unable to create if not available
> follow up to #1286, handling no personalized questions

- bin/build
This keeps the original files around so they can be loaded by webpack if
they're built to dynamically load
> When building, copy asset files when making them MD5ified

- tutor/src/flux/task-plan.coffee
PIvotal: https://www.pivotaltracker.com/story/show/127926577
There was a javascript error when removing sections from readings, this fixes that.
> Removing sections from readings

- tutor/src/api.coffee
- tutor/src/components/task-plan/guide.cjsx
- tutor/src/flux/course.coffee
- tutor/src/flux/guide.coffee
- tutor/test/components/course-listing.spec.coffee
These fluxes should've been separate to begin with.  Server errors for guide was rare, so this was going undetected.
> prevent server errors from guide from messing with loaded course data

- shared/src/helpers/mathjax.coffee
IE11 is buggy with / does not have support for classList.
http://caniuse.com/#feat=classlist
http://stackoverflow.com/questions/8098406/code-with-classlist-does-not-work-in-ie
rendering now, though still has some alignment issues.
> IE11 Mathjax - use classNames instead of classList

- tutor/src/components/student-dashboard/event-info-icon.cjsx
Uses the task helper for determining lateness.
The earlier check was marking exercises as non-late as soon as any work was performed
> Don't mark tasks as not late when work is preformed

- tutor/src/components/task-plan/builder/index.cjsx
Can't believe no-ones noticed this before.  Guess we all just got so used to seeing it say "All Periods"
> Replace bare "All Periods" on course builder with switcher for Sections

- tutor/src/components/task-teacher-review/exercise.cjsx
Will need to clarify with @openstax/tutor-be as to why this might happen, but for some reason, for this [Bug: Reviewing assignment not loading for some assignments](https://www.pivotaltracker.com/n/projects/1156756/stories/128086791), this particular `review` has`content` where `question.id` is `52229`, but there is no matching `question_stats` where `questions_id` is `52229`.
> dont try to render questions when there are no stats for it

- tutor/src/components/student-dashboard/event-info-icon.cjsx
The original code was only showing it for Homework, but that got lost in https://github.com/openstax/tutor-js/pull/1312  This puts that check back
Otherwise there's things like this:
> Only display late icon on homework

- shared/src/model/user.coffee
- shared/test/model/user.spec.coffee
So, looks like I messed this up and broke resending email confirmation
Fixes:
> Fix email confirmation URL

- coach/src/concept-coach/index.cjsx
Fixes [logging out from coach does not close coach](https://trello.com/c/OJkEmiFh/22-concept-coach-bug-log-out-doesn-t-work).
Specifically, as @nathanstitt found, this happened whenever the webview was loaded with a coach route suffix.  When this happens, the `cc.open` function where we were adding the listeners for `logout.received` does not get called.  This PR moves adding the listeners on `cc.initialized`, which will always get called, regardless of webview loading with or without coach route suffix.
> listen for logout.received when opening from a coach view route.

- tutor/resources/styles/global/navbar.less
regarding: https://www.pivotaltracker.com/story/show/127732387
There is an edge case when a reading name is long but the header has not switched to compact mode for certain tablet resolutions/orientations.  In this case the course title and reading title may overlap. 
text ellipsis way w/ tooltip:
> Readings: Course name and assignment name overlap in a reading assignment on tablet

- tutor/resources/styles/book-content/base.less
- tutor/resources/styles/book-content/learning-objectives.less
- tutor/resources/styles/book-content/mixins.less
- tutor/resources/styles/book-content/theming-mixins.less
From https://trello.com/c/Asuv9A1Y/69-bug-abstracts-div-data-type-abstract-not-being-displayed-in-college-books-readings-or-reference-view
This styles abstracts like learning-objectives.  The only difference is that they do not have the separating line.  I had to disable that because all abstracts do not have a "In this chapter you will learn about" pre-amble.  Without that, the line looks weird because it doesn't separate anything.
HS Physics abstract with pre-amble:
College physics without one:
> Display data-type=abstract elements in content

- tutor/resources/styles/components/cc-dashboard/index.less
- tutor/resources/styles/components/icon.less
- tutor/src/components/icon.cjsx
remove hanging classNames assignment, move button de-styling to icon.less so that buttons tutor-icons not in dashboard will revert to original style
> tutor-icon followup

- tutor/resources/styles/components/questions-dashboard.less
- tutor/src/components/questions/exercises-display.cjsx
regarding: https://trello.com/c/ijsIXHqp/43-bug-ql-details-view-actions-are-mis-placed-height-is-incorrect
in testing, filter placement on scroll is working correctly.
moved green info bar above filter bar as requested.
> Question Library -  details view filter bar height/placement

- shared/resources/styles/components/question.less
- tutor/resources/styles/book-content/base.less
- tutor/resources/styles/book-content/index.less
- tutor/resources/styles/book-content/learning-objectives.less
- tutor/resources/styles/book-content/note.less
- tutor/resources/styles/book-content/questions.less
- tutor/resources/styles/book-content/theming-mixins.less
- tutor/resources/styles/components/reference-book/exercise.less
- tutor/resources/styles/components/reference-book/page.less
- tutor/resources/styles/components/task-step/all-steps.less
- tutor/resources/styles/components/task-step/reading/interactive.less
- tutor/src/components/book-content-mixin.cjsx
follow up to #1331
Also, get rid of extraneous exercise numbers
Make styled (almost) the same as embedded exercises, fix numbering
> Follow Up reading content styling details

- coach/resources/styles/components/navigation/index.less
Would only appear when tabbing to the menu
Before:
After:
> Remove focus outline from CC user menu

- tutor/src/components/task-plan/event/index.cjsx
- tutor/src/components/task-plan/external/index.cjsx
- tutor/src/components/task-plan/footer/back-button.cjsx
- tutor/src/components/task-plan/footer/cancel-button.cjsx
- tutor/src/components/task-plan/footer/delete-link.cjsx
- tutor/src/components/task-plan/footer/help-tooltip.cjsx
- tutor/src/components/task-plan/footer/index.cjsx
- tutor/src/components/task-plan/footer/save-as-draft.cjsx
- tutor/src/components/task-plan/footer/save-button.cjsx
- tutor/src/components/task-plan/footer/save-link.cjsx
- tutor/src/components/task-plan/homework.cjsx
- tutor/src/components/task-plan/reading.cjsx
- tutor/src/helpers/plan.coffee
- tutor/test/components/task-plan/footer.spec.coffee
Work was done via the the "get the code to a place where you can make the easy change, then make it" philosophy.
Also, I'm surprised we don't have a "isPlanOpened" helper somewhere.  Maybe I just missed it though?
> Don't warn about students working when deleting unopened assignments

- tutor/src/components/scores/homework-cell.cjsx
- tutor/src/components/scores/late-work.cjsx
- tutor/src/components/scores/reading-cell.cjsx
- tutor/src/helpers/task.coffee
It had the same bug as Reading, where it would vanish as soon as you moved the mouse over it.  
This one wasn't a showstopper though since it had no actions to click on it.
> Fix scores reports HW cell's popover

- tutor/resources/styles/book-content/index.less
- tutor/resources/styles/book-content/interactive.less
- tutor/resources/styles/book-content/mixins.less
- tutor/resources/styles/book-content/note.less
- tutor/resources/styles/book-content/questions.less
- tutor/resources/styles/components/reference-book/page.less
- tutor/resources/styles/components/related-content-link.less
- tutor/resources/styles/components/task-step/all-steps.less
- tutor/resources/styles/components/task-step/reading.less
- tutor/resources/styles/components/task-step/reading/interactive.less
- tutor/resources/styles/components/task/index.less
- tutor/resources/styles/variables.less
- tutor/src/components/book-content-mixin.cjsx
Sims will be
* `100%` of content width on small screens
* `960px`, centered, for sizes above `960px`
* squishy margin for sizes below `1020px`
* fixed margin, centered within content, bulging out of the content, for sizes above `1020px`
Take note that this particular sim happens to be responsive.  Most of our sims are not.  They will center and size down as window size shrinks.  This is a temporary solution, as sims will not be workable below a certain width.
> handle sim width in 3 cases -- base, skinny, and wide, and note vs non-note

- tutor/src/components/student-dashboard/index.cjsx
Fixes the FE part of the bug that https://github.com/openstax/tutor-server/pull/1272 addresses.
This simply displays an error and redirects to the dashboard course listing if the given course id isn't found.  Before there would be a JS error when it attempted to get the `is_concept_coach` member of null, and only a blank page would be displayed.
> redirect to dashboard when course is not found

- tutor/resources/styles/components/performance-forecast/heading.less
- tutor/resources/styles/components/performance-forecast/index.less
- tutor/src/components/performance-forecast/info-link.cjsx
Fixes performance forecast tooltip not showing up on tablets
Pivotal: https://www.pivotaltracker.com/story/show/128026799
> Performance Forecast tooltip on tablet

- coach/src/exercise/index.cjsx
- coach/test/exercise/index.spec.coffee
this is important. @Dantemss pointed this out.   currently, students in coach can attempt to submit multiple times before previous requests complete..so yah bad.
:( almost done, need to update tests
> set waiting text when saving, also prevents double submits

- exercises/src/components/exercise/answer.cjsx
- exercises/src/components/exercise/question-format-type.cjsx
- exercises/src/components/exercise/question.cjsx
- exercises/src/components/tags/requires-context.cjsx
- exercises/src/components/tags/single-dropdown.cjsx
- exercises/src/stores/question.coffee
- exercises/src/stores/tagging-mixin.coffee
https://trello.com/c/bTWS6Rcy/111-bug-create-edit-first-try-in-exercises-has-trash-data-in-the-detailed-solution-and-causes-an-error-at-save
If an input's value is set to undefined, it doesn't clear it.  This was causing old record's values to be retained in the input field of a new record
> Fix exercise editor bug with old values persisting in fields

- shared/src/model/ui-settings.coffee
- shared/test/model/ui-settings.spec.coffee
Otherwise if `set` is called in quick succession before the `_.debounce` has fired `PREVIOUS_SETTINGS` will be updated before save occurs and the BE will reject the save.
> Update UiSetting's PREVIOUS_SETTINGS only after save

- tutor/src/components/task/progress/milestones.cjsx
- tutor/src/flux/step-title.coffee
noticed some weird milestone snippets, this makes them generally make more sense
> fix weird milestone snippets

- tutor/src/components/task-step/exercise.cjsx
- tutor/src/components/task/index.cjsx
- tutor/src/flux/task.coffee
step indices were mismatched and confused, and so which step to scroll to was confused as well.  this more carefully matches the visual step indices with real steps on tasks, especially around things like whether steps are part of same multipart
TODO clean up.
hopefully addresses
* https://trello.com/c/28Do07p1
* https://trello.com/c/DBTgj8Ba
* https://trello.com/c/247ytbaE
> should fix mpq scrolling

- tutor/src/components/task-plan/footer/help-tooltip.cjsx
- tutor/src/components/task-plan/footer/index.cjsx
Somehow we got the logic slightly wrong and were looking at isEditable as well.
The previous logic looked only at isPublished https://github.com/openstax/tutor-js/blob/8138187dd23103b3c7e6bee81b9e79a357c80127/tutor/src/components/task-plan/footer.cjsx#L178
> info icon should appear until plan is published

- coach/src/task/index.cjsx
Coach will no long close for when the page has no exercises
> problem was with isContinue return true for tasks without steps

- shared/resources/styles/components/exercise/intro.less
- shared/src/helpers/step-helps.cjsx
As defined here: https://trello.com/c/7VIdD1Y3/166-update-the-wording-in-the-first-time-two-step-card-in-tutor-readings-and-homeworks and [here for coach](https://trello.com/c/tCSxdOJh/168-update-the-wording-in-the-first-time-two-step-card-in-concept-coach-readings)
> change for intro two step message

- shared/resources/styles/components/exercise-preview/index.less
- shared/src/components/exercise-identifier-link.cjsx
- shared/test/components/exercise-preview/index.spec.coffee
> Fix duplicated choice letter displayed on exercise preview

- shared/src/components/breadcrumb/index.cjsx
- shared/test/components/breadcrumb/index.spec.coffee
> Fix breadcrumb end has title (popover) with "undefined"

- shared/src/components/exercise-preview/index.cjsx
- shared/src/components/scroll-to-mixin.cjsx
- shared/test/helpers/fake-window.coffee
- tutor/resources/styles/components/exercises.less
- tutor/src/components/exercises/cards.cjsx
- tutor/src/components/exercises/details.cjsx
- tutor/src/components/icons/arrow.cjsx
- tutor/src/components/questions/exercises-display.cjsx
- tutor/src/components/task-plan/homework/add-exercises.cjsx
- tutor/test/components/exercises/cards.spec.coffee
- tutor/test/components/exercises/details.spec.coffee
Applies to both QL and HW builder
The selected exercise is focused after it's returned to so it can be identified:
> Scroll to current exercise when returning from details view

- tutor/resources/styles/book-content/ap-bio/variables.less
- tutor/resources/styles/book-content/hs-physics/variables.less
- tutor/resources/styles/book-content/index.less
- tutor/resources/styles/book-content/intro-sociology/variables.less
- tutor/resources/styles/book-content/learning-objectives.less
- tutor/resources/styles/book-content/note.less
- tutor/resources/styles/book-content/questions.less
- tutor/resources/styles/book-content/related-content.less
- tutor/resources/styles/book-content/theming-mixins.less
- tutor/resources/styles/book-content/variables.less
- tutor/resources/styles/components/task/index.less
- tutor/resources/styles/components/task/teacher-review-controls.less
- tutor/resources/styles/variables/colors.less
- tutor/src/components/reference-book/page.cjsx
- tutor/src/components/related-content.cjsx
- tutor/src/components/task-step/step-with-reading-content.cjsx
- tutor/src/components/task/progress/milestones.cjsx
- tutor/src/flux/reference-book-page.coffee
- tutor/src/flux/step-title.coffee
- tutor/test/components/reference-book.spec.coffee
- tutor/test/components/related-content-link.spec.coffee
https://trello.com/c/qd29BT5E/140-bug-section-title-does-not-show-anywhere-in-the-reading-content
> fix missing section titles

- shared/src/helpers/router.coffee
They had a bug where undefined params were being returned as the string 'undefined', which made Coffee's  `?` check return true, breaking the Performance Forecast
> Fix Performance Forecast; work around react-router bug with params

- tutor/resources/styles/components/scores/table.less
- tutor/src/components/scores/table.cjsx
Avoid multiply by undefined, default average to 0.  Also adds missing border to top of names column
Before:
After:
> Fix scores overall cell displaying NaN 

- tutor/resources/styles/global/navbar.less
- tutor/src/components/navbar/index.cjsx
Since it's 100% width it was intercepting clicks for the logo and course title.
> Allow clicks to pass through navbar-overlay

- tutor/src/components/qa/index.cjsx
Otherwise it'll just load the first section over and over
> Fix qa view menu; only redirect to first ecosystem if not present

- tutor/resources/styles/components/course-calendar/header.less
> fix layout bugs when calendar is narrow

- tutor/src/components/course-calendar/add-menu-mixin.cjsx
- tutor/src/components/course-settings/no-archive-help.cjsx
Otherwise it causes an error when it attempts to dereference query
Also fixed bug where they help modal wouldn't display for the "Why Can't I Archive periods?" link.
> Fix js error when course has no periods 

- tutor/src/components/course-calendar/past-assignments.cjsx
- tutor/src/components/course-calendar/plan.cjsx
- tutor/src/components/course-calendar/task-dnd.cjsx
- tutor/src/components/new-course/wizard.cjsx
- tutor/src/helpers/task-plan.coffee
And stop using mini editor for draft plans
> Display tooltip w/due-date for past plans in sidebar 

- configs/test/jest.setup.coffee
- tutor/specs/components/scores/homework-cell.spec.cjsx
Per
https://facebook.github.io/jest/docs/troubleshooting.html#unresolved-promises,
this is most likely the cause of the random spec timeout's we've been having
> Set promises globally to fix timeout issues

- tutor/resources/styles/components/course-calendar/sidebar.less
And then a bit of margin between them so the hover shadow shows
> Safari D&D: set an explicit background color on draggables

- shared/src/components/buttons/close-button.cjsx
- tutor/specs/components/tutor-dialog.spec.cjsx
- tutor/src/components/tutor-dialog.cjsx
Believe this is the root cause of the various "task builder can't exit" bugs.  It was trying to display the "unsaved data" warning but was failing.
> Fix bug with displaying dialog more than once

- tutor/src/components/breadcrumb/index.cjsx
- tutor/src/flux/task-step.coffee
While debugging a different bug I noticed we were binding step.completed
to different functions.  This binds once and then calls checkPlaceholder
from update.
I think this is a good idea so that we'll have fewer event listeners bound and lessen the maxListeners warning.
> Only bind to 'step.completed' once

- tutor/resources/styles/global/forms.less
This makes me nervous but I don't see any areas of the app that are adversely affected.  I think that we needed the rule to fix material-design bugs, but don't need it any longer now that we're not using that.
The bug that i'm attempting to fix is that the recent addition of `[type=number]` to the rule caused Safari to style numeric inputs like this:
> remove global font-size and padding

- tutor/resources/styles/components/performance-forecast/colors-mixin.less
- tutor/resources/styles/components/performance-forecast/guide-key-mixin.less
- tutor/resources/styles/components/performance-forecast/section-mixin.less
- tutor/resources/styles/components/student-dashboard/progress-guide.less
- tutor/src/components/performance-forecast/color-key.cjsx
The new BS code sets the component class on the parent element, not the bar itself.  This updates styles to match.
> Fix performance bar colors

- tutor/resources/styles/components/paging-navigation.less
- tutor/resources/styles/components/task/index.less
fixes https://trello.com/c/rSo2elYe/270-bug-it-s-difficult-to-navigate-tutor-readings
works now in firefox and chrome
i wanted to test on safari...but my safari crashes as soon as i load tutor...so that doesnt bode well...
> firefox arrow adjustment in paging navigation

- tutor/src/flux/new-course.coffee
https://trello.com/c/XfE14EFB/304-bug-wrong-number-of-sections-when-cloning-it-shows-archive-sections-are-part-of-total
> exclude archived periods from number of sections default

- tutor/specs/components/new-course/course-details.spec.cjsx
- tutor/src/components/new-course/course-details.cjsx
Otherwise cursor jumps to end when value is set
> Use defaultValue instead of value prop

- tutor/resources/styles/components/multi-select.less
- tutor/specs/components/multi-select.spec.cjsx
- tutor/src/components/multi-select.cjsx
The new RB sends the selection first to the onSelect handler, and the css classes have changed.    Also restored it's existing spec
Was breaking the "Exercise Types" selector on QA view
> Update multi-select styles and behaviour

- README.md
This changes the `README.md` to let developers know to use `nvm` so everyone is using the same version of node 😄
> add instructions for nvm

- tutor/src/components/course-calendar/month.cjsx
- tutor/src/components/course-calendar/plan.cjsx
- tutor/src/components/task-plan/mini-editor/editor.cjsx
- tutor/src/components/task-plan/teacher-task-plans-listing.cjsx
- tutor/src/flux/teacher-task-plan.coffee
https://trello.com/c/QcSuNFGk/337-bug-un-clickable-gray-bar-on-calendar
> various plan dragging editing details

- exercises/src/api/index.coffee
Looks like this got missed when we updated the api stuff
> restore inadvertently removed CRSF_TOKEN constant

- tutor/src/components/course-listing/course.cjsx
When a course is named something like "College Biology, Mr Jones", the
last segment would end up as ', Mr Jones' and look weird.
Turns
Into:
> Strip non word characters from last segment

- tutor/specs/components/scores/index.spec.cjsx
- tutor/specs/components/scores/student-data-sorter.spec.coffee
- tutor/src/components/scores/assignment-header.cjsx
- tutor/src/components/scores/sorting-header.cjsx
- tutor/src/components/scores/student-data-sorter.coffee
- tutor/src/components/scores/table.cjsx
The code was using weird `children.refs` to determine the type of sort that should be performed and was also looking at the wrong column.  I'm not sure what the `FIRST_DATA_COLUMN` was doing?
> Fix score report column sorting

- tutor/specs/components/course-calendar/__snapshots__/sidebar-toggle.spec.cjsx.snap
- tutor/specs/components/course-calendar/sidebar-toggle.spec.cjsx
- tutor/src/components/course-calendar/sidebar-toggle.cjsx
Fixes a small bug, previously when the sidebar was defaulted to open, the icon would be wrong and have the bars even though it's open:
it's now the correct 'X':
> Set sidebar toggle icon to correct value when rendering open

- tutor/resources/styles/components/exercises.less
It was inheriting the outline from the card view.  Not sure why chrome et al didn't also show it
> explicitly remove the style from detailed cards

- tutor/src/components/course-calendar/add-assignment-sidebar.cjsx
Fixes https://trello.com/c/0Or0r08U/431-bug-close-hide-the-tooltip-when-the-sidebar-closes
> intro popover hides on sidebar cloase

- tutor/specs/components/new-course/__snapshots__/select-course.spec.cjsx.snap
- tutor/specs/components/new-course/select-course.spec.cjsx
- tutor/src/components/new-course/select-course.cjsx
Some courses do not have an offering_id, which means that even thought they're selected as a source, we can't pair them with an offering.
We'll have to fix them in the admin screen for production, but in the meantime we shouldn't blow up the FE code
> Skip selecting course only if offering is set

- tutor/specs/flux/course-information.spec.coffee
- tutor/src/flux/course-information.coffee
When a appearance code isn't found it's usually because admin has set
something that's just like the book's title.  In that case we're better
off to send back a cleaned up code instead of 'default'
> Use a titleized version of code instead of "default" for course info

- tutor/src/components/course-calendar/month.cjsx
- tutor/src/components/task-plan/builder/index.cjsx
- tutor/src/components/task-plan/initialize-editing.coffee
- tutor/src/components/task-plan/mini-editor/editor.cjsx
- tutor/src/components/task-plan/teacher-task-plans-listing.cjsx
https://trello.com/c/GMlX0LA7/353-bug-intermittent-assignments-shift-back-one-day-after-dragging-to-intended-due-date
can be triggered as easily as going to calendar, click on an assignment to edit, and then clicking cancel.  Builder unmount to unsync timezone was getting called after the calendar's sync call.
> Fix timezone missyncing

- shared/src/components/pinned-header-footer-card/index.cjsx
this is the simplest way to reset the classes on the pinned components.  `without` wasnt working because the function expects the excluded values as individual and not the whole array of values to exclude. for that, `difference` is the function to use.  also, pinned-on and pinned-shy, classes added or removed based on scroll were not being considered despite needing to be removed on unmount
https://trello.com/c/suWaGT0S/358-bug-menu-disappearing-on-all-browsers-randomly
a reliable way to reproduce this is to go to homework builder from calendar, scroll down to where the main menu hides, and then click the back button
> fix disappearing navbar

- package.json
https://github.com/insin/react-maskedinput/pull/80 has been released, this silences the console.warn messages when loading the builder.
> Update masked input to silence warnings

- tutor/src/components/enroll/index.cjsx
- tutor/src/flux/course-enrollment.coffee
https://trello.com/c/AyiPjKha/386-bug-sign-up-with-a-tutor-student-join-url-doesn-t-get-students-to-the-right-place
dashboard now has all classes, including the new one i just joined without page reload
going to the dashboard after enrollment shows this:
now, going to the dashboard after enrollment shows this if this is the only class for the student.
It shows the full list of courses including the new one if student is in more than one course.
> Course listing needs to be updated after successful enrollment

- coach/src/helpers/index.coffee
It looks like this somehow this got missed when implementing hot reloading
> Fix hot reloading: Wrap rendered root with hostloading AppContainer

- coach/demo.cjsx
- coach/resources/styles/components/concept-coach/launcher.less
- coach/resources/styles/components/course/registration.less
- coach/resources/styles/components/graphics/laptop-and-mug.less
- coach/resources/styles/components/graphics/launcher-animation.less
- coach/specs/concept-coach/launcher/__snapshots__/index.spec.cjsx.snap
- coach/specs/user/login-gateway.spec.cjsx
- coach/src/concept-coach/index.cjsx
- coach/src/concept-coach/launcher/index.cjsx
- coach/src/course/model.coffee
- coach/src/course/new-registration.cjsx
- coach/src/course/registration.cjsx
- coach/src/graphics/coach.cjsx
- coach/src/graphics/laptop-and-mug.cjsx
- coach/src/helpers/index.coffee
- coach/src/user/menu.cjsx
- coach/src/user/status-mixin.coffee
- shared/specs/helpers/fake-window.coffee
i think we should leave style overrides to webview side -- i.e.button text being white is already the default for webview buttons.
Note that styles appear as in screenshots when embedded into webview.  they will look a little different in demo mode.
likely for other PRs
> a few more udpatesss

- tutor/api/courses/1.json
- tutor/specs/components/new-course/wizard.spec.cjsx
- tutor/src/components/new-course/wizard.cjsx
When the offerings aren't present then the source course won't be found
in the offerings store, causing the wizard to display the "choose
course" panel, even when the source id was present.
By re-testing after the load, that panel can be skipped if a source
course is given.
> Set stage after offerings are loaded

- coach/auth/status/GET.json
- coach/specs/user/model.spec.coffee
- coach/src/user/model.coffee
When a student is taking a second-semester of a course, there will be multiple matching courses for the given ecosystem uuid.  In that case we must use only the most recently joined
> Use the most recently joined course for an ecosystem

- shared/specs/components/notifications/bar.spec.cjsx
- shared/src/components/notifications/bar.cjsx
The bar only was firing updates on mount, which didn't work for CC when someone logs in
> notify notices store when course and/or role updates
